### ISSUE TITLE
Make Rekall offsets array available for plugins

### ISSUE THREAD

**Issue by aoshiken** [tklengyel/drakvuf#100]
Hi,

Currently the Drakvuf Rekall offsets array (located at _src/libdrakvuf/vmi.h_) is not available for using within the plugins so, in the end, each plugin allocate each own Rekall offsets array, this way we're dealing with duplicated entries wasting memory as more plugins comes into play.

I agree isn't critical but in my humble opinion combining all the offsets into one and making this available for all plugins  would be desirable. 

What do you think about?

**Comment by tklengyel** [comment]
My thinking was to have the offset array internal to libdrakvuf containing elements that are needed for libdrakvuf to work, then have each plugin pull the offsets they need individually. The extra memory needed is marginal so I wouldn't worry about that. This way we don't end up pulling offsets out that may only needed by some plugins if they get disabled.

**Comment by aoshiken** [comment]
Thanks Tamas
