### ISSUE TITLE
Failed to enable altp2m on domain!

### ISSUE THREAD

**Issue by noorkaximi** [tklengyel/drakvuf#101]
i installed drakvuf successfully but when i try to inject a process it gives error
> root@noor-HP-ENVY-m6-Notebook-PC:~# injector /root/windows7-sp1.rekall.json 8 1820 calc.exe
> Failed to enable altp2m on domain!

```
(process:9067): GLib-CRITICAL **: g_hash_table_iter_init: assertion 'hash_table != NULL' failed

(process:9067): GLib-CRITICAL **: g_hash_table_iter_next: assertion 'ri->version == ri->hash_table->version' failed

(process:9067): GLib-CRITICAL **: g_hash_table_destroy: assertion 'hash_table != NULL' failed

(process:9067): GLib-CRITICAL **: g_hash_table_destroy: assertion 'hash_table != NULL' failed
Segmentation fault (core dumped)

```

**Comment by aoshiken** [comment]
@noorkaximi 
Just thinking... Could you provide your DomU configuration file?

**Comment by noorkaximi** [comment]
arch = 'x86_64'
name = "windows7-sp1"
maxmem = 2000
memory = 2000
vcpus = 1
maxcpus = 1
builder = "hvm"
boot = "cd"
hap = 1
acpi = 1
on_poweroff = "destroy"
on_reboot = "destroy"
on_crash = "destroy"
vnc=1
vnclisten="0.0.0.0"
usb = 1
usbdevice = "tablet"
altp2mhvm = 1
vif = ['type=ioemu,model=e1000,bridge=xenbr0,mac=00:06:5B:BA:7C:01']
disk = [
    'phy:/dev/foo/windows7-sp1,xvda,w', 
    'file:Downloads/win7.iso,hdc:cdrom,r'
]

**Comment by noorkaximi** [comment]
# If you change this file, run 'update-grub' afterwards to update
# /boot/grub/grub.cfg.
# For full documentation of the options in this file, see:
#   info -f grub -n 'Simple configuration'
altp2mhvm=1
GRUB_DEFAULT=0
GRUB_HIDDEN_TIMEOUT=0
GRUB_HIDDEN_TIMEOUT_QUIET=true
GRUB_TIMEOUT=10
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
GRUB_CMDLINE_LINUX=""

# Uncomment to enable BadRAM filtering, modify to suit your needs
# This works with Linux (no patch required) and with any kernel that obtains
# the memory map information from GRUB (GNU Mach, kernel of FreeBSD ...)
#GRUB_BADRAM="0x01234567,0xfefefefe,0x89abcdef,0xefefefef"

# Uncomment to disable graphical terminal (grub-pc only)
#GRUB_TERMINAL=console

# The resolution used on graphical terminal
# note that you can use only modes which your graphic card supports via VBE
# you can see them in real GRUB with the command `vbeinfo'
#GRUB_GFXMODE=640x480

# Uncomment if you don't want GRUB to pass "root=UUID=xxx" parameter to Linux
#GRUB_DISABLE_LINUX_UUID=true

# Uncomment to disable generation of recovery mode menu entries
#GRUB_DISABLE_RECOVERY="true"

# Uncomment to get a beep at grub start
#GRUB_INIT_TUNE="480 440 1"

**Comment by noorkaximi** [comment]
```
# If you change this file, run 'update-grub' afterwards to update
# /boot/grub/grub.cfg.
# For full documentation of the options in this file, see:
#   info -f grub -n 'Simple configuration'
altp2mhvm=1
GRUB_DEFAULT=0
GRUB_HIDDEN_TIMEOUT=0
GRUB_HIDDEN_TIMEOUT_QUIET=true
GRUB_TIMEOUT=10
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
GRUB_CMDLINE_LINUX=""

# Uncomment to enable BadRAM filtering, modify to suit your needs
# This works with Linux (no patch required) and with any kernel that obtains
# the memory map information from GRUB (GNU Mach, kernel of FreeBSD ...)
#GRUB_BADRAM="0x01234567,0xfefefefe,0x89abcdef,0xefefefef"

# Uncomment to disable graphical terminal (grub-pc only)
#GRUB_TERMINAL=console

# The resolution used on graphical terminal
# note that you can use only modes which your graphic card supports via VBE
# you can see them in real GRUB with the command `vbeinfo'
#GRUB_GFXMODE=640x480

# Uncomment if you don't want GRUB to pass "root=UUID=xxx" parameter to Linux
#GRUB_DISABLE_LINUX_UUID=true

# Uncomment to disable generation of recovery mode menu entries
#GRUB_DISABLE_RECOVERY="true"

# Uncomment to get a beep at grub start
#GRUB_INIT_TUNE="480 440 1"
```

**Comment by aoshiken** [comment]
I don't know for sure but it seems you're not passing the altp2m variable to Xen kernel.

Take a look to the grub file example from DRAKVUF:
```
GRUB_CMDLINE_XEN_DEFAULT="dom0_mem=4096M,max:4096M dom0_max_vcpus=4 dom0_vcpus_pin=true hap_1gb=false hap_2mb=false altp2m=1"
```
Remember to execute `update-grub` after your changes.

Hope this helps

**Comment by noorkaximi** [comment]
@aoshiken thanx man it worked.....

**Comment by noorkaximi** [comment]
@aoshiken i have another problem 
i have connected to wifi connection and i dont have ethernet connection now i am unable to connect it to my xen guest OS (domain U) can you give me detail instruction to configure it so that i can connect domain U to Internet ...

**Comment by aoshiken** [comment]
If your issue has been solved, please, close it and open a new one.

That's just for the sake of being helpful for next readers.

**Comment by tklengyel** [comment]
For Xen networking questions I suggest the xen-users mailinglist but you should also be able to find many tutorials by googling around.
