### ISSUE TITLE
How to inject an executable from host?

### ISSUE THREAD

**Issue by Id3aFly** [tklengyel/drakvuf#1017]
Hey guys,

I followed the official [video from drakvuf.com](https://www.youtube.com/watch?v=0Dk5RehrA-Q&feature=emb_title) to inject an executable which is saved already at the guest.
I also tried to run another executable which is saved at my guest so far e.g. "/home/kali/drakvuf/calc2.exe" but I had no luck with it so far. Therefore, I wanted to ask you, if this is possible at all?

My second questions which points to the same direction is:
How do you move files from host to guest without using the internet? Is there something like scp for xen?

Thank you! :)

**Comment by icedevml** [comment]
> I also tried to run another executable which is saved at my guest so far e.g. "/home/kali/drakvuf/calc2.exe" but I had no luck with it so far.

Could you post the full command line you are using?

**Comment by Id3aFly** [comment]
Sure 
`sudo ./src/drakvuf -r /root/win10.json -d win10 -i 7700 -e '/home/kali/drakvuf/calc2.exe' `

**Comment by icedevml** [comment]
Path provided to `-e` must be a valid path on guest (not host). You could instead try sth like:

```
sudo ./src/injector -r /root/win10.json -d win10 -i 7700 -m writefile -e '%USERPROFILE%\Desktop\calc2.exe' -B /home/kali/drakvuf/calc2.exe
sudo ./src/drakvuf -r /root/win10.json -d win10 -i 7700 -e 'C:\Users\YOUR_USERNAME_HERE\Desktop\calc2.exe'
```

**Comment by Id3aFly** [comment]
This solved my problem! Thank you @icedevml!

Is there any other way to move files from host to guest without using the internet? So is there something easier than injecting the file?

**Comment by icedevml** [comment]
You can insert virtual CD. This is however risky as Windows might start seeing the CD with some delay, so you need to account for that when writing your automation scripts.

```
xl qemu-monitor-command DOMAIN_NAME "change ide-5632 /path/to/some.iso"
```

**Comment by Id3aFly** [comment]
That is amazing! Thank you so much!
