### ISSUE TITLE
Running drakvuf with default plugins makes guest uncontrollable

### ISSUE THREAD

**Issue by Id3aFly** [tklengyel/drakvuf#1020]
Hey guys,

when running in my default ubuntu shell
`sudo ./src/drakvuf -r /root/win10.json -d win10`
I see incoming monitoring messages from drakvuf SYSCALL, POOLMON, etc, but I can't interact with my guest anymore because it get's really really slow. One click takes around 20s. 

Or when injecting a executable (calc.exe) in taskmgr (PID 7700) I cannot see the cmd window to open for more than 60s.
`sudo ./src/drakvuf -r /root/win10.json -d win10 -i 7700 -e cmd.exe'`

When I stop drakvuf with Ctrl+C the cmd windows suddenly gets visible.
Am I doing something wrong? Or how could I improve this lagging?

Thank you

**Comment by icedevml** [comment]
Are you running natively or nested inside VMware Player or some other virtualization software?

**Comment by Id3aFly** [comment]
Natively with a i7-4700MQ 2.4GHz x 4
Hardware -> Ubuntu&Drakvuf -> Guest

**Comment by icedevml** [comment]
I think something is certainly wrong. It should work pretty fast on native.

Don't you have some processes running in the background of the VM (e.g. some SearchIndexer or some .NET stuff)? If you've snapshotted the VM right after installation then some processes might be still doing heavy computations in the background.

You may also try to disable certain plugins using `-x` switch or even `-a` switch. This might be some bug in some plugin as well.

**Comment by Id3aFly** [comment]
> 
> 
> I think something is certainly wrong. It should work pretty fast on native.
Ok, that is super strange.

> Don't you have some processes running in the background of the VM (e.g. some SearchIndexer or some .NET stuff)?
Nothing special. Usual it is really fast and I can just work with it as with any other PC. It is a plain Win10 VM with nothing installed to it and no modiciations.

> If you've snapshotted the VM right after installation then some processes might be still doing heavy computations in the background.
I just made a fresh snapshot today. But the days before it was similar as well.

> You may also try to disable certain plugins using `-x` switch or even `-a` switch. This might be some bug in some plugin as well.
It is faster if I limit the monitored syscalls to 2 or 3 specific ones.

Maybe my CPU does not support any "special" features XEN or drakvuf makes use of?

**Comment by icedevml** [comment]
> Maybe my CPU does not support any "special" features XEN or drakvuf makes use of?

I think it's rather binary. Either there is support or you wouldn't be able to run DRAKVUF at all. Everything else is a grey area. There might be some bug that affects your CPU specifically, but IMHO the chance is pretty low and I would first search on the higher layers (DRAKVUF, LibVMI).

Could you try `-a syscalls` but without a syscall limiter? This would deactivate all plugins except `syscalls`, so lots of complex logic will be deactivated. Will it run acceptably fast in this case?

**Comment by Id3aFly** [comment]
-a syscalls is faster in a way I could accept it.
So it ust takes ~4s to change a folder. Starting my test c++ executable takes around 10s, but at least it is faster than before!
Restricting the syscalls with -S to ust 2 syscalls is that quick, I don't feel any difference. So this really might be because of my old test laptop. I'll try to do some tests and look at my CPU load.

**Comment by Id3aFly** [comment]
When running 
`sudo ./src/drakvuf -r /root/win10.json -d win10 -a syscalls -S hypermonitor/xenguest/syscallsmonitor `
![Bildschirmfoto von 2020-09-29 22-11-28](https://user-images.githubusercontent.com/5712180/94610670-ed0ce400-02a0-11eb-81a7-c6728b930ad7.png)

When running
`sudo ./src/drakvuf -r /root/win10.json -d win10 -a syscalls 
`
![Bildschirmfoto von 2020-09-29 22-09-55](https://user-images.githubusercontent.com/5712180/94610675-eed6a780-02a0-11eb-97de-de07c787684d.png)

I'm not that super familiar with htop, but I can see significant differences in CPU% and the load of my 4 kernels.

**Comment by icedevml** [comment]
IMHO from what you've described it looks like the CPU might be slow itself :(

**Comment by chivay** [comment]
If you haven't already, you may also try redirecting the output to a file. Sometimes the terminal emulator might be a bottleneck.

**Comment by icedevml** [comment]
Yup, in some circumstances it can't keep up and it synchronously blocks which basically blocks DRAKVUF and the VM as well.

**Comment by Id3aFly** [comment]
Since this error is probably more related to my hardware than to drakvuf, I'm closing this now.

**Comment by Id3aFly** [comment]
> 
> 
> If you haven't already, you may also try redirecting the output to a file. Sometimes the terminal emulator might be a bottleneck.

This idea didn't help that much for the syscall plugin, but for others it brought a speedup to be acceptable fast.
