### ISSUE TITLE
How to use memdump plugin

### ISSUE THREAD

**Issue by Id3aFly** [tklengyel/drakvuf#1026]
Hey together,

I've been trying to use the memdump plugin, but everytime I execute the following command my guest machine crashes.
`sudo ./src/drakvuf -r /root/win10.json -d win10 -a memdump --memdump-dir /tmp/`

This is the output of the drakvuf terminal:
`1601814687.241887 DRAKVUF v0.8-git20200828135902+72a2535-1 Copyright (C) 2014-2020 Tamas K Lengyel`

This is the regarding output of `xl info`:
```
host                   : kali-W350SKQ-W370SK
release                : 5.4.0-48-generic
version                : #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020
machine                : x86_64
nr_cpus                : 4
max_cpu_id             : 7
nr_nodes               : 1
cores_per_socket       : 4
threads_per_core       : 1
cpu_mhz                : 2394.476
hw_caps                : bfebfbff:76daf3bf:2c100800:00000021:00000001:000027ab:00000000:00000100
virt_caps              : pv hvm hap shadow
total_memory           : 16272
free_memory            : 8958
sharing_freed_memory   : 0
sharing_used_memory    : 0
outstanding_claims     : 0
free_cpus              : 0
xen_major              : 4
xen_minor              : 14
xen_extra              : .0
xen_version            : 4.14.0
xen_caps               : xen-3.0-x86_64 xen-3.0-x86_32p hvm-3.0-x86_32 hvm-3.0-x86_32p hvm-3.0-x86_64 
xen_scheduler          : credit2
xen_pagesize           : 4096
platform_params        : virt_start=0xffff800000000000
xen_changeset          : 
xen_commandline        : placeholder dom0_mem=4096M,max:4096M dom0_max_vcpus=4 dom0_vcpus_pin=1 force-ept=1 ept=pml=0 hap_1gb=0 hap_2mb=0 altp2m=1 smt=0
cc_compiler            : gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
cc_compile_by          : kali
cc_compile_domain      : 
cc_compile_date        : Sat Sep 12 16:08:58 CEST 2020
build_id               : 81d3da994b309cd8e7262d6b23c75ab255d8071b
xend_config_format     : 4
```

I couldn't find any information on how to use the plugin properly. So maybe you could provide me some more information please?

Thank you!

**Comment by icedevml** [comment]
> everytime I execute the following command my guest machine crashes

This is very weird. Seems like crash occurs at the very beginning. Could you provide a screenshot of BSOD? Is it reproducible? (i.e. whether the same kind of BSOD occurs every time or is it random reason every time).

The `memdump` plugin is designed to work out of the box. It would however only dump memory buffers that are considered "interesting". This could be applied to unpack common malware packers.

**Comment by Id3aFly** [comment]
I could resolve it. The PDB GUID has changed.
Therefore drakvuf led to a crash of my guest each time I started drakvuf.

**Comment by icedevml** [comment]
> I could resolve it. The PDB GUID has changed.
> Therefore drakvuf led to a crash of my guest each time I started drakvuf.

This was my bet that your kernel offsets are mismatched with the actual kernel.

The exact reason of this crash was probably that breakpoints were placed in some random places in memory (e.g. in the middle of instructions). This caused corruption of the machine code and thus Windows crashed at the very beginning.

**Comment by Id3aFly** [comment]
Somehow my guest got corrupted, even my snapshot wasn't working anymore strangely. That's why I had to reinstall and completely forgot to correct the PDB GUID.
