### ISSUE TITLE
Can't stop DRAKVUF via SIGINT

### ISSUE THREAD

**Issue by v-p-b** [tklengyel/drakvuf#103]
DRAKFVUF occasionaly fails to stop on SIGINT. The domain it was attached to gets paused but the drakvuf process must be killed with SIGKILL. In this case it's not possible to reattach DRAKVUF to the unpaused process:

```
xc: error: Failed to enable vm_event
 (16 = Device or resource busy): Internal error
VMI_ERROR: vm_event is (or was) active on this domain
VMI_ERROR: Failed to initialize xen events.

(process:28551): GLib-CRITICAL **: g_hash_table_destroy: assertion 'hash_table != NULL' failed
```

The issue came up when testing https://github.com/tklengyel/drakvuf/pull/102 but I was able to reproduce it on master too: although the first SIGINT was handled correctly after unpause and reattach the second SIGINT didn't work and I had to kill the process.

**Comment by tklengyel** [comment]
I'll check if I can reproduce this but in the meanwhile enabling the debug output and pasting the portion after SIGINT was sent might pinpoint where it gets stuck.

**Comment by v-p-b** [comment]
This is the only meaningful message that I get at the first interrupt:

```
VMI_ERROR: xc_hvm_set_mem_access failed with code: -1
VMI_ERROR: xc_hvm_set_mem_access failed with code: -1
```

After this I can unpause the VM and reattach. The second interrupt results in a single `Interrupted` message.

More importantly: I was yet unable to reproduce the issue in debug mode!

**Comment by tklengyel** [comment]
I'm unable to reproduce this issue unfortunately. I can run DRAKVUF on a VM, press CTRL+C, then start DRAKVUF on it again multiple times without any issue. How do you trigger SIGINT?

**Comment by v-p-b** [comment]
Ctrl+C as usual. I suggest to ice this issue until I can repro the problem in debug mode.

**Comment by tklengyel** [comment]
Yea, this is pretty strange.

**Comment by v-p-b** [comment]
I think this was related to #106 and the outdated LibVMI version. Closing for now.
