### ISSUE TITLE
How to build drakvuf plugins

### ISSUE THREAD

**Issue by Id3aFly** [tklengyel/drakvuf#1033]
Hey guys,

I am currently trying to modify a drakvuf plugin: memdump.
I modified the source code, but I'm not familiar with the build system in linux.

That's why I have two questions:
1. Just under the assumption I modified memdump.cpp, how can I rebuild this plugin, that drakvuf is using my version?

2. If I want to create a custom plugin memdump2.cpp what do I have to change, to make it work with drakvuf?

Thank you ;)

**Comment by icedevml** [comment]
Ad 1. You need to rebuild the whole DRAKVUF. Just execute `make` in the project root. If something goes wrong, you can do `make clean && ./configure && make` just to be 100% sure.

Ad 2. Look at other PRs which were adding new plugins, e.g.: https://github.com/tklengyel/drakvuf/pull/837

**Comment by Id3aFly** [comment]
Thank you! Your answer solved my problem so far.

**Comment by Id3aFly** [comment]
I was able to write a a very basic plugin right now.
