### ISSUE TITLE
Idea of drakvuf_lock_and_get_vmi?

### ISSUE THREAD

**Issue by Id3aFly** [tklengyel/drakvuf#1051]
Hey guys,

I'm currently trying to understand the code of drakvuf, and came accross `drakvuf_lock_and_get_vmi(drakvuf) ` and `drakvuf_release_vmi(drakvuf)`.
I've seen it calls `g_mutex_lock` which tries to [prevent access from another thread](https://developer.gnome.org/glib/stable/glib-Threads.html).
_1. Why is it necessary to prevent access from other threads to the drakvuf object at this point?_

The method is called for some plugins (memdump, procmon, ...), but not for all (poolmon, regmon).
_2. Why do some plugins require this code, while others don't?_

Thank you

**Comment by tklengyel** [comment]
DRAKVUF is currently single threaded but the lock is added now to make it easier to make it multi-threaded in the future. LibVMI itself is not thread safe. Some plugins dont have it if they don't need to interact with LibVMI directly.

**Comment by Id3aFly** [comment]
Thanks for the explanation!
Gracias!
