### ISSUE TITLE
How to stop a drakvuf debug session?

### ISSUE THREAD

**Issue by Id3aFly** [tklengyel/drakvuf#1052]
Hey guys,

I'm trying to debug drakvuf with CLion.
Whenever I press "stop" the drakvuf process is killed instantly - without executing the drakvuf shutdown code which would be ran then pressing Ctrl+C.
Sometimes it requires my guest to be rebooted or sometimes even my host.

That's why I'd like to know how can I stop the debug session correctly.

Thank you!

**Comment by icedevml** [comment]
If you are using gdb, please enter `signal SIGINT` in the console, within the `(gdb)` prompt.

**Comment by Id3aFly** [comment]
Ok, thank you!
