### ISSUE TITLE
Difference of breakpoint, hook and trap

### ISSUE THREAD

**Issue by Id3aFly** [tklengyel/drakvuf#1056]
Hey guys,

what is the difference of a hook, trap and a breakpoint?

And in this context: what does the abbreviation 'cb' mean. For example it is used in `trap->cb`?

Thank you!

**Comment by icedevml** [comment]
`cb` is a shortcut from (asynchronous) `callback` ( https://en.wikipedia.org/wiki/Callback_(computer_programming) )

**Comment by icedevml** [comment]
`breakpoint` specifically in DRAKVUF project (I belive) means "shadow int3 breakpoint placed somewhere in VM's memory, hidden using altp2m"

`trap` is a much broader concept, it's +/- a watch for some event which calls an asynchronous callback once this event actually occurred, `trap` could be `breakpoint` but it could be `memaccess` as well (we are watching for access to a physical page), could be `registry` (notification on CR3 registry change) etc.

**Comment by Id3aFly** [comment]
> 
> 
> `breakpoint` specifically in DRAKVUF project (I belive) means "shadow int3 breakpoint placed somewhere in VM's memory, hidden using altp2m"

Thanks for your answers!

With 'shadow ' you mean, that the int3 is "hidden" by altp2m, or does shadow mean something else in this context?

**Comment by icedevml** [comment]
`shadow` is a colloquialism in this context, I was meaning that int3 is hidden from guest VM by appropriate manipulation with altp2m

**Comment by Id3aFly** [comment]
Perfect, than I got you right! Thanks!
