### ISSUE TITLE
Tracing VMI_MEMACCESS_X even DEP is disabled?

### ISSUE THREAD

**Issue by Id3aFly** [tklengyel/drakvuf#1059]
Hey guys, 

I'm not sure whether my question is rather related to LibVMI or drakvuf:

I found [this information](https://support.microsoft.com/en-us/help/912923/how-to-determine-that-hardware-dep-is-available-and-configured-on-your):
In 64-bit versions of Windows, hardware-enforced DEP is always enabled for 64-bit native programs. However, depending on your configuration, hardware-enforced DEP may be disabled for 32-bit programs.

So assuming I try to trace when a page is executed (as for example [in the ipt plugin](https://github.com/tklengyel/drakvuf/blob/41306ffcc66b8e4226840c6a13602870849b9fb6/src/plugins/ipt/ipt.cpp#L311))

```
    drakvuf_trap_t* exec_trap = (drakvuf_trap_t*)malloc(sizeof(drakvuf_trap_t));
    exec_trap->type = MEMACCESS;
    exec_trap->memaccess.gfn = p_info.paddr >> 12;
    exec_trap->memaccess.type = PRE;
    exec_trap->memaccess.access = VMI_MEMACCESS_X;
    exec_trap->data = ef_data; // FIXME memleak
    exec_trap->cb = execute_faulted_cb;
    exec_trap->name = nullptr;
    drakvuf_add_trap(drakvuf, exec_trap);
```

Would this also allow me to trace 32bit programs (without manually enforcing DEP enabled) on 64bit windows?

Thank you

**Comment by icedevml** [comment]
I think yes, DEP and no-execute bit are on different abstraction layer than EPT R/W/X access permissions.

**Comment by Id3aFly** [comment]
Do you have any sources / information for me, to make me understand this in more detail?

**Comment by icedevml** [comment]
https://drakvuf.com/ (-> Presentations) + DRAKVUF whitepaper

and I remember @tklengyel had something more recent than DRAKVUF whitepaper

**Comment by tklengyel** [comment]
https://github.com/tklengyel/drakvuf/wiki
