### ISSUE TITLE
Syscalls plugin doesn't read all system calls triggered on the systems 

### ISSUE THREAD

**Issue by MMaohoub** [tklengyel/drakvuf#1062]
I work on a guest machine with kernel 4.10.0 and try to trace  the system execution using SYSCALLS plugging and I wrote a simple C program that directly invokes some system calls like getting process Id, create a file and read from It.
i checked the log it only has four entries 
syscall entry for clone 
sysret entry for clone 
syscall entry for execve
sysret entry for execve

**Comment by tklengyel** [comment]
You would need to provide more information than that. If the log had syscalls saved than it seems to work. So I'm not sure what the question is. Enable the debug output and make sure the json is correct for your target kernel.

**Comment by manorit2001** [comment]
Can be closed for inactivity
