### ISSUE TITLE
can't start the OS after install drakvuf with pre-built release version 

### ISSUE THREAD

**Issue by DanniellaL** [tklengyel/drakvuf#1071]
OS: ubuntu18.04
kernel: 5.4.0-52-generic
release: ubuntu_bionic_drakvuf-bundle-0.8-git20201026094855+24d7990-1-generic.deb
error1: “Stopping User Manager for UID 121”,blocked，keep blinking
error2: change to  lightdm, blocked，without output

**Comment by icedevml** [comment]
Have you installed it on Ubuntu 18.04 Desktop? This might be not well-supported, as test mostly on servers (headless).

**Comment by DanniellaL** [comment]
> Have you installed it on Ubuntu 18.04 Desktop? This might be not well-supported, as test mostly on servers (headless).

Thanks for your reply. Yes, my OS is Desktop version, I tried to install it from source code.
