### ISSUE TITLE
Drakvuf Performance Evaluation

### ISSUE THREAD

**Issue by malinaaa** [tklengyel/drakvuf#108]
Hi, 
How I can measure the performance of analyzing a malware sample with Drakvuf?
One way is to count the number of VMEXITs which I guess is equal to counting the system calls a malware executes , is that right ? Or you have chosen another approach in evaluating the performance of Drakvuf?

**Comment by aoshiken** [comment]
Hi,
IMHO not really, VM EXITS can be the CPUID usage, among other things, and this is not a system call.

Anyway, what do you understand by "performance" when speaking about a malware? That's the first thing that comes to mind... :)

**Comment by tklengyel** [comment]
@aoshiken is correct, you need to define what you mean by performance before you can answer this question. If you mean overhead your best bet is to run some performance analysis tool in the guest with and without monitoring and compare the results.

**Comment by malinaaa** [comment]
To be clear, I want to measure the overhead of Drakvuf in analyzing a malwares. Whenever a system call happens or a kernel function executes, VMEXIT happen and this affects the performance of the monitoring phase. 
What I want to measure is something like what you have done in the evaluation part of the article (Drakvuf article) but I want to know how can I do so ?

**Comment by tklengyel** [comment]
Pick your choice of performance evaluation tool and run it in the guest with and without DRAKVUF running on it, then compare the results. Take a look at iperf for example. There is no "standard" and your mileage may vary based on how many plugins and which ones you have enabled.
