### ISSUE TITLE
Performace degradation on multiple concurrent ananlyses

### ISSUE THREAD

**Issue by skvl** [tklengyel/drakvuf#1101]
With Windows 10 1803 x64 (where concurrency is number of concurrent drakvuf instances, and delay is number of seconds before first occurrence of some test event):
Concurrency | Delay (seconds)
------------------|----------------------
1                   | 103-105
2                   | 109-119
4                   | 116-136
8                   | 140-165
12                 | 180-224

It could be seen in VNC console the slowdown of some operations (e.g. Microsoft Office document open).

I believe it could be possible to explain this with global lock in `do_domctl`:
![изображение](https://user-images.githubusercontent.com/20656851/101644804-b1338f00-3a46-11eb-85ac-697dc0cdae2b.png)

What should we do about that? Is it possible to fix slowdown?

**Comment by tklengyel** [comment]
I don't really see what the domctl lock has to do with the slowdown, once DRAKVUF is running there aren't any domctl's we issue. Any slowdown when running multiple instances is likely due to scheduling. How many CPUs does your system have? Pinning the CPUs and making sure each VM you use for analysis has a dedicated core will ensure the best performance. But of course dom0 also needs usually about the same number of CPUs assigned (and preferrably pinned) as the number of CPUs that are being monitored. Big NUMA machines may run into additional issues if dom0 is on a different node then the VM being monitored.

**Comment by tklengyel** [comment]
It's also weird to have just 1 DRAKVUF instance but a 103-105 second delay before any event pops up. That means the VM doesn't actually start running for a long time. But that's not a DRAKVUF issues, that's a Xen issue. I've seen that also with Windows 10 VMs in the past but after upgrading to Xen 4.14 the issue went away AFAICT.

**Comment by skvl** [comment]
> I don't really see what the domctl lock has to do with the slowdown, once DRAKVUF is running there aren't any domctl's we issue. Any slowdown when running multiple instances is likely due to scheduling. How many CPUs does your system have? Pinning the CPUs and making sure each VM you use for analysis has a dedicated core will ensure the best performance. But of course dom0 also needs usually about the same number of CPUs assigned (and preferrably pinned) as the number of CPUs that are being monitored. Big NUMA machines may run into additional issues if dom0 is on a different node then the VM being monitored.

```
$ sudo xl info
host                   : host
release                : 5.4.0-56-generic
version                : #62~18.04.1-Ubuntu SMP Tue Nov 24 10:07:50 UTC 2020
machine                : x86_64
nr_cpus                : 56
max_cpu_id             : 191
nr_nodes               : 2
cores_per_socket       : 14
threads_per_core       : 2
cpu_mhz                : 2397.248
hw_caps                : bfebfbff:77fef3ff:2c100800:00000121:00000001:001cbfbb:00000000:00000100
virt_caps              : pv hvm hvm_directio pv_directio
total_memory           : 130978
free_memory            : 33052
sharing_freed_memory   : 0
sharing_used_memory    : 0
outstanding_claims     : 0
free_cpus              : 0
xen_major              : 4
xen_minor              : 12
xen_extra              : .4-pre
xen_version            : 4.12.4-pre
xen_caps               : xen-3.0-x86_64 xen-3.0-x86_32p hvm-3.0-x86_32 hvm-3.0-x86_32p hvm-3.0-x86_64 
xen_scheduler          : credit
xen_pagesize           : 4096
platform_params        : virt_start=0xffff800000000000
xen_changeset          : 
xen_commandline        : placeholder hap_1gb=0 hap_2mb=0 altp2m=1 sched=credit dom0_mem=-32768M,max:-32768M dom0_max_vcpus=56 dom0_vcpus_pin=1 force-ept=1 ept=pml=0 watchdog=force watchdog_timeout=20
cc_compiler            : gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
cc_compile_by          : pkg-xen-devel
cc_compile_domain      : lists.alioth.debian.org
cc_compile_date        : Mon Sep 14 08:45:39 UTC 2020
build_id               : 622028126a9a56e6916b92191bd3532ce05f03ac
xend_config_format     : 4
```

I would try to pin CPUs and to switch to Xen 4.14.

Thank you!

**Comment by skvl** [comment]
> It's also weird to have just 1 DRAKVUF instance but a 103-105 second delay before any event pops up. That means the VM doesn't actually start running for a long time. But that's not a DRAKVUF issues, that's a Xen issue. I've seen that also with Windows 10 VMs in the past but after upgrading to Xen 4.14 the issue went away AFAICT.

This is not the first event. This is an event of new process appeared (created with macros in MS Word file).

**Comment by tklengyel** [comment]
> nr_nodes               : 2

This is a big NUMA machine. You need to make sure the CPU running DRAKVUF (in dom0) and the VM's CPU are on the same NUMA core. This might be easier to accomplish with a secondary control domain and XSM where you pin dom0 on one NUMA core and the second control domain on the other.

**Comment by skvl** [comment]
@tklengyel could you please provide some examples of `xl` commands and VM configs?

Thanks in advance.

**Comment by tklengyel** [comment]
FYI https://wiki.xenproject.org/wiki/Xen_Security_Modules_:_XSM-FLASK & https://github.com/tklengyel/xen/commit/96cb42ae16a362a6f701d9db067dd9a95333b5d6

**Comment by skvl** [comment]
@tklengyel thanks!

Several questions:
* The patch you've mentioned creates `drakvuf` FLASK role?
* Do you suggest to create stubdom for Qemu and stubdom for drakvuf and place them on the same node as VM? E.g. create cpupool "trap" of 4 cores for VM with 2 cores and 2 stubdoms on single node.

**Comment by skvl** [comment]
@tklengyel I failed to get accurate documentation on how to create secondary control domain.

Though I've found some related links about stub domains:
* https://xenbits.xen.org/gitweb/?p=mini-os.git;a=summary
* https://wiki.xenproject.org/wiki/Device_Model_Stub_Domains
* https://tinyvmi.github.io/quick-start-windows/
* https://wiki.xenproject.org/wiki/Linux_stub_domains

But I'm not sure if I dig into right direction.

Could you please to point me into some useful documentation please?

Thanks in advance!

**Comment by aoshiken** [comment]
@skvl 
Have you advanced with that?

**Comment by skvl** [comment]
The issue gone away.

**Comment by aoshiken** [comment]
But just upgrading to Xen v4.14, doing the CPU pinning or both things?
