### ISSUE TITLE
How to stop drakvuf programmatically (and keeping the vm alive)

### ISSUE THREAD

**Issue by Id3aFly** [tklengyel/drakvuf#1110]
Hey guys,

right now I'm writing a test for my drakvuf plugin.
How can I stop drakvuf when the test was successfull?

I would like to keep my VM running. I experimented with throw and exit() but both lead to a crash of my vm (or at least it is frozen)

Thank you

**Comment by tklengyel** [comment]
Call `drakvuf_interrupt` with an arbitrary signal number, like
```
drakvuf_interrupt(drakvuf, 22);

**Comment by Id3aFly** [comment]
Thank you!
