### ISSUE TITLE
Change memcaccess.access?

### ISSUE THREAD

**Issue by Id3aFly** [tklengyel/drakvuf#1113]
Hey guys,

When hitting a trap I would like to use its callback to change its memaccess.access. So let's say at first a trap is set up to be active at VMI_MEMACCESS_X and after it was hit the first time it shall only react to  VMI_MEMACCESS_R or e.g. VMI_MEMACCESS_W.

How would I realize this? So far, I've seen that e.g. vmi.c can update a trap within its inject_trap_mem method (which combines the old and new access type). But there is no method to solely swap the access. 

Is there any clever way or am I required to delete the old trap and add a new one with the other access type?

Thank you

**Comment by tklengyel** [comment]
Just register a new drakvuf trap with the new access and clear the old one in the old one's callback.

**Comment by Id3aFly** [comment]
Thanks Tamas.
If I set the memaccess.access to VMI_MEMACCESS_WX, is it possible to find out whether the trap arouse from W or X?

**Comment by tklengyel** [comment]
You can tell what the access was the triggered the trap, yes.

**Comment by tklengyel** [comment]
FYI: https://github.com/libvmi/libvmi/blob/6d65cc3dea8646a8bf8298aa09794f1183fd8317/libvmi/events.h#L258

**Comment by Id3aFly** [comment]
Wow, that sounds perfect. 

I tried to use _vmi_get_mem_event_ but the **resulting test_event is empty**. Is there a mistake? (I used VMI_MEMACCESS_INVALID because this parameter is required). 

Example code:
```
static event_response_t myTrap(drakvuf_t drakvuf, drakvuf_trap_info_t *info) {
   vmi_instance_t vmi = drakvuf_lock_and_get_vmi(drakvuf);
   vmi_event_t *test_event = vmi_get_mem_event(vmi, info->trap->memaccess.gfn, VMI_MEMACCESS_INVALID);
   drakvuf_release_vmi(drakvuf);
   drakvuf_remove_trap(drakvuf, info->trap, nullptr);
   return VMI_EVENT_RESPONSE_NONE;
}
```

If this approach is wrong, what is the recommended method to retrieve a  _vmi_event_t_ or the _mem_access_event_t_ or _out_access_?

Within my trap there is a _drakvuf_trap_info_t_ parameter that contains _uint64_t event_uid_. I would guess that I could somehow extract the data referring to that event_uid from libvmi. But I did not find a matching [API](http://libvmi.com/api/)

![grafik](https://user-images.githubusercontent.com/5712180/104126199-8eeda380-535b-11eb-8cf3-35e2346ae499.png)

**Comment by tklengyel** [comment]
So currently the `libdrakvuf` API does not give you direct access to the libvmi event structure - you shouldn't need it. I was just showing you the LibVMI as a reference that the information is available. When you are building plugins with DRAKVUF what you want to do is if you want to do different things when the access is `X` vs `W` is to register two drakvuf traps, one for `X` and one for `W`, with different callbacks specified for each.

**Comment by icedevml** [comment]
`event_uid` is not for LibVMI, it's currently only used to correlate events between Intel Processor Trace and DRAKVUF

**Comment by Id3aFly** [comment]
Thank you guys. Then I'm going to use two different traps!
