### ISSUE TITLE
Differences of event_response_t

### ISSUE THREAD

**Issue by Id3aFly** [tklengyel/drakvuf#1116]
Hey guys,

In some classes like the example below I see that the the usual return of traps is `VMI_EVENT_RESPONSE_NONE`.

https://github.com/tklengyel/drakvuf/blob/17a81d71ea20cee68c0cb45c155ce4dc6fe2d495/src/plugins/memdump/memdump.cpp#L519

In the declaration (events.h) there are also other responses as e.g. `VMI_EVENT_RESPONSE_DENY, VMI_EVENT_RESPONSE_EMULATE, VMI_EVENT_RESPONSE_SLAT_ID`. Where can I find more information what happens if I return these?

Thank you

**Comment by icedevml** [comment]
e.g. for int3 type of breakpoint, the situation is as follows:

https://github.com/tklengyel/drakvuf/blob/036faa4ee4fbdc1cffda794f3216a9c5d268f94d/src/libdrakvuf/vmi.c#L554
(just follow what happens to the `rsp` variable in this function)

so the flags returned by all applicable callbacks will be ORed together and then passed to LibVMI.

I think this is generally done on Xen vm_event level, so the implementation details are going to be there.

**Comment by tklengyel** [comment]
The flag values are documented in both the LibVMI event header and in the Xen vm_event header to which they are ultimately get translated. Be aware that currently plugins are expected not to set any response flag. It is exposed to plugins only to aid experimenting. 

Some flag combination are incompatible and there are no sanity checks in place, so libdrakvuf does not ensure you will have a working VM if two plugins not knowing about each other set different flags in response to the same event. There be dragons.

**Comment by Id3aFly** [comment]
Ah, very good to know! Thanks once more guys!
