### ISSUE TITLE
Unify configuration files

### ISSUE THREAD

**Issue by kscieslinski** [tklengyel/drakvuf#1117]
Some plugins let user decide which syscalls/winapi calls to hook on and which action to trigger when such hook is invoked.

The ones I know about:
i) `syscalls` plugin allows user to specify a file with a list of syscalls to log. It also takes a parameter whether or not to log results of these syscalls,
ii) `apimon` plugin allows user to specify a file with winapi calls that should be logged,
iii) `memdump` plugin uses same file as apimon, but checks for presence of `stack` keyword. If such entry is found it sets a hook with a callback that performs heuristic to dump memory.

It might be more intuitive for a user if we unify them into a single file. Parsing then can be shared and moved to separate file, taking out the unnecessary complexity from plugins.

**Comment by tklengyel** [comment]
I understand where this request is coming from but on the other hand the more "standardization" we push on to plugins the harder it will be for someone new to quickly clobber together a new plugin. I would rather let the plugin decide whether it wants to read its config from a config file (and what format that config file is), from the cli, a combination of the two or something else. Even if that results in a more fragmented "overall" interface. Most users don't run all the plugins and actually pick-and-choose the ones they run with anyway.

If a plugin you want to use don't support the config format you prefer? Add it as an option to the plugin.

**Comment by kscieslinski** [comment]
Ok, I do understand the idea behind such approach. Thanks for detailed explanation. I'm closing the issue.

**Comment by BonusPlay** [comment]
Hmmm, my idea was to fill [`plugins_options`](https://github.com/tklengyel/drakvuf/blob/master/src/plugins/plugins.h#L120-L146) struct from file passed as an argument. That way it's backwards compatible & both options can be used at once (some params from file, some in cmd line).
