### ISSUE TITLE
Changes to printing behaviour?

### ISSUE THREAD

**Issue by Id3aFly** [tklengyel/drakvuf#1136]
Hey guys,

Did drakvuf change something with its "print to shell" behaviour?

I recently was debugging my code for my hyperbee pull request #1133. When stepping over executions like fmt::print and jsonfmt::print I expected the regarding content to be printed. But within my shell no new lines appeared.
Only after like ~8 executions (of fmt::print or jsonfmt::print) the ~8 lines got printed. 

Is there something like a buffer in the background that is just printed if it reaches a certain size? It would be interesting to know how to disable that, to get (if one wants) each single line printed on its own.
My plugin is based on the quite recent master commit "bae104035f7692a76dca890901c500f9df856942".

My custom implementation (which I use for my master thesis) is based on "7633c2f90648f10245748dd880161b63455ee37f" and each single line is printed on its own. That why I guess, something has changed in between.

Maybe it has something to do with "5681f92fc0dcb2362b6b296dd1ca50909a1bb783" Refactor output format printers (#1118) which is the direct commit after "7633c2..."?

Has one of you an idea?
Thank you
Klaus

**Comment by chivay** [comment]
I guess that this commit could introduce this behavior: 2f52692f67bfd9678603eaa6fb6e1e9208c8fb13

**Comment by Id3aFly** [comment]
I see that this is an improvement in general. But during debugging I would like to print each output on its own.

I can test right now, but it looks to me as this line is reponsible for the buffer size/threshold:
https://github.com/tklengyel/drakvuf/commit/2f52692f67bfd9678603eaa6fb6e1e9208c8fb13#diff-57b431cc7642ae3fe878f53ad3ec1778b46395eece67f708a4418bb69e00d242R127

Is there a possibility to have a compile flag increasing/decreasing the buffer size?

**Comment by chivay** [comment]
IMO it would be best to do it automatically, i.e. call `isatty` and disable buffering when printing to terminal.

**Comment by Id3aFly** [comment]
Is buffering disabled when changing `return sync(4 * 1024);` to `  return sync(0);`? Or has something more to be done?

**Comment by chivay** [comment]
From my understanding, yes, https://github.com/tklengyel/drakvuf/blob/2f52692f67bfd9678603eaa6fb6e1e9208c8fb13/src/plugins/output_format/ostream.cpp#L132-L133

the `sync_impl` function is invoked when the given threshold (default 4KiB) is exceeded. Changing the value to 0 should be enough.
