### ISSUE TITLE
drakvuf_get_module_list() returns successfully with module_list=NULL

### ISSUE THREAD

**Issue by v-p-b** [tklengyel/drakvuf#114]
I watch process startups and if a process with a specific name is starting I fetch the loaded module list with `drakvuf_get_module_list()`. The API always works fine on a fresh attach. Starting parallel instances of the same process also works fine. However if I start and close the same executable twice so that the second instance will get the same entry in the page table (same CR3) the API always fails on the second run. 

I added some debug output and found that either looking up the LDR or the head of the module list results in 0 being read into the corresponding output variables. The corresponding VMI reads always succeed so in some cases `drakvuf_get_module_list()` returns with success (true) although `module_list = NULL`.

It might worth noting that using `drakvuf_get_process_name()` and `drakvuf_get_process_pid()` in the same function always work as expected.

**Comment by tklengyel** [comment]
If it returns success but the module_list is still NULL that means that the process legitimately has no module list. Does this happen early on during the startup of the process? It may be that Windows still hasn't finished setting up the process. If in doubt, pause the VM at that point and run Volatility's ldrmodules to verify.

**Comment by v-p-b** [comment]
So this is a valid state for the API to return, and the caller needs to check the validity of the module list pointer if I understand correctly. I'm closing this issue and will reopen if possible enhancements to `drakvuf_get_module_list()` occur. Thanks!

**Comment by tklengyel** [comment]
Right, from an API design perspective it may make sense to do that check in the library side and return false if it's NULL, as it may be a more intuitive way of using the function.

**Comment by v-p-b** [comment]
Question: How should a caller handle the situation described above?

The most naive/primitive (also ugly) solution is to wait until the LDR is populated. I've been trying this to confirm that the problem is indeed related to timing, but using `std::this_thread::sleep_for()` didn't lead to a "good" PEB state. Here's the code:

```cpp
    // VMI lock is aquired
    drakvuf_get_module_list(drakvuf, process, &module_list);
    while(module_list==0){
        printf("Sleeping...\n");
        this_thread::sleep_for(chrono::seconds(1));
        drakvuf_get_module_list(drakvuf, process, &module_list);
    }   
```

Am I doing this right? If no, how should I do it? If yes what else could cause this behavior?

**Comment by tklengyel** [comment]
I would first verify with Volatility that indeed the module list is empty for that process. If that loop constantly returns NULL but Volatility sees a module, then it might be a cache-related problem in LibVMI. So let's start there.

**Comment by v-p-b** [comment]
Volatility successfully extracts the module list.

DRAKVUF debug prints:
```
EPROC found
PID found: 610
PEB found: 7ffd7000
LDR found: 777e7880
MODLIST found: 0
```

At this point my test plugin pauses the VM so I can manually start Volatility in another window:

```
# vol.py --profile=Win7SP0x86 -l vmi://domid/65 -p 1552 dlllist
Volatility Foundation Volatility Framework 2.5
************************************************************************
CrashMe.exe pid:   1552
Command line : "C:\Users\b\Desktop\CrashMe.exe"


Base             Size  LoadCount Path
---------- ---------- ---------- ----
0x00400000    0x89000     0xffff C:\Users\b\Desktop\CrashMe.exe
0x77710000   0x13c000     0xffff C:\Windows\SYSTEM32\ntdll.dll
0x77130000    0xd4000     0xffff C:\Windows\system32\kernel32.dll
0x758e0000    0x4a000     0xffff C:\Windows\system32\KERNELBASE.dll
0x70490000    0xeb000     0xffff C:\Windows\system32\dbghelp.dll
0x76f50000    0xac000     0xffff C:\Windows\system32\msvcrt.dll
0x77350000    0xc9000     0xffff C:\Windows\system32\USER32.dll
0x77520000    0x4e000     0xffff C:\Windows\system32\GDI32.dll
0x77850000     0xa000     0xffff C:\Windows\system32\LPK.dll
0x76930000    0x9d000     0xffff C:\Windows\system32\USP10.dll
0x76cb0000    0x7b000     0xffff C:\Windows\system32\comdlg32.dll
0x772f0000    0x57000     0xffff C:\Windows\system32\SHLWAPI.dll
0x74900000   0x19e000     0xffff C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7600.16385_none_421189da2b7fabfc\COMCTL32.dll
0x75b60000   0xc49000     0xffff C:\Windows\system32\SHELL32.dll
0x71180000    0x51000     0xffff C:\Windows\system32\WINSPOOL.DRV
0x778a0000    0xa0000     0xffff C:\Windows\system32\ADVAPI32.dll
0x76d30000    0x19000     0xffff C:\Windows\SYSTEM32\sechost.dll
0x77080000    0xa1000     0xffff C:\Windows\system32\RPCRT4.dll
0x76b50000   0x15c000     0xffff C:\Windows\system32\ole32.dll
0x77260000    0x8f000     0xffff C:\Windows\system32\OLEAUT32.dll
0x77000000    0x1f000        0x2 C:\Windows\system32\IMM32.DLL
0x76a70000    0xcc000        0x1 C:\Windows\system32\MSCTF.dll
0x74780000    0x40000        0x3 C:\Windows\system32\uxtheme.dll
0x73700000    0x13000        0x1 C:\Windows\system32\dwmapi.dll
0x757b0000     0xc000        0x1 C:\Windows\system32\CRYPTBASE.dll
```

**Comment by tklengyel** [comment]
Can you also run the ldrmodules plugin and post it?

So if Volatility finds the dlllist what could be an issue is if the v2p
translation is cached in the libvmi tlb. Try installing Libvmi with the
caches disabled.

**Comment by v-p-b** [comment]
This is the output:

```
# vol.py --profile=Win7SP0x86 -l vmi://domid/66 -p 1168 ldrmodules
Volatility Foundation Volatility Framework 2.5
Pid      Process              Base       InLoad InInit InMem MappedPath
-------- -------------------- ---------- ------ ------ ----- ----------
    1168 CrashMe.exe          0x758e0000 True   True   True  \Windows\System32\KernelBase.dll
    1168 CrashMe.exe          0x00400000 True   False  True  \Users\b\Desktop\CrashMe.exe
    1168 CrashMe.exe          0x76930000 True   True   True  \Windows\System32\usp10.dll
    1168 CrashMe.exe          0x77130000 True   True   True  \Windows\System32\kernel32.dll
    1168 CrashMe.exe          0x75b60000 True   True   True  \Windows\System32\shell32.dll
    1168 CrashMe.exe          0x74780000 True   True   True  \Windows\System32\uxtheme.dll
    1168 CrashMe.exe          0x77000000 True   True   True  \Windows\System32\imm32.dll
    1168 CrashMe.exe          0x76a70000 True   True   True  \Windows\System32\msctf.dll
    1168 CrashMe.exe          0x77080000 True   True   True  \Windows\System32\rpcrt4.dll
    1168 CrashMe.exe          0x778a0000 True   True   True  \Windows\System32\advapi32.dll
    1168 CrashMe.exe          0x772f0000 True   True   True  \Windows\System32\shlwapi.dll
    1168 CrashMe.exe          0x74900000 True   True   True  \Windows\winsxs\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7600.16385_none_421189da2b7fabfc\comctl32.dll
    1168 CrashMe.exe          0x77710000 True   True   True  \Windows\System32\ntdll.dll
    1168 CrashMe.exe          0x77520000 True   True   True  \Windows\System32\gdi32.dll
    1168 CrashMe.exe          0x76b50000 True   True   True  \Windows\System32\ole32.dll
    1168 CrashMe.exe          0x71180000 True   True   True  \Windows\System32\winspool.drv
    1168 CrashMe.exe          0x76f50000 True   True   True  \Windows\System32\msvcrt.dll
    1168 CrashMe.exe          0x757b0000 True   True   True  \Windows\System32\cryptbase.dll
    1168 CrashMe.exe          0x77350000 True   True   True  \Windows\System32\user32.dll
    1168 CrashMe.exe          0x76cb0000 True   True   True  \Windows\System32\comdlg32.dll
    1168 CrashMe.exe          0x77850000 True   True   True  \Windows\System32\lpk.dll
    1168 CrashMe.exe          0x77260000 True   True   True  \Windows\System32\oleaut32.dll
    1168 CrashMe.exe          0x70490000 True   True   True  \Windows\System32\dbghelp.dll
    1168 CrashMe.exe          0x76d30000 True   True   True  \Windows\System32\sechost.dll
    1168 CrashMe.exe          0x73700000 True   True   True  \Windows\System32\dwmapi.dll
```

Now recompiling libvmi...

**Comment by v-p-b** [comment]
So I recompiled libvmi with `--disable-address-cache` and also recompiled DRAKVUF. Now the `drakvuf_add_trap()` calls in my plugin constructor never seem to return :(

**Comment by tklengyel** [comment]
That's odd. Do the LibVMI examples still work?

**Comment by tklengyel** [comment]
Also, did you notice that DRAKVUF prints for your process that the PID is 610, but Volatility says it's 1552? How did you get the "process" address that you pass to the get_module_list function? If you use drakvuf_find_eprocess it should find the same PID as Volatility does.

**Comment by v-p-b** [comment]
That PID is in hex: 0x610=1552 

The libvmi examples seem to work just fine.

**Comment by v-p-b** [comment]
On the other hand, traps are added just reeeally slowly...

**Comment by v-p-b** [comment]
So I can't reproduct the original issue with the cache disabled so it seems that this was actually the cause. The plugin runs noticeably slower though (module list: blink of an eye -> seconds), do you think it's possible get up-to-date module information while preserving performance?

**Comment by tklengyel** [comment]
Ah OK. Good, I'll update the install instructions to disable the cache.

I also have a fix for the slow trap addition in the module_loop branch, I
just don't have the PR tester online so it will be a while before I can
merge it.
On Apr 11, 2016 11:33, "buherator" <notifications@github.com> wrote:

So I can't reproduct the original issue with the cache disabled so it seems
that this was actually the cause. The plugin runs noticeably slower though
(module list: blink of an eye -> seconds), do you think it's possible get
up-to-date module information while preserving performance?

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/tklengyel/drakvuf/issues/114#issuecomment-208465269>

**Comment by v-p-b** [comment]
Sounds great! 

I'd keep this issue open until we see how module_loop resolves things if that's not a problem.
