### ISSUE TITLE
What does vmi_lock_guard do?

### ISSUE THREAD

**Issue by Id3aFly** [tklengyel/drakvuf#1170]
I am currently wondering, what exactly the line
`auto vmi = vmi_lock_guard(drakvuf);`
is good for?

Of course is returns the vmi_instance vmi, but what else is it needed fore?

Following its call I see it starts `drakvuf_lock_and_get_vmi`.
Does this pause the hypervisor, or just a process, or something similar? What is it locking, and why is the locking required?

Thank you

**Comment by tklengyel** [comment]
LibVMI is not thread safe. This lock guard ensures that all code interacting with LibVMI does it in a thread-safe way.

**Comment by Id3aFly** [comment]
Thanks :)

And when talking about "lock": If I register a trap (e.g. the execute or breakpoint traps used in codemon) and a event starts its callback, at what point is the hypervisor paused?

**Comment by tklengyel** [comment]
The vCPU is paused when the int3 instruction executes in the guest. It will remain paused until the event response is sent to xen with the flag saying its OK to resume the vCPU.

**Comment by Id3aFly** [comment]
Ok, let's assume I have 2 vCPUs and a execute trap for page_a.
If vCPU1 fetches an instruction from page_a, it gets paused and my trap is activated.
Can vCPU2 (while the trap for vCPU1 is still active) modify page_a  in the mean time, as there is no write trap?

That would indicate, that I cannot guarantee the integrity of page_a during the trap execution?

**Comment by tklengyel** [comment]
No, by default pages that have a breakpoint are execute-only. If vCPU2 tries to modify the page it will itself trap to the hypervisor. The modification will be allowed to happen in the callback handler for the write-event, but after the write-happened the shadow-copy of the page where the breakpoint lives is refreshed (to include the new change) and then the breakpoint(s) reapplied.

**Comment by Id3aFly** [comment]
Awesome thanks!
