### ISSUE TITLE
vcpus settings for Xen and guest.cfg

### ISSUE THREAD

**Issue by Id3aFly** [tklengyel/drakvuf#1176]
Hey guys,

I'm using a [Intel® Core™ i7-4700MQ with 4 kernels and 8 threads](https://ark.intel.com/content/www/de/de/ark/products/75117/intel-core-i7-4700mq-processor-6m-cache-up-to-3-40-ghz.html). How many vcpus do I actually have and how should I distribute them over the dom0 (grub config) and domU (guest.cfg). I know that distribution depends on the requirements, but what is the max of available vcpus and what would you recommend in general?

dom0: `"GRUB_CMDLINE_XEN_DEFAULT=\" ... dom0_max_vcpus=4 dom0_vcpus_pin=1 ...`

How should I modify the settings for my win10.cfg which is used by `xl create`?
```
vcpus = 2
maxvcpus = 2
```

Thank you

**Comment by tklengyel** [comment]
There is no one-size fits all answer. I usually go with a 50/50 split, so in your case 4 vCPUs in dom0 and then 4 available for VMs. You can oversubscribe your vCPUs of course, so say 4 vCPUs in dom0 and 8 vCPUs for VMs. Depending on the workload in your VMs that may be find (for example if they are mostly idle).

**Comment by Id3aFly** [comment]
Thanks Tamas,

so the number of threads equals the number of vCPUs?

**Comment by tklengyel** [comment]
Well, I don't know what you are doing. But 4 in dom0 and 4 for VMs is a good bet if you are running DRAKVUF.

**Comment by Id3aFly** [comment]
Ok, I got that. 

My question was rather aimed at the fact that with a distribution dom0 -> 2 and domU -> 2 some resources (4 threads?) remain unused?

**Comment by tklengyel** [comment]
Only if you count a thread as a full resource ;) If you are spinning your system close to a 100% you are better off with `smt=0`.

**Comment by Id3aFly** [comment]
thank you!
