### ISSUE TITLE
Enabling/disabling plugins.

### ISSUE THREAD

**Issue by kscieslinski** [tklengyel/drakvuf#1221]
At the moment drakvuf accepts both commands:
'-a <plugin>': [Activate](https://github.com/tklengyel/drakvuf/blob/master/src/main.cpp#L200) the specified plugin
'-x <plugin>': [Don't activate](https://github.com/tklengyel/drakvuf/blob/master/src/main.cpp#L197) the specified plugin

This is confusing – as it doesn't describe the default option. Moreover in code there is suspicious [disabled_all](https://github.com/tklengyel/drakvuf/blob/master/src/main.cpp#L349) variable:
```
bool disabled_all = false; // Used to disable all plugin once
```
that when changed to `true` will not disable any of the plugins as long at least one plugin was activated?

**Proposed solution**:
Disable all plugins as default and delete `-x` option.
Add additional logic for `-a all` to enable all plugins.

Or

Enable all plugins as default and delete `-a` option.
Add additional logic for `-x all` to disable all plugins.

**Comment by tklengyel** [comment]
I don't follow the concern. By default all plugins are enabled. With -x you can disable a select plugins leaving the rest enabled. With -a you can choose to only enable select plugins leaving the rest disabled.

**Comment by aoshiken** [comment]
I'd prefer the first option proposed by @kscieslinski because having all plugins enabled by default makes a lot of noise in the logs besides if you need just the logs/behaviour of 1 or 2 plugins you end up with a very long command line.

If drakvuf will continue with all plugins enabled by default at least a `-x all` would be desirable IMHO.

**Comment by tklengyel** [comment]
You can always disable plugins at compile time which would leave you with only your desired plugins activated by default. The -x all option is superflous, any use of -a implies that already.
