### ISSUE TITLE
Enabling plugins by command line...

### ISSUE THREAD

**Issue by aoshiken** [tklengyel/drakvuf#123]
...instead of the current "all or nothing" compiling approach.

IMHO would be very useful so we can enable just the plugins we are interested on or even using a keyword for enabling all (`ALL` for example). E.g.:

-  `drakvuf -E exmon -E filedelete -E objmon`
-  `drakvuf -E ALL`

By default no plugins would be enabled.

**Comment by tklengyel** [comment]
I agree, this would be useful but I think the other way around: disabling plugins that were compiled in but should not activate.

**Comment by aoshiken** [comment]
Ok, this is not an issue for me :)
