### ISSUE TITLE
RFC | Failed to add trap for paged out Windows syscall

### ISSUE THREAD

**Issue by skvl** [tklengyel/drakvuf#1242]
With _Windows 7 SP1 x64_ and _Windows 10 build 1803_ I have noticed `drakvuf_add_trap` fails while trapping `NtCreateProcessEx`, `NtOpenKeyTransacted`, etc. Thus resulting in _procmon_, _regmon_, _syscalls_ initialization failures.

The bug is unstable. Though I was able to debug that at some points of time the functions been paged out:
![windbg](https://user-images.githubusercontent.com/20656851/122579720-dd674280-d05d-11eb-9941-a4c03cac9ee7.png)

From the picture above one could conclude that `NtOpenKeyTransacted` been paged out. Though `NtOpenKeyTransactedEx` is accessible. The debugger session is done for _minidump_ file produced from Xen state file of VM.

I suggest that the bug is a result of high memory pressure.

To deal with the bug I would like to re-use the idea of _libusermode_: inject "page faults" if `drakvuf_add_trap()` fails. Though I understand that this is hard to achieve while plug-in initialization. So any help is appreciated.

Other questions to consider is how _drakvuf_ deals with trapped pages been paged out? Does it loose such traps? How to detect or prevent such a situation?

Thanks!

-----

*UPDATE 1* I should notice that page file is disabled.

Though there is some option for executables. Code segments of executables could be paged out because it could not be modified. So system could load it at any time.

Though I didn't know that ntoskrnl is just a mere executable from the perspective of Windows!

**Comment by tklengyel** [comment]
We don't currently track when pages with traps are paged out. From DRAKVUF perspective those traps are still considered active. Of course when those pages are brought back in to a different location, the traps would no longer trigger. Or something else gets moved into the physical range, we would get callbacks of unrelated stuff.

**Comment by tklengyel** [comment]
A work-around if you run into this situation a lot is to just disable paging.

**Comment by tklengyel** [comment]
Ideally we would hook the kernel's paging mechanism to keep an eye when pages of interest are moved around.

**Comment by skvl** [comment]
I should notice that page file is disabled.

Though there is some option for executables. Code segments of executables could be paged out because it could not be modified. So system could load it at any time.

Though I didn't know that `ntoskrnl` is just a mere executable from the perspective of Windows!

**Comment by skvl** [comment]
The issue been caused by image creation fault: the page file have not been disabled.
