### ISSUE TITLE
[Linux] Kernel structure layout randomization

### ISSUE THREAD

**Issue by kscieslinski** [tklengyel/drakvuf#1265]
I'm creating this issue to discuss how to approach a problem with [kernel structures randomization](https://lwn.net/Articles/722293/). Maybe someone has an idea what kind of wrappers might be worth implementing.

**Update**
I'm closing this issue, as it turned out that libvmi does already handle this problem: [ref](https://github.com/libvmi/libvmi/blob/3f5b0d5b3cef8639df4cd7ff52d42e04baf262fd/libvmi/json_profiles/volatility_ist.c#L112)

**Example**
Let's say we would like to retrieve a `mm_struct->context` field offset ([mm_struct](https://elixir.bootlin.com/linux/latest/source/include/linux/mm_types.h#L387)).

This is how the `mm_struct` is defined:
```c
struct mm_struct {
	struct {
		struct vm_area_struct *mmap;
		[...]
                mm_context_t context;
                [...]
         }  __randomize_layout;
         unsigned long cpu_bitmap[];
}
```
And in `kernel.json` file it's represented like this:
```json
"mm_struct": {
    "size": 1024,
    "fields": {
        "cpu_bitmap": {
            "type": {
                "count": 0,
                "kind": "array",
                "subtype": {
                    "kind": "base",
                    "name": "long unsigned int"
                }
            },
            "offset": 1024
        },
        "unnamed_field_0": {
            "type": {
                "kind": "struct",
                "name": "unnamed_d740b18b8642642a"
            },
            "offset": 0
        }
    },
    "kind": "struct"
}
```
of course we will find `context` in `unnamed_d740b18b8642642a`, but referencing `unnamed_d740b18b8642642a` is ugly and moreover what about older kernels without this anonymous structure:
```json
"unnamed_d740b18b8642642a": {
    "size": 1024,
    "fields": {
      "arg_end": {
        "type": {
          "kind": "base",
          "name": "long unsigned int"
        },
        "offset": 312
      },
      [...]
      "context": {
        "type": {
          "kind": "struct",
          "name": "unnamed_1b032a1ce51217e5"
        },
        "offset": 744
      },
      [...]
    }
}
```

**Comment by kscieslinski** [comment]
@chivay @tklengyel @disaykin @manorit2001

**Comment by chivay** [comment]
As I've said in out private chat, it's more of an issue with anonymous unions/structures, rather than structure layout randomization. ;)

Would "flattening" the structure work - skipping this anonymous struct altogether and moving its fields directly into the structure?
This would require some rework on the profile-generation side, but could probably work quite nicely in DRAKVUF.

Unless this would break in some edge cases that I'm not seeing at this moment.  :thinking:

**Comment by manorit2001** [comment]
> As I've said in out private chat, it's more of an issue with anonymous unions/structures, rather than structure layout randomization. ;)
> 
> Would "flattening" the structure work - skipping this anonymous struct altogether and moving its fields directly into the structure?
> This would require some rework on the profile-generation side, but could probably work quite nicely in DRAKVUF.
> 
> Unless this would break in some edge cases that I'm not seeing at this moment.

Can't this introduce redundancy?

**Comment by chivay** [comment]
> Can't this introduce redundancy?

What do you mean by redundancy? If you're worried about some cases where
 field name would be ambiguous, I think that It wouldn't be also valid C. Consider this:
 
```c
struct foo {
    struct {
        int a;
    };
    int a;
};
```

```
$ clang xd.c -o xd
xd.c:5:9: error: duplicate member 'a'
    int a;
        ^
xd.c:3:13: note: previous declaration is here
        int a;
            ^
1 error generated.
```
