### ISSUE TITLE
Too much time elapsed before setting trap

### ISSUE THREAD

**Issue by aoshiken** [tklengyel/drakvuf#130]
Hi,
After recompiling libvmi for not using cache I'm experimenting BSoD due to the time elapsed for clock interrupt when setting just 1 initial trap (vm with 2 vcpus).

I will post an screenshot with the aforementioned BSoD tomorrow morning.

Regards

**Comment by tklengyel** [comment]
That's possible, depending on what trap you are adding. You don't necessarily need to disable the LibVMI cache, but it can help with some issues so that's why I recommend disabling it by default.

**Comment by aoshiken** [comment]
Well, I disabled the cache due to unexpected memory data issues, in fact, with cache disabled, all issues were gone but unfortunately the trade-off is the BSoD.

The trap is a VA one on some code of NtCreateProcess.

**Comment by tklengyel** [comment]
Yea, we will have to work on a better cache invalidation method. I have a branch that traps on all CR3 writes, it would probably be prudent to flush the cache on those events. It's in the pipeline.

**Comment by aoshiken** [comment]
Perfect, I will leave this issue open by now if you don't mind

**Comment by tklengyel** [comment]
Can you give this branch a try: https://github.com/tklengyel/drakvuf/tree/cr3 ? It should automatically flush the LibVMI cache on CR3 changes. It's not perfect but better then not having a cache at all.

**Comment by aoshiken** [comment]
So I infere Libvmi must be compiled the usual way (using cache), right?

**Comment by tklengyel** [comment]
Yeap, this branch will take care of flushing the cache when needed (mostly).

**Comment by aoshiken** [comment]
After some initial testing I have been unable to reproduce the memory access issues so it seems that the "CR3" branch works pretty well,  well done. :)

I will close this issue and re-open if needed.

Thanks Tamas.
