### ISSUE TITLE
Guidance Needed

### ISSUE THREAD

**Issue by mohitbhatt-du** [tklengyel/drakvuf#1371]
Dear Tamas K. Lengyel Sir,

We are undergraduate students and working on a project on malware analysis.

Following your blog, we have successfully setup drakvuf tool and it is giving us the system call traces of all the processes running in the system.

We now request you to guide us how to use drakvuf efficiently for generating various types of logs of malware executables.

We would be grateful if you can please provide us some specific commands related to:

Injecting malware files directly from dom0 (ubuntu) terminal into domU (win7)
Commands to generate various logs such as network dump info of a particular process, system calls of a particular process, file related artifacts etc.
We need to generate dataset having variety of features of malware after executing them in VM and extracting logs at Dom0.

Kindly provide your guidance so that we can move ahead further.

Thanks

Mohit

**Comment by manorit2001** [comment]
Hi, please open such questions in the discussion panel instead of issues. Also, you had asked the same question in this https://github.com/tklengyel/drakvuf/issues/1360 where Tamas has replied. Please refer to it
