### ISSUE TITLE
Traced VM runs out of memory while add new breakpoint

### ISSUE THREAD

**Issue by skvl** [tklengyel/drakvuf#1381]
In some rear cases an error like this occur:
```
1638889265.836679 envmon attempt to setup a trap for "kernelbase.dll"
...
1638889265.956195 Found module KERNELBASE.dll at 0x7ffe3d7a0000
1638889265.956681 Physmap populated? -1
...
1638889265.997616 Failed to set a trap for function kernelbase.dll::DefineDosDeviceW in PID: 4120
1638889265.997647 Failed to add a trap for DefineDosDeviceW
...
Plugin envmon startup failed!
```

I have traced this until call to `xc_domain_populate_physmap_exact` in `inject_trap_pa`.

With old Xen and Qemu issues I have found similar [bug](https://bugs.xenproject.org/xen/bug/46):
```
BTW the reason for the failure seems to be that QEMU runs out of ram (xen: failed to populate ram at 80110000, so xc_domain_populate_physmap_exact failed)
```

And Qemu patch [increase maxmem before calling xc_domain_populate_physmap](https://qemu-devel.nongnu.narkive.com/9mMuPeVl/patch-increase-maxmem-before-calling-xc-domain-populate-physmap):
```
Increase maxmem before calling xc_domain_populate_physmap_exact to avoid the risk of running out of guest memory.
```

Should we consider similar fix?

**Comment by tklengyel** [comment]
No, the error is because you are running out of shadow memory, not because of maxmem. We already set maxmem to `~0` with drakvuf (see https://github.com/tklengyel/drakvuf/blob/master/src/libdrakvuf/vmi.c#L1712). You just need to assign more shadow_memory to your VM if you are running into issues like this. Try 64 or even 128.

**Comment by skvl** [comment]
Thanks very much for clarification. But how to assign more shadow_memory to VM?
