### ISSUE TITLE
Non-ascii logs generated by syscall and sysret plugins

### ISSUE THREAD

**Issue by 3niol4** [tklengyel/drakvuf#1398]
Hello, I'm using drakvuf through drakvuf-sandbox, and I noticed that sometimes non-ascii logs are generated by the `syscall` and `sysret` plugins, specifically in the `Method` field of the logs.

I'm using the `Procmon64` binary (directly pulled from the [website](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon)) to test.

The full command line that gets  created by the sandbox is:

`drakvuf -a apimon -a memdump -a procmon -a syscalls -a tlsmon -o json -F -j 60 -t 600 -i 4048 -k 0x1aa002 -d ws1-1 --dll-hooks-list /tmp/drakrun/ws1-1/hooks.txt --memdump-dir /tmp/drakrun/ws1-1/output/dumps --ipt-dir /tmp/drakrun/ws1-1/output/ipt --ipt-trace-user --codemon-dump-dir /tmp/drakrun/ws1-1/output/ipt --codemon-log-everything --codemon-analyse-system-dll-vad -r /var/lib/drakrun/profiles/ws1_kernel.json -e C:\Users\user\Desktop\Procmon64.exe -c C:\Users\user\Desktop`

Example problematic logs would be (unflattened for readability):

```json
{
    "Plugin": "sysret",
    "TimeStamp": "1646300483.858736",
    "PID": 3400,
    "PPID": 632,
    "TID": 5416,
    "UserName": "SessionID",
    "UserId": 0,
    "ProcessName": "\\\\Device\\\\HarddiskVolume2\\\\Windows\\\\System32\\\\SecurityHealthService.exe",
    "Method":"/\x8b b",
    "EventUID": "0x7b1366",
    "Module": "nt",
    "vCPU": 0,
    "CR3": "0x7c5f0002",
    "Syscall": 161,
    "Ret": 0,
    "Info": "STATUS_SUCCESS"
}
```

```json
{
    "Plugin": "syscall",
    "TimeStamp": "1646300466.552653",
    "PID": 292,
    "PPID": 632,
    "TID": 2328,
    "UserName": "SessionID",
    "UserId": 0,
    "ProcessName": "\\\\Device\\\\HarddiskVolume2\\\\Windows\\\\System32\\\\svchost.exe",
    "Method":"/\x8b b",
    "EventUID": "0x785a65",
    "Module": "nt",
    "vCPU": 1,
    "CR3": "0x6f52002",
    "Syscall": 161,
    "NArgs": 0
}
```

It seems that in all cases, the `Syscall` field of the log is `161`. I don't really know enough about the internals of drakvuf or Windows to know if that's relevant though...

Sorry for the somewhat lackluster report, but that's all I have been able to gather.

**Comment by tklengyel** [comment]
The Method field is not actually used by the syscall plugin, so it's just noise.

**Comment by tklengyel** [comment]
OK, I'm able to reproduce it. It happens if you encounter a Windows build with a new syscall that has no internal definition.

**Comment by tklengyel** [comment]
It would be helpful if you could build a debug version of DRAKVUF (`./configure --enable-debug`) and then run it with `-v`. Save the stderr output to a file (`./drakvuf ... 1>log 2>&1`) and you should see something like:

```
Syscall NtQueryPerformanceCounter has no internal definition. New syscall?
```

We should probably add a definition for that syscall that you bumped into.

**Comment by 3niol4** [comment]
Here is the list running the same sample as before:

```
Syscall NtAcquireCrossVmMutant has no internal definition. New syscall?
Syscall NtAllocateUserPhysicalPagesEx has no internal definition. New syscall?
Syscall NtContinueEx has no internal definition. New syscall?
Syscall NtCreateCrossVmEvent has no internal definition. New syscall?
Syscall NtCreateCrossVmMutant has no internal definition. New syscall?
Syscall NtPssCaptureVaSpaceBulk has no internal definition. New syscall?
Syscall NtLoadKey3 has no internal definition. New syscall?
```
