### ISSUE TITLE
help, how to use proctracer to trace a proc

### ISSUE THREAD

**Issue by zdzhjx** [tklengyel/drakvuf#142]
I want to trace notepad.exe, so I use proctracer config: test.config, content is following 

{
"modules":["kernel32.dll", "ntdll.dll"]
}

and I put files kernel32.dll.proctracer.json  ntdll.dll.proctracer.json in the same dirctory.

then, I run the command
# drakvuf -r win7.rekall.json  -d w7drakvuf  -P test.json -i $notepad_pid
I got output messge, it seems that in function "cb", 
if (p->mod_config.find(proc_name) == p->mod_config.end() || p->trace_status.find(info->regs->cr3) != p->trace_status.end()){
        printf("not found %x [%s]???\n",process, proc_name);
        free(proc_name);
        drakvuf_release_vmi(drakvuf);
        return 0;
    }
drakvuf will run this branch.

so I change this code to:
    if( strcmp(proc_name,"notepad.exe") != 0 ) 
    { 
        printf("quit,[%s]\n", proc_name);
        free(proc_name);
        drakvuf_release_vmi(drakvuf); 
        return 0;
    }

there will show endless loop messge like:

Switching altp2m and to singlestep on vcpu 1
reset trap, switching 1->1
reset trap, switching 1->1
INT3 event vCPU 1 altp2m:0 CR3: 0x7e6652c0 PA=0x2c9a40b4 RIP=0x77f070b4
[BINTRACE] hit - CR3: 0x7e6652c0 Module: ntdll.dll Offset: 0x470b4 
[BINTRACE] hit - CR3: 0x7e6652c0 Module: ntdll.dll Offset: 0x470b4 
[BINTRACE] hit - CR3: 0x7e6652c0 Module: ntdll.dll Offset: 0x470b4 
[BINTRACE] hit - CR3: 0x7e6652c0 Module: ntdll.dll Offset: 0x470b4 
[BINTRACE] hit - CR3: 0x7e6652c0 Module: ntdll.dll Offset: 0x470b4 
[BINTRACE] hit - CR3: 0x7e6652c0 Module: ntdll.dll Offset: 0x470b4 
[BINTRACE] hit - CR3: 0x7e6652c0 Module: ntdll.dll Offset: 0x470b4 
Switching altp2m and to singlestep on vcpu 1

I am confused how to use it trace a program, please give me some help, thanks.

**Comment by v-p-b** [comment]
First of all PROCTRACER is in highly experimental state, I recommend to use my branch which is more up-to-date:

https://github.com/v-p-b/drakvuf/tree/proctracer_origin/

The -P switch doesn't work yet, you have to name your PROCTRACER config "proctracer.json". 

If you want to trace notepad.exe you have to include the "notepad.exe" string in the proctracer config too, this way the process should be found automatically , there's no need for hardcoding the process name. Be careful though, as module names are case-sensitive!

I don't know how the output format changed (the original code emits messages prefixed with PROCTRACE not BINTRACE), but the messages you provided indicates that the tracing works as expected.

**Comment by zdzhjx** [comment]
Thanks for the quick response!

Using "notepad.exe" is for test , the output message I changed, because that is too long, :)


OK, I will test your branch, could you please give me the config file?

**Comment by v-p-b** [comment]
The config should look something like this (I'm not sure about lowercase...):

```js
{
"modules":["notepad.exe","kernel32.dll", "ntdll.dll"]
}
```

You have to generate profiles for the three indicated modules yourself and name them appropriately.

**Comment by zdzhjx** [comment]
How to get profiles of notepad.exe/kernel32.dll/ntdll.dll ? Pre-used is from ​https://github.com/allewwaly/new-drakvuf, which do not have notepad.exe

**Comment by v-p-b** [comment]
The README  of the linked repository points to: 

http://rekall-forensic.blogspot.hu/2014/02/the-rekall-profile-repository-and.html

I'm currently using radare2 to analyse EXEs and DLLS and some Python to transform the output to JSON. You can create empty profiles like this:

```js
{"$FUNCTIONS": {}}
```

These will be parsed correctly although no trace points will be added. So for example you can use the DLL profiles you donwloaded with an empty profile for the main notepad.exe module.

**Comment by zdzhjx** [comment]
YES, It works!  

Thanks a lot
