### ISSUE TITLE
Problem with clone.pl

### ISSUE THREAD

**Issue by Gleb-H** [tklengyel/drakvuf#1470]
I completed all the steps following the link:
https://github.com/tklengyel/drakvuf/wiki/Automated-malware-analysis-setup
and after running this command: 
`sudo dirwatch poll windows7-sp1 /etc/xen/windows7.cfg /root/windows7-sp1.json 1148 /var/www/malware_incoming /var/www/malware_processing /var/www/malware_finished 1 /home/hlib/drakvuf/tools/clone.pl /home/hlib/drakvuf/tools/preconfig.sh /home/hlib/drakvuf/tools/drakvuf.sh /home/hlib/drakvuf/tools/cleanup.sh /home/hlib/drakvuf/tools/tcpdump.sh`

I get an error `Can't get domid of domain name 'windows7-sp1-1-clone', maybe this domain does not exist.`

```
hlib@hlib-MS-7788:~/drakvuf$ sudo dirwatch poll windows7-sp1 /etc/xen/windows7.cfg /root/windows7-sp1.json 1148 /var/www/malware_incoming /var/www/malware_processing /var/www/malware_finished 1 /home/hlib/drakvuf/tools/clone.pl /home/hlib/drakvuf/tools/preconfig.sh /home/hlib/drakvuf/tools/drakvuf.sh /home/hlib/drakvuf/tools/cleanup.sh /home/hlib/drakvuf/tools/tcpdump.sh
DRAKVUF dirwatch v1.0-git20220508205830+e983e7e-1 Copyright (C) 2014-2022 Tamas K Lengyel
** MOVING FILE FOR PROCESSING: mv /var/www/malware_incoming/Calculator.exe /var/www/malware_processing/Calculator.exe
[0] Making clone
** RUNNING COMMAND: /home/hlib/drakvuf/tools/clone.pl windows7-sp1 1 /etc/xen/windows7.cfg
Can't get domid of domain name 'windows7-sp1-1-clone', maybe this domain does not exist.
[0] Clone creation failed, trying again
** RUNNING COMMAND: /home/hlib/drakvuf/tools/clone.pl windows7-sp1 1 /etc/xen/windows7.cfg
Can't get domid of domain name 'windows7-sp1-1-clone', maybe this domain does not exist.
[0] Clone creation failed, trying again
** RUNNING COMMAND: /home/hlib/drakvuf/tools/clone.pl windows7-sp1 1 /etc/xen/windows7.cfg
Can't get domid of domain name 'windows7-sp1-1-clone', maybe this domain does not exist.
[0] Clone creation failed, trying again
** RUNNING COMMAND: /home/hlib/drakvuf/tools/clone.pl windows7-sp1 1 /etc/xen/windows7.cfg
Can't get domid of domain name 'windows7-sp1-1-clone', maybe this domain does not exist.
[0] Clone creation failed, trying again
** RUNNING COMMAND: /home/hlib/drakvuf/tools/clone.pl windows7-sp1 1 /etc/xen/windows7.cfg
^CBatch processing started 1 samples (total 1)
g_mutex_clear() called on uninitialised or locked mutex
Аварийный останов
hlib@hlib-MS-7788:~/drakvuf$ 
```
Also in the directory `/tmp` i get the file `drakvuf_pipe_windows7-sp1-1-clone` that is 0 bytes and the file `windows7-sp1-1-clone.config` with the following content:
```
arch = 'x86_64'
name = "windows7-sp1-1-clone"
maxmem = 3000
memory = 3000
vcpus = 2
maxvcpus = 2
builder = "hvm"
boot = "cd"
hap = 1
on_poweroff = "destroy"
on_reboot = "destroy"
on_crash = "destroy"
vnc = 1
vnclisten = "0.0.0.0"
vga = "stdvga"
usb = 1
usbdevice = "tablet"
audio = 1
soundhw = "hda"
viridian = 1
altp2m = 2
shadow_memory = 32
vif = [ 'type=ioemu,model=e1000,bridge=xenbr1.1,script=vif-openvswitch,backend=0
disk = [ 'phy:/dev/vg/windows7-sp1-1-clone,hda,w', 'file:/home/hlib/win/windows7.iso,hdc:cdrom,r' ]
```
I noticed that the "vif line" didn't have a `' ]`at the end, so I changed the clone.pl script to have that line with a `' ]`at the end, but that didn't fix my problem. I am getting the same error. Help me fix the problem please.

**Comment by manorit2001** [comment]
You can maybe give [drakvuf-sandbox](https://github.com/CERT-Polska/drakvuf-sandbox) a try. The DRAKVUF wiki page doesn't seem to be updated after 2017 so it might have a few things that might be broken wrt the current revision

**Comment by Gleb-H** [comment]
> You can maybe give [drakvuf-sandbox](https://github.com/CERT-Polska/drakvuf-sandbox) a try. The DRAKVUF wiki page doesn't seem to be updated after 2017 so it might have a few things that might be broken wrt the current revision

I installed drakvuf-sandbox, but it only allows one file to be loaded. And I need to analyze about 10 thousand files. Or maybe I can fix drakvuf-sandbox for using set of files? Can you help me to do this please?

**Comment by manorit2001** [comment]
> I installed drakvuf-sandbox, but it only allows one file to be loaded. And I need to analyze about 10 thousand files. Or maybe I can fix drakvuf-sandbox for using set of files? Can you help me to do this please?

I had seen this script somewhere which can maybe be used to push samples in sandbox using CLI. I believe it was [this](https://github.com/CERT-Polska/drakvuf-sandbox/blob/master/drakrun/drakrun/drakpush.py). I haven't tried using it but maybe you can see if you can tweak it to your use case, maybe it might help ig.

**Comment by catsuryuu** [comment]
Yes, `drakpush` script should be a perfect match for your usecase I think.
You can just run it 10k times and the internal `karton-system` will queue all the samples.
If you have any problems with it, don't hesitate to create an issue at the [DRAKVUF Sandbox](https://github.com/CERT-Polska/drakvuf-sandbox) repository :)

**Comment by manorit2001** [comment]
This can be closed i think
