### ISSUE TITLE
injector causing BSOD on Win7x86SP1

### ISSUE THREAD

**Issue by JimmyTwoShoes** [tklengyel/drakvuf#148]
Following the automated malware analysis documentation. Dirwatch is running and picking samples. Preconfig.log records "Process startup failed". Trying the commands myself, injector is causing a BSOD:

```
[root@drakvuf drakvuf]# ./src/injector /root/win7x86sp1.json win7x86sp1 1920 calc.exe
Init VMI on domID 16 -> win7x86sp1
Rekall profile: '_KTRAP_FRAME' has no 'Rip' member
Failed to find offset for _KTRAP_FRAME:Rip
Reservation increased? 0 with new gfn: 0x3ff598
Xen altp2m view created with idx: 1 idr: 2
Injector starting calc.exe through PID 1920
Target PID 1920 with DTB 0x7ef1e2e0 to start 'calc.exe'
Starting injection loop
Current thread: 1972. Base: 0x854c51d8. ApcQueueable: 1.
Kernel stack base: 0x920e3ed0. Limit: 0x920e1000
Found target pid of 1920. PEB @ 0x7ffdf000. LDR @ 0x77ce7880. INLOADORDER @ 0x2117d0.
Found module in PID 1920: Explorer.EXE
Found module in PID 1920: ntdll.dll
Found module in PID 1920: kernel32.dll
        CreateProcessA @ 0x762d2082
APC Normal routine @ 0x762d2082. Kernel routine @ 0x8091742f
APC injected at 0x920e1000
Wrote trap to 0x762d2082. Backup: 139
^CFinished with injection. Ret: 0
Process startup failed
close_vmi_drakvuf finished
[root@drakvuf drakvuf]#
```
At `Wrote trap to 0x762d2082. Backup: 139` the BSOD occurs and injector hangs. BSOD is PAGE_FAULT_IN_NONPAGED_AREA. 

Tried again, injecting to notepad.exe instead:
```
[root@drakvuf drakvuf]# ./src/injector /root/win7x86sp1.json win7x86sp1 776 calc.exe
Init VMI on domID 17 -> win7x86sp1
Rekall profile: '_KTRAP_FRAME' has no 'Rip' member
Failed to find offset for _KTRAP_FRAME:Rip
Reservation increased? 0 with new gfn: 0x3df596
Xen altp2m view created with idx: 1 idr: 2
Injector starting calc.exe through PID 776
Target PID 776 with DTB 0x7ef21320 to start 'calc.exe'
Starting injection loop
Current thread: 852. Base: 0x855aea58. ApcQueueable: 1.
Kernel stack base: 0x94fffed0. Limit: 0x94ffd000
Found target pid of 776. PEB @ 0x7ffdc000. LDR @ 0x77187880. INLOADORDER @ 0x401878.
Found module in PID 776: notepad.exe
Found module in PID 776: ntdll.dll
Found module in PID 776: kernel32.dll
        CreateProcessA @ 0x76302082
APC Normal routine @ 0x76302082. Kernel routine @ 0x8091742f
APC injected at 0x94ffd000
Wrote trap to 0x76302082. Backup: 139
^CFinished with injection. Ret: 0
Process startup failed
close_vmi_drakvuf finished
[root@drakvuf drakvuf]#
```
It sometimes works...
```
[root@drakvuf drakvuf]# ./src/injector /root/win7x86sp1.json win7x86sp1 1916 calc.exe
Init VMI on domID 19 -> win7x86sp1
Rekall profile: '_KTRAP_FRAME' has no 'Rip' member
Failed to find offset for _KTRAP_FRAME:Rip
Reservation increased? 0 with new gfn: 0x3ce480
Xen altp2m view created with idx: 1 idr: 2
Injector starting calc.exe through PID 1916
Target PID 1916 with DTB 0x7ef21300 to start 'calc.exe'
Starting injection loop
Current thread: 1920. Base: 0x854e1280. ApcQueueable: 1.
Kernel stack base: 0x94d0bed0. Limit: 0x94d09000
Found target pid of 1916. PEB @ 0x7ffdf000. LDR @ 0x77637880. INLOADORDER @ 0x2717d0.
Found module in PID 1916: Explorer.EXE
Found module in PID 1916: ntdll.dll
Found module in PID 1916: kernel32.dll
        CreateProcessA @ 0x76462082
APC Normal routine @ 0x76462082. Kernel routine @ 0x828d202f
APC injected at 0x94d09000
Wrote trap to 0x76462082. Backup: 139
INT3 Callback @ 0x76462082. PID 1916. CR3 0x7ef21300
Stack setup finished and return trap added @ 0x775a6f7d
INT3 Callback @ 0x775a6f7d. PID 1916. CR3 0x7ef21300
RAX: 0x1
Injected PID: 1228. TID: 1084
Finished with injection. Ret: 1
Process startup success
close_vmi_drakvuf finished
[root@drakvuf drakvuf]#
```

BSOD screenshot attached.
![xen-bsod](https://cloud.githubusercontent.com/assets/18746226/15316389/1d2c6aec-1c60-11e6-9781-78db1e86dcd9.png)

**Comment by JimmyTwoShoes** [comment]
Wondering if this is related to #25.

Will check tomorrow when I'm back in the office.

**Comment by tklengyel** [comment]
#25 has been caused by the use of multiple vCPUs when it was not yet supported, so it's likely unrelated. I'm in the process of reworking the injector code to use drakvuf traps so it will likely help with issues like this. In the meanwhile what you can do is create a snapshot of the VM and try injection. If it works, it will work, if not, restore and let it run for a bit, open/close the process you want to hijack, then save it and try again until you find a stable point where it doesn't crash the guest.

**Comment by JimmyTwoShoes** [comment]
Changing my VM to 1 CPU, I've had 5 for 5 successful injections. Spent about 10 minutes before that saving/restoring VM, restarting the target process with 2 and then 4 CPU cores configured - BSOD each time.

Changed the VM back to 2 cores, managed to get 1 successful inject of calc.exe via explorer.exe. 2nd attempt == BSOD.

Back to 1 core, 5 successful injects.

I know of malware that checks the CPU/core count prior to execution and if <2, abort.

**Comment by tklengyel** [comment]
Can you also try with Windows 7 x64?

**Comment by JimmyTwoShoes** [comment]
Win7x64RTM VM, 2 Cores: 10/10 injects, no BSOD.

Rebooted, another 10/10 injects, no BSOD.

**Comment by tklengyel** [comment]
Yea, injection works a little bit differently on 32-bit and 64-bit and we have only been testing the 32-bit injection with single-vCPU VMs. I'm in the process of reworking it anyway so I'll try to fix this issue. In the meanwhile, just use 64-bit Win7 if you want to run with multiple vCPUs.

**Comment by tklengyel** [comment]
You may want to give the branch in #150 a try, it might be stable for 32-bit Win7 as well.
