### ISSUE TITLE
Injector adds an extra empty argument on Linux

### ISSUE THREAD

**Issue by X-m7** [tklengyel/drakvuf#1486]
When trying out the injector on Linux (with the execproc method) I noticed that the new process gets an additional blank argument, so for example if I try injecting `/usr/bin/rm` to a Bash instance running in a terminal I get `/usr/bin/rm: cannot remove '': no such file or directory` instead of a missing operand error, and if I try injecting `/usr/bin/pkill` it ends up acting on all processes. If I do add an argument with `-f` with `rm` to delete a nonexistent file I get two errors instead of one, with the second one being for `''`, so I guess that blank argument gets tacked on to the end every time.

The full command I used is `injector -r /path/to/kernel.json -d TestVM-Linux -l -i 1579 -m execproc -e /usr/bin/rm`. If I add `-v` to that command I see two lines saying `Total arguments: 0` and `Args 0: /usr/bin/rm`.

I am using DRAKVUF at commit 447e2943e7a475bad31cc50c0c7bdb1e2b86e5af from the automated build, and the VM is running Ubuntu 20.04.4 with kernel 5.13.0-51-generic.

**Comment by manorit2001** [comment]
Hey @disaykin , will https://github.com/tklengyel/drakvuf/pull/1492 fix this?

**Comment by disaykin** [comment]
@manorit2001 yes

**Comment by disaykin** [comment]
@X-m7 try latest drakvuf commit, please.

**Comment by X-m7** [comment]
Can confirm latest commit fixes it, thanks!
