### ISSUE TITLE
Malware can detect xen environment

### ISSUE THREAD

**Issue by saaie** [tklengyel/drakvuf#151]
Malware can detect Xen environment by checking registry key "HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\Disk\Enum" SubKey "0" that contains "IDE\DiskQEMU_HARDDISK".
Is there any way to prevent this problem?

**Comment by tklengyel** [comment]
You can change the string in qemu and recompile it. However, with DRAKVUF we are not trying to hide the fact that the machine is virtualized, we only try to hide the monitoring components. From the guest you should not be able to tell if you are running on vanilla Xen or one with DRAKVUF.
