### ISSUE TITLE
Latest commit in master fails to compile

### ISSUE THREAD

**Issue by jeinstos** [tklengyel/drakvuf#156]
The latest commit fails to compile. Seems like a different version of `libvmi` is being used than the one publicly available in the Drakvuf branch of the libvmi repo.

**Comment by jeinstos** [comment]
It was a problem in my system configuration. Pulling from the drakvuf libvmi repository does solve the compilation issues.

**Comment by tklengyel** [comment]
Make sure you check out the latest drakvuf branch. If you have checked it
out previously you will need to delete the branch and check it out again.
