### ISSUE TITLE
Error in running Drakvuf

### ISSUE THREAD

**Issue by ravifatty** [tklengyel/drakvuf#1586]
I am working on setting up drakvuf. On running drakvuf, i am geeting this error. Please help
`1673115424.562174 DRAKVUF v1.1-git20230105184407+42212a4-1 Copyright (C) 2014-2023 Tamas K Lengyel
VMI_ERROR: xen_start_single_step error: no system support for event type
Failed to register singlestep for vCPU 0
VMI_ERROR: xc_altp2m_switch_to_view returned rc: -1
Failed to switch on default view
Failed to initialize DRAKVUF: drakvuf_init() failed
root@drak-VirtualBox:/home/drak/drakvuf# sudo ./src/drakvuf -r windows7-sp1.json -d 5
1673115430.756454 DRAKVUF v1.1-git20230105184407+42212a4-1 Copyright (C) 2014-2023 Tamas K Lengyel
VMI_ERROR: xen_start_single_step error: no system support for event type
Failed to register singlestep for vCPU 0
VMI_ERROR: xc_altp2m_switch_to_view returned rc: -1
Failed to switch on default view
Failed to initialize DRAKVUF: drakvuf_init() failed
`

**Comment by tklengyel** [comment]
Sounds like the CPU you are trying to run on doesn't have the required features, in this case MTF singlestepping.

**Comment by ravifatty** [comment]
Thanks Tamas for the help. I am using ubuntu 20 over VirtualBox 7. If you can please guide what do we do to enable MTF support.

**Comment by BonusPlay** [comment]
Don't use virtualbox as it doesn't support required CPU features.

**Comment by tklengyel** [comment]
You should be able to run DRAKVUF inside VMWare Workstation if you enable nested virtualization options. It's going to be slow but you can use it to experiment.

**Comment by ravifatty** [comment]
Thanks. Will check it.

**Comment by BonusPlay** [comment]
@ravifatty Please provide output of `lscpu` command.

**Comment by ravifatty** [comment]
I am retrying it but getting the same error. As requested output of lscpu is 
`Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              4
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           140
Model name:                      11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
Stepping:                        1
CPU MHz:                         2803.196
BogoMIPS:                        5606.39
Hypervisor vendor:               Xen
Virtualization type:             full
L1d cache:                       48 KiB
L1i cache:                       32 KiB
L2 cache:                        1.3 MiB
L3 cache:                        12 MiB
NUMA node0 CPU(s):               0-3
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu de tsc msr pae mce cx8 apic sep mca cmov pat clflush acpi mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc rep_good nopl
                                  nonstop_tsc cpuid tsc_known_freq pni pclmulqdq monitor est ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hyper
                                 visor lahf_lm abm 3dnowprefetch cpuid_fault ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase bmi1 avx2 bmi2 erms avx512f avx512dq rdseed a
                                 dx avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 avx512vbmi avx512_vbmi2 gfni vaes vpclmulqdq 
                                 avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm md_clear arch_capabilities`

**Comment by BonusPlay** [comment]
I believe you're missing EPT feature inside the VM. The CPU is quite new, so I doubt it lacks any hardware features. Are you sure you checked all checkboxes under CPU tab in VMware Workstation?
