### ISSUE TITLE
procmon changed log format

### ISSUE THREAD

**Issue by BonusPlay** [tklengyel/drakvuf#1588]
Procmon has changed it's log format. On the first glance, it's missing `Method` fields in output. This has broken it's integration with drakvuf-sandbox.

**Comment by tklengyel** [comment]
Sounds like the issue belongs to drakvuf-sandbox

**Comment by BonusPlay** [comment]
It's drakvuf that broke API, not drakvuf-sandbox. I understand that there's no guarantee of a stable API, but current logs format is missing the most important part "what happened". It contains "how it happened" (here's the new PID, new TID, etc.) but it's missing what method actually caused this change to begin with. I've created issue for myself to fix it in a PR soon.

**Comment by tklengyel** [comment]
Yea, we don't guarantee stable log format or a stable libdrakvuf API. If drakvuf-sandbox requires such stability I would recommend using only releases, not using the latest git head.
