### ISSUE TITLE
Issue in running Drakvuf.

### ISSUE THREAD

**Issue by ravifatty** [tklengyel/drakvuf#1600]
I have tried to setup Drakvuf over VMware as virtuablbox was creating some issues. But after completing the setup process, it i try to run it. I am getting this error. 

`Failed to set HVM_PARAM_ALTP2M, RC: -1
VMI_ERROR: xc_altp2m_switch_to_view returned rc: -1`

Please help. Thanks.

**Comment by tklengyel** [comment]
You have to enable the nested virtualization settings in VMware. 
![image](https://user-images.githubusercontent.com/3172829/212914952-f979910b-26ba-47a1-8508-37a39a0e31b9.png)

**Comment by ravifatty** [comment]
Thanks for the suggestion.
