### ISSUE TITLE
xl create -c failing qemu-dm not executable not found

### ISSUE THREAD

**Issue by cvcachagua** [tklengyel/drakvuf#1604]
I am getting an error when I try to bring up a VM using xl create -c the reported problem is libxl error /usr/local/lib/xen/bin/qemu-dm is not executable: no such file or directory

xl info:
host                   : xxxxx
release                : 5.15.0-41-generic
version                : #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022
machine                : x86_64
nr_cpus                : 72
max_cpu_id             : 223
nr_nodes               : 4
cores_per_socket       : 18
threads_per_core       : 1
cpu_mhz                : 2194.843
hw_caps                : bfebfbff:77fef3ff:2c100800:00000121:0000000f:d39ffffb:00000808:00000100
virt_caps              : pv hvm hvm_directio pv_directio hap shadow iommu_hap_pt_share vmtrace gnttab-v1 gnttab-v2
total_memory           : 261596
free_memory            : 254901
sharing_freed_memory   : 0
sharing_used_memory    : 0
outstanding_claims     : 0
free_cpus              : 0
xen_major              : 4
xen_minor              : 17
xen_extra              : .0
xen_version            : 4.17.0
xen_caps               : xen-3.0-x86_64 hvm-3.0-x86_32 hvm-3.0-x86_32p hvm-3.0-x86_64
xen_scheduler          : credit2
xen_pagesize           : 4096
platform_params        : virt_start=0xffff800000000000
xen_changeset          :
xen_commandline        : placeholder dom0_mem=4096M,max:4096M dom0_max_vcpus=4 dom0_vcpus_pin=1 force-ept=1 ept=ad=0 hap_1gb=0 hap_2mb=0 altp2m=1 hpet=legacy-replacement smt=0 no-real-mode edd=off
cc_compiler            : gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
cc_compile_by          : xxxxx
cc_compile_domain      :
cc_compile_date        : Tue Jan 31 08:28:52 PST 2023
build_id               : 05207cdc613739e48ec8aac486d3d8bb01cecbd6
xend_config_format     : 4

I downloaded the repo last week, but performed a git pull again yesterday too, git version:
git 694f3f26fb91d662249b7ddc20b4a04360912ce2

Is there a work around or a fix or a way to pull in the latest xen, or use a previous xen, or is it my system does not meet the requirements?  I had performed a make clean all after pulling in an acceptable kernel (5.15.0-41-generic), and then re-performed the install (make -j4 .... instructions).  I have checked (xl list) it provides me with reasonable output.

Please, any help would be appreciated.

**Comment by cvcachagua** [comment]
Since xen cannot build /usr/local/lib/xen/bin/qumu-dm can we get a work around?

**Comment by tklengyel** [comment]
Use the pre-packaged deb files from the drakvuf-builds repo.

**Comment by cvcachagua** [comment]
I removed the old .../git/drakvuf/xen/dist/*.deb package "xen-upstream" (from dpkg -l) then downloaded the build:
ubuntu_focal_xen-hypervisor-4.17.0-generic-amd64.deb , for ubuntu 20.04,
and installed the new build -- but still no qemu-dm which still is required from 'xl create -c <path/vm.cfg>'

Just to check I also downloaded the ubuntu_focal_drakvuf-bundle-1.1-git20230221092926+8260f2f-1-generic.deb 
and installed it too, but still no qemu-dm and still cannot create a VM -- since I am checking out injection, I would need to re-build drakvuf anyway, but just decided to check if qemu-dm would be installed from that package (which I believe is most assuredly wrong).

Perhaps I did something wrong?

**Comment by tklengyel** [comment]
I'm not sure what error you are seeing but the pre-built packages are working fine. There is no such binary `qemu-dm` used by Xen. Xen uses `qemu-system-i386` for VMs.

**Comment by cvcachagua** [comment]
I am probably using something old-ish in the cfg file. This file used to work on 4.16, and this cfg has been around since 2018.

I am really wondering if the problem is my cfg line:
device_model_version="qemu-xen-traditional"

libxl_dm.c:2899 has to do with the libxl__domain_device_model call.
I will remove the line and see if that fixes it?

Here is the output of
# xl create -c /etc/xen/vm1.cfg
Parsing config from /etc/xen/vm1.cfg
libxl: error: libxl_dm.c:2899:libxl__spawn_local_dm: Domain 4:device model /usr/lib/xen/bin/qemu-dm is not executable: No such file or directory
libxl: error: libxl_dm.c:3148:device_model_spawn_outcome: Domain 4:(null): spawn failed (rc=-3)
libxl: error: libxl_dm.c:3368:device_model_postconfig_done: Domain 4:Post DM startup configs failed, rc=-3
libxl: error: libxl_create.c:1894:domcreate_devmodel_started: Domain 4:device model did not start: -3
libxl: error: libxl_domain.c:1183:libxl__destroy_domid: Domain 4:Non-existant domain
libxl: error: libxl_domain.c:1137:domain_destroy_callback: Domain 4:Unable to destroy guest
libxl: error: libxl_domain.c:1064:domain_destroy_cb: Domain 4:Destruction of domain failed

$ cat vm1.cfg
arch = 'x86_64'
name = "vm1"
maxmem = 1024
memory = 1024
vcpus = 1
maxcpus = 1
builder = "hvm"
hap = 1
acpi = 1
on_poweroff = "destroy"
on_reboot = "destroy"
on_crash = "destroy"
vnc=1
vnclisten="0.0.0.0"
vga = "stdvga"
usb = 1
usbdevice = "tablet"
viridian = 1
altp2m = 2
shadow_memory = 16
on_crash="preserve" 
device_model_version="qemu-xen-traditional"
vif = [ 'type=ioemu,model=e1000,bridge=xenbr0,mac=E4:42:A6:BA:7C:01' ]
boot = "dc"
disk = [ 'phy:/dev/vg/vm1,hda,w' , 'file:/root/cdrom/ubuntu-focal-20.04-server.iso,hdc:cdrom,r' ]

there is nothing new in /var/log/xen when run.

**Comment by cvcachagua** [comment]
That works!  I guess I no longer need to have device_model_version="qemu-xen-traditional" in the cfg, I just commented it out, now xl probably chooses qemu-xen.

What a horrible error message.

Thanks Tamas!!!  I thought the error was a build problem.

**Comment by tklengyel** [comment]
qemu-traditional is no longer built by default (or used) by Xen since the 4.16 release. There are very few edge-cases where it's needed. Not sure where you go that config from, we never used it with DRAKVUF. In case anyone needs it in the future, you need to build the Xen tools by configuring with `--enable-qemu-traditional` to make it available.
