### ISSUE TITLE
Networking set up (give internet to VM but isolate from lan with only one NIC).

### ISSUE THREAD

**Issue by lluisbessa** [tklengyel/drakvuf#1623]
Hello everyone, I set up drakvuf with the automated malware analysis procedure, changing a little bit the clone.pl (only modifications to the clone.config rewrite), preconfig.sh (injector command), and drakvuf.sh (drakvuf command). I'm trying to make that the VMs that test the malware have internet access, but not access to my LAN. 

I'm asking for three things: 
- Can i make a  createproc(windows) and execproc (linux) to configure an IP and execute the file, like "ifconfig eth0 192.168.$VLAN.5 netmask 255.255.255.0 up; /path/to/file", i think this isn't how the CreateProcessW works, but i think that execproc can work with this. Perhaps try shellexec in windows?
- The second thing is how can i make the  xenbr1 to connect to same network card than xenbr0, configure vlans, and set xenbr1 up to communicate with my router, even with being in a different vlan, also make sure that communication goes out of my network. For example with a `iptables -A FORWARD -i xenbr1.$VLAN -o 192.168.1.0/24 -j DROP` could work?
- As experts in malware, is safe to give malware access only to world wide net, not my LAN? I need to work with a RAT malware and i would like to see it's network communication going to C2 and returning.

I have a little setup on my home to learn and I have limited resources, the router doesn't accept new vlans and i only have one network card.

Any guidance will be much apreciated.

**Comment by tklengyel** [comment]
You can inject a command to configure in the network in the VM any way you want. On the host side you can't have a network card attached to two bridges but you can enable NAT and have traffic go from xenbr1 to your default route (which may be the network card in xenbr0).

**Comment by tklengyel** [comment]
As for your last question, yes, limiting access to LAN is a good idea. I would also only give limited wan access and only through some proxy so that your own IP is leaked to C&C.
