### ISSUE TITLE
Reverting the VM to a clean state

### ISSUE THREAD

**Issue by willow19** [tklengyel/drakvuf#165]
How do you quickly revert the VM to a clean state after running a malware on it?

**Comment by zashraf1337** [comment]
check out 
https://github.com/tklengyel/drakvuf/wiki/Automated-malware-analysis-setup

**Comment by zashraf1337** [comment]
Once you have a VM with proper config

you can also do the likes of the following

```
lvcreate -s -n <new logical volume snapshot name>  -L16G <original logical volume>;
#make a fifo file -  /tmp/drakvuf_pipe_XenWin7-1-clone
xl save -c XenWin7 /tmp/drakvuf_pipe_XenWin7-1-clone 2>&1 | /usr/local/sbin/xl restore -p -e /tmp/XenWin7-1-clone.config /tmp/drakvuf_pipe_XenWin7-1-clone
```

**Comment by tklengyel** [comment]
What @zashraf1337 described is correct. Feel free to reopen the issue if you are still having problems.

**Comment by Alibm73** [comment]
Hi @tklengyel  @zashraf1337 
i used the below command and it worked ok.
```
lvcreate -s -n windows7-clone -L20G /dev/vg/windows7 2>&1
mkfifo /tmp/drakvuf_pipe_windows7-clone 2>&1
```
but when i use command below i get an error:
```
xl save -c windows7 /tmp/drakvuf_pipe_windows7-clone 2>&1 | xl restore -p -e /tmp/windows7-clone.config /tmp/drakvuf_pipe_windows7-clone 2>&1;
Loading new save file /tmp/drakvuf_pipe_windows7-clone (new xl fmt info 0x3/0x0/1760)
Savefile contains xl domain config in JSON format
Failed to read config file: /tmp/windows7-clone.config: No such file or directory
```
I know `Failed to read config file: /tmp/windows7-clone.config: No such file or directory` is the error. but i don't know how to resolve it
i have a config file when i first created the vm and it's called `windows7.cfg` and saved domain when i used `xl save` command in `wiki Automated malware analysis setup` and it's called `windows7snapshot`. other than that nothing.
how should i create a config file for my clone??
