### ISSUE TITLE
Drakvuf installation failing

### ISSUE THREAD

**Issue by willow19** [tklengyel/drakvuf#166]
My Drakvuf installation fails with the following message:

win-exports.c: In function 'modlist_sym2va':
win-exports.c:147:9: warning: implicit declaration of function 'vmi_read_unicode_str' [-Wimplicit-function-declaration]
         unicode_string_t *us = vmi_read_unicode_str(vmi, ctx);
         ^
win-exports.c:147:32: warning: initialization makes pointer from integer without a cast [enabled by default]
         unicode_string_t *us = vmi_read_unicode_str(vmi, ctx);
                                ^
win-exports.c:162:17: warning: passing argument 2 of 'vmi_translate_sym2v' makes integer from pointer without a cast [enabled by default]
                 *va = vmi_translate_sym2v(vmi, ctx, (char *) symbol);
                 ^
In file included from win-exports.c:116:0:
/usr/local/include/libvmi/libvmi.h:577:8: note: expected 'addr_t' but argument is of type 'struct access_context_t *'
 addr_t vmi_translate_sym2v(
        ^
win-exports.c:162:17: warning: passing argument 3 of 'vmi_translate_sym2v' makes integer from pointer without a cast [enabled by default]
                 *va = vmi_translate_sym2v(vmi, ctx, (char *) symbol);
                 ^
In file included from win-exports.c:116:0:
/usr/local/include/libvmi/libvmi.h:577:8: note: expected 'vmi_pid_t' but argument is of type 'char *'
 addr_t vmi_translate_sym2v(
        ^
win-exports.c:162:17: error: too few arguments to function 'vmi_translate_sym2v'
                 *va = vmi_translate_sym2v(vmi, ctx, (char *) symbol);
                 ^
In file included from win-exports.c:116:0:
/usr/local/include/libvmi/libvmi.h:577:8: note: declared here
 addr_t vmi_translate_sym2v(
        ^
win-exports.c: In function 'modlist_va2sym':
win-exports.c:279:32: warning: initialization makes pointer from integer without a cast [enabled by default]
         unicode_string_t *us = vmi_read_unicode_str(vmi, ctx);
                                ^
win-exports.c:291:13: warning: passing argument 2 of 'vmi_translate_v2sym' makes integer from pointer without a cast [enabled by default]
             const char *sym = vmi_translate_v2sym(vmi, ctx, va);
             ^
In file included from win-exports.c:116:0:
/usr/local/include/libvmi/libvmi.h:596:13: note: expected 'addr_t' but argument is of type 'struct access_context_t *'
 const char* vmi_translate_v2sym(
             ^
win-exports.c:291:13: error: too few arguments to function 'vmi_translate_v2sym'
             const char *sym = vmi_translate_v2sym(vmi, ctx, va);
             ^
In file included from win-exports.c:116:0:
/usr/local/include/libvmi/libvmi.h:596:13: note: declared here
 const char* vmi_translate_v2sym(
             ^
make[3]: *** [win-exports.lo] Error 1
make[3]: Leaving directory `/home/admin123/drakvuf/src/libdrakvuf'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/admin123/drakvuf/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/admin123/drakvuf'
make: *** [all] Error 2

**Comment by tklengyel** [comment]
Make sure you have the latest version of libvmi from my drakvuf branch.

**Comment by willow19** [comment]
Resolved by updating LibVMI
