### ISSUE TITLE
Trivial beginner's question - monitor lstrcpyA

### ISSUE THREAD

**Issue by hexrays4711** [tklengyel/drakvuf#1667]
Hi everyone!

I set up Drakvuf and it is working as expected. As it is promising work in progress I examined a few use-cases which I require for my work and I currently was not able to implement:

Monitor e.g. lstrcpyA from kernel32.dll.
Adding 
kernel32.dll,lstrcpyA,log,lpstr,lpcstr
to the dll hook list and calling the apimon
-a apimon --dll-hooks-list

did not result in any change in behaviour.

By adding
msvcrt.dll,memcpy,log,lpwstr,lpwstr,uint
msvcrt.dll,memcpy_s,log,void,uint,lpwstr,uint
I could monitor all memcpy operations and it gave deep insight in parameters of called APIs.

I even built the appropriate kernel32.json:
--json-kernel32 /home/aut/kernel32.json
as well as
--json-wow-kernel32 /home/aut/wkernel32.json
but I don't see 

Are there any modifications I have to make to make this work? Do I have to flag 32-bit calls differently in the monitored apis?

Actually I'm interested in monitoring TLS traffic, but the 
-a tlsmon
did not gain any additional information.

Best regards
Thomas

**Comment by hexrays4711** [comment]
Hi,

I made some progress.  I am able to monitor 64 bit versions with lstrcpyA from kernel32.dll by creating a new plugin.

    if (!c->kernel32_profile)
    {
        fprintf(stderr, "plugin requires the JSON debugging profile for kernel32.dll!\n");
        return;
    }
    if (!c->wow_kernel32_profile)
    {
        fprintf(stderr, "plugin requires the JSON wow debugging profile for kernel32.dll!\n");
        return;
    }

    json_object* kernel32_profile = json_object_from_file(c->kernel32_profile);
    if (!kernel32_profile)
    {
        fprintf(stderr,"plugin fails to load JSON debug ingo profile for kernel32.dll\n");
        throw -1;
    }

    json_object* wow_kernel32_profile = json_object_from_file(c->wow_kernel32_profile);
    fprintf(stderr,"Loading WOW kernel32 profile: %s\n",c->wow_kernel32_profile);
    if (!wow_kernel32_profile)
    {
        fprintf(stderr,"plugin fails to load JSON wow debugging profile for kernel32.dll\n");
        throw -1;
    }

    {
        breakpoint_in_dll_module_searcher bp(kernel32_profile, "kernel32.dll");
        if (!register_trap(nullptr, trap_lstrcpyA_cb, bp.for_syscall_name("lstrcpyA")))
            throw -1;
        fprintf(stderr, "success, %p\n",bp.for_syscall_name("lstrcpyA"));
    }
    {
        breakpoint_in_dll_module_searcher bp32(wow_kernel32_profile, "kernel32.dll");
        if (!register_trap(nullptr, trap_lstrcpyA_wow_cb, bp32.for_syscall_name("lstrcpyA")))
            throw -1;
        fprintf(stderr, "success, %p\n",bp32.for_syscall_name("lstrcpyA"));
    }

    json_object_put(kernel32_profile);
    json_object_put(wow_kernel32_profile);

Calling a 64-bit binary within the win10 machine deterministically causes the trap to trigger. Although the wow profile is included for kernel32 and traps are set I don't get traps triggered for 32 bit binaries.

Can anyone please confirm that Drakvuf is currently not able to trigger 32 bit (SysWOW64) traps?

Best regards

**Comment by hexrays4711** [comment]
Hi!

Managed to do some progress. envmon monitors 32-bit code - the main problem is that these dlls don't seem to be loaded all the times which means hooking only works properly when the WOW dlls are loaded. Monitoring the loads- unloads via libmon might work.

Best regards

**Comment by hexrays4711** [comment]
Tried to modify envmon and apimon (and not libmon, as here the individual loaded wow64 dlls are loaded)  plugins for adding breakpoints when a 32 bit dll is loaded.

LdrLoadDLL seems not always to catch all loaded dlls and set the breakpoints of Userhook for WOW64 processes correctly. I saw that page table faults are performed. Conclusion: 

Setting usermode hooks on libraries works for 64 bit code. Malware that mixes 32 and 64 bit code cannot be monitored properly. Ending activities.

**Comment by hexrays4711** [comment]
Correction: Found the root cause. Starting a process through process injection causes this behaviour. If the process is started from the inside of the guest SysWOW64 (32 bit) seem to be monitored properly. Be careful when starting 32-bit processes through injection.

**Comment by tklengyel** [comment]
@hexrays4711 did you try the different injection methods?

**Comment by hexrays4711** [comment]
Hi,

not yet - I'm just aware of a call like this (process injection method):

/home/aut/drakvuf/build/drakvuf  -s -l -r /root/windows10-2004.json -d windows10-2004 \
        --codemon-filter-executable c:\\users\\aut\\Desktop\\${1}  \
        -i 5784 \
        -e c:\\users\\aut\\Desktop\\${1} \
        -c c:\\users\\aut\\Desktop\\ \
        -C --context-process ${1} \
        --json-kernel32 /home/aut/exported_json/kernel32.json \
        --json-wow-kernel32 /home/aut/exported_json/wkernel32.json \
        --json-wow /home/aut/exported_json/wntdll.json  \
        --json-kernelbase /home/aut/exported_json/kernelbase.json \
        --json-ntdll /home/aut/exported_json/ntdll.json \
        --json-ci /home/aut/ci.json \
        --json-netio /home/aut/netio.json \
        -a apimon --dll-hooks-list   /home/aut/drakvuf/src/plugins/apimon/example/modified-hooks \

Direct method is doubleclick the binary in VNC.

I did not find any documentation on other injection methods.

**Comment by hexrays4711** [comment]
Item closed. Problems can be circumvented by calling a cmd.exe that calls that binary. -e "c:\\windows\system32\\cmd.exe /c <binary to start>"
