### ISSUE TITLE
Error with filetracer & ole32 pdb

### ISSUE THREAD

**Issue by yguseto** [tklengyel/drakvuf#1673]
after @EscardosS refactor on filetracer, plugin doesnt work.
commit says we need to use ole32.json to use plugin but i cant convert ole32.pdb to json format with volatility and drakpdb

can you show me a way

**Comment by tklengyel** [comment]
Looking at #1661 I think some of that should be reversed so that the plugin could still work without `ole32_profile` being provided.

**Comment by yguseto** [comment]
I tried on Win 7 vm without ole32.json and got "VMI_ERROR: xen_request_page_fault error -1 injecting page fault exception"  + "VMI_ERROR: Could not find EPROCESS struct for pid = 2652."
