### ISSUE TITLE
Socketmon plugin

### ISSUE THREAD

**Issue by ravifatty** [tklengyel/drakvuf#1686]
i am running a windows 7 vm on xen and trying to monitor the network activity using socketmon plugin. i have already created the JSON configuration file for ntkrpamp.pdb. But do i also need to create the json config for tcpip.sys for using socketmon. Please help. I am unable to see any network activity using socketmon.

Thanks.

**Comment by tklengyel** [comment]
You do, see the instructions under "Optional: Generate usermode profiles" at drakvuf.com
