### ISSUE TITLE
Trouble understanding how `inject_trap_pa` works.

### ISSUE THREAD

**Issue by archercreat** [tklengyel/drakvuf#1693]
Hello. I'm having trouble understanding how DRAKVUF hides breakpoints from guest software. As I understood, it creates a shadow page with traps in place. Switches `current gfn` with `remapped gfn` and sets EXECUTE ONLY page but how is it implemented in code?
Specifically I don't understand the following lines of code:
```c
    container->breakpoint.guard.type = MEMACCESS;
    /* We need to merge rights of the previous traps on this page (if any) */
    container->breakpoint.guard.memaccess.access = VMI_MEMACCESS_RW;
    container->breakpoint.guard.memaccess.type = PRE;
    container->breakpoint.guard.memaccess.gfn = current_gfn;

    container->breakpoint.guard2.type = MEMACCESS;
    container->breakpoint.guard2.memaccess.access = VMI_MEMACCESS_RWX;
    container->breakpoint.guard2.memaccess.type = PRE;
    container->breakpoint.guard2.memaccess.gfn = remapped_gfn->r;
```

How does `r/w` trap on `current_gfn` and `r/w/x` trap on remapped gfn work?
I expected to see `r/w` trap on remapped gfn and `r/w/x` trap on current gfn. Thanks.

**Comment by tklengyel** [comment]
The shadow page where the traps are also part of the guest memory at a magic offset. The magic offset while not advertised via e820/efi memory map would still be accessible by a guest that knows where to look. So the guard2 rwx trap is to protect the shadow page from being accessed via the magic offset and keep it only accessible through the remapped gfn.

**Comment by archercreat** [comment]
Thank you, Tamas! I now understand that the original page under current gfn will be swapped with remapped one. So the r/w trap is actually placed on remapped page.
