### ISSUE TITLE
How do you start an exe from Drakvuf?

### ISSUE THREAD

**Issue by willow19** [tklengyel/drakvuf#172]
Suppose I have an executable called **random.exe**. How do I use it with the _-e_ option of Drakvuf? Where do I have to put it? In the environment variables, PATH or somewhere of the Windows VM?

**Comment by tklengyel** [comment]
It needs to be on the disk of the Windows VM somewhere and the -e option specifies the path of where it is.

**Comment by willow19** [comment]
I would put a long path in quotes right? Like "C:\Users\rachit\Visual Studio 2015\random.exe"?

**Comment by tklengyel** [comment]
Yes but you need to escape backslashes, essentially every backslash turns into two.
