### ISSUE TITLE
apimon doesn't work after 9/1's commit

### ISSUE THREAD

**Issue by yuno-x** [tklengyel/drakvuf#1731]
Apimon doesn't work after following commit.  
When I use drakvuf's code before 9/1's commit, apimon can work.

[Search system DLLs for hooking via VADs (not via PEB)](https://github.com/tklengyel/drakvuf/commit/3a0905b1fce7d7c613a48c90fe6626e5012104a9) ([#1698](https://github.com/tklengyel/drakvuf/pull/1698))

`
            if (drakvuf_mmvad_type(drakvuf, mmvad) != 2) // VAD_TYPE_DLL
                return false;
`

I think "drakvuf_mmvad_type(drakvuf, mmvad)" cannot return VAD_TYPE_DLL.  
So this code surely returns false.

**Comment by onemid** [comment]
I've encountered the same problem recently. If you use `drakvuf-sandbox` and use `draksetup postinstall` to generate the PDB JSON profile, it may lack `_MMVAD_FLAGS` bitfields information in the `kernel.json` (located at `/var/lib/drakrun/profiles/kernel.json` or a similar path), which is an essential part to fetch the `VadType` flag.

To work around this issue, you can take a look at [https://github.com/libvmi/libvmi/blob/12d3a8cc4d81033ff0b5c737ca35f54bcaf0264b/tests/ntkrnlpa.pdb.bd8f451f3e754ed8a34b50560ceb08e31.rekall.json#L17220-L17270](url) and try to fill in the missing part in the kernel.json.

Here's my configuration:

VM OS: Windows 7 SP1 x64

Replace the `_MMVAD_FLAGS` value with the following:
```json
{
    "_MMVAD_FLAGS": [
            8,
            {
                "CommitCharge": [
                    0,
                    ["BitField", {
                        "start_bit": 0, 
                        "end_bit": 51, 
                        "target": "unsigned long"
                    }]
                ],
                "NoChange": [
                    0,
                    ["BitField", {
                        "start_bit": 51, 
                        "end_bit": 52, 
                        "target": "unsigned long"
                    }]
                ],
                "VadType": [
                    0,
                    ["BitField", {
                        "start_bit": 52, 
                        "end_bit": 55, 
                        "target": "unsigned long"
                    }]
                ],
                "MemCommit": [
                    0,
                    ["BitField", {
                        "start_bit": 55, 
                        "end_bit": 56, 
                        "target": "unsigned long"
                    }]
                ],
                "Protection": [
                    0,
                    ["BitField", {
                        "start_bit": 56, 
                        "end_bit": 61, 
                        "target": "unsigned long"
                    }]
                ],
                "Spare": [
                    0,
                    ["BitField", {
                        "start_bit": 61, 
                        "end_bit": 63, 
                        "target": "unsigned long"
                    }]
                ],
                "PrivateMemory": [
                    0,
                    ["BitField", {
                        "start_bit": 63, 
                        "end_bit": 64, 
                        "target": "unsigned long"
                    }]
                ]
            }
        ]
}
```
The `start_bit` and `end_bit` might vary for x86 or x64 OS.

**Comment by yuno-x** [comment]
Thank you for sharing.

I attempted this method, but unfortunately, it didn't work.
I am using drakvuf instead of drakvuf-sandbox, and a JSON file is created through drakpdb.
Although making modifications to the generated JSON file, apimon did not function as expected.
I am using Windows 10 (x64) as the guest OS and that may make a difference.

**Comment by yuno-x** [comment]
It may not be the root of the problem, but when I removed the block of "if" statements in the program code, drakvuf worked as expected.
