### ISSUE TITLE
Plugin etwmon startup failed!

### ISSUE THREAD

**Issue by XingZhiKaBi** [tklengyel/drakvuf#1732]
I tried to follow the construction steps on the official website to build drakvuf. And drakVuf runs well when installing Win7. But when Win7 installation was completed, the system restarted. 
Then I run the command 
` sudo vmi-win-guid name windows7-sp3`
found that the PDB GUID changed and turned into “daddb88936de450292977378f364b1101”.
So I try to rebuild and run drakvuf. It shows:
`sudo ./build/drakvuf -r /root/windows7-sp3.json -d 8
1697972607.698313 DRAKVUF v1.1-ee0bc46 Copyright (C) 2014-2023 Tamas K Lengyel
Plugin etwmon startup failed!`

**Comment by XingZhiKaBi** [comment]
when I run 
`sudo vmi-process-list windows7-sp3`
It can output the information like
`[  324] csrss.exe (struct addr:fffffa80043ce060)
[  360] csrss.exe (struct addr:fffffa8003284060)
[  368] wininit.exe (struct addr:fffffa8003280060)
[  396] winlogon.exe (struct addr:fffffa8004f5e3e0)
[  456] services.exe (struct addr:fffffa8004f95900)`

**Comment by tklengyel** [comment]
If you don't need that plugin you can just disable it.
