### ISSUE TITLE
How to automated batch analysis

### ISSUE THREAD

**Issue by qth1991** [tklengyel/drakvuf#1743]
like cuckoo sandbox put batch samples into  /mnt/mnt/sanitizer/input, and start analysis, the result will conduct in /path/to/cuckoo/storage/analyses

**Comment by tklengyel** [comment]
For a basic setup see https://github.com/tklengyel/drakvuf/wiki/Automated-malware-analysis-setup. For more advanced you might want to check the frontend https://github.com/CERT-Polska/drakvuf-sandbox
