### ISSUE TITLE
Information regarding processor specific feature change by DRAKVUF

### ISSUE THREAD

**Issue by Preetixen** [tklengyel/drakvuf#179]
Hi,

Could you please provide me some information regarding the modifcation done in processor-specific features by DRAKVUF.

For example, To limit the execution of RDTSC instruction, some analyzers modifies TSC bit which can be seen by invoking CPUID instruction..

**Comment by tklengyel** [comment]
I have really no idea what you are asking.

**Comment by Preetixen** [comment]
Actually Some tools like Ether disable the TSC flag for guest view to limit the in-guest timing attacks.
RDTSC is executed for timing-related information. In analysis environment, analyzer tool generally works slow.

To make the in-memory writes easier, Ether also disables the PAE (physical address extension) and PSE (Page size extension) which are again CPU specific features.

I am asking for some modification in CPU specific information by DRAKFUV.

**Comment by tklengyel** [comment]
There are no such modifications with DRAKVUF and IMHO they are not a good idea either as they would easily reveal the non-standard nature of the sandbox. Like why the hell would you disable PAE or PSE? These seem to have been just shortcuts during Ether's development to just get something working. Also, it didn't disable rdtsc to the guest, it just turned it a counter that's incremented only when rdtsc is executed which is also a bad idea. I suggest reading the paper `nEther: In-guest Detection of Out-of-the-guest Malware Analyzers` which points out a bunch of issues with Ether.
