### ISSUE TITLE
BUG Memevent callback called whatever the type of memaccess violation

### ISSUE THREAD

**Issue by masthoon** [tklengyel/drakvuf#183]
When you register multiple MEMEVENT traps with different access rights, all the callbacks are called  indifferently of the type of memaccess violation.

**Example :** I set up two memevents on the same physical page, the first is an execute trap (_VMI_MEMACCESS_X_) and the other one is a read/write trap (_VMI_MEMACCESS_RW_). When data is read from that page, both traps callbacks are called.

Can Drakvuf filter the traps using _event->mem_event.out_access_ (from LibVMI) and _trap->memaccess.access_ in [pre_mem_cb](https://github.com/tklengyel/drakvuf/blob/4085bc629a9d2ade7749e21d6c95c0355b8c2ea6/src/libdrakvuf/vmi.c#L286) and [post_mem_cb](https://github.com/tklengyel/drakvuf/blob/4085bc629a9d2ade7749e21d6c95c0355b8c2ea6/src/libdrakvuf/vmi.c#L188) ?

Thanks

**Comment by tklengyel** [comment]
Hm, yes we can add a filter to ensure only the appropriate callbacks are called.
