### ISSUE TITLE
How to use drakvuf on XenServer 7

### ISSUE THREAD

**Issue by xiaoyuyang** [tklengyel/drakvuf#189]
Thanks for helping me on googlegroup. https://groups.google.com/forum/#!topic/vmitools/4YB_3fKq9sE
I already enabled feature altp2m for platform. But Drakvuf still can not work on XenServer 7.0.
I find that feature altp2m need to be enabled for target vm by adding "altp2mhvm = 1" to the config file.
But I can not find such a file on Xenserver. Is there any way to add this configuration to target vm on Xenserver 7.0?

**Comment by tklengyel** [comment]
Well, if you are using some other administration tool for XenServer and not xl, then you need to find where the domain configuration is stored and find a way to add the option. Post back here if you were able to track it down!

**Comment by tklengyel** [comment]
Also, depending on your usecase, XenServer7 is not recommended for DRAKVUF as it exposes some critical vulnerabilities that malware may use to detect/subvert DRAKVUF. The recommended base is Xen 4.7 with the extra patches applied from my github repository. So unless you know you will not be dealing with any malicious software in the guest, using XenServer7 is not advised.

**Comment by xiaoyuyang** [comment]
Thanks. I will try Xen 4.7.
And I figured out that feature altp2m can be enabled by libxc api: 
xc_hvm_param_set(xci, domid, HVM_PARAM_ALTP2M, 1)

**Comment by tklengyel** [comment]
Thanks, good to know! I'll close this for now but feel free to reopen any time.
