### ISSUE TITLE
Can I singlestep one vcpu when the whole VM is paused?

### ISSUE THREAD

**Issue by shibin1992** [tklengyel/drakvuf#190]
"Solutions to this problem exist already. For example we can pause all vCPUs while the one violating the access is single-stepped." ------your blog "xen altp2m"

------------------------------------------------------
**my code:**
vmi_reset_trap()
{
 vmi_resume_vm();
}

event_callback()
{
  vmi_pause_vm(vmi);
  vmi_step_event(vmi, event, event->vcpu_id, 1, vmi_reset_trap);
}

------------------------------------------------------------
Hi,tklengyel:
I am trying to realize your solution mentioned above. But vmi_step_event seems to be also paused when vm is paused.
So I wander: For the existing interface in libvmi, can I singlestep one vcpu when the VM is paused?

Looking forward to your answer! Thank you very much!

**Comment by tklengyel** [comment]
Unfortunately that solution is only possible theoretically, Xen doesn't expose an API to let this happen. When you pause the domain all vCPUs get paused, and unfortunately it is not possible to unpause only a single vCPU. The feature could be added to Xen in the future though.
