### ISSUE TITLE
Breakpoint not triggering on a page with a VMI_MEMACCESS_X trap

### ISSUE THREAD

**Issue by masthoon** [tklengyel/drakvuf#192]
If you place a breakpoint in a page trapped (_VMI_MEMACCESS_X_), the breakpoint won't trigger.

The EPT violation will raise first and Drakvuf will handle it by switching to another view (_VMM_PAGETABLE_ID to altp2m_idr_). The problem is that the breakpoint isn't present on **idr** view, so the handler of the breakpoint will never be called.

I fixed it by calling all the breakpoint handlers of the physical address if the violation is a execute access in **_pre_mem_cb_**.

I can open a Pull Request if you want.

**Comment by tklengyel** [comment]
Hi, yes that sounds like a sensible solution! Please open a PR for this. Thanks!
