### ISSUE TITLE
Setting up a breakpoint resets the right of the page

### ISSUE THREAD

**Issue by masthoon** [tklengyel/drakvuf#193]
When you place a breakpoint on a page, Drakvuf uses that page as a shadow copy, allocates another one to write the breakpoint and changes the mapping to link the gfn to the new page in the **idx** view.

Drakvuf also adds a guard2 trap (_VMI_MEMACCESS_RW_) to hide the breakpoint and to catch modifications on the breakpoint page. But, if the original page was trapped on execute, Drakvuf doesn't reapply the old right on the new page and the _VMI_MEMACCESS_X_ memevent is lost.

In order to fix it, I merged the [guard2 rights](https://github.com/tklengyel/drakvuf/blob/098103540d4544ff5a301782bd7390f5790e87d4/src/libdrakvuf/vmi.c#L743) with the right of the old page (shadow copy), I can open a Pull Request if you want.

**Comment by tklengyel** [comment]
Thanks for finding this! Yes, please open a pull request.
