### ISSUE TITLE
a crash in  vmi.c

### ISSUE THREAD

**Issue by zdzhjx** [tklengyel/drakvuf#197]
void remove_trap(drakvuf_t drakvuf,
                 const drakvuf_trap_t *trap)
{
    vmi_instance_t vmi = drakvuf->vmi;

    switch(trap->type) {
    case BREAKPOINT:
    {
        struct wrapper *container =
            g_hash_table_lookup(drakvuf->breakpoint_lookup_trap, &trap);
        xen_pfn_t current_gfn = container->breakpoint.pa >> 12; // will crash if container==NULL
        uint64_t _current_gfn = current_gfn;

        if ( !container )
            return;

**Comment by tklengyel** [comment]
Can you provide more details about this issue? Where exactly does it crash and under what circumstances?

**Comment by zdzhjx** [comment]
It seems that is my bug make this crash, but I think as we used the code to test "container" :
====
    if ( !container )
        return;
====

It is better to do it before we really refer the "container".


=========
    struct wrapper *container =
        g_hash_table_lookup(drakvuf->breakpoint_lookup_trap, &trap);
    if ( !container ) // so, I move the code to here
        return;
    xen_pfn_t current_gfn = container->breakpoint.pa >> 12; // will crash if container==NULL
    uint64_t _current_gfn = current_gfn;

**Comment by tklengyel** [comment]
Ah yes I see, thanks, will fix it shortly!
