### ISSUE TITLE
installation -  Unable to load flask policy

### ISSUE THREAD

**Issue by cdshann** [tklengyel/drakvuf#213]
Followed instructions on drakvuf.com with fresh Ubuntu 14.04 and 16.04 installations. When trying to boot into Xen from Grub I am seeing an error about being unable to load the flask policy.

I also tried setting flask_enforcing to 0 and saw the same error.

Is XSM required for Drakvuf? Is there a way I can just disable it?

**Comment by masthoon** [comment]
Maybe [this](https://github.com/tklengyel/drakvuf/issues/201#issuecomment-243160502) can help you.
Try to append the line _module ${rel_dirname}/xenpolicy-4.7.0_ just after _module ${rel_dirname}/${basename} ..._.

**Comment by tklengyel** [comment]
XSM is required if you are using DRAKVUF for malware analysis. Certain components of the system are accessible by default from within the domain, so we need XSM to restrict it. If you are doing something else where you have no malicious code then you can skip it.

**Comment by tklengyel** [comment]
I've updated the installation instructions to reflect that the flask policy module should be the last module that gets loaded by grub.
