### ISSUE TITLE
Loading Initial ramdisk

### ISSUE THREAD

**Issue by Preetixen** [tklengyel/drakvuf#215]
Hi,
We are installing current version. We installed xen4.7 .updated grub and rebooted.

However, when We restart PC, we selected Ubuntu with Xen

But system can't proceed and hangs with a message on boo time: 
Loading Initial ramdisk....

please help

**Comment by tklengyel** [comment]
Please follow the installation instructions exactly from the website. You likely didn't install checkpolicy and the xsm policy file is missing required for the latest version.

**Comment by tklengyel** [comment]
This is a duplicate of #213
