### ISSUE TITLE
Userland Event - Invalid Procname and Sessionid fields

### ISSUE THREAD

**Issue by masthoon** [tklengyel/drakvuf#217]
In userland, the _GS_BASE_ (or _FS_BASE_ in 32 bits) points to the **TEB** and not the **KPCR**. So, all  functions based on _drakvuf_get_current_thread_ API don't work in userland and _drakvuf_get_current_process_ / events' fields are wrong.

If Drakvuf stores the **KPCR** address for each processor, _drakvuf_get_current_thread_ can use it to get the current thread from kernel and userland.
I assume the adress of KPCR is fixed after Windows' initialization.

Before testing my proposal, I want to know if you have any better idea ?

Thanks

**Comment by tklengyel** [comment]
That sounds like a good approach, make DRAKVUF cache the KPCR address on mov-to-cr3 for each vCPU and make the function needing the KPCR use that cache .

**Comment by tklengyel** [comment]
This has been implemented in #224
