### ISSUE TITLE
No trap callbacks

### ISSUE THREAD

**Issue by SecureStack** [tklengyel/drakvuf#219]
I have modified the proctracer plugin to trace all modules in a single process. Program seems to run fine, except I am not entering the trap callback function trace_cb. This is the code I have used to set the trap:

```c
drakvuf_trap_t *tracetrap = (drakvuf_trap_t*)g_malloc0(sizeof(drakvuf_trap_t));

//we are currently breakpointing at  the module's base address
//we can specify offset to breakpoint at specific symbols/function

addr_t offset = 0;
addr_t dll_pa = vmi_pagetable_lookup(vmi, cr3, dllbase+offset);

tracetrap->lookup_type = LOOKUP_NONE;
tracetrap->addr_type = ADDR_PA;
tracetrap->type = BREAKPOINT;
tracetrap->name = "TraceTrap";
tracetrap->cb = trace_cb;
tracetrap->u2.addr = dll_pa;

trace_info_t *ti = (trace_info_t*)g_malloc0(sizeof(trace_info_t));

ti->mod_name = strdup((char*)out.contents);
ti->offset = offset;
ti->p = p;

tracetrap->data = ti;

drakvuf_add_trap(drakvuf,tracetrap);
```

**Comment by SecureStack** [comment]
@zdzhjx, @v-p-b any suggestions?

**Comment by zdzhjx** [comment]
From your code, I suggest you to check var dll_pa, make sure it not be NULL.
It that is 0, maybe offset is wrong or it's physical address is not mapped.

**Comment by SecureStack** [comment]
@zdzhjx Thanks. Yes, I did verify the dll_pa and it is neither NULL nor 0. As of now the offset is hardcoded to 0. Which leaves the option of physical address not being mapped. I am currently running the trace against a executing process, so the physical address should be mapped?

**Comment by zdzhjx** [comment]
Var offset is RVA, I think it should not to be 0, maybe something wrong in getting offset?

**Comment by tklengyel** [comment]
So a module's base address may simply not be something that gets called. Usually you want to trap function entry points or locations otherwise known to get executed from time-to-time. So if you are not getting any callbacks then it might very well be because that address is never executed.

**Comment by SecureStack** [comment]
Got it. Now, I am trapping on the module entry points and am hitting the breakpoints. Thanks @tklengyel @zdzhjx
