### ISSUE TITLE
Fix for Xen blank startup screen in Ubuntu 14.04 guest on VMware

### ISSUE THREAD

**Issue by m73** [tklengyel/drakvuf#220]
This is just to note it down and help others if they stumble into the same. Also might want to add it to the instructions in the drakvuf site:

I was following the instructions on the drakvuf site and stranded on a blank screen on startup after the Xen installation and reboot. I fixed it by changing the grub variable so it has nomodeset:
`GRUB_CMDLINE_LINUX_DEFAULT="quiet splash nomodeset"`
in
`/etc/default/grub`

**Comment by tklengyel** [comment]
Thanks, not sure if this is a DRAKVUF issue or an Ubuntu issue or a hw issue specific to your system. Also, I running Xen in a nested setting on top of VMware is probably not going to work and is not a supported setup.

**Comment by romanshein** [comment]
Thanks. The fixed worked for 16.04
