### ISSUE TITLE
 How DRAKVUF is safe from malware which can detect break points

### ISSUE THREAD

**Issue by Preetixen** [tklengyel/drakvuf#221]
Hi,

My question is is there any mechanism to ensure the drakvuf safety from malware whcih detects break points?

Thanks

**Comment by tklengyel** [comment]
Yes. DRAKVUF's breakpoints are protected with EPT, thus malware running in the guest is unable to detect them directly or remove them. The breakpoints are also trapped directly to the hypervisor so malware can't disable them.
