### ISSUE TITLE
Detecting loading modules  dynamically

### ISSUE THREAD

**Issue by SecureStack** [tklengyel/drakvuf#222]
I am trying to detect loading modules dynamically (dll/exe) of a process. For this, I am setting up breakpoints in the PsCallimageNotifyRoutines function as shown below:

```c
drakvuf_trap_t dyn_mod_trap = {
	.lookup_type = LOOKUP_PID,
	.u.pid = 4,
	.addr_type = ADDR_RVA,
	.name = "PsCallImageNotifyRoutines",
	.module = "ntoskrnl.exe",
	.type = BREAKPOINT
};
```

The breakpoints are being set without errors but I am not receiving any call backs. What could be the problem? Is there a better way to trap/detect loading modules dynamically?

**Comment by SecureStack** [comment]
Okay, I tried disabling all other plugins to test my plugin and the breakpoints are getting hit! Is another plugin hijacking the breakpoint callback?

**Comment by tklengyel** [comment]
Having other plugins enabled should not affect the delivery of your callback. Plugins are supposed to co-exist without interfering with one-another. Can you narrow down which plugin seem to interfere with your breakpoint?

**Comment by tklengyel** [comment]
I'm closing this issue as I assume it has been resolved since it was opened. Feel free to reopen it if you still have the problem.

**Comment by SecureStack** [comment]
Yes, it was resolved. The problem was due to another locally modified plugin. Thanks.
