### ISSUE TITLE
drakvuf/libvmi broken after recent upgrade to Xen 4.8?

### ISSUE THREAD

**Issue by ChuckFoo** [tklengyel/drakvuf#225]
Hi,

I previously had a partially working Drakvuf setup that when I updated to your latest Xen 4.8 based setup yesterday became significantly more broken for me.  Currently I can't even get any of the libvmi based utilities like win-guid or process-list to talk to the VM, they immediately fail with "VMI_ERROR: Failed to get domain info for Xen.".

I suspect it has something to do with the new XSM permissions stuff, but I'm having a hard time figuring out what or why.  Using strace on process-list shows that it's getting a permission denied calling ioctl on /proc/xen/privcmd (which is owned by root and I'm running as root, which is why I think it perhaps has something to do with the XSM stuff).

I'm pretty new to using Xen and libvmi and Drakvuf, so any hints about how to more effectively chase down what is happening would be greatly appreciated!

Thanks,
Chuck Hines

**Comment by tklengyel** [comment]
Do normal Xen things like `xl list` work? Does `xl dmesg` show calls being denied? You can always try to relax the policy enforcement temporarily with `xl setenforce 0` if you suspect XSM being the issue.

Otherwise I would guess you just need to follow the installation manual from https://drakvuf.com step-by-step again. With such an upgrade you usually have to upgrade LibVMI and all other tools as well.

**Comment by ChuckFoo** [comment]
Yup, `xl list` works fine, as does starting the VM.  `xl dmesg` shows one thing being denied:

> (XEN) avc:  denied  { setup } for domid=0 scontext=system_u:system_r:dom0_t tcontext=system_u:system_r:xen_t tclass=resource

No new messages appear in `xl dmesg` output after I try `process-list` and it fails:

```
root@old-dysfunctional:~# xl create ~/xen_win7_drakvuf_inst.conf
Parsing config from /root/xen_win7_drakvuf_inst.conf
oot@old-dysfunctional:~# xl list
Name                                        ID   Mem VCPUs	State	Time(s)
Domain-0                                     0  4095     4     r-----   33786.4
drakvuf-windows7-sp1                         5  4096     2     -b----      24.8
root@old-dysfunctional:~# process-list drakvuf-windows7-sp1
VMI_ERROR: Failed to get domain info for Xen.
Failed to init LibVMI library.
```

I tried the `xl setenforce 0` suggestion, but `process-list` still fails in the same way afterwards.

After pulling down your updates I of course rebuilt and reinstalled all the things that had changed: Xen, libvmi, and Rekall, and I redid the installation things that seemed obvious to redo in the instructions, and backed out the previous manual addition of the xenpolicy module to the grub.d file since that was no longer in the instructions.  I was slightly concerned that perhaps that grub.d 20_linux_xen file should have been replaced with a new/updated one with the new Xen install but wasn't.

I'll try manually uninstalling everything, rebooting into non Xen setup, rebuilding and reinstalling and see how that goes...

**Comment by ChuckFoo** [comment]
Well, I manually cleaned out everything as best as I could, rebooted clean, and followed your instructions from the very beginning again (including pulling down fresh clones of the repos again), and same end result: get to the `win-guid` part and it fails the same way:

```
root@old-dysfunctional:~# win-guid name drakvuf-windows7-sp1
VMI_ERROR: Failed to get domain info for Xen.
Failed to init LibVMI library.
```
Tried `xl setenforce 0` again too, same behavior.  Nothing jumping out from `xl dmesg` output either.

I'll keep trying to figure out what is going on here, but any additional hints you might have for what to look for next will be greatly appreciated.

**Comment by ChuckFoo** [comment]
Nevermind, figured out what happened...apparently at some point while installing development packages I accidentally installed libxen-dev (which is still back at version 4.6) and the libvmi build was finding some older xen libs from the /usr/lib/x86_64*/  and some newer ones from the hand built xen from /usr/local/lib/ and the combo was doing odd things.

Sorry for the false alarm and thanks for the diagnostic hints.

Now I can get back to actually trying Drakvuf, assuming I didn't make another silly mistake... :)

**Comment by tklengyel** [comment]
Glad you figured it out ;)
