### ISSUE TITLE
win-guid can't identify running OS after upgrade

### ISSUE THREAD

**Issue by v-p-b** [tklengyel/drakvuf#233]
The latest version of `win-guid` provided as part of the libvmi submodule gives no output when trying to identify the running Windows 7 32-bit VMs. The VMs were created with Xen 4.6 and are successfully recognized by an older version of win-guid (I couldn't find exact version information in the provided docs). I tried to pass the VM identifiers both by name and domid in the command line. 

(Please note if I should move this to libvmi)

**Comment by tklengyel** [comment]
Yes, this is a LibVMI issue. If the win-guid tool can't find the kernel in memory you can always just go straight to the kernel on the disk and use Rekall directly on that file to get the PDB guid. Running win-guid is really just for convenience as it (used to..) work quite nicely.

**Comment by tklengyel** [comment]
Also, in my experience win-guid usually fails if Windows didn't actually boot properly (like it's in the recovery mode). Can you double check that it is actually fully booted?

**Comment by v-p-b** [comment]
The VM is fully booted yes. I'm closing this one and will open a new ticket at LibVMI. Thanks!
