### ISSUE TITLE
Error while running ./drakvuf command

### ISSUE THREAD

**Issue by amita4581** [tklengyel/drakvuf#240]
Hi,
i am successfully able to install  libvmi and generated rekall profile for ubuntu 14.04 vm, installed DRAKVUF also. when i use below command it gives the error.  any help will be appreciated.
host is running ubuntu 14.04, xen 4.8

root@amita-Inspiron-N5110:~/drakvuf/src# sudo ./drakvuf -r /root/linux.json -d 1
DRAKVUF v0.4-7a79990
xc: error: Failed to enable vm_event
 (13 = Permission denied): Internal error
VMI_ERROR: Error enabling vm_event
VMI_ERROR: Error disabling monitor vm_event ring.
Failed to initialize DRAKVUF

**Comment by v-p-b** [comment]
Check your XSM policy, domain configuration should include something like: 

`seclabel='drakvuf:vm_r:drakvuf_domU_t'`

(The values should match the XSM policy in Xen)

**Comment by amita4581** [comment]
ok i added that in config file. and run the below command. error msg gone. but this terminates the vm.

root@amita-Inspiron-N5110:~/drakvuf/src# sudo ./drakvuf -t 30  -r /root/linux.json -d 5
DRAKVUF v0.4-7a79990
root@amita-Inspiron-N5110:~/drakvuf/src# xl list
Name                                        ID   Mem VCPUs	State	Time(s)
Domain-0                                     0  2500     4     r-----    5087.8
root@amita-Inspiron-N5110:~/drakvuf/src#

**Comment by v-p-b** [comment]
Try reconfigure and compile DRAKVUF with debugging enabled (`./configure --enable-debug && make`) and paste the output when executing it with the -v switch please.

**Comment by amita4581** [comment]
sure. i reconfigure - debugging enabled-  run below command. here is the file showing the output. plz have a look

[vm-shutdown-aftercmd.tar.gz](https://github.com/tklengyel/drakvuf/files/760719/vm-shutdown-aftercmd.tar.gz)

**Comment by tklengyel** [comment]
This is pretty odd and the problem doesn't seem to be in DRAKVUF. You will need to recompile and reinstall LibVMI with the debug option enabled in `libvmi/libvmi/debug.h`, then recompile DRAKVUF too. Hopefully that log will show what is going wrong.

**Comment by amita4581** [comment]
Ok I will try this morning

**Comment by tklengyel** [comment]
@amita4581 any updates on this?

**Comment by amita4581** [comment]
Yes.. Now the vm is not shutting down but the command is running for endless time mentioning drakvuf version...  Act.  I m travelling these 2days I will put snapshot as soon I get back

**Comment by tklengyel** [comment]
Yea, that doesn't sound like normal at all, something is seriously off on your setup.. Might want to try to set it up from scratch again.

**Comment by amita4581** [comment]
well... i stop working on my notebook and started from scratch on one desktop with better config. i am able to generate the trace. may be after a while i have to find and fix it in my notebook as well.. good thing is now i can move ahead.. thanks for all your support
