### ISSUE TITLE
Running DRAKVUF with KVM instead of Xen

### ISSUE THREAD

**Issue by dongphuong2410** [tklengyel/drakvuf#241]
Hello, 

We are building a system based on DRAKVUF. The problem is that our system is required to support both VMs using XEN or using KVM. 
As far as I know, currently DRAKVUF requires XEN to run. Do you have any plan to support KVM in the near future ? 
If not, can you let me know if I can extend DRAKVUF  to do that,  is it possible, impossible or possible but take very long time ? I've just worked with DRAKVUF for a few days so I cannot imagine that.
Thank you.

**Comment by tklengyel** [comment]
No, there are no plans to support KVM. KVM lacks many many things that would be necessary to get it working. You would need both an events API and altp2m support. So while technically possible, it's lot of very technical work.

**Comment by dongphuong2410** [comment]
Ah, I got it. Thank you for your quick reply !

**Comment by mabj** [comment]
> No, there are no plans to support KVM. KVM lacks many many things that would be necessary to get it working. 

Hi @tklengyel, apologises for reviving this Issue. I'm studying VMI and AgentLess sandboxing alternatives and these topics brought me to your project. 

Do you have any documentation on which features of libvmi bounds Drakvuf to XEN hypervisor? Which "many many things" KVM lacks to be supported by Drakvuf?

Thank you very much.

**Comment by tklengyel** [comment]
Look for Xen's vm_event, monitor and altp2m interfaces.
