### ISSUE TITLE
Guest machine runs very slow when DRAKVUF is on.

### ISSUE THREAD

**Issue by dongphuong2410** [tklengyel/drakvuf#253]
I run Drakvuf with simple monitoring mode using following command : 
$ sudo ./src/drakvuf -r /root/windows.json -d windows

But the Windows guest performs really slow , especially when browsing the websites. It took many minutes to open a webpage. Just when I turned off the filedelete plugin and filetracer plugin, it's a little bit faster (40second for loading a website). When Drakvuf is off, the loading time for that page is 7second.

I couldn't find any document about how the performance of guest machine will be affected when Dravuf runs, so I'm not sure if it is supposed to be like that, or that I'm making something wrong while testing . Could you give me some idea ? 

Below is the configuration that I used for the experience: 
Host Machine : Intel (R) Xeon(R) CPU E5-2620 2.10GHz, 8 cores, 500GB Hard disk, 2G RAM, Ubuntu 16.04
Guest Machine : Windows 7, 2G RAM, 100G Hard disk, 1 core

Thank you

**Comment by tklengyel** [comment]
That's expected. The more plugins your run on the system the slower it will be. Especially if you run plugins that monitor the heap allocations (filetracer, poolmon, objmon, socketmon). The syscall plugins is also quite invasive, so that would also slow things down.

**Comment by dongphuong2410** [comment]
I've got it. Thank you
