### ISSUE TITLE
problem while installing Drakvuf

### ISSUE THREAD

**Issue by SunitaNICK** [tklengyel/drakvuf#256]
I have Installed xen 4.8,  and other softwares like libvm, rekall, volatility.

problem in drakvuf after running win-guid command

error: win-guid command not found
![screenshot from 2017-04-04 12-39-27](https://cloud.githubusercontent.com/assets/26893102/24647157/5a75bb5e-193c-11e7-9e16-d17d3ec41ac9.png)

**Comment by tklengyel** [comment]
I've updated the website to show the correct names (win-guid and process-list now both start with `vmi-`).
