### ISSUE TITLE
DRAKVUF User Menualls

### ISSUE THREAD

**Issue by MohammadBilalArif** [tklengyel/drakvuf#26]
drakvuf.com is good source for installation of DRAKVUF, even for a lay user. According to me what i get after studing DRAKVUF, it support live file extraction and many others, but from DRAKVUF i could not learn about use of DRAKVUF. Only i get is process ijection and system calls. It would be a lot easier if Someone can past some more documentation about use. some user menual type stuff.

**Comment by tklengyel** [comment]
It's in the plans to add some extra tutorials. Anything in particular you are looking for when you say "use of DRAKVUF"?

**Comment by MohammadBilalArif** [comment]
Yes right now I am looking for some very specific description not for long tutorials, Specific description Like:

**-List of Features available in DRAKVUF** 
**-Parameters to Add in ./configure to enable those features**
**-Commands to use them**

I am not expecting very much right now, I will wait for tutorials, but the bullets listed above are compulsory to use DRAKVUF.

**Comment by tklengyel** [comment]
By default all plugins are enabled when you run ./configure. There are options available to disable plugins you don't intend to use. I'll try to document what each plugin is doing as time permits..

**Comment by MohammadBilalArif** [comment]
I run ./configure without any parameter, thanks i have all plugins enabled.
Only thing i could not perform is *Live file extraction*, because i don't
know how to perform. You can help me on this? How, which inputs arguments?

**Comment by tklengyel** [comment]
A new wiki-page has been created to track what each DRAKVUF plugin is doing: https://github.com/tklengyel/drakvuf/wiki/DRAKVUF-Plugin-Documentation

**Comment by MohammadBilalArif** [comment]
Its Great :-) . Thanks
