### ISSUE TITLE
Latest Ubuntu update broke something?

### ISSUE THREAD

**Issue by paspe** [tklengyel/drakvuf#262]
Hi,
I have been working on drakvuf for a couple of weeks now successfully. It seems that after some of the latest updates something changed. 
I am running the latest Ubuntu as both the host and the guest. I have been using the syscalls plugin to monitor some of them, open and rename. Today, for some reason, when running the modified syscalls plugin, it stopped calling the linux_cb. I reverted the plugin to the original and it seems that not all syscalls manage to call the cb, and also when running it on all of them, after a few seconds the guest gets corrupted and removed.
Has anyone encountered the same problem?

I tried downloading the entire package from the beginning and compile again with the same results.
Thanks

**Comment by paspe** [comment]
Well, after some search I just realized that a newer kernel was installed. That broke my rekall profile and needed to be rebuilt. 

Sorry for bringing up such a trivial issue.

**Comment by tklengyel** [comment]
No problem :)
