### ISSUE TITLE
DRAKVUF Ubuntu Process Injection

### ISSUE THREAD

**Issue by portugasian** [tklengyel/drakvuf#267]
Hello,
I have managed to get process injection working for my Windows 7 DomU but have problems with getting it to work on my Ubuntu 14.04 DomU. Whenever I run the injector command I always get a process startup failed message:
Injector starting xterm through PID 2293 TID: 0
Process startup failed
regardless of what process I hijack (this specific error message came after trying to hijack a basic ping command) and what executable I try to run. Any help would be appreciated, thanks.

**Comment by tklengyel** [comment]
Injection is not yet supported for Linux guests.
