### ISSUE TITLE
Wrong parameter in xc_domain_setmaxmem()

### ISSUE THREAD

**Issue by deliciousdish** [tklengyel/drakvuf#268]
xc_domain_setmaxmem in drakvuf/src/libdrakvuf/vmi.c, the third parameter should be mem in kb. So, i think 
xc_domain_setmaxmem(drakvuf->xen->xc, drakvuf->domID, drakvuf->memsize+VMI_PS_4KB); ------>
xc_domain_setmaxmem(drakvuf->xen->xc, drakvuf->domID, drakvuf->memsize+VMI_PS_4KB >> 10);

**Comment by tklengyel** [comment]
Yeap, you are right. Would you mind opening a PR fixing it?

**Comment by deliciousdish** [comment]
I'm sorry , i am a fresh man in github and don't know how to open a PR. sorry.

**Comment by tklengyel** [comment]
That's OK. This may be a good task to learn how to do it ;) Take a look at https://help.github.com/articles/creating-a-pull-request/ for more information.

In a nutshell, you fork the project into your own space, clone it to your local machine, create a branch, make the modifications, commit your changes, push the branch to github and then you can create the PR on the webinterface.
