### ISSUE TITLE
Caught a error when execute xc_domain_populate_physmap_exact, rc is -1

### ISSUE THREAD

**Issue by deliciousdish** [tklengyel/drakvuf#269]
I run a vm with 4G memory, and caught a error when execute _xc_domain_populate_physmap_exact_, rc is -1. The code related is as following

       int rc = xc_domain_setmaxmem(drakvuf->xen->xc, drakvuf->domID, drakvuf->memsize+VMI_PS_4KB);
       drakvuf->memsize+=VMI_PS_4KB;

        rc = xc_domain_increase_reservation_exact(drakvuf->xen->xc, drakvuf->domID, 1, 0, 0, &remapped_gfn->r);
        if (!rc)
            PRINT_DEBUG("Reservation increased? %u with new gfn: 0x%lx\n", rc, remapped_gfn->r);
        else
            return 0;

        rc = xc_domain_populate_physmap_exact(drakvuf->xen->xc, drakvuf->domID, 1, 0, 0, &remapped_gfn->r);
        if (rc)
            return 0;
Between the function _xc_domain_increase_reservation_exact_ and _xc_domain_populate_physmap_exact_, i print some values, the value of drakvuf->memsize is **0x10004a000**, the value of remapped_gfn->r is **0xbe0887**. Obiviously, the value of remapped_gfn returned is mfn and i checked code in xen-4.6.1, it indeed is. 
But I think the last parameter of _xc_domain_populate_physmap_exact_ should be the array of guest pfn. Code related is as the following:
```
            if ( unlikely(__copy_from_guest_offset(&gpfn, a->extent_list, i, 1)) )
            goto out;
......
            mfn = page_to_mfn(page);
            guest_physmap_add_page(d, gpfn, mfn, a->extent_order);
```
I am not sure whether it's the reason of the failure. Can you check the code in /src/libdrakvuf/vmi.c, and the related xen code is at XEN_SRC/xen/common/memory.c? I think something maybe wrong around the _xc_domain_populate_physmap_exact_.

**Comment by tklengyel** [comment]
Passing a single entry to `xc_domain_populate_physmap_exact` is correct. An array is simply a continuous memory space for the underlying storage type. For example:
```
int x = 0;
int y[1] = {0};
```
are equivalent when looking at it from memory. Both simply allocate space for a single `int`. The difference with the array is that you get a `pointer` to the beginning of the array. For example:
```
int z1 = *(int*)&x;
int z2 = *(int*)y;
printf("z1: %i z2: %i\n", z1, z2);
```
will produce the output `z1: 0 z2: 0`. Notice how you can treat the variable `y` as an `int*`. So with that you can see that passing `&remapped_gfn->r` to the function with an array size of 1 is correct.

As for where your error comes from I'm not sure. If increase reservation succeeds than the memory is already allocated for the page, so mapping it into the guest should work fine. Are you able to trigger this error every time, or does it occur only occasionally?

**Comment by deliciousdish** [comment]
I can trigger this error every time, i am working on suse 12 sp2 with xen 4.7. 
I agree with what you said, but my focus is on the meaning of the last parameter of the function _xc_domain_increase_reservation_exact_ and  _xc_domain_populate_physmap_exact_ (&remapped_gfn->r).

 I think the last parameter of _xc_domain_increase_reservation_exact_  means an array of host mfn and the last parameter of  _xc_domain_populate_physmap_exact_ means an array of guest gfn. So the value of remapped->r got by _xc_domain_increase_reservation_exact_ should not be set as the input of _xc_domain_populate_physmap_exact_. 

Do you agree with me?

**Comment by tklengyel** [comment]
This has been fixed in the latest `master`. Please update and check whether you can still trigger the problem.

**Comment by tklengyel** [comment]
> So the value of remapped->r got by xc_domain_increase_reservation_exact should not be set as the input of xc_domain_populate_physmap_exact.

You are correct here, it was a mistake of using increase_reservation completely. However, as long as the MFN it returned was a GFN unused by the guest, populate_physmap would work fine, so where exactly your error was coming from is still unclear.

**Comment by deliciousdish** [comment]
When mfn is much greater than max gfn used by the guest，there will be an error，i did't dive into it.
