### ISSUE TITLE
Drakvuf and Libvmi

### ISSUE THREAD

**Issue by YukunDu** [tklengyel/drakvuf#27]
I am very new with drakvuf and libVMI. I followed the instructions in http://drakvuf.com/.
When I compile drakvuf, I got an error which told me the definitions in libvmi/events.h mybe is to old for drakvuf. 
So I download libvmi from https://github.com/libvmi/libvmi. But when I run ./configure, It shows that missing xen-events. I am stucked.
Do I need to add any parameters when I compile Xen?
Hypervisor: Xen 4.5.0
OS:CentOS 7
kernel:3.12.50
and I run this on VMware.

**Comment by YukunDu** [comment]
I solved this by updating my Xen version to 4.6.0. ：）

**Comment by tklengyel** [comment]
I'm glad you got it working ;) Feel free to open another issue if you get stuck somewhere.
