### ISSUE TITLE
Objmon doesn't initialize

### ISSUE THREAD

**Issue by v-p-b** [tklengyel/drakvuf#28]
I'm trying to create a new plugin based on objmon. I noticed that the `plugin_myplugin_init()` method never runs so I checked objmon and found the same behavior by simply recompiling the plugin with a debug printf() in the `plugin_objmon_init()` method (no output when running). 

Neither can I observe any output from the objmon plugin. 

While investigating the issue I also noticed that the `#ifdef` in plugins.h around PLUGIN_OBJMON refers to configuration options of the filedelete plugin, see: https://github.com/tklengyel/drakvuf/blob/master/src/plugins/plugins.h#L130 

Unfortunately this can't be the cause of the issue as both plugins were enabled.

**Comment by v-p-b** [comment]
I think I got it: drakvuf.c doesn't contain the initialization code for objmon. This commit should fix the issue:

https://github.com/v-p-b/drakvuf/commit/789827587d46d15fc376215a261f3f2b6711a4ef

**Comment by tklengyel** [comment]
Good catch! I think I need to simplify the number of ifdefs needed for a
plugin to avoid these issues =) Do you mind submitting a PR for it?

**Comment by v-p-b** [comment]
Absolutely, but as you can see my commits are a bit out of order, so I think I'll finish https://github.com/v-p-b/drakvuf/commit/dddea5fc57a7d2000f9731d6b2272cb3b57fbefa and issue the pull requests at once.

I also plan to start the plugin dev manual today in which I plan to summarize the necessary changes (we can upgrade this later as the plugin API develops).

**Comment by tklengyel** [comment]
So I quickly simplified the plugin interface to require fewer ifdefs in https://github.com/tklengyel/drakvuf/compare/simplify?expand=1. The PR tester is off right now so I can't merge this but could you base your stuff on this branch?

**Comment by v-p-b** [comment]
I merged simplify:

https://github.com/tklengyel/drakvuf/compare/simplify?expand=1

Honestly my git-fu isn't strong enough to do a proper rebase... How should we move forward?

**Comment by tklengyel** [comment]
PR #31 has resolved this issue.
