### ISSUE TITLE
a problem when xen 4.9 and xen 4.8 isntalled

### ISSUE THREAD

**Issue by hsuwad** [tklengyel/drakvuf#286]
i install 4.9 by mistake on my machine which was running very smoothly,, with xen 4.9 drakfuv tolls wouldn't work ( im not sure if there is any compatibility issue) so i returned bach to xen 4.8 to un my drakfuv

but the following message appear

Parsing config from ../win.cfg
libxl: error: libxl.c:363:libxl_get_physinfo: getting physinfo: Permission denied
libxl_get_physinfo failed

so any suggestion ?

**Comment by hsuwad** [comment]
i here the messages when tried with xen 4.9

sudo xl create ../winnew.cfg
Parsing config from ../winnew.cfg
libxl: warning: libxl_create.c:799:initiate_domain_create: XSM Disabled: init_seclabel not supported
libxl: error: libxl_device.c:381:libxl__device_disk_set_backend: Disk vdev=hda failed to stat: /dev/vg/windows7-sp2: No such file or directory
libxl: error: libxl_create.c:941:initiate_domain_create: Domain 3:Unable to set disk defaults for disk 0
libxl: error: libxl_domain.c:1003:libxl__destroy_domid: Domain 3:Non-existant domain
libxl: error: libxl_domain.c:962:domain_destroy_callback: Domain 3:Unable to destroy guest
libxl: error: libxl_domain.c:889:domain_destroy_cb: Domain 3:Destruction of domain failed

**Comment by tklengyel** [comment]
You probably have a mix of libraries installed at this point. I would suggest purging all Xen libs and starting from scratch installing Xen 4.9

**Comment by tklengyel** [comment]
Feel free to reopen the issue if you are still stuck.
