### ISSUE TITLE
Xen not running

### ISSUE THREAD

**Issue by Preetixen** [tklengyel/drakvuf#291]
Hello Tamas,

Hope you are doing good. 
I am again setting up DRAKVUF. We followed same instruction till xen installation without any error.

Though after reboot it say Xen-detect says Xen not running..
Please help

**Comment by tklengyel** [comment]
In the grub menu when you reboot you have to make sure you boot into Xen.

**Comment by Preetixen** [comment]
We still can't resolve the issue...
Could plz suggest how to boot a machine into Xen. Default it is booting on Ubuntu.

please provide some references of links too

**Comment by tklengyel** [comment]
Is your system configured to boot in UEFI mode? If so, you could try to switch it yo legacy. Otherwise follow this https://wiki.xenproject.org/wiki/Xen_EFI

**Comment by Preetixen** [comment]
Thanks for the message.

We were trying the below syntax got from wiki xen project

https://wiki.xenproject.org/wiki/Xen_EFI

will it not work for UEFI boot?

Configure GRUB to start Xen Project
By executing the below command we are moving the hypervisor to a higher priority than default Linux so that it gets the first position in the boot menu.
   dpkg-divert --divert /etc/grub.d/08_linux_xen --rename /etc/grub.d/20_linux_xen

We then generate the /boot/grub/grub.cfg file by running the command below:
 update-grub
We can now reboot and the default boot option will be our dom0 running on top of the hypervisor!

**Comment by tklengyel** [comment]
In my experience if you are using UEFI you should not use GRUB to boot Xen but boot Xen directly (ie. Xen as EFI binary (loading) in that wiki)
