### ISSUE TITLE
error while installing xen hypervisor

### ISSUE THREAD

**Issue by prithvisbisht** [tklengyel/drakvuf#292]
i am trying to install xen hypervisor(with drakvuf) on ubuntu 16.04 following the steps mentioned in https://drakvuf.com/ .. i am strictly following these steps and after setting up the system when i run "sudo xen-detect" command it is showing that "not running on xen". I have tried this several time and each time it gives the same error.
![issue1](https://user-images.githubusercontent.com/22067692/29487972-9d29c022-851f-11e7-8520-5ef331492e97.png)

**Comment by tklengyel** [comment]
When you reboot you have to make sure you select Xen in the grub menu.

**Comment by prithvisbisht** [comment]
when i run the reboot command, the system reboots normally no grub menu appears.. even if  i am updating grub every time before rebooting..

**Comment by prithvisbisht** [comment]
if there any other command we should run so please tell.

**Comment by prithvisbisht** [comment]
can u also tell me that ,for which version of ubuntu this version of drakvuf(integrated with xen) will be best suited.

**Comment by tklengyel** [comment]
Version of Ubuntu doesn't matter. Is your system using UEFI for boot? You would have to install xen.efi in that case and select it in the UEFI boot prompt.

**Comment by prithvisbisht** [comment]
the above have been executed succesfully..
Following command is to be executed before updating the Grub and Rebooting the system.
"cd /etc/grub.d/;mv 20_linux_xen 09_linux_xen"
Now i have installed libvmi and i want to explore its functionality on vm introspection. I tried searching on internet but not getting expected commands/information about libvmi or its uses. it will be great if u can help me and provide some information over libvmi.
Thanx for your help.

**Comment by tklengyel** [comment]
For LibVMI tutorials and help look around the LibVMI examples folder. Questions regarding LibVMI should be opened on the LibVMI mailinglist or github page.
