### ISSUE TITLE
Error creating windows domain

### ISSUE THREAD

**Issue by takadito15** [tklengyel/drakvuf#293]
Hello Tamas,

I've installed the latest version (with Xen 4.9) on Ubuntu 16.04.
I have created config file for existing win7-x86 raw image:

arch = 'x86'
name = "windows7-sp1"
seclabel='drakvuf:vm_r:drakvuf_domU_t'
maxmem = 3000
memory = 3000
vcpus = 2
maxcpus = 2
builder = "hvm"
hap = 1
acpi = 1
on_poweroff = "destroy"
on_reboot = "destroy"
on_crash = "destroy"
vnc=1
vnclisten="0.0.0.0"
usb = 1
usbdevice = "tablet"
altp2m = 2
shadow_memory = 16
audio=1
soundhw='hda'
vif = [ 'type=ioemu,model=e1000,bridge=xenbr0,mac=00:06:5B:BA:7C:01' ]
disk = [  'file:/home/user/Desktop/win7SP1_x86.img,xvda,w' ]

while running "xl create" I got this error:
Parsing config from windows7-sp1.cfg
libxl: warning: libxl_create.c:799:initiate_domain_create: XSM Disabled: init_seclabel not supported
libxl: error: libxl_create.c:554:libxl__domain_make: domain creation fail: Invalid argument
libxl: error: libxl_create.c:923:initiate_domain_create: cannot make domain: -3

Also tried with simple cfg:

builder = "hvm"
name = "test.hvm"
memory = 2048
maxmem = 2048
vcpus = 2
vif = [ '' ]
disk = [ 'file:/home/user/Desktop/win7SP1_x86.img,hda,w' ]
vnc = 1

And got the same error.
Any idea?

Thanks

**Comment by tklengyel** [comment]
You can remove the line `seclabel='drakvuf:vm_r:drakvuf_domU_t'`, with Xen 4.9 it's no longer needed.
