### ISSUE TITLE
Possible error in winscproto.h

### ISSUE THREAD

**Issue by shlomopongartz** [tklengyel/drakvuf#296]
Hi,

In winscproto.h I see that the arguments of NtContinue are declared with DIR_OUT direction shouldn't it be DIR_IN?

Best regards,

S.P.

**Comment by tklengyel** [comment]
Indeed, both inputs should be labeled `DIR_IN`. Do you want to open a PR to fix it?

**Comment by shlomopongartz** [comment]
Hi,
I'm not familiar with GitHub, I don't know how to open a PR.
Can you send a link to the instructions?

S.P.

**Comment by tklengyel** [comment]
Of course, here you go: https://help.github.com/articles/creating-a-pull-request/

**Comment by tklengyel** [comment]
This may also be helpful to read: https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by shlomopongartz** [comment]
10Q

**Comment by tklengyel** [comment]
Thanks for the fix!
