### ISSUE TITLE
Plugin socketmon startup failed!

### ISSUE THREAD

**Issue by NeerajNegi** [tklengyel/drakvuf#299]
Hello, we have succesfully run all the commands of drakvuf. LibVMI is also working. Rekall file is also generated , but when running the drakvuf command for introspection we are getting some error attached with the issue. Please help us to solve the issue.
![configure_drakvuf](https://user-images.githubusercontent.com/17411633/30209662-c3e47c20-9488-11e7-8662-8236ff637caf.png)
![dra](https://user-images.githubusercontent.com/17411633/30209663-c3e99bc4-9488-11e7-8ecd-6903ce187db3.png)

**Comment by tklengyel** [comment]
That's normal. The socketmon plugin requires a Rekall profile to be generated for tcpip.sys as well. If you don't have that just disable socketmon by adding `-x socketmon` option when running drakvuf.
