### ISSUE TITLE
Unable to boot xen

### ISSUE THREAD

**Issue by amfaizal** [tklengyel/drakvuf#300]
I have follow the step at drakvuf.com but after running  command make -j4 dist-xen, error message display x86/32 is not supported appear. Is it normal error ?..
I just proceed the installation and the same error message appear again during installation of xen.
Could you please help me..i'm newbies in this area

**Comment by tklengyel** [comment]
The error is definitely not normal. Looks like you are on a 32-bit system which is not supported.

**Comment by amfaizal** [comment]
Dear sir...
Currently my installation using ubuntu 14.04 64bit and the machine is
supported 64 bit...may i know how to solve it...tq

**Comment by tklengyel** [comment]
Then it sounds like you didn't follow the installation steps exactly. Either way, copying in the exact error message would be a good start to pinpoint your issue.

**Comment by amfaizal** [comment]
dear sir...
may i know why the Drakvuf failed to initialize...
here are the output after running this command
./src/drakvuf -r /root/windows7-sp1.rekall.json -d 7

output
DRAKVUF v0.5-c9ffafe
Failed to initialize DRAKVUF

**Comment by amfaizal** [comment]
Dear sir ...
i have change the domain to 12 and run the same command...but other error
appear

Socketmon plugin requires the Rekall profile for tcpip.sys!
Plugin socketmon startup failed

could you please help me

**Comment by tklengyel** [comment]
Just disable the socketmon plugin with `-x socketmon`.
