### ISSUE TITLE
Trace process memory read & write events

### ISSUE THREAD

**Issue by takadito15** [tklengyel/drakvuf#301]
Is it possible to monitor memory read and write events per process?
I would like to generate memory reference trace for specific process, something similar to the one create by Pin tool: [https://software.intel.com/sites/landingpage/pintool/docs/81205/Pin/html/index.html#MAddressTrace](url)

Thanks

**Comment by tklengyel** [comment]
It is possible but the way it works with virtualization is that you get events for a physical page. If you want to only see when it is being accessed by a specific process you would have to filter out unrelated events in software.

**Comment by carter-yagemann** [comment]
I don't know if this is helpful, but I've played around a bit with tracking per process memory events. Specifically, I started building a generic malware unpacker using libVMI (library DRAKVUF is built on): https://github.com/carter-yagemann/vmi-unpack

My high-level logic is to track CR3 writes and when a target process' page table is loaded into it, parse the page table and register write memory events for the page table pages (to capture changes like new allocations or swapping) and also add memory events for the process pages currently present in memory. When an event is triggered, I recheck CR3 and the page table to make sure I'm still in the context of the target process and then handle it.

As Tamas pointed out, the challenge is VMI works on physical pages, so you have to carefully track context. Pages can swap in and out, shared across processes, freed and reallocated, etc. Honestly, PIN is a much more direct solution.

**Comment by tklengyel** [comment]
@carter-yagemann cool project, thanks for sharing it!

**Comment by tklengyel** [comment]
I'm closing this issue for now, feel free to reopen if you still have questions.
