### ISSUE TITLE
Why number of intercepted syscalls don't affect the analyze time?

### ISSUE THREAD

**Issue by skvl** [tklengyel/drakvuf#304]
Hello.

Thank you for Your project.

I have tried a simple test: run sample program with and without Drakvuf. It takes about 40sec without analyzer and 6min with analyzer. Then I've reduced the number of syscalls up to 40 (instead 900 by default). But time remains the same. Why?

NB To reduce the number of syscalls I've patched `create_trap_config()` in `syscalls.cpp` to `strcmp()` with every function of interest.

**Comment by tklengyel** [comment]
Is this for WIndows or Linux? For Windows `syscalls` is not where the majority of the overhead comes from but from `poolmon` trapping `ExAllocatePoolWithTag`. Try disabling that.

**Comment by skvl** [comment]
Hello @tklengyel,

Thank You for quick reply. I have switched off all other plugins.

**Comment by tklengyel** [comment]
Any noticeable difference?

**Comment by skvl** [comment]
Sorry for my bad Eglish. I've mean that I have disabled them from the start. With other plugins the time was 19min.

**Comment by tklengyel** [comment]
I see, in that cans it might just be that the syscalls you trap are ones that are in the fastpath (get called a lot).

**Comment by skvl** [comment]
Thank You.

Could You please explain architecture of breakpoints? I could try to optimize it because believe that it is possible to speed up. May I would be able to change something in mechanism of cross-VM event delivery (XSM?). Or compile some parts inside Xen.

**Comment by tklengyel** [comment]
The architecture is explained in the paper: https://www.sec.in.tum.de/i20/assets/Uploads/scalability-fidelity-stealth.pdf

**Comment by skvl** [comment]
Thank You. I will read it.

**Comment by skvl** [comment]
I have read the paper (very good one!) but it doesn't contain the required information. Still I don't have any view on technical details of Drakvuf<->Xen interaction.

I think that the main reason of such long sample run is inter-domain communication. If this is true the only way to speed it up is to put all analysis inside hypervisor itself and leave some API to get results in domU.

What do You think about this? Is it implementable? Are there some plug-in system in Xen or some "operating environment" to execute some binary?

P.S. I understand that this could be incorrect place for such discussion. If so You could close the issue.

**Comment by tklengyel** [comment]
Technically it is possible to do analysis in the hypervisor itself but you
will have a hard time doing that with Xen as it has no access to the disk
or the network. If you want to go that route KVM may be a better platform
for you.

**Comment by skvl** [comment]
Yes. I understand about network and disk. But currently I'm interested in breakpoints.

As I understand the steps for breakpoints hiding are the most time consuming. Am I right? Could You explain where should I look for understanding the process? I understand how EPT works but I don't know where exact steps took place: in Xen, LibVMI, Drakvuf? What the interaction diagram looks like?

Thank You for Your patience.

**Comment by tklengyel** [comment]
The overhead doesn't come from breakpoint hiding but from the several VMEXITs happening for the breakpoint delivery. With Xen you 2 for each, one coming from the target VM when the breakpoint is hit, and one when dom0 proccesses the event and passes the execution back to Xen. With doing processing in the hypervisor you could eliminate the second exit.

**Comment by skvl** [comment]
Yes. I understand this. I'm digging through the code to understand where to look.

**Comment by skvl** [comment]
I think this question could be closed. Thank You very much.
