### ISSUE TITLE
windows 7 cannot refresh while running drakvuf

### ISSUE THREAD

**Issue by amfaizal** [tklengyel/drakvuf#307]
Hai...
thank you for assist me in installing drakvuf. Finally manage to install. Unfortunately, the windows 7 is not refreshing after running drakvuf. May i know how to run a malware sample inside the windows7 while the drakvuf is running. 
Hope you can help me

**Comment by aoshiken** [comment]
May I ask what exactly means "refreshing" in this context? 
Are you referring to the screen not being refreshed or what?

**Comment by aoshiken** [comment]
Regarding on how to run a malware what most people uses are injecting an executable into a suitable process and thread into the DomU using the following drakvuf options:

  -i <injectionq pid>        The PID of the process to hijack for injection
  -I <injection thread>     The ThreadID in the process to hijack for injection (requires -i)
  -e <inject_exe>           The executable to start with injection

Hope this helps

**Comment by amfaizal** [comment]
The refreshing means that the i windows is freezing while running drakvuf at the same time. I  cannot done anything at the windows 7 e.g cannot click anything at windows 7...
I manage to control it after i stop the drakvuf..
Could you help me...tq

**Comment by aoshiken** [comment]
I'm assuming you're using VNC, am I right?

If so take a look to the issue #238

**Comment by amfaizal** [comment]
Currently I'm using xtightvnc...any suggestion solve it..or is there any
alternative to used others than vnc..
Hope u can help...tq sir

**Comment by aoshiken** [comment]
So yes, you're using VNC.
Have you taken a look at the aforementioned issue?

**Comment by amfaizal** [comment]
Ok sir...i will tried it first...tq for your help

**Comment by amfaizal** [comment]
Hai Sir..
i have a problem regarding the network setting at my dom0 and guest os..
My xenbro ip address is 192.168.2.129 and i set my guest os using windows 7 is 192.168.2.150. The problem is my dom0 cannot ping my guest os..here are my network config file and ifconfig

file /etc/network/interfaces
auto lo
iface lo inet loopback


auto eth5
iface eth5 inet static
   address 192.168.2.211
   broadcast 192.168.2.255
   netmask 255.255.255.0
   gateway 192.168.2.1
   dns-nameservers 8.8.8.8
   allow-hotplug eth5

auto xenbr0
iface xenbr0 inet static
#iface xenbr0 
   #bridge_ports eth0
   bridge_ports none
   address 192.168.2.129
   broadcast 192.168.2.255
   netmask 255.255.255.0
   gateway 192.168.2.1
   bridge_stp on
   bridge_maxwait 0
   bridge_fd 0
   allow-hotplug xenbr0


ifconfig 

eth5      Link encap:Ethernet  HWaddr 50:9a:4c:46:03:be  
          inet addr:192.168.2.211  Bcast:192.168.2.255  Mask:255.255.255.0
          inet6 addr: fe80::529a:4cff:fe46:3be/64 Scope:Link
          UP BROADCAST RUNNING PROMISC MULTICAST  MTU:1500  Metric:1
          RX packets:570514 errors:0 dropped:149 overruns:0 frame:0
          TX packets:411352 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:741879680 (707.5 MiB)  TX bytes:39276947 (37.4 MiB)
          Interrupt:20 Memory:f7200000-f7220000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:423216 errors:0 dropped:0 overruns:0 frame:0
          TX packets:423216 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:266706694 (254.3 MiB)  TX bytes:266706694 (254.3 MiB)

vif2.0    Link encap:Ethernet  HWaddr fe:ff:ff:ff:ff:ff  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:32 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

vif2.0-emu Link encap:Ethernet  HWaddr fe:ff:ff:ff:ff:ff  
          inet6 addr: fe80::fcff:ffff:feff:ffff/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:158 errors:0 dropped:0 overruns:0 frame:0
          TX packets:863 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:18389 (17.9 KiB)  TX bytes:47964 (46.8 KiB)

xenbr0    Link encap:Ethernet  HWaddr fe:ff:ff:ff:ff:ff  
          inet addr:192.168.2.129  Bcast:192.168.2.255  Mask:255.255.255.0
          inet6 addr: fe80::fcff:ffff:feff:ffff/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:6990 errors:0 dropped:0 overruns:0 frame:0
          TX packets:247 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:851276 (831.3 KiB)  TX bytes:28334 (27.6 KiB)


could you please help me...i stuck for two days to troubleshoot this problem...

tq

**Comment by tklengyel** [comment]
Try putting xenbr0 and the domu on a different subnet. Looks like right now
you have multiple interfaces routing 192.168.2.0/24.

**Comment by tklengyel** [comment]
I assume you were able to fix your issue so I'm closing this for now.
