### ISSUE TITLE
how to run automated malware analysis

### ISSUE THREAD

**Issue by amfaizal** [tklengyel/drakvuf#311]
Dear sir..
i have follow the instruction to setup the malware analysis at this webpage 

https://github.com/tklengyel/drakvuf/wiki/Automated-malware-analysis-setup

here is my command 
screen -L -d dirwatch windows7-sp1 /home/windows7-sp1 /root/windows7-sp1.rekall.json 1180 /var/www/malware_incoming /malware_processing /var/www/malware_finished/ 1 /root/drakvuf/tools/clone.pl /root/drakvuf/tools/preconfig.sh /root/drakvuf/tools/drakvuf.sh /root/drakvuf/tools/cleanup.sh /root/drakvuf/tools/tcpdump.sh 

after run 
i have this error
There is no screen to be detached

Could you please help me...is it a correct command to run it. 

tq

**Comment by tklengyel** [comment]
Before you run it in screen you should run it manually to see whether it works. Looks like there was something missing and it doesn't actually start.

**Comment by tklengyel** [comment]
Also, make sure you update the shell scripts to fit your setup.

**Comment by Alibm73** [comment]
@tklengyel @amfaizal 
Hi
I use this code to run the setup:
`dirwatch loop windows7-sp1 ./windows7new.cfg /root/windows7-sp1.rekall.json 2608 ./malware_incoming ./malware_processing ./malware_finished 1 ./clone.pl ./preconfig.sh ./drakvuf.sh ./cleanup.sh ./tcpdump.sh`
everything is in my `drakvuf/tools` folder. 
when i run i get this error:
`** MOVING FILE FOR PROCESSING: mv ./malware_incoming/e9d7b791-b42e-11e7-b29d-80e65024849a.file ./malware_processing/e9d7b791-b42e-11e7-b29d-80e65024849a.file
[0] Making clone
** RUNNING COMMAND: ./clone.pl windows7-sp1 1 ./windows7new.cfg
[0] Clone creation failed, trying again`
I changed some things in the clone.pl:
`# The LVM volume group
our $lvm_vg = "vg";
# Clone network bridge name
our $clone_bridge = "xenbr1";`
and
`sub clone {
    if (@ARGV != 3) {
        die "Insufficient number of arguments!\nUsage: /home/ali-admin/drakvuf/tools/clone.pl windows7-sp1 xenbr1 /home/ali-admin/drakvuf/tools/windows7new.cfg\n";
    }`
any thoughts??

**Comment by Alibm73** [comment]
also i think i configured the apache in a wrong way. i edited the `/etc/apache2/apache2.conf ` and i just changed this line:
`<Directory /home/ali-admin/drakvuf/tools/malware_processing>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>`
and i commented the `Options Indexes FollowSymLinks` line.
is this right??

**Comment by Alibm73** [comment]
![Screenshot from 2019-06-22 10-42-16](https://user-images.githubusercontent.com/39646882/59960228-82d09580-94da-11e9-8529-33515a0481bf.png)

**Comment by Alibm73** [comment]
![Screenshot from 2019-06-22 10-43-32](https://user-images.githubusercontent.com/39646882/59960231-a1cf2780-94da-11e9-8a24-cd76e04d3675.png)

**Comment by Alibm73** [comment]
![Screenshot from 2019-06-22 10-49-06](https://user-images.githubusercontent.com/39646882/59960264-63863800-94db-11e9-9c17-03a02d91e529.png)

**Comment by Alibm73** [comment]
just to be sure i'm uploding my drakvuf script too

**Comment by Alibm73** [comment]
![Screenshot from 2019-06-22 10-51-11](https://user-images.githubusercontent.com/39646882/59960299-d7284500-94db-11e9-9cac-2f2b997b1541.png)
