### ISSUE TITLE
Some questions about installtion!

### ISSUE THREAD

**Issue by bigbigbanana** [tklengyel/drakvuf#312]
![img_0176](https://user-images.githubusercontent.com/24928429/31222324-49da41fe-a9f9-11e7-903b-1979ae181137.JPG)

I follow the installtion guide,but when i reboot the computer,the screen stayed in this menu and don't moving on,probably the meaning is cannot mount /proc/xen,how can i solve this problem?The system i used is Ubuntu14.04,and the kernel version is 4.4.0-31-generic.

**Comment by tklengyel** [comment]
That sounds like you didn't boot into Xen properly and then Linux can't find `/proc/xen`. Did you choose the Xen entry from GRUB?

**Comment by bigbigbanana** [comment]
Yes,i choose the Xen entry from GRUB,but whatever i choose,at last there still exists error,and go back to the  GRUB menu.
![img_0178](https://user-images.githubusercontent.com/24928429/31258170-f98afdac-aa6f-11e7-89c3-d7da27f9e97d.JPG)
![img_0179](https://user-images.githubusercontent.com/24928429/31258171-f9beca1a-aa6f-11e7-8778-8334c68dd7e7.JPG)

**Comment by tklengyel** [comment]
That's a pretty odd error message you get there from Xen. My bet is that your hardware doesn't fully support virtualization. Is it an older machine?

**Comment by bigbigbanana** [comment]
No,my computer is an newer machine,i used to install xen-4.1.2 on ubuntu12.04,but after installtion,there  is no graphical interface，i use remote connection to solve this problem,i think maybe the problem is that hardware and software is not compatible properly,in your opinion,should i use another computer to install drakvuf?

![2017-10-09 14_14_47](https://user-images.githubusercontent.com/24928429/31326949-32bfb91a-acfe-11e7-8165-861625f7b0bd.png)

**Comment by tklengyel** [comment]
Yes, the installation guide is correct. I also see `vmx ept vpid` in the cpuinfo for your CPU so it should work. Without further information though I can't pinpoint what's wrong with your setup. You should get a full Xen debug log, maybe that will have something. You can get that log by attaching a serial cable to your system or by using Intel AMT (see https://wiki.xenproject.org/wiki/Xen_Serial_Console for more info).
