### ISSUE TITLE
Add more EPROCESS fields of the current process to drakvuf_trap_info_t

### ISSUE THREAD

**Issue by aoshiken** [tklengyel/drakvuf#313]
It would be useful to add the following EPROCESS fields to the `drakvuf_trap_info_t` structure ( windows symbols parenthesized):
- Current process id ` ( "_EPROCESS" -> "UniqueProcessId" )`
- Current parent process id `( "_EPROCESS" -> "InheritedFromUniqueProcessId" )`
- Current eprocess address

@tklengyel, Makes sense for you?

**Comment by tklengyel** [comment]
So there are already APIs that you can use to gather these fields when needed. Or do you think all plugins should include these informations in the log output they generate?

**Comment by aoshiken** [comment]
I think the second would be right :)

**Comment by tklengyel** [comment]
Sure, if you are willing to do that update I don't have anything against it ;)

**Comment by aoshiken** [comment]
You can count of me, it's just a matter of time ;)
