### ISSUE TITLE
Cannot create VM - XSM policy error 

### ISSUE THREAD

**Issue by paspe** [tklengyel/drakvuf#314]
Hi, I tried to make a clean install of DRAKVUF, and everything seems to be fine installing Xen. But when I try to create a VM I get the following error:
"libxl: warning: libxl_create.c:799:initiate_domain_create: XSM Disabled: init_seclabel not supported"
I used the Xen source linked from your repo and followed every step, but I don't see any other error. I haven't proceeded to install LibVMI yet. Should I?
Any other help?

**Comment by tklengyel** [comment]
Your domain configuration file probably has the older `seclabel` field still in it. Comment it out or remove it completely and it will work.

**Comment by bigbigbanana** [comment]
@paspe 
Hello,i followed the installtion guide but i failed to install the drakvuf,i want to know your computer hardware configuration.Thanks!

**Comment by paspe** [comment]
Hi. 
For starters I am sorry for the late response. After deleting the seclabel everything was fine. 

I am working on a Dell desktop, I don’t remember the model right now, with i7-6700 with 8GB of RAM. I have set an LVM for the VMs according to the Xen wiki.  Where do you encounter problem?

**Comment by bigbigbanana** [comment]
@paspe 
Hi,i used ubuntu14.04.5 as my OS,and i followed the installtion guide,but when i reboot,it shows cannot mount /proc/xen,i don't know what's wrong with it?
![img_0176](https://user-images.githubusercontent.com/24928429/32158173-702dadd6-bd82-11e7-94db-d8a7e38d5b51.JPG)
![Uploading IMG_0178.JPG…]()

**Comment by paspe** [comment]
It seems that is a Xen issue. To be honest I don’t know. I have made a lot of installations from scratch and never had any problem. I am using Ubuntu 16.04, but I don’t think that is the issue.

**Comment by bigbigbanana** [comment]
@paspe 
Do you follow the installtion guide from https://drakvuf.com?I used to successfully install xen4.1.2 and linux3.2.16 kernel on my computer,but there is no graphics interface,i think maybe hardware and software is not compatible,could u tell me the model of your computer?Thanks.

**Comment by tklengyel** [comment]
@bigbigbanana I think your best option for getting help with xen boot issues is posting to the xen-users mailinglist: https://lists.xenproject.org/mailman/listinfo/xen-users

**Comment by paspe** [comment]
@tklengyel just a follow-up question.
I was working on a previous version of libvmi and drakvuf. I updated to the current.
There are some changed in the function calls, but I figured them out.
My problem is that I have added somne extra Linux stucts to retrieve from the rekall profile, and I get wrong results.
For example I try to get the offset of the fs struct in the task_struct, which in the profile is 1720, and somehow I end up with 93825006051504. Any ideas?

**Comment by tklengyel** [comment]
Are you using `drakvuf_get_struct_member_rva`?

**Comment by paspe** [comment]
I use the actual code for reading the profile as is. I just have added some extra structs and offsets in the linux-offsets.h and linux-offsets-map.h. 
It worked before correctly.

**Comment by tklengyel** [comment]
It should work, so I'm not sure.

**Comment by paspe** [comment]
I have a new question, so if you want I can open a new topic.
I was trapping some system calls like you do in your syscalls plugin, using an older version of all drakvuf, libvmi and xen. When I updated to the latest version, firstly I have some issues compiling your code in the syscalls plugin.

syscalls/syscalls.cpp:510:59: error: member access into incomplete type 'const struct syscalls_config'
    symbols_t* symbols = drakvuf_get_symbols_from_rekall(c->rekall_profile);
                                                          ^
syscalls/syscalls.cpp:509:18: note: forward declaration of 'syscalls_config'
    const struct syscalls_config * c = (const struct syscalls_config*)config;

Since I don't use it ( I created a new plugin) I just commented it out, so I can't be sure if I will have the same issue with your plugin. When I am doing the loop to trap the system calls, on some of them I get the following error, but not on others:

VMI_ERROR: Error, Xen reports a VM_EVENT_INTERFACE_VERSION that doesn't match what we expected (0x00000002)!

Do you have any idea why that could be? The trapping is in a loop, so I use the exact same way to do it.
Thanks

**Comment by tklengyel** [comment]
Please open a separate issue for that so that it's searchable. Thanks.
