### ISSUE TITLE
Questions about how to trace system calls under Xen!

### ISSUE THREAD

**Issue by bigbigbanana** [tklengyel/drakvuf#318]
Hello,Tamas.I used to install drakvuf(based on the installtion guide in https://drakvuf.com/) on my computer but i failed,i want to trace system calls in vm under Xen,i do know some ideas like set sysenter eip's value to a non-existent value,then cause page fault and trap the syscall,but i don't know how to achieve this.Could you give me some suggestions?

**Comment by tklengyel** [comment]
There is already a plugin for doing syscall tracing so you would not have to re-implement that.
