### ISSUE TITLE
Unable to run: Memory event outside max physical address

### ISSUE THREAD

**Issue by aoshiken** [tklengyel/drakvuf#320]
The current Drakvuf version have breaking issues in my setup.

I think I've get rid of the first one with the PR #319 but unfortunately that was just the beginning. :(

The latest LibVMI update made appear something that was hidden in previous versions and it's Drakvuf trying to set memory events beyond the DomU max physical address.

I've nailed down the issue to the `vmi_set_mem_event_ function` in the `libvmi/libvmi/events.c` file,  there's a new check in the latest version that wasn't present before:
```
   if ( gfn > (vmi->max_physical_address >> vmi->page_shift) )
   {
       errprint("Invalid GFN for setting memory event: 0x%lx, beyond max physical address\n", gfn);
       return VMI_FAILURE;
   }
```
...so after adding a little printing line to that function and running Drakvuf again we get the following data confirming the error:
```
FRED: gfn[FF050] vmi->max_physical_address[FF04E000] vmi->page_shift[C]  bits-arithmetic[FF04E]
```

The previous version of LibVMI didn't show that error (obviously because it doesn't have the check) but adding the same printing line showed the same issue:
```
FRED: gfn[FF052] vmi->max_physical_address[FF050000] vmi->page_shift[C] bits-arithmetic[FF050]
```
I don't know for sure if that's related to LibVMI or to Drakvuf (I'm afraid it's something related on how LibVMI calculates the max physical address for a domain) so I preferred to open the current issue just in case.

**Comment by aoshiken** [comment]
I forgot to mention that getting rid of the check in `vmi_set_mem_event` function made Drakvuf to work as expected

**Comment by tklengyel** [comment]
Yea, that might just be because DRAKVUF adds extra memory to the VM and LibVMI is not aware of it as it just gets the max phys address once in the beginning.

**Comment by aoshiken** [comment]
Thank you @tklengyel 

I'm afraid there must be more people failing to run Drakvuf as currently is, unfortunately I'm running out of time so as a first step I'm going to remove the check in my local repository, time will tell but meanwhile I'd keep this issue open... :)

**Comment by tklengyel** [comment]
Yes, that fix should suffice for now.

**Comment by aoshiken** [comment]
I'm afraid something is still wrong getting the `current_process` `base_addr` but it isn't directly related to this issue.

I'll take a look tomorrow. :)

**Comment by aoshiken** [comment]
I know I'm too late :)

The PR #321 works like a charm, well done!! 👍
