### ISSUE TITLE
Not able to create win 7 domain Vm

### ISSUE THREAD

**Issue by dhruv21995** [tklengyel/drakvuf#328]
Hi, i am working on a project in which i have to use drakvuf and i have completed all the previous steps but when i try to create the domain for my windows 7 VM it shows some libxl errors:

i run the command:

xl create /etc/xen/win7.cfg

below is the screenshot of the error.
![error](https://user-images.githubusercontent.com/20474980/32544369-3978b1ec-c470-11e7-95eb-3d8688c94474.png)

**Comment by aoshiken** [comment]
I think it's pretty selfexplanatory, you're using the deprecated config variable `altp2mhvm `instead of the current `altp2m`.

Try to remove the old variable on your config file and replace the entry with the following one:
`
altp2m = 2
`

**Comment by tklengyel** [comment]
While the altp2m warning can indeed be fixed by changing the config option that would not result in the error. You probably don't have either the network bridge or the disk available for the domain you are trying to create.

**Comment by dhruv21995** [comment]
Following are screenshots of the file win7.cfg and the next error which comes after correcting altp2mhvm to altp2m

![error2](https://user-images.githubusercontent.com/20474980/32650979-acd4828c-c5f7-11e7-924e-77ab54003ac0.jpeg)
![error3](https://user-images.githubusercontent.com/20474980/32650982-addf117e-c5f7-11e7-98f5-58cc3790866b.jpeg)

**Comment by tklengyel** [comment]
Your config file looks correct, just ensure you have `/dev/vg/windows7-sp1` disk available and the `virbr0` bridge available. The error you are getting right now is because it complains there is already a vm with that name (got stuck somehow). So either reboot or change the vm name.
