### ISSUE TITLE
VMI Doppelgänging injection

### ISSUE THREAD

**Issue by saimoon** [tklengyel/drakvuf#332]
As highlighted in issue #290 current implementation of injector has some cons.
Directly injecting a binary will be a great improvement.
Process hollowing was not the best way (suspicious, miss file mapping, forensic and other known prob..)
A new injection method was introduced at London BlackHat2017 named  Doppelgänging:

[https://www.blackhat.com/docs/eu-17/materials/eu-17-Liberman-Lost-In-Transaction-Process-Doppelganging.pdf](url)

It could be a implemented in VMI world.

**Comment by JohnPeng47** [comment]
Hey I would to take this task if no one else has started working on it. Reading through the code in libinjector, I came across the following reference to Rekall in the injector_start_app function:
`    // Get the offsets from the Rekall profile
    unsigned int i;
    for (i = 0; i < OFFSET_MAX; i++)
    {
        if ( !drakvuf_get_struct_member_rva(injector.rekall_profile, offset_names[i][0], offset_names[i][1], &injector.offsets[i]))
        {
            PRINT_DEBUG("Failed to find offset for %s:%s\n", offset_names[i][0],
                        offset_names[i][1]);
        }
}`
Googling for Rekall, found out it is a memory forensics framework. Just wanted to ask, what is Rekall being used in for DRAKVUF, and in this code snippet in particular?

**Comment by MICSEC** [comment]
Hi JohnPen47,
 you can check my branch:

https://github.com/saimoon/drakvuf/tree/doppelganging

I developed this kind of injection, but the code (or the 
technique ?!?)  has proved not so efficient, I had probs with it and until now I've had not time to check it (it worked only using "explorer" process as target...)

If you'll experiment with it, please let us know...

**Comment by tklengyel** [comment]
@JohnPeng47 Rekall is used to create an easily readable debug profile for the target operating system, this is what we call the "Rekall profile". This is a json file containing a bunch of important information about function rva's and structure layouts.

**Comment by JohnPeng47** [comment]
@MICSEC Ok will do. Which version of Windows did you test it on?

**Comment by saimoon** [comment]
@JohnPeng47 : code tested on windows 10.

Saimoon (ex @MICSEC, wrong account before :)

**Comment by mdolmen** [comment]
Hi! I'm working on this task as part of my Summer of Code project.

@saimoon : maybe you tried to inject a 64-bit process into a 32-bit one. If not I think the problem come from the DLL path passed in argument to __RtlCreateProcessParameters__. Still, I didn't figure out yet how to correctly pass it to the function, during my last tests it was never taken into account. I have to dig more into that and redo my tests with the last Windows update. I've written some code to do it from a Windows machine (without Drakvuf), you can check it here : https://github.com/mdolmen/proc_dopp (you will have to tuned it a little to run it : filenames, etc.)

**Comment by tklengyel** [comment]
Implemented by #444
