### ISSUE TITLE
Rekall profile: no $STRUCTS section found

### ISSUE THREAD

**Issue by Alex287** [tklengyel/drakvuf#333]
![image](https://user-images.githubusercontent.com/26807502/34115488-c4e59862-e450-11e7-9e5b-f66bf18f6516.png)
You see! When I run 'vmi-process-list win8' with simple 'win_pid、win_tasks...'in the libvmi.conf file, everything goes fine. But when I use rekall, the error appears! Any help will be appreciated! Thanks in advance!

**Comment by tklengyel** [comment]
This is not a DRAKVUF issue.
