### ISSUE TITLE
Xen VM work fine but when using wmi-win-guid all the error appear

### ISSUE THREAD

**Issue by allanng78** [tklengyel/drakvuf#334]
Hi,
I have install the xen hypervisor 4.9 on ubuntu 16.04.02. It tooks me quite a while to create the guest windows 7 vm. 

allan@allan-GE62VR-7RF:~/drakvuf/xen$ sudo xl list
[sudo] password for allan: 
Name                                        ID   Mem VCPUs	State	Time(s)
Domain-0                                     0  4095     4     r-----     714.9
window7-sp1                                  1  3000     2     -b----     119.9

The guest vm use a dedicated hd (/dev/dba)  just for virtualization. It is located in /dev/vg/windo7-sp1.

just in case vm .cfg file. I have included it below:
-------------------------------------------------------------------------------------------------------------
arch = 'x86_64'
name = "window7-sp1"
maxmem = 3000
memory = 3000
vcpus = 2
maxcpus = 2
builder = "hvm"
boot = "c"
hap = 1
acpi = 1
on_poweroff = "destroy"
on_reboot = "destroy"
on_crash = "destroy"
vnc=1
vnclisten="0.0.0.0"
vncconsole=1
usb = 1
usbdevice = "tablet"
altp2m = 2
shadow_memory = 16
audio=1
soundhw='hda'
vif = [ 'type=ioemu,model=e1000,bridge=xenbr0,mac=00:06:5B:BA:7C:01' ]
disk = [ 'phy:/dev/vg/window7-sp1,hda,w', 'file:/home/allan/Desktop/en_windows.iso,hdc:cdrom,r']

Installation for the libvmi have no problem. But when I run : sudo vmi-win-guid name window7-sp1. It seem to give me alot of error using the debug. Below is some of the error display:

--xen_get_memory_pfn success on pfn=0xfeffb
--PEPARSE: DOS header signature not found
--PEPARSE: failed to validate PE header(s)
--MEMORY cache set 0xfeffc000
--xen_get_memory_pfn success on pfn=0xfeffc
--PEPARSE: DOS header signature not found
--PEPARSE: failed to validate PE header(s)
--MEMORY cache set 0xfeffd000
--xen_get_memory_pfn success on pfn=0xfeffd
--PEPARSE: DOS header signature not found
--PEPARSE: failed to validate PE header(s)
--MEMORY cache set 0xfeffe000
--xen_get_memory_pfn success on pfn=0xfeffe
--PEPARSE: DOS header signature not found
--PEPARSE: failed to validate PE header(s)
--MEMORY cache set 0xfefff000
--xen_get_memory_pfn success on pfn=0xfefff
--PEPARSE: DOS header signature not found
--PEPARSE: failed to validate PE header(s)
--MEMORY cache cleanup round complete (cache size = 256)
--MEMORY cache set 0xff000000
--xen_get_memory_pfn failed on pfn=0xff000
--PEPARSE: failed to read PE header

How can I solve this? Please help me. Thanks

**Comment by tklengyel** [comment]
From what you posted I can't spot anything wrong. Is the Windows VM fully booted and functional when you open it in VNC?

**Comment by allanng78** [comment]
Hi,
The windows is fully functional when I open in VNC.

**Comment by allanng78** [comment]
The vmi-win-guid name window7-sp1 is not giving the windows kernel info. I try to find kernel file but not available. Please help me

**Comment by tklengyel** [comment]
I would try rebooting the VM a couple times to see if you can get it working. If not, you will have to locate ntoskrnl.exe on the disk of the VM and extract the PDB information manually as described here: https://github.com/libvmi/libvmi/#rekall-profiles

**Comment by allanng78** [comment]
Hi tklengyel,
Thank for your reply and sorry for the late reply. I have booted several times. I just wondered, is it because I am running on HWM. Please advise me on this. 

You did mentioned about manually extract the ntoskrnl.exe. How do I convert this to pdb file and where should I place them?

Hope to hear from you soon. Thanks.

**Comment by allanng78** [comment]
Hi tklengyel,
I try to manually extract pdb from ntoskrnl.exe using rekall. But rekall gives error stating unable to find physical address space. Is there other similar to that can do the same things?

I really need help. Please help.....

**Comment by tklengyel** [comment]
If Rekall is giving you errors the best place to ask about it would be on Rekall's github page. If you can dump the VMs memory (vmi-dump-memory) and make it accessible somewhere I could perhaps take a look at why vmi-win-guid doesn't work.
