### ISSUE TITLE
Xl list is blank. 

### ISSUE THREAD

**Issue by mangokey** [tklengyel/drakvuf#338]
I have followed the steps on the website mutiple times, but when I attempt to see if the 4GB of virtual memory is there using xl list, the table appears with no entries. 

The only warning I have is  when I run: 
update-rc.d xendomains defaults 21 20 

_insserv: Service xenconsoled has to be enabled to start service xendomains
insserv: exiting now!
update-rc.d: error: insserv rejected the script header_

I am also missinga file for xen in var/run/ thanks!

**Comment by tklengyel** [comment]
What distro are you trying to use as your dom0?

**Comment by tklengyel** [comment]
I assume you have figured it out since, so I'm closing this issue.
