### ISSUE TITLE
Missing dereference when parsing KPCR

### ISSUE THREAD

**Issue by v-p-b** [tklengyel/drakvuf#34]
I think the FILEDELETE plugin misses a dereference when parsing the KPCR in order to find the EPROCESS structure.

At https://github.com/tklengyel/drakvuf/blob/master/src/plugins/filedelete/filedelete.c#L204 :

```c
    vmi_read_addr_va(vmi, fsgs + offsets[KPCR_PRCB] + offsets[KPRCB_CURRENTTHREAD],
                     0, &thread);
```

As you can see on the following KD output (Win7 32-bit), the `KPCR_PRCB` offset is a pointer not a substructure:

```
kd> dt _KPCR 0x82941c00
ntdll!_KPCR
   +0x000 NtTib            : _NT_TIB
   +0x000 Used_ExceptionList : 0x8ad8653c _EXCEPTION_REGISTRATION_RECORD
   +0x004 Used_StackBase   : (null) 
   +0x008 Spare2           : (null) 
   +0x00c TssCopy          : 0x801db000 Void
   +0x010 ContextSwitches  : 0x6a6d4
   +0x014 SetMemberCopy    : 1
   +0x018 Used_Self        : 0x7ffdf000 Void
   +0x01c SelfPcr          : 0x82941c00 _KPCR
   +0x020 Prcb             : 0x82941d20 _KPRCB
   +0x024 Irql             : 0x1f ''
...

kd> dt _EPROCESS poi(poi(poi(0x82941c00+0x20)+4)+0x150)
ntdll!_EPROCESS
   +0x000 Pcb              : _KPROCESS
   +0x098 ProcessLock      : _EX_PUSH_LOCK
   +0x0a0 CreateTime       : _LARGE_INTEGER 0x01d13401`f7ad4a81
   +0x0a8 ExitTime         : _LARGE_INTEGER 0x0
   +0x0b0 RundownProtect   : _EX_RUNDOWN_REF
   +0x0b4 UniqueProcessId  : 0x00000e14 Void


```

I noticed this while studying the code but couldn't specifically test it yet, although I remember Volatility failing on null pointers during previous (unrelated) tests.

**Comment by tklengyel** [comment]
True, what you are looking at 0x20 is only a pointer. However, at the very end of the struct you have 'PrcbData' which is the actual _KPRCB.

    'PrcbData' : [ 0x120, ['_KPRCB']]

This is what we actually use for x86 Win7 (see https://github.com/tklengyel/drakvuf/blob/master/src/plugins/filedelete/filedelete.c#L334). The name used by DRAKVUF, KPCR_PRCB might be deceptive a bit as on x86 Win7 it is called PrcbData, while on x64 it's just called Prcb:

    'Prcb' : [ 0x180, ['_KPRCB']],
