### ISSUE TITLE
error installation of linux vm

### ISSUE THREAD

**Issue by prithvisbisht** [tklengyel/drakvuf#340]
im trying to install linux on xen hypervisor as a vm but im getting following error(picture attached). The file extension of linux file is .ova.
![error in linux](https://user-images.githubusercontent.com/22067692/36019391-24271616-0da5-11e8-87cd-4ce6eb2c0c8c.png)

**Comment by tklengyel** [comment]
This question belongs to the `xen-users` mailinglist
