### ISSUE TITLE
drakvuf halts vm

### ISSUE THREAD

**Issue by analyst321** [tklengyel/drakvuf#341]
Hi,

I was checking out drakvuf and it looks like as soon as I execute drakvuf the VM halts. It only becomes reusable again once I exit drakvuf. I thought maybe the monitoring is too intensive, so I disabled all the plugins in drakvuf and recompiled it, and without even any plugins running, drakvuf just halts and renders the VM no longer useable till it is exited.

Using:

- Ubuntu 14.04.5 LTS x86_64
- Latest drakvuf checked out from Git, xen 4.9, latest libvmi from Git etc.
- Windows 7 SP1 x86 VM
- xvnc4viewer for UI
- statically configured xenbr0 interface
- intel core i7 7500u processor
- 8GB (4*2) 1600MHZ memory

Config file is as follows:

arch = 'x86_64'
name = "win7"
maxmem = 3000
memory = 3000
vcpus = 2
maxcpus = 2
builder = "hvm"
boot = "cd"
hap = 1
acpi = 1
on_poweroff = "destroy"
on_reboot = "destroy"
on_crash = "destroy"
vnc=1
vnclisten="0.0.0.0"
usb = 1
usbdevice = "tablet"
altp2m = 2
shadow_memory = 16
audio=1
soundhw='hda'
vif = [ 'type=ioemu,model=e1000,bridge=xenbr0,mac=00:06:5B:BA:7C:01' ]
disk = [ 'phy:/dev/vg/windows7-sp1,hda,w', 'file:/home/path/iso.iso,hdc:cdrom,r' ]

The logs with all plugins disabled and debugging enabled are at: https://pastebin.com/3ZNdP4aX
The VM becomes irresponsive through the VNC UI, till I send a Ctrl+C and it seems to become responsive once again. Any insights on what might be going on here?

**Comment by tklengyel** [comment]
I don't see anything wrong based on the logs. Usually I recommend using the version of LibVMI that DRAKVUF has as a submodule. Try that?

**Comment by analyst321** [comment]
I was using the submodule already. However, I noticed reestablishing vnc connections showed although halted but updated views, hinting that VM was fine but VNC was not refreshing. I searched for it and found this existing issue: 

https://github.com/tklengyel/drakvuf/issues/238

So just going to try and setup RDP with the VM then. Thanks Tamas.
