### ISSUE TITLE
Stack alignment is incorrect in libinjector

### ISSUE THREAD

**Issue by skvl** [tklengyel/drakvuf#342]
According to [Microsoft](https://docs.microsoft.com/en-us/cpp/build/overview-of-x64-calling-conventions) the stack must be alligned to 16 bytes.

But in `src/libinjector/injector.c` the argument for *CreateProcessA* is aligned to 8 bytes (`addr -= len + 0x8 - (len % 0x8);`).

This is not an issue for *CreateProcessA* but if one use other function (like *ShellExecute* in #339) this could result in access violation on *SSE* instructions.

**Comment by skvl** [comment]
Push fix at 2121e46e1399fc6d2b874e65486e138915cf0df8

**Comment by tklengyel** [comment]
I wouldn't say the alignment wasn't absent, it was just done on 8-byte boundary instead of 16. Also, could you check that the 32-bit injection is doing the correct alignment? It is currently aligning on 4-byte.

**Comment by skvl** [comment]
@tklengyel thank you for quick response. Currently I don't have Windows x86 image.

**Comment by skvl** [comment]
@tklengyel from Intel SDM ([PDF](https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf)) for `MOVDQA`:
> When the source or destination operand is a memory operand, the operand must be aligned on a 16 (EVEX.128)/32(EVEX.256)/64(EVEX.512)-byte boundary or a general-protection exception (#GP) will be generated.

So I think that for 32-bit it should be aligned too.

**Comment by disaykin** [comment]
This issue was fixed in PR #410.
