### ISSUE TITLE
windows 10 failed to list the process in DRAKVUF

### ISSUE THREAD

**Issue by fakapinthehouse** [tklengyel/drakvuf#344]
hello.. i need to ask something.. i already installed windows 10 in Xen.. but when i run this command "vmi-process-list windows10" and error occured... it says "Failed to init LibVMI library" ... i already follows the steps in drakvuf website. .. did i miss anything in configuration because i exactly followed all the steps .. ?

**Comment by tklengyel** [comment]
I would probably double check whether the Rekall profile you created for it matches the kernel it's running with. Does `vmi-win-guid` works?

**Comment by fakapinthehouse** [comment]
yea.. vmi-win-guid is works .. i already create and check the Rekall profile based on the PDB guid and kernel name when i run vmi-win-guid name windows10 .. but i confused why vmi-process-list windows10 get error ..

**Comment by tklengyel** [comment]
In that case you will need to enable the debug output and post the log so we can check where things go wrong.

**Comment by fakapinthehouse** [comment]
i think .. the problems is rekall .. 
![screenshot from 2018-02-20 22-47-33](https://user-images.githubusercontent.com/25030998/36462436-66d93260-1691-11e8-8b43-0e908204d209.png)

this rekall is valid or invalid ?

**Comment by tklengyel** [comment]
Doesn't look like it did anything, so I guess you never had a valid Rekall profile created? That would certainly explain why process-list didn't work. The Rekall profile should be a large json file.

**Comment by fakapinthehouse** [comment]
yea . i think rekall is problem.. it didnt create a valid rekall profile for windows 10 .. so what i suppose to do ? please help me ..

**Comment by tklengyel** [comment]
You need to create a valid Rekall profile, there is no way around that. If Rekall is unable to do that, you will need to open a ticket on their github page.

**Comment by mdolmen** [comment]
@fakapinthehouse these links should resolve your issue : 

https://github.com/libvmi/libvmi/issues/548
https://github.com/google/rekall/issues/355

I had the same error as you. It seems that Rekall fails to generate a proper profile for Windows 10 with Python 2.7.x versions. It works well for Linux though. You can switch into a Python 3 virtualenv and either compile it or install it directly with pip.

https://pypi.python.org/pypi/rekall/1.7.2rc1
