### ISSUE TITLE
uuid-dev not listed as a dependency 

### ISSUE THREAD

**Issue by daniangelos** [tklengyel/drakvuf#346]
Running make after configure and got 
/usr/include/libxl_uuid.h:34:10: fatal error: uuid/uuid.h: No such file or directory

**Comment by tklengyel** [comment]
It is listed as a dependency.

**Comment by daniangelos** [comment]
Yes, I saw it on the .yml after. This is odd, ./configure pointed out all missing dependencies with the exception of this one. I'm investigating if it is something in my computer.

Anyway, closing this issue. Thanks

**Comment by tklengyel** [comment]
Might be the libxl dependency is not coded into its configure script. That is being maintained by Xen so you can post the error to the xen-devel mailinglist!
