### ISSUE TITLE
linbinjector injects corrupted string

### ISSUE THREAD

**Issue by skvl** [tklengyel/drakvuf#348]
## Steps to reproduce
1. Build Drakvuf for Xen
2. Run Windows 7 x64
3. Run injector: `injector win7-sp1-x64.rekall.json <VM ID> <PID> '"C:\Program Files (x86)\Microsoft Office\Office12\WINWORD.exe" C:\test_doc_1.doc'`
4. Nothing happens

## Info
While debugging I've noticed:
1. In `libvmi/libvmi/drivers/xen/xen.c:xen_put_memory()` the string is good at `memcpy()`.
2. If I add reading the string from destination buffer after `memcpy()` the string is good too.
3. In donor application at the begining of `kernel32!CreateProcessA` the string on the is corrupted (I could see this in WinDbg): one of the symbols is `null`.
4. In all test cases the string places in single page.
5. I have thought that this corresponds to libvmi/libvmi#464. So I have tried to configure LibVMI as `--disable-address-cache --disable-page-cache`. But with both configs it could not run (`undefined symbol ...`) and none of them didn't help.

**Comment by tklengyel** [comment]
When you specify the string you are injecting, you have to make sure `\` signs are properly escaped. Could that be the issue you are seeing?

**Comment by skvl** [comment]
No I don't think so. Because in GDB attached to `injector` I could see correct string. And in VM through WinDbg I could see almost correct string. And the corrupted byte is not neare any `\`. For example for the string above (`'"C:\Program Files (x86)\Microsoft Office\Office12\WINWORD.exe" C:\test_doc_1.doc'`) I have seen that character `e` in `exe` could be corrupted (with null).

**Comment by tklengyel** [comment]
Unfortunately I'm not sure what might be causing this issue on your side. Is it consistently reproducible? I would try to perhaps set a memory trap on the injected string to see what - if any - is modifying the memory after its written by the injector.

**Comment by skvl** [comment]
@tklengyel, close the issue please because after system reinstall it have disappeared. I think that was some artifact.
Sorry to trouble you.
