### ISSUE TITLE
error in rekall fetch_pdb

### ISSUE THREAD

**Issue by fakapinthehouse** [tklengyel/drakvuf#352]
hello.. i got errors by using command "rekall fetch_pdb ntkrnlmp c68ee22fdcf6477895c54a862be165671" 

![screenshot from 2018-02-27 21-55-18](https://user-images.githubusercontent.com/25030998/36767583-1b8f82a0-1c09-11e8-97ec-d52493ff2a66.png)

please help me...

**Comment by tklengyel** [comment]
This seems like an issue with only Rekall so please open an issue on their page: https://github.com/google/rekall
