### ISSUE TITLE
VMI_ERROR: Xen reports a VM_EVENT_INTERFACE_VERSION that doesn't match what we expected 

### ISSUE THREAD

**Issue by paspe** [tklengyel/drakvuf#355]
Here is the issue.
I had created a plugin to trap some system calls like you do in your syscalls plugin, using an older version of all drakvuf, libvmi and xen, on a Linux guest (Ubuntu). When I updated to the latest version, firstly I had some issues compiling your code in the syscalls plugin.

`
syscalls/syscalls.cpp:510:59: error: member access into incomplete type 'const struct syscalls_config'
symbols_t* symbols = drakvuf_get_symbols_from_rekall(c->rekall_profile);
^
syscalls/syscalls.cpp:509:18: note: forward declaration of 'syscalls_config'
const struct syscalls_config * c = (const struct syscalls_config*)config;
`

Since I don't use it as is ( I created a new plugin), I just commented it out to compile. Therefore, I cannot say if I would have the same issue with the original plugin. 
When I am doing the loop to trap the system calls, on some of them I get the following error, but not on others:

`
VMI_ERROR: Error, Xen reports a VM_EVENT_INTERFACE_VERSION that doesn't match what we expected (0x00000002)!
`
Do you have any idea why that could be? The trapping is in a loop, so I use the exact same way to do it.
Thanks

**Comment by tklengyel** [comment]
When you update to the latest version of DRAKVUF you need to ensure you are using the version of Xen that is recorded in the submodule. Currently this is Xen 4.9.1. Also, when updating, you should clean your folder before compiling, ie run `make clean`.
