### ISSUE TITLE
libvmi vmi-process-list not working

### ISSUE THREAD

**Issue by rohaaan** [tklengyel/drakvuf#365]
hi,
I followed instructions at https://www.drakvuf.com

In case of Libvmi after compilation and installation,
vmi-win-guid is working but vmi-process-list is not.

On execution following error is displayed:
root@ubuntu:/home/ubuntu# vmi-process-list windows7-x64
Failed to init LibVMI library.

Please suggest a way to resolve this.

**Comment by rohaaan** [comment]
/drakvuf/libvmi/libvmi/os/windows/core.c
function: check_pdbase_offset
                                       rekall_profile_symbol_to_rva fails

**Comment by tklengyel** [comment]
Check that the rekall profile you created is a valid json file. If not, try to recreate it.

**Comment by rohaaan** [comment]
> "Check that the rekall profile you created is a valid json file. If not, try to recreate it."

Confirm json validity -- What exactly should be checked here??

**Comment by tklengyel** [comment]
Is it a json file?

**Comment by rohaaan** [comment]
> "Is it a json file?"
yes

**Comment by rohaaan** [comment]
Windows7 x64 sp1: ntkrnlmp

**Comment by rohaaan** [comment]
I confirmed json validity and also recreated it But still the error is not gone...

**Comment by tklengyel** [comment]
You will need to enable LibVMI debug output and check where the error comes from.

**Comment by rohaaan** [comment]
hi,
I made alternate installation of python3.5 and recompiled rekall
created the json which was correct and had no missing information.
the vmi-process-list worked.

**Comment by sodajiaojiao** [comment]
Hello,
I have the same problem with you now,can you tell me what's the meaning of   "recompile rekall" with python3?
