### ISSUE TITLE
Could't run Drakvuf and shows "Failed to initialize DRAKVUF"

### ISSUE THREAD

**Issue by Skakf** [tklengyel/drakvuf#376]
Hello,  I met some problems in running Drakvuf :(

Last time , after I change to python3.5, the rekall1.7.1 works and libvmi could run vmi-process-list succeed.
However, when I tried to run drakvuf, it shows Failed to initialize DRAKVUF.

The debug output is shown as follow.
> root@ubuntu-Lenovo-Product:/home/ubuntu/Desktop/Drakvuf/drakvuf# sudo ./src/drakvuf -r /root/win7.rekall.json  -d 1
DRAKVUF v0.6-d077e69
LibVMI Version 0.11.0
LibVMI Driver Mode 0
**The running Xen version is 4.9
--completed driver init.
--got name from id (1 --> win7)
**set image_type = win7
**set vm_type HVM
--xen: setup live mode
**set allocated_ram_size = 8004b000, max_physical_address = 0xff001000
**set pae = 1
**set pse = 1
**set lme = 1
**IA-32e paging
**sanity checking cr3 = 0x0000000000187000
**set os_type to Windows.
**Trying to init from Rekall profile
--PTLookup: lookup vaddr = 0xfffff80003c68000
--PTLookup: dtb = 0x0000000000187000
--MEMORY cache set 0x187000
--xen_get_memory_pfn success on pfn=0x187
--PTLookup: pml4e_address = 0x0000000000187f80
--MEMORY cache set 0x199000
--xen_get_memory_pfn success on pfn=0x199
--PTLookup: pdpte_address = 0x0000000000199000, pdpte_value = 0x0000000000198063
--MEMORY cache set 0x198000
--xen_get_memory_pfn success on pfn=0x198
--PTLookup: pde_address = 0x00000000001980f0, pde_value= 0x00000000001e2063
--MEMORY cache set 0x1e2000
--xen_get_memory_pfn success on pfn=0x1e2
--PTLookup: pte_address = 0x00000000001e2340, pte_value = 0x8000000003c68963
--PTLookup: paddr = 0x0000000003c68000
--V2P cache set 0xfffff80003c68000 -- 0x0000000003c68000
**KernBase PA=0x3c68000
**KernBase VA=0xfffff80003c68000
--MEMORY cache set 0x3e17000
--xen_get_memory_pfn success on pfn=0x3e17
**init from Rekall profile success
**Getting kernel page directory from Rekall profile
--MEMORY cache set 0x3f10000
--xen_get_memory_pfn success on pfn=0x3f10
**Found PsInitialSystemProcess at 0xfffffa8001836b30
--PTLookup: lookup vaddr = 0xfffffa8001836b58
--PTLookup: dtb = 0x0000000000187000
--MEMORY cache hit 0x187000
--PTLookup: pml4e_address = 0x0000000000187fa8
--MEMORY cache set 0x5000000
--xen_get_memory_pfn success on pfn=0x5000
--PTLookup: pdpte_address = 0x0000000005000000, pdpte_value = 0x0000000005001863
--MEMORY cache set 0x5001000
--xen_get_memory_pfn success on pfn=0x5001
--PTLookup: pde_address = 0x0000000005001060, pde_value= 0x000000007f4009e3
--PTLookup: 2MB page
--PTLookup: paddr = 0x000000007f436b58
--V2P cache set 0xfffffa8001836b58 -- 0x000000007f436b58
--MEMORY cache set 0x7f436000
--xen_get_memory_pfn success on pfn=0x7f436
--kpgd from rekall profile success
**set pae = 1
**set pse = 1
**set lme = 1
**IA-32e paging
**sanity checking cr3 = 0x0000000000187000
--Starting single step on domain 1
Enabling single step
--Shutting down single step on domain 1
--Removing MTF flag from vcpu 0
--Shutting down single step on domain 1
--Removing MTF flag from vcpu 0
Destroying memaccess on gfn events
Destroying memaccess generic events
Destroying register events
Destroying MSR events
Destroying singlestep events
Destroying interrupt events
Destroying clear events
Failed to initialize DRAKVUF

So...what happened? It seems that there is something wrong in the latter part.
Why is it removing and destroying those things?
Is...there something wrong with my VM win7 ??

My PC: Ubuntu16.04, win7_VM

> root@ubuntu-Lenovo-Product:/home/ubuntu/Desktop/Drakvuf/drakvuf# sudo xl list
Name                                        ID   Mem VCPUs	State	Time(s)
Domain-0                                     0  5942     4            r-----    1199.4
win7                                              1  2048     1             -b----      98.9

Please give me some help.
Thanks a lot!

**Comment by Skakf** [comment]
And this is my xl info

> root@ubuntu-Lenovo-Product:/home/ubuntu/Desktop/Drakvuf/drakvuf# sudo xl info
host                   : ubuntu-Lenovo-Product
release                : 4.13.1
version                : #1 SMP Thu Jan 25 18:04:57 CST 2018
machine                : x86_64
nr_cpus                : 4
max_cpu_id             : 3
nr_nodes               : 1
cores_per_socket       : 4
threads_per_core       : 1
cpu_mhz                : 3192
hw_caps                : bfebfbff:77bae3ff:28100800:00000001:00000001:00000281:00000000:00000100
virt_caps              : hvm hvm_directio
total_memory           : 8122
free_memory            : 1
sharing_freed_memory   : 0
sharing_used_memory    : 0
outstanding_claims     : 0
free_cpus              : 0
xen_major              : 4
xen_minor              : 9
xen_extra              : .1
xen_version            : 4.9.1
xen_caps               : xen-3.0-x86_64 xen-3.0-x86_32p hvm-3.0-x86_32 hvm-3.0-x86_32p hvm-3.0-x86_64 
xen_scheduler          : credit
xen_pagesize           : 4096
platform_params        : virt_start=0xffff800000000000
xen_changeset          : 
xen_commandline        : placeholder
cc_compiler            : gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
cc_compile_by          : ubuntu
cc_compile_domain      : 
cc_compile_date        : Thu Jan 25 17:00:57 CST 2018
build_id               : 4f360c7ab51e89c1b51e359aebcb8d2fb61ee513
xend_config_format     : 4

**Comment by tklengyel** [comment]
From the logs posted it is not obvious why it fails to initialize. Please compile DRAKVUF itself with `--enable-debug` and run with the `-v` flag, then post the log.

**Comment by Skakf** [comment]
Thank you very much! :-)
I compile Drakvuf with debug and I have already found the problem.
I forgot to enable the altp2m.

**Comment by tklengyel** [comment]
Care to post what the problem was in case someone runs into this in the future?
