### ISSUE TITLE
Request: UPDATE INSTALLATION INSTRUCTIONS

### ISSUE THREAD

**Issue by rohaaan** [tklengyel/drakvuf#377]
Please update the installation instructions.
Add python3.5 in section to compile rekall

**Comment by Skakf** [comment]
Hello, can I ask a question?
Can you run drakvuf successfully?
Do we still need to  install volatility before running drakvuf?
Because I find that the new installation instruction on drakvuf.com seems not to mention this.

**Comment by tklengyel** [comment]
@rohaaan the instructions have already been updated last week
