### ISSUE TITLE
regmon and procmon with win7x86

### ISSUE THREAD

**Issue by asabellico** [tklengyel/drakvuf#378]
Hello, did anyone experienced problems using regmon and procmon plugins with Windows 7 x86 guest?
I've no problem with those in Win7 x64 but with x86 no regmon lines are shown, and no commandline and imagepath are shown in procmon lines.

Anyone had the same problem?

**Comment by tklengyel** [comment]
I think `procmon` exclusively supports 64-bit at the moment, at least that's in the code right now:
```
        // TODO: Implement and test for 32bit guests.

**Comment by disaykin** [comment]
I add support for x86 in procmon in PR #415.

**Comment by disaykin** [comment]
I add support for x86 in regmon in PR #418 .

**Comment by disaykin** [comment]
Fixed
