### ISSUE TITLE
"Failed to determine init_task!" for kernel 4.13.0+

### ISSUE THREAD

**Issue by richarduu** [tklengyel/drakvuf#381]
Hi,

It seems that libvmi and rekall has a problem working together when the kernel version is higher than 4.13.0...
I am doing evaluation for my paper using libvmi and Drakvuf.
I have managed to run all the experiments for kernel versions acroos 3.13.0 ~ 4.11.0 (specifically, I tested 3.13.0, 3.16.0, 3.19.0, 4.2.0, 4.4.0, 4.10.0, 4.11.0, both Ubuntu 14.04 and 16.04)

But it failed starting from 4.13.0. (4.13.0-16, 4.13.0-38, 4.15.0-13)

It failed because it can not find "tasks" member in task_struct somehow. I enabled the debug option of libvmi and here is the output.

licai@c3:/mnt/extra/flkt/libvmi-app$ sudo vmi-process-list  v1
**The running Xen version is 4.9
--found Xen
LibVMI Version 0.11.0
LibVMI Driver Mode 0
**The running Xen version is 4.9
--completed driver init.
--got id from name (v1 --> 54)
**set image_type = v1
**set vm_type HVM
--xen: setup live mode
**set allocated_ram_size = 3f84a000, max_physical_address = 0xff001000
**set pae = 1
**set pse = 1
**set lme = 1
**IA-32e paging
**sanity checking cr3 = 0x000000000b40a000
--looking for config file at /mnt/extra/flkt/libvmi-app/libvmi.conf
--looking for config file at /users/licai/etc/libvmi.conf
--looking for config file at /users/licai/etc/libvmi.conf
--looking for config file at /etc/libvmi.conf
**Using config file at /etc/libvmi.conf
**set os_type to Linux.
Rekall profile: task_struct has no tasks member
VMI_ERROR: Failed to determine init_task!
Failed to init LibVMI library.

There is no much more logs to show. But please let me know if any other info. may help for diagnosing the problem.

thanks,
Richard

**Comment by mbushou** [comment]
Richard, take a look at this.

https://github.com/google/rekall/issues/337

**Comment by richarduu** [comment]
Thank you very much @mbushou , I am trying it out!

**Comment by richarduu** [comment]
Ok, it works after 1) converting the profile following the [link](https://github.com/google/rekall/issues/337) suggested by @mbushou to fix problems in the profile, 2) applying this [patch](https://github.com/libvmi/libvmi/pull/600) to fix a kaslr bug for new kernels.
