### ISSUE TITLE
Process injection fails on Windows 10

### ISSUE THREAD

**Issue by mdolmen** [tklengyel/drakvuf#395]
The process injection fails on a Windows 10 guest. I first thought that was an issue with the rekall profile because of the `Rekall profile: symbol 'KiInitialPCR' not found` message but I have the same for a Windows 7 guest and everything works fine so I don't think the problem lies here. I made the last Windows update and recompile Drakvuf and LibVMI with the latest version (from submodule for LibVMI). 

The guest always end up crashing before the end of the injection process and Drakvuf has to be stopped manually. I tried _explorer.exe_ and _TaskMgr.exe_ as the target process and both the `CreateProcess` and `ShellExec` methods.

Here are the logs produced by `./src/injector` (got the same with `drakvuf`) : 

> 3264 cmd.exe
> Init VMI on domID 8 -> windows10
> Max GPFN: 0xff001
> Max mem set? 0
> Physmap populated? 0
> Altp2m enabled? 0
> Altp2m view X created? 0 with ID 1
> Altp2m view R created? 0 with ID 2
> Switched Altp2m view to X? 0
> Windows kernel base address is 0xfffff80144aa2000
> Rekall profile: symbol 'KiInitialPCR' not found
> Failed to find offset for KiInitialPCR:(null)
> Rekall profile: '_KPCR' has no 'PrcbData' member
> libdrakvuf initialized
> Injector starting cmd.exe through PID 3264 TID: 0
> Target PID 3264 with DTB 0x53bf0002 to start 'cmd.exe'
> Found PEB @ 0x68e000. LDR @ 0x7ffb3e16c360. INLOADORDER @ 0xa72520.
> Found module Explorer.EXE
> Found module ntdll.dll
> Found module KERNEL32.DLL
>     CreateProcessA @ 0x7ffb3b9d97e0
>     Starting injection loop
>     Started DRAKVUF loop
>     CR3 cb on vCPU 1: 0x11b00002
>     CR3 changed to 0x11b00002
>     CR3 cb on vCPU 1: 0x1aa002
>     CR3 changed to 0x1aa002
>     CR3 cb on vCPU 0: 0x273b0002
>     CR3 changed to 0x273b0002
>     CR3 cb on vCPU 1: 0x3d4a0002
>     CR3 changed to 0x3d4a0002
>     CR3 cb on vCPU 1: 0x1aa002
>     CR3 changed to 0x1aa002
>     [ ... ]
>     CR3 cb on vCPU 0: 0x1aa002
>     CR3 changed to 0x1aa002
>     CR3 cb on vCPU 1: 0x1000002
>     CR3 changed to 0x1000002
>     CR3 cb on vCPU 0: 0x1aa002
>     CR3 changed to 0x1aa002
>     CR3 cb on vCPU 1: 0x1aa002
>     CR3 changed to 0x1aa002
>     CR3 cb on vCPU 1: 0x53bf0002
>     CR3 changed to 0x53bf0002
>     Thread @ 0xffffda84b095f080. ThreadID: 3404
>     Breakpoint VA 0x7ffb3e0ad8e4 -> PA 0x53de8e4
>     Physmap populated? 0
>     Copied trapped page to new location
>     Activating remapped gfns in the altp2m views!
>             Trap added @ PA 0x53de8e4 RPA 0xff0038e4 Page 21470 for entry. 
>             Got return address 0x7ffb3e0ad8e4 from trapframe and it's now
>             trapped!
>             INT3 Callback @ 0x7ffb3e0ad8e4. CR3 0x53b70001.
>             INT3 received but CR3 (0x53b70001) doesn't match target process
>             (0x53bf0002)
>             Switching altp2m and to singlestep on vcpu 1
>             reset trap on vCPU 1, switching altp2m 0->1     <= manually stopped it here
>             ^CDRAKVUF loop finished
>             [INJECT] TIME:1525188207.662914 PID:3264 DTB:0x53bf0002
>             FILE:"cmd.exe" INJECTED_PID:0 INJECTED_TID:0
>             Finished with injection. Ret: 0
>             Process startup failed
>             starting close_vmi_drakvuf
>             close_vmi_drakvuf finished

Do you have any ideas what is going on?

Thanks for your help!

**Comment by mdolmen** [comment]
I got this with Windows 7 too, even on success : 

>     Activating remapped gfns in the altp2m views!
>             Trap added @ PA 0x2c0b046a RPA 0xff00546a Page 180400 for entry. 
>             Got return address 0x778d046a from trapframe and it's now trapped!
>             INT3 Callback @ 0x778d046a. CR3 0x14be3000.
>             Switching altp2m and to singlestep on vcpu 0
>             reset trap on vCPU 0, switching altp2m 0->1
>             INT3 Callback @ 0x778d046a. CR3 0x18100000.
>             INT3 received but CR3 (0x18100000) doesn't match target process
>             (0x14be3000)
>             Switching altp2m and to singlestep on vcpu 1
>             reset trap on vCPU 1, switching altp2m 0->1
>             INT3 Callback @ 0x778d046a. CR3 0x7736f000.
>             INT3 received but CR3 (0x7736f000) doesn't match target process
>             (0x14be3000)
>             Switching altp2m and to singlestep on vcpu 1
>             reset trap on vCPU 1, switching altp2m 0->1
>             INT3 Callback @ 0x778d046a. CR3 0x7736f000.
>             INT3 received but CR3 (0x7736f000) doesn't match target process
>             (0x14be3000)
>             Switching altp2m and to singlestep on vcpu 1
>             reset trap on vCPU 1, switching altp2m 0->1
>             INT3 Callback @ 0x778d046a. CR3 0x7736f000.
>             INT3 received but CR3 (0x7736f000) doesn't match target process
>             (0x14be3000)
>             Switching altp2m and to singlestep on vcpu 1
>             reset trap on vCPU 1, switching altp2m 0->1
>             INT3 Callback @ 0x778d046a. CR3 0x7736f000.
>             INT3 received but CR3 (0x7736f000) doesn't match target process
>             (0x14be3000)
>             Switching altp2m and to singlestep on vcpu 1
>             reset trap on vCPU 1, switching altp2m 0->1
>             INT3 Callback @ 0x778d046a. CR3 0x7736f000.
>             INT3 received but CR3 (0x7736f000) doesn't match target process
>             (0x14be3000)
>             Switching altp2m and to singlestep on vcpu 1
>             reset trap on vCPU 1, switching altp2m 0->1
>             INT3 Callback @ 0x778d046a. CR3 0x14be3000.
>             RAX: 0x1
>             Injected PID: 1212. TID: 1504
>             Removing breakpoint trap from 0x2c0b046a.
>             Removed memtrap for GFN 0x2c0b0 in altp2m view 1
>             Removed memtrap for GFN 0xff005 in altp2m view 1
>             DRAKVUF loop finished
>             [INJECT] TIME:1525187540.072626 PID:1740 DTB:0x14be3000
>             FILE:"cmd.exe" INJECTED_PID:1212 INJECTED_TID:1504
>             Finished with injection. Ret: 1
>             Process startup success
>             starting close_vmi_drakvuf
>             close_vmi_drakvuf finished

It means that other processes are generating INT3 right?

**Comment by mdolmen** [comment]
Here are the xen logs. 

> [---------- many more `printk` like the following ----------]
> (XEN) printk: 245 messages suppressed.
> (XEN) [VT-D]DMAR:[DMA Read] Request device [0000:00:02.0] fault addr 7d1b717000, iommu reg = ffff82c000a0d000
> (XEN) printk: 199 messages suppressed.
> (XEN) [VT-D]DMAR:[DMA Read] Request device [0000:00:02.0] fault addr 7d1b717000, iommu reg = ffff82c000a0d000
> (XEN) Disabling non-boot CPUs ...
> (XEN) Entering ACPI S3 state.
> (XEN) CPU0 CMCI LVT vector (0xf1) already installed
> (XEN) Finishing wakeup from ACPI S3 state.
> (XEN) Enabling non-boot CPUs  ...
> (XEN) mwait-idle: max C-state count of 8 reached
> (XEN) mwait-idle: max C-state count of 8 reached
> (XEN) mwait-idle: max C-state count of 8 reached
> (XEN) mwait-idle: max C-state count of 8 reached
> (XEN) mwait-idle: max C-state count of 8 reached
> (XEN) mwait-idle: max C-state count of 8 reached
> (XEN) mwait-idle: max C-state count of 8 reached
> [---------- started the injection at this point ----------]
> (XEN) d1v0 vmentry failure (reason 0x80000021): Invalid guest state (0)
> (XEN) ************* VMCS Area **************
> (XEN) *** Guest State ***
> (XEN) CR0: actual=0x0000000080050039, shadow=0x0000000080050031, gh_mask=ffffffffffffffff
> (XEN) CR4: actual=0x0000000000172678, shadow=0x0000000000170678, gh_mask=ffffffffffffffff
> (XEN) CR3 = 0x8000000051290002
> (XEN) PDPTE0 = 0x0000004000000000  PDPTE1 = 0x0000000280000000
> (XEN) PDPTE2 = 0x0000003380050011  PDPTE3 = 0x0000003380050011
> (XEN) RSP = 0x8000000051290002 (0x8000000051290002)  RIP = 0xfffff80082971124 (0xfffff80082971124)
> (XEN) RFLAGS=0x00000046 (0x00000046)  DR7 = 0x0000000000000400
> (XEN) Sysenter RSP=0000000000000000 CS:RIP=0000:0000000000000000
> (XEN)        sel  attr  limit   base
> (XEN)   CS: 0010 0a09b ffffffff 0000000000000000
> (XEN)   DS: 002b 0c0f3 ffffffff 0000000000000000
> (XEN)   SS: 0018 0c093 ffffffff 0000000000000000
> (XEN)   ES: 002b 0c0f3 ffffffff 0000000000000000
> (XEN)   FS: 0053 040f3 00003c00 0000000000000000
> (XEN)   GS: 002b 0c0f3 ffffffff fffff80081b40000
> (XEN) GDTR:            00000057 fffff80085a53fb0
> (XEN) LDTR: 0000 1c000 ffffffff 0000000000000000
> (XEN) IDTR:            00000fff fffff80085a51000
> (XEN)   TR: 0040 0008b 00000067 fffff80085a52000
> (XEN) EFER = 0x0000000000000000  PAT = 0x0007010600070106
> (XEN) PreemptionTimer = 0x00000000  SM Base = 0x00000000
> (XEN) DebugCtl = 0x0000000000000000  DebugExceptions = 0x0000000000000000
> (XEN) PerfGlobCtl = 0x0000000000000000  BndCfgS = 0x0000000000000000
> (XEN) Interruptibility = 00000000  ActivityState = 00000000
> (XEN) *** Host State ***
> (XEN) RIP = 0xffff82d08030a140 (vmx_asm_vmexit_handler)  RSP = 0xffff8304b311ff90
> (XEN) CS=e008 SS=0000 DS=0000 ES=0000 FS=0000 GS=0000 TR=e040
> (XEN) FSBase=0000000000000000 GSBase=0000000000000000 TRBase=ffff8304b3144c80
> (XEN) GDTBase=ffff8304b3138000 IDTBase=ffff8304b3136000
> (XEN) CR0=000000008005003b CR3=00000002bdc10000 CR4=00000000003526e0
> (XEN) Sysenter RSP=ffff8304b311ffc0 CS:RIP=e008:ffff82d080348ba0
> (XEN) EFER = 0x0000000000000000  PAT = 0x0000050100070406
> (XEN) *** Control State ***
> (XEN) PinBased=0000003f CPUBased=b6a0e5fa SecondaryExec=001214eb
> (XEN) EntryControls=000153ff ExitControls=008fefff
> (XEN) ExceptionBitmap=0006008a PFECmask=00000000 PFECmatch=00000000
> (XEN) VMEntry: intr_info=000000d1 errcode=00000000 ilen=00000000
> (XEN) VMExit: intr_info=00000000 errcode=00000000 ilen=00000003
> (XEN)         reason=80000021 qualification=0000000000000000
> (XEN) IDTVectoring: info=00000000 errcode=00000000
> (XEN) TSC Offset = 0xffffffcd9b775214  TSC Multiplier = 0x0000000000000000
> (XEN) TPR Threshold = 0x00  PostedIntrVec = 0x00
> (XEN) EPT pointer = 0x00000002b94fe01e  EPTP index = 0x0000
> (XEN) PLE Gap=00000080 Window=00001000
> (XEN) Virtual processor ID = 0x1104 VMfunc controls = 0000000000000000
> (XEN) **************************************
> (XEN) domain_crash called from vmx.c:3337
> (XEN) Domain 1 (vcpu#0) crashed on cpu#5:
> (XEN) ----[ Xen-4.9.1  x86_64  debug=n   Not tainted ]----
> (XEN) CPU:    5
> (XEN) RIP:    0010: [fffff80082971124] <= RIP seems to be '0010' after every crash
> (XEN) RFLAGS: 0000000000000046   CONTEXT: hvm guest (d1v0)
> (XEN) rax: 0000000000001004   rbx: 0000000001725d50   rcx: 00007ffbd73a10a4
> (XEN) rdx: 0000000000000000   rsi: 00000000034ff5c0   rdi: 0000000000000000
> (XEN) rbp: 0000000000000001   rsp: 8000000051290002   r8:  0000000000000000
> (XEN) r9:  0000000000000000   r10: 00000000034ff5c0   r11: 0000000000000246
> (XEN) r12: 00007ff69d150130   r13: 0000000000000000   r14: 0000000000000000
> (XEN) r15: 00000000034ff5c0   cr0: 0000000080050031   cr4: 0000000000170678
> (XEN) cr3: 8000000051290002   cr2: 00007ffbc5b12010
> (XEN) fsb: 0000000000000000   gsb: fffff80081b40000   gss: fffff80081b40000
> (XEN) ds: 002b   es: 002b   fs: 0053   gs: 002b   ss: 0018   cs: 0010

**Comment by tklengyel** [comment]
Does this happen only for injection or if you try to run DRAKVUF normally? Could be related to: https://lists.xenproject.org/archives/html/xen-devel/2018-01/msg02275.html The solution to that is going to be upgrading to Xen 4.11 which should be released in the next month or so, but the release candidates work well already.

**Comment by mdolmen** [comment]
Yeah I think that's the same problem, it fails when running Drakvuf normally too. I will upgrade ASAP and keep you updated. Thanks!

**Comment by mdolmen** [comment]
After upgrading Xen to 4.11 and LibVMI everything works great!
