### ISSUE TITLE
Adding NtDeleteFile Hook no Output

### ISSUE THREAD

**Issue by JohnPeng47** [tklengyel/drakvuf#401]
I tried following the implementation in the regmon and filedelete plugins to implement a hook for the NtDeleteFile API call. When I compiled and ran my new code with verbose debugging, it showed that the hook registration was successful:
Copied trapped page to new location
Activating remapped gfns in the altp2m views!
		Trap added @ PA 0x26098bb0 RPA 0xff008bb0 Page 155800 for NtDeleteFile. 
Starting plugin filedelete finished

However, when I ran drakvuf on my VM, I was unable to get any output any plugins. Basically, this was the only output I see, even though with all plugins activated:

DRAKVUF v0.6-c81e2cb
Starting DRAKVUF initialization
Init VMI on domID 4 -> win10
Max GPFN: 0xff00d
Max mem set? 0
Physmap populated? 0
Altp2m enabled? 0
Altp2m view X created? 0 with ID 1
Altp2m view R created? 0 with ID 2
Switched Altp2m view to X? 0
Windows kernel base address is 0xfffff8001528b000
Rekall profile: symbol 'KiInitialPCR' not found
Failed to find offset for KiInitialPCR:(null)
Rekall profile: '_KPCR' has no 'PrcbData' member
Failed to find offset for _KPCR:PrcbData
libdrakvuf initialized
DRAKVUF initializated
Starting plugins
Starting plugin syscalls
Starting plugin syscalls finished
Starting plugin poolmon
Starting plugin poolmon finished
Starting plugin filetracer
Starting plugin filetracer finished
Starting plugin filedelete
	ntoskrnl.exe @ 0xfffff8001528b000
Physmap populated? 0
Copied trapped page to new location
Activating remapped gfns in the altp2m views!
		Trap added @ PA 0x1ee3ea0 RPA 0xff00fea0 Page 7907 for NtSetInformationFile. 
	ntoskrnl.exe @ 0xfffff8001528b000
Physmap populated? 0
Copied trapped page to new location
Activating remapped gfns in the altp2m views!
		Trap added @ PA 0x26098bb0 RPA 0xff010bb0 Page 155800 for NtDeleteFile. 
Starting plugin filedelete finished
Starting plugin objmon
Starting plugin objmon finished
Starting plugin exmon
Starting plugin exmon finished
Starting plugin ssdtmon
SSDT is at 0x21d4cb0. Number of syscalls: 460. Size: 3680
Starting plugin ssdtmon finished
Starting plugin debugmon
Starting plugin debugmon finished
Starting plugin cpuidmon
Starting plugin cpuidmon finished
Starting plugin socketmon
Starting plugin socketmon finished
Starting plugin regmon
Starting plugin regmon finished
Starting plugin procmon
	ntoskrnl.exe @ 0xfffff8001528b000
Physmap populated? 0
Copied trapped page to new location
Activating remapped gfns in the altp2m views!
		Trap added @ PA 0x231ff34 RPA 0xff011f34 Page 8991 for NtCreateUserProcess. 
Starting plugin procmon finished
Beginning DRAKVUF loop
Started DRAKVUF loop
Pre mem cb with vCPU 0 @ 0x26098000 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x26098000 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x26098008 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x26098008 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x26098010 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x26098010 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x26098018 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x26098018 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x26098020 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x26098020 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x26098028 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x26098028 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x26098030 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x26098030 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x26098038 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x26098038 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x26098040 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x26098040 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x26098048 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x26098048 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x26098049 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x26098049 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x2609804a in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x2609804a vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x2609804b in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x2609804b vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x26098060 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x26098060 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x26098068 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x26098068 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x26098070 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x26098070 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x26098078 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x26098078 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x26098079 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x26098079 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x2609807a in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x2609807a vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x2609807b in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x2609807b vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x2609807c in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x2609807c vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x2609807d in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x2609807d vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x26098084 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x26098084 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x2609808c in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x2609808c vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x26098094 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x26098094 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x2609809c in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x2609809c vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x260980a4 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x260980a4 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x260980ac in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x260980ac vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x260980b4 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x260980b4 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x260980bc in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x260980bc vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x260980c4 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x260980c4 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x260980cc in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x260980cc vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x260980d4 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x260980d4 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x260980dc in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x260980dc vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x260980e4 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x260980e4 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x260980ec in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x260980ec vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x260980f4 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x260980f4 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x260980fc in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x260980fc vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x26098104 in view 1: r--
Switching to altp2m view 0 on vCPU 0
Post mem cb @ 0x26098104 vCPU 0 altp2m 0
Pre mem cb with vCPU 0 @ 0x2609810c in view 1: r--

And it just goes on until I stopped drakvuf.
Below is the code for my hook callback:
```
static event_response_t deletefile_cb(drakvuf_t drakvuf, drakvuf_trap_info_t* info){
    printf("im hooooked\n");
    filedelete* f = (filedelete*)info->trap->data;
    vmi_instance_t vmi = drakvuf_lock_and_get_vmi(drakvuf);

    access_context_t ctx;
    ctx.translate_mechanism = VMI_TM_PROCESS_DTB;
    ctx.dtb = info->regs->cr3;

    if(f->pm == VMI_PM_IA32E){
        printf("hook caught\n");
        ctx.addr = info->regs->rcx + f->objattr_name; //get address of objectname
        if ( VMI_FAILURE == vmi_read_addr(vmi, &ctx, &ctx.addr))
            printf("Failure reading address\n");
            drakvuf_release_vmi(drakvuf);
            return 0;
    }
    else{
        printf("32-bit Not supported\n");
        drakvuf_release_vmi(drakvuf);
        return 0;
    }
    unicode_string_t* us = vmi_read_unicode_str(vmi, &ctx);   
    unicode_string_t str2 = { .contents = NULL };

    if (VMI_SUCCESS == vmi_convert_str_encoding(us, &str2, "UTF-8")){
        printf(">>>>>NOTICE ME>>>>>>>>>>>>File deleted: %s\n", (const char*)str2.contents);
        g_free(str2.contents);
    }
    else{
        drakvuf_release_vmi(drakvuf);
        return 0;
    }

    drakvuf_release_vmi(drakvuf);
    return 0;
}
```
Is there anything I'm missing from the callback? And also, any advice on how to debug this situation?

**Comment by tklengyel** [comment]
I'm closing this issue for now, if you have any more updates on it please feel free to reopen.
