### ISSUE TITLE
Windows 10 x64 vmi process list problem

### ISSUE THREAD

**Issue by nystilaps** [tklengyel/drakvuf#406]
Couldn't get drakvuf and even vmi-process-list to work on Win10 x64 build 1083.
First I created rekall profile with 'remnux/rekall' docker image for rekall 
`rekal parse_pdb tcpip.pdb > tcpip.json`
Then I had a problem with unknown ntbuildnumber=18080 in ntbuild2version(...) function.
I added this number to ntbuild2version(...), 
and got another error:
```
** (vmi->page_mode == VMI_PM_IA32E) Entering KPCR register selection loop...
** (vmi->page_mode == VMI_PM_IA32E) => Using kpcr_register_to_use=GS_BASE.
**Trying to init from Rekall profile
Rekall profile: symbol 'KiInitialPCR' not found in $CONSTANTS
Rekall profile: symbol 'KiInitialPCR' not found in $FUNCTIONS
Rekall profile: symbol 'KiDivideErrorFault' not found in $CONSTANTS
**KernBase PA=0x1eb9400
**KernBase VA=0xfffff80188751400
Got ntbuildnumber=18080
**init from Rekall profile success
**Getting kernel page directory from Rekall profile
**Found PsInitialSystemProcess at 0x4140c48348682474
--windows symbol lookup (PsActiveProcessHead)
--trying Rekall profile
--got symbol from kernel sysmap (PsActiveProcessHead --> 0xfffff80188b07850).
--starting search from PsActiveProcessHead (0x45d878894cff3240) using kpgd (0x00000000001aa000).
--failed to find system process with pid 4
--windows symbol lookup (PsInitialSystemProcess)
--trying Rekall profile
--got symbol from kernel sysmap (PsInitialSystemProcess --> 0xfffff80188baf660).
--got PA to PsInitialSystemProcess (0x4140c48348682474).
VMI_ERROR: --requesting PA [0x4140c48348683000] beyond max physical address [0xff000000]
VMI_ERROR:      paddr: 4140c48348682000, length 1000, vmi->max_physical_address ff000000
VMI_ERROR: create_new_entry failed
--failed to resolve PD for System process
VMI_ERROR: Failed to find kernel page directory.
```
Is this a known error?
What may be wrong?
What can I do to fix it?

**Comment by tklengyel** [comment]
Well, `**Found PsInitialSystemProcess at 0x4140c48348682474` doesn't look right. I'm suspecting your Rekall profile may be bad.

**Comment by nystilaps** [comment]
Thank you! I'll investigate it further with time.
Maybe you could tell me which exact version of 64 bit Windows 10 you saw working with drakvuf?

**Comment by mdolmen** [comment]
Hi @nystilaps, the Windows 10 build 1803 from Microsoft's official download page is working with Drakvuf. You can try to generate the profile with `rekall -v` to have more output. You should also use the last version of rekall, the docker container of remnux/rekall was build 3 years ago.. It probably doesn't support the latest Windows kernel images. Personally I use a Python 3 virtualenv to use rekall.

**Comment by enjhnsn2** [comment]
@mdolmen Did rekall form a profile without any trouble for you? Mine cant seem to find the pdb files for Windows build 1803.

**Comment by mdolmen** [comment]
Yeah it works fine. You mean `rekall fetch_pdb ...` doesn't return any result?

**Comment by enjhnsn2** [comment]
Well, it creates a profile, but in the process it complains:
`_EPROCESS.ThreadListHead not valid`
Several times, and then when I try to use the profile it creates, libvmi segfaults :(

**Comment by tklengyel** [comment]
Sounds like the profile is malformed.

**Comment by enjhnsn2** [comment]
@tklengyel I could not figure it out in a reasonable amount of time, so I ended up switching over to Windows 7.
