### ISSUE TITLE
How to capture TCP/UDP segment or datagram using socketmon?

### ISSUE THREAD

**Issue by wax100628** [tklengyel/drakvuf#417]
I found `socketmon.cpp` trap functions in `tcpip.sys` like `TcpTcbDelay`/`TcpDiconnectTcb`, then call the registered function specified in `drakvuf_trap_t.breakpoint.rva`.

I wanna know:

1.  Does the line `access_context_t.addr = info->regs->rsp + sizeof(uint32_t);` in callback function( e.g., `tcpe_x86_cb(...)` ) mean to get the first argument of trapped function(e.g., TcpTcbDelay) ?
2. Which function in `tcpip.sys` can I get tcp/udp send/recv buffer ?

I make a lot of effort to search for documents of tcpip.sys and found many functions using tcpip.sys + tcpip.pdb via IDA, however, I am not familiar with Windows driver programming...

**Comment by tklengyel** [comment]
To answer your questions:
1. Yes
2. You would need to find this out yourself, the plugin is not designed to capture the contents of the packets, only the fact that the connections were made.

**Comment by wax100628** [comment]
Hi, 
Thanks for your reply..

I found an api's prototype is  `int __stdcall TcpFinAcknowledged(PKSPIN_LOCK SpinLock, int);`(used in `socketmon.cpp`) , I'm confused if `esp + 4` means the first param...

By the way, is there an effective approach to capture tcp/udp packets via DRAKVUF or VMI except `tcpdump` program out of VM ..?
