### ISSUE TITLE
Using libdrakvuf in multithreading environment

### ISSUE THREAD

**Issue by aoshiken** [tklengyel/drakvuf#43]
Hi,
I don't know for sure if this is the right place to ask a question but haven't found any mailing list or forum, my apologies in advance.

I wonder how difficult would be to make libdrakvuf thread safe, apart from the usual suspects as the global variables from the libdrakvuf itself (the arrays "offsets" and "struct_sizes" being the main candidates) and the global variables from the plugins, it doesn't seem impossible to me but perhaps there is something I'm unaware of...

All the data needed can be encapsulated into the drakvuf_t struct and used as a drakvuf session along the code, in fact that's how it seems to be already thought.
 
Regards and keep up the good work

**Comment by tklengyel** [comment]
@aoshiken: yes, this is the correct place to talk about issues like this ;)

At the moment libdrakvuf is not thread safe. A quick and dirty way to make it thread safe would be to make all functions declared for libdrakvuf accessible outside (those in drakvuf.h) aquire a lock internally before doing anything, then releasing the lock when done.

Moreover, the underlying LibVMI instance is not thread safe either. Currently in DRAKVUF we do implement a locking scheme that I described above for LibVMI, so that using the vmi instance would be thread safe, but this is really not the best method from a performance perspective as there may well be a bunch of functions that could be run in parallel without much issue (those function only reading memory and from pages already in the cache, etc...).

So overall, it could be made thread-safe rather easily, but the harder part would be to make it thread safe in an optimized way.

**Comment by aoshiken** [comment]
@tklengyel: Many thanks for your quick and accurated response

Well, I was explaining my ideas in a wrong way (it was my fault). I'm referring to the fact of multisession more than multithreading, that is, using many instances of libdrakvuf within the same address space.

Libdrakvuf is synchronous due to the loop waiting for events or timeout so the main program must take that into account and make use of threads accordingly.

The creation, usage and termination of the threads would be the task of the main program, libdrakvuf would encapsulate its global arrays into the drakvuf_t structure as well as provide a "plugin context" suitable for the plugins (basically a "void *") to store their global data, this "plugin context" would be passed to any callback used by the plugins removing the need of global data.

Just my thoughts (probably wrong) ;)

**Comment by tklengyel** [comment]
@aoshiken: I see. Yes, that should be no problem. As long as each drakvuf_t instance is for a separate VM and there is a dedicated thread to handle each drakvuf_t, it should "just work".

**Comment by aoshiken** [comment]
That's where the mentioned "plugin context" enter in action: instead of each plugin having global variables, the plugin maintains its own state using that context.

Probably something like an array of "void *" and size PLUGINS_COUNT count embedded in drakvuf_t could do the trick so the plugin callbacks instead of...

     typedef int (*plugin_init_t) (drakvuf_t drakvuf, const void *config);
     typedef int (*plugin_start_t) (drakvuf_t drakvuf);
     typedef int (*plugin_close_t) (drakvuf_t drakvuf)

...could be something like...

     typedef int (*plugin_init_t) (drakvuf_t drakvuf, void **plugin_context );
     typedef int (*plugin_start_t) (drakvuf_t drakvuf, void *plugin_context );
     typedef int (*plugin_close_t) (drakvuf_t drakvuf, void *plugin_context );

So the plugin context would be initially allocated by the plugin itself on the callback plugin_init and freed on the callback plugin_close, obviously these callbacks would be called once per drakvuf session.

On the other hand, regarding the traps...
     event_response_t callback(drakvuf_t drakvuf, drakvuf_trap_info_t *info)
would be replaced by...
     event_response_t callback(drakvuf_t drakvuf, drakvuf_trap_info_t *info, void *plugin_context)

That makes sense for you? :)

**Comment by tklengyel** [comment]
The problem I see with that is then libdrakvuf will need to be aware of what plugins are present and store them in a way to be able to differentiate between various plugin_context. That's not ideal as I would prefer libdrakvuf to be plugin-agnostic.

What I could forsee as a potential solution is that for plugins that need to maintain some state, each could have a GHashTable defined locally where the various contexts are cached with the key being the drakvuf_t pointer itself. That way the plugin would be able to just grab the context associated with the drakvuf_t instance directly, without libdrakvuf having to be aware of what plugins are enabled.

**Comment by tklengyel** [comment]
Alternatively, each DRAKVUF trap already has the option to carry a void* to arbitrary data (`void *data;`), which could be used to carry the plugin context as well. Maybe that's a better way to solve this problem as that would avoid having to lookup the context in each callback.

**Comment by aoshiken** [comment]
Regarding the GHashTable solution I don't see it clearly (please, enlighten me if I'm wrong), apart from the GHashTable itself you would need a synchronization primitive (e.g. mutex) anyway because different plugin instances can access the same GHashTable at the same time (one instance just for reading while other for adding a new element, for example).

That's an interesting discussion, more to come later... ;)

**Comment by tklengyel** [comment]
Yea, I think the other approach would be better, just passing the plugin context through the trap data pointer itself. I think I'll just merge plugin_init_t and plugin_start_t (really there is no need to have both), and then for each trap that is registered the context is passed through the trap. For freeing that context on plugin close, the plugin will just have a GSList for storing each context protected by a mutex, and that list wouldn't be used for other purposes.. How does that sound?

**Comment by tklengyel** [comment]
@aoshiken: I've changed filetracer based on this idea that you can see at https://github.com/tklengyel/drakvuf/blob/multithreading_plugins/src/plugins/filetracer/filetracer.c. However, it adds quite a bit of complexity to the development of plugins. So the question I have for you, why can't you run separate instances of the drakvuf binary? Instead of having a single binary managing multiple drakvuf_t instances, you can run multiple instances of the binary each having internally just a single drakvuf_t instance.

**Comment by aoshiken** [comment]
@tklengyel: First, thanks for your time and your effort :)

I was thinking on using libdrakvuf as a lib more than DRAKVUF as a program with the following purposes on mind:
- Using less resources when starting multiple analysis (dozens over and over again)
- Sharing data more easily between our plugins and the main program (kernel handles, pids, etc.).

Don't mind, I'm pretty sure I can deal with the current DRAKVUF status.

Again, thanks a lot for your time, you can close this ticket :)

**Comment by tklengyel** [comment]
@aoshiken: I've made some progress on this issue by converting the plugins and the top-level drakvuf instance to C++. Check out the branch cpp (https://github.com/tklengyel/drakvuf/tree/cpp) and see if that would work for you. I actually kind-of like it this way and it doesn't seem to add too much complexity to the development of plugins.

**Comment by aoshiken** [comment]
@tklengyel Again, thanks for your invaluable time.

Sincerely, I get used to DRAKVUF as is in its current status, anyway I can use whatever you finally choose.

As I said in my previous comment you can close this ticket
