### ISSUE TITLE
Gather syscall return value

### ISSUE THREAD

**Issue by tklengyel** [tklengyel/drakvuf#442]
Currently the syscall plugin only triggers at syscall entry. It would also be valuable for gathering the return value of the syscall. Prior work in PR #261 attempted to address this but needs update and has been without activity for a while.

**Comment by mdolmen** [comment]
I start working on it.

**Comment by GameCaretaker** [comment]
Hello,seniors! I am also searching the way to get return value.And in my test, i have some questions.
1:When the memory page is changed into memory from virtual memory,will the PA changed also?
2:How the callback run when a memory breakpoint event is triggered?i can see int3_cb, pre_mem_cb and post_mem_cb. and in some callback functions, i find drakvuf will reinject the breakpoint,this is conflicted whth the drakvuf_remove_trap in ret_callback funtion,is this?
And drakvuf_get_current_thread_id have been called in callback functions in vmi.c,so we need not to call it in our callback functions . Instead, we can use info->proc_data.pid to get it.
i am not good at English,and i hope i donnot make error in my sentences.if i offend you, i

**Comment by GameCaretaker** [comment]
if i offend you ,i sincerely apologize to you

**Comment by tklengyel** [comment]
@GameCaretaker please open separate issues for your questions as they don't directly relate to this one
