### ISSUE TITLE
Failure to inject malware

### ISSUE THREAD

**Issue by winnythomas** [tklengyel/drakvuf#446]
Hi, I got a working drakvuf setup. Ubuntu 16.04, latest Xen (xen-4.11), latest drakvuf and libvmi. I can inject and start notepad.exe and calc.exe into explorer.exe inside a 32 bit windows7-sp1. But when I try to inject the adylkuzz malware (f2e1d236c5d2c009e1749fc6479a9ede) I get the "process startup failed" message. I got the same when I tried the code from https://github.com/LordNoteworthy/al-khaser. So except for notepad, calc and some simple binaries, the injection does not work.

I have attached the logs. It goes the same with 64 bit version too. Look forward to your help.

Cheers,

[analysis.log](https://github.com/tklengyel/drakvuf/files/2280135/analysis.log)

**Comment by mdolmen** [comment]
Did you put the binary you want to execute in the VM first and give the full path to it to the `-e` option? If so try to inject the task manager (taskmgr.exe) instead of explorer.exe.

**Comment by winnythomas** [comment]
I got the malware to inject inside the VM. both taskmgr.exe and explorer.exe works fine. When injected into taskmgr.exe it calls CreateProcess to launch the inject binary. So in my syscall trace I should see NtCreateProcess or something that hints at taskmgr.exe called a process creation API. I dont see this! From the point of injecting till I stop the logs I get a lot of syscall traces, but I dont see anything related to the malware being analyzed. For example like I just mentioned the CreateProcess syscall cannot be seen nor the corresponding call to CreateProcessInternalW which the malware makes. The malware talks to the service control manager to query and start services. Since these are at the user layer I guess drakvuf wont see these?

Thank you. cheers

**Comment by tklengyel** [comment]
Plugins like the syscall trace only start after the injection already finished, so you wouldn't see injection related events in yours logs.

**Comment by tklengyel** [comment]
> The malware talks to the service control manager to query and start services. Since these are at the user layer I guess drakvuf wont see these?

You could if you add a plugin for it. By default no.

**Comment by winnythomas** [comment]
Thank you folks for the response.
