### ISSUE TITLE
NtDelayExecution(...) print actual dalay

### ISSUE THREAD

**Issue by nystilaps** [tklengyel/drakvuf#449]
Now when function NtDelayExecution(...) is called it prints DelayInterval which is PLARGE_INTEGER, a pointer to number containing delay in hundreds of nanoseconds.

https://undocumented.ntinternals.net/index.html?page=UserMode%2FUndocumented%20Functions%2FNT%20Objects%2FThread%2FNtDelayExecution.html

I want to print actual delay in miliseconds.

Where should this enhancement go codewise?
Should it be another plugin like `delaymon` or somewhere else?

**Comment by tklengyel** [comment]
A new plugin sounds appropriate for this.
