### ISSUE TITLE
Compilation fails on incompatible vmi_clear_event() invocation

### ISSUE THREAD

**Issue by v-p-b** [tklengyel/drakvuf#45]
I tried to compile the latest master, but make fails with the following error (multiple occasions):

```c
injector.c:781:9: error: too many arguments to function 'vmi_clear_event'
         vmi_clear_event(vmi, event, NULL);
```
(Edit: this is `injector.c` in libdrakvuf)

The corresponding API is defined like this in my `/usr/local/include/libvmi/events.h`:

```c
status_t vmi_clear_event(
    vmi_instance_t vmi,
    vmi_event_t *event);
```

I looked at the history but couldn't find any relevant changes that would cause this. What am I missing?

Edit:
Now I see that the change was introduced with the altp2m merge but it's still unclear how this should work

**Comment by tklengyel** [comment]
Make sure you update LibVMI to the latest master branch!

**Comment by v-p-b** [comment]
Thanks, this resolved the issue!
