### ISSUE TITLE
Support WoW64 processes

### ISSUE THREAD

**Issue by skvl** [tklengyel/drakvuf#456]
As I understand there is no simple way to intercept _DLLs_ of *WoW64* processes.

In `libdrakvuf/win-exports.c:eprocess_sym2va()` the `_PEB` (actually `_PEB64` from rekall profile) address is taken from `_EPROCESS`. But there's no such link for `_PEB32` (also no reference in rekall profile from other structures).

From _WinDbg_ one could see that `NtQueryInformationProcess()` returns the address of some structure similar to `_PEB32` if called with `ProcessWow64Information` argument (`=0x1a`). But I didn't debug the kernel so I don't know where it is stored. It is possible that it displacement against `_PEB64` is hard-coded.

After receiving the address of `_PEB32` one could use the `modlist_sym2va()` to resolve a symbol from 32-bit _DLL_.

**Comment by wbenny** [comment]
32bit TEB is always 2 pages after 64bit TEB. From that you can get the 32bit PEB.

**Comment by skvl** [comment]
Hello @wbenny 

> 32bit TEB is always 2 pages after 64bit TEB
This could be version specific.

Though for my task I had moved down into the kernel. Intercepting the _DLLs_ is bad idea for me because some times I work with raw system calls.

**Comment by wbenny** [comment]
> This could be version specific.

Could be, it definitelly isn't documented. But it applies since WoW64 exists - from XP to latest Win10. Also, PEB32 is always 1 page after PEB64.

I just wanted to point out that there is relatively easy way how to get TEB32/PEB32 from WoW64 process.

**Comment by skvl** [comment]
@wbenny , thank You very much for Your research. I will definitely use this if I'll return to this.

**Comment by tklengyel** [comment]
@sklv FYI https://github.com/bigzz/WRK/blob/master/public/internal/base/inc/wow64t.h#L378

```
#define WOW64_ROUND_TO_PAGES(Size)  \
(((ULONG_PTR)(Size) + PAGE_SIZE - 1) & ~(PAGE_SIZE - 1))

#define WOW64_GET_TEB32_SAFE(teb64) \
((PTEB32) ((ULONGLONG)teb64 + WOW64_ROUND_TO_PAGES (sizeof (TEB))))

**Comment by aoshiken** [comment]
> > This could be version specific.
> 
> Could be, it definitelly isn't documented. But it applies since WoW64 exists - from XP to latest Win10. Also, PEB32 is always 1 page after PEB64.
> 
> I just wanted to point out that there is relatively easy way how to get TEB32/PEB32 from WoW64 process.

**No**, that's not entirely true as you can see from my Windows7 SP1 x64 after entering into the context of my own WoW process :
```
kd:x86> .load wow64exts
kd:x86> !info

PEB32: 0x7efde000
PEB64: 0x7efdf000
```

**Comment by wbenny** [comment]
Interesting, I would swear that I've always seen those two in the reverse order.

Anyway, what about TEB32? Is it 2 pages after TEB64 or not? If it is, it shoud be possible to take TEB32 and get the PEB32 address from there.

**Comment by aoshiken** [comment]
I'm currently getting the PEB32 in two ways:
- The usual `EPROCESS -> LIST_ENTRY -> KTHREAD -> TEB64 + offset with the macros from the windows souce code -> TEB32 -> PEB32`
- Another way that I found today from EPROCESS (probably it's something known but I don't care), anyway I'm not sure how trustworthy is, in my Win7 SP1 x64 seems to work nicely but like to test with Windows 8 and Windows 10

**Comment by aoshiken** [comment]
Ok, seems to work fairly well.

Find below the debug log of my "test" plugin looking for the `rcprt4.dll` module, there's a WoW64 process called `wowserv.exe` with that module loaded:
```
[...]
1549303770.750850 Found module wowsrv.exe at 0x13c0000
1549303770.750887 Found module ntdll.dll at 0x77010000
1549303770.750910 Found module wow64.dll at 0x73f80000
1549303770.750938 Found module wow64win.dll at 0x73f20000
1549303770.751033 Found module wow64cpu.dll at 0x73ff0000
1549303770.751064 Failed to find rpcrt4.dll in list starting at 0x2e2880
1549303770.751271 Found WoW64 module wowsrv.exe at 0x13c0000
1549303770.751353 Found WoW64 module ntdll.dll at 0x771f0000
1549303770.751409 Found WoW64 module kernel32.dll at 0x75df0000
1549303770.751426 Found WoW64 module KERNELBASE.dll at 0x75390000
1549303770.751515 Found WoW64 module ADVAPI32.dll at 0x75fb0000
1549303770.751548 Found WoW64 module msvcrt.dll at 0x75470000
1549303770.751579 Found WoW64 module sechost.dll at 0x76dc0000
1549303770.751615 Found WoW64 module RPCRT4.dll at 0x75520000
[TEST] visit: CR3[0x95FA8000] pid[0x508 1288] wow_proc[1] base_name[RPCRT4.dll] load_address[0x75520000] wow_module[1] full_name[C:\Windows\syswow64\RPCRT4.dll]
[...]
```
I'll send a PR in a few hours hopping to get some comments about it (@tklengyel and the rest of the contributors).

**Comment by aoshiken** [comment]
@tklengyel,
#552 is merged so we can close this issue right now
