### ISSUE TITLE
libdrakvuf as an external repository

### ISSUE THREAD

**Issue by Wenzel** [tklengyel/drakvuf#458]
Hi,

I would like to use `libdrakvuf`'s features in my projects, in order to work at higher-level than `LibVMI`, in terms of breakpoints mostly.

The reason I'm asking is because I built `r2vmi` on top of `LibVMI`, but now i realize that I need more abstractions.
Instead of using memory events + emulating/single stepping the entire page, i would like to use fast and invisible breakpoints offered by your library.

@tklengyel  what do you think of having `libdrakvuf` in a separate repository, and `Drakvuf` using it as a submodule ?

Do you intend to merge these abstractions into `LibVMI` one day ?
When KVM will have a new VMI interface upstream, having `LibVMI` as the only layer to provide a high-level API would be an interesting goal to reach.

Thanks.

**Comment by tklengyel** [comment]
No, the features in DRAKVUF are not intended to be merged back into LibVMI. Also, the license of DRAKVUF places special restrictions on integrating it with other projects so using it as just a library is not compatible with most open source licenses (ie can't be combined with plain GPL). So unless you want use the DRAKVUF license on the entire project you integrate it with it is unlikely to work.
