### ISSUE TITLE
What is the maximum EPT pages limit ?

### ISSUE THREAD

**Issue by trapframe** [tklengyel/drakvuf#466]
Hi,

What is the number limit of EPT pages we can create ?
is this bound to each CPU/CORE  or to each guest ?

For kernel breakpoints the number of shadow pages created should remain low, but for  user land hooking this number could rise up drastically....
thanks

**Comment by tklengyel** [comment]
The maximum number of shadow pages you can create is limited by the domain's `shadow_memory` parameter in its config file (it's in terms of Mb that the pagetables will consume). If you are expecting to create a lot of shadow pages you should set this reasonably high (64 or even 128 or even higher perhaps).

**Comment by trapframe** [comment]
awesome, thanks
