### ISSUE TITLE
WaitForProcessStart option (-w) may misbehave

### ISSUE THREAD

**Issue by disaykin** [tklengyel/drakvuf#474]
1. In case of injection of "C:\\Program Files\\Microsoft Office\\Root\\Office16\\WINWORD.EXE C:\\sample.doc" drakvuf need to wait for WINWORD process.

2. In case of program with this name and parent already running the drakvuf will premature exit from injection loop. This can ocur in case of warmed up (preloaded for speed) application.

3. In case if there is already running application with similar name (the first 8 characters are the same).

**Comment by arkfps** [comment]
Can we implement WaitForProcess functionality by using the following algorithm?
1. Call `CreateProcess` with `CREATE_SUSPENDED` flag;
2. Perform the necessary initialization;
3. Call `ResumeThread` to wake up process.

**Comment by tklengyel** [comment]
To clarify the issue, when `-w` is specified `injector_start_app` may return earlier then the actual process is injected. Injection would still go through and handled properly by `injector_cleanup` though. But `start_app` would report the wrong PID/TID for the injected process.

@arkfps that's an interesting idea. It would require another function-call injection though while the plugins are already running. So it would still be noisy, logging things before the actual injected process is scheduled yet.

A workaround for setups where processes are already running with the name and ppid matching that of what the injected process would have is to start the applications from another process then what injection would hijack. So if injection is using `explorer.exe` to start winword, use powershell to start the copies of it beforehand. That would ensure that ppid wouldn't be the same.

Another way to resolve this would be to just collect the already running pids on the system, and in the cr3 callback check whether the pid is in that list and only exit if it wasn't. That may be perhaps the easiest to implement.

**Comment by tklengyel** [comment]
@disaykin while that would certainly work, we don't have to use CREATE_SUSPENDED for it necessarily. We could just as well trap inside the kernel to see when the process/thread structures are finished being initialized. That would eliminate the need for a second injection for resuming it.

**Comment by disaykin** [comment]
@tklengyel On the other hand, in case of CREATE_SUSPENDED we does not need to use heuristics to determine the running process by name. We get an absolutely correct way to determine the process we need.

**Comment by tklengyel** [comment]
@disaykin right, but we could read the same out of the new EPROCESS directly when it's initialized. That said, doing it with CREATE_SUSPEND is probably the better route because it's closer to process hollowing which I would still want to have implemented some day (doppelganging is unfortunately too limited).

**Comment by disaykin** [comment]
Fixed in #494
