### ISSUE TITLE
Guest crash after unpause and reattach

### ISSUE THREAD

**Issue by v-p-b** [tklengyel/drakvuf#48]
Steps to reproduce:
  - Start a domain
  - Attach DRAKVUF to the domain (I disabled SYSCALLS and POOLMON for cleaner output)
  - Do stuff
  - Send Ctrl-C to DRAKVUF, the domain gets paused
  - Unpause domain
  - Attach DRAKVUF to the domain again
  - Wait
  - BSOD / VMI_ERROR

I was able to reproduce this on master with 32 and 64-bit Win7 VMs. The latest error msg I got was this (32-bit):
```
VMI_ERROR: Caught a memory event that had no handler registered in LibVMI @ GFN 760112 (0xb9930b0c), access: 6
```

On 64-bit EXMON usually catches an access violation in kernel mode:
```
[EXMON] EXCEPTION_RECORD: 166ce58 EXCEPTION_CODE: 10000004 FIRST_CHANCE: 1 RIP: 44c0b83 RAX: 0 RBX: 3c41610 RCX: d0b RDX: 232a000 RSP: 166d098 RBP: 72ffffb8 RSI: 61766441 RDI: 3c417c8 R8: 6860 R9: 500 R10: 2657000 R11:29c
```

Can anyone else reproduce this? Or is this expected behavior?

**Comment by tklengyel** [comment]
Hm, I'll check, it should clean up after itself and not leave the guest unstable..

**Comment by tklengyel** [comment]
Can you check if 64d0338168fe1e703b802f3964e0df4a7487e054 in the unstable_fix branch fixes this issue for you?

**Comment by aoshiken** [comment]
@v-p-b I've noticed the same behaviour (including the EXMON violation) with my win7 32 and win7 64 VMs but using the DRAKVUF timeout option insted of CTRL+C, not reproducible 100%

@tklengyel I will check asap

**Comment by aoshiken** [comment]
After some testing that DRAKVUF branch seems to fix the issue for me (as far as I can see).

Nice work!
