### ISSUE TITLE
Collecting syscalls/hypercalls for specific processes

### ISSUE THREAD

**Issue by saatvikshah1994** [tklengyel/drakvuf#50]
I want to collect system call traces of specific processes running inside Guest VMs.
1. There is a related question here https://github.com/tklengyel/drakvuf/issues/3, but has this been integrated in the current version of Drakvuf?
2. Is there any way to collect hypercalls invoked by the GuestOS kernel to provide a low level memory access to user processes?
Thanks

**Comment by tklengyel** [comment]
1. Right now we monitor the system calls made by all processes, so filtering it down to the one you are interested in would not be too difficult. There is no official support to do it right now, but essentially you just need to check the CR3 when a system call trap happens and only print if it matches the one corresponding to your process. I'll add the CR3 info the syscalls plugin to be printed, that we you could just grep through the output as well.

2. Yes, though not directly. To issue hypercalls there needs to be a kernel driver responsible for setting up everything before issuing VMCALL, your goal would be to find the function in the kernel driver responsible for that and trap it before the VMCALL is issued. For example for Xen that is done through the xen-privcmd kernel driver (http://lxr.free-electrons.com/source/drivers/xen/privcmd.c) so trapping the functions in there would allow you to monitor the hypercalls before the hypercalls actually happen. Of course, if you are dealing with malicious code, it could issue hypercalls outside of this driver so you need to keep that in mind. In that case your best bet is actually extending the hypervisor itself to just let you know that there was a hypercall.

**Comment by tklengyel** [comment]
I'm closing this issue for now, feel free to open it if you have more questions.
