### ISSUE TITLE
find

### ISSUE THREAD

**Issue by qth1991** [tklengyel/drakvuf#502]
I find in

**Comment by tklengyel** [comment]
It is possible, yes. There is no plugin that does it out-of-the box but you can write your own. Check out the wiki and the plugin developer guide at https://github.com/tklengyel/drakvuf/wiki/DRAKVUF-Developers-Guide. What you would need to do is walk the process list to find the target pid, walks its loaded module list to find the library and then either find the function in the import or export table or use a Rekall profile for it to find where you have to put a trap at.

**Comment by qth1991** [comment]
Thank you for your timely reply.Is that you mean I need to find  "dllbase" which in struct_LDR_DATA_TABLE_ENTRY then  use rekall profile  to find  "RegSetKeyValueA" offset address last put a trap at (dllbase+offset address).
![1](https://user-images.githubusercontent.com/39185602/50063664-5ca70180-01e8-11e9-8516-10b3860d704c.png)

**Comment by tklengyel** [comment]
Correct. Or you can try `drakvuf_exportsym_to_va` if that funtion is exported, then you don't need the Rekall profile.

**Comment by qth1991** [comment]
Thank you for your reply.I see currently available plugins but I don't know how to used the three inputs "myplugin::myplugin(drakvuf,config,output)" of plugin interfaces .
 May i write the plugins base on the plugins of "syscalls" to  monitoring user-level function calls? 
 For example I changed "this->traps = create_trap_config(drakvuf, this, symbols);" to set a  trap of RegSetKeyValueA dllbase+offset address,if it's correct which type trap(trap->type = BREAKPOINT;)
 should to be set? Could you tell me more details about it?

**Comment by tklengyel** [comment]
Breakpoint trap would be probably the best. Syscalls is  OK to start as your base but you will have to adjust it significantly. There is no current plugin that does trapping in userspace so there may also be unknowns that you encounter along the way.

**Comment by qth1991** [comment]
Hi，I almost finshed my  test,but there are some troubles in user-level function of rva(dllbase+offset address),I can 't find correct offset  with guide at http://rekall-forensic.blogspot.com/2014/02/the-rekall-profile-repository-and.html, Could you tell me how to use rekall to find it step by setp. Thank you very much.
![2](https://user-images.githubusercontent.com/39185602/50224864-f2ee4980-03d9-11e9-830d-231c9a7eb5ef.png)

**Comment by qth1991** [comment]
I am sorry to trouble you, but  I don't know  how to find the function parameter in figure one , Is that like the syscall in regs::rcx  regs::rdx regs::r8  regs::r9? Thank you!
![1](https://user-images.githubusercontent.com/39185602/50383221-31da1300-06ea-11e9-9d9d-3123c5e6bfb9.png)

**Comment by tklengyel** [comment]
Yes, the first 4 function parameters are passed in those registers on Windows. The rest will be on the stack.

**Comment by qth1991** [comment]
Thank you very much  for your answer.I use the address in fig2 as the base address of  the advapi32.dll and add the function of rva to it, then call "vmi_pagetable_lookup" to find the pa accordingly , last set trap at the pa . Is that correct?
![1](https://user-images.githubusercontent.com/39185602/50401271-3c6ada00-07c8-11e9-8e32-71dab02dab11.png)

**Comment by tklengyel** [comment]
Sounds right.

**Comment by dscdo** [comment]
@qth1991 how's it going

**Comment by qth1991** [comment]
Hi, how are you recently，I use this function to find the "trap function" of pa, but there a number of "trap function" can't find pa accordingly, is that  because of the caching of vmi_pagetable_lookup? if so, which function should be called?
![image](https://user-images.githubusercontent.com/39185602/50821766-ffc3e480-136a-11e9-8da0-f71f8824a928.png)

![tim 20190108173426](https://user-images.githubusercontent.com/39185602/50822227-22a2c880-136c-11e9-8367-4d83d0f3c009.png)

**Comment by tklengyel** [comment]
It's not because of the cache, it is because the virtual address you are looking up is not valid / loaded into memory yet.

**Comment by qth1991** [comment]
but how to make these virtual address work? I tried to call  the "trap function" in VM , then call the "vmi_pagetable_lookup" function again ，But it still returns an error.
![tim 20190109093517](https://user-images.githubusercontent.com/39185602/50870222-12cdc780-13f2-11e9-9113-d9d7f5675987.png)

![tim 20190109093627](https://user-images.githubusercontent.com/39185602/50870224-15c8b800-13f2-11e9-9a07-584357504393.png)

**Comment by tklengyel** [comment]
Accessing virtual memory not loaded by the guest operating system is not supported right now.

**Comment by qth1991** [comment]
Oh~， I mean call the corresponding function in guest operating system to load it into memory，or what to do in guest operating system to load virtual memory into  memory？ thanks！

**Comment by tklengyel** [comment]
If you called that function and the function executed the it is loaded into memory. You should be able to trap it afterwards. If you can't it is likely because you are using the wrong virtual address or the wrong pagetable for the translation.

**Comment by tklengyel** [comment]
In the guest you should be able to print the virtual address of the function. Do that and compare with what you have in your vmi application.

**Comment by qth1991** [comment]
OK，I see，Thank you very much for your reply！

**Comment by qth1991** [comment]
Hi,When I use the syscalls  plugin, sometimes drakvuf fails to start and sometimes succeeds.I don't know how to fix it.
![1](https://user-images.githubusercontent.com/39185602/51303655-f58f9d80-1a70-11e9-9f67-17445f789b87.png)

**Comment by qth1991** [comment]
Hi,When I use the syscalls  plugin, sometimes drakvuf fails to start and sometimes succeeds.I don't know how to fix it.
![1](https://user-images.githubusercontent.com/39185602/51303655-f58f9d80-1a70-11e9-9f67-17445f789b87.png)

**Comment by tklengyel** [comment]
It likely means that the pagetable LibVMI grabbed to initialize with has invalid entries. This can happen for example if the pagetable is in the middle of being updated by the guest OS. You can probably work around that by having a `libvmi.conf` on your system that defines `win_ntoskrnl` and `win_ntoskrnl_va` for the target VM so that initialization can skip trying to use a bad pagetable. Use the `-l` flag when starting DRAKVUF and you have a `libvmi.conf`.

**Comment by qth1991** [comment]
Yes，Thank you for your reply. Is that drakvuf support using JSON print format? how to turn it up? 
![default](https://user-images.githubusercontent.com/39185602/51528703-3a9d4080-1e72-11e9-908f-2da7ca82b274.png)

**Comment by tklengyel** [comment]
It does not. There is csv and kvp output formats available. Json and XML are both stateful formats that would make drakvuf use more memory then it needs to. So it's unlikely it will ever be an option.

**Comment by qth1991** [comment]
Hi ,Is this due to memory leaks?
![default](https://user-images.githubusercontent.com/39185602/51650901-f53d5800-1fc4-11e9-96af-64167f7f6277.png)

**Comment by tklengyel** [comment]
Possibly. Try to narrow it down if it happens by disabling plugins. If it happens only with a certain plugin enabled then it might be leaking.

**Comment by qth1991** [comment]
Hi,How to get the function of return value in plugin syscalls? Thanks！

**Comment by tklengyel** [comment]
Not sure I understand the question but it if you want the return value after a syscall there is a PR open right now that is trying to do just that.

**Comment by qth1991** [comment]
Oh~ Sorry，My question is when call syscall like "NtCreateFile", How to get  the function return value of "NtCreateFile"

**Comment by qth1991** [comment]
> Not sure I understand the question but it if you want the return value after a syscall there is a PR open right now that is trying to do just that.

Could you give me the url or more information about PR, I can 't  find it!

**Comment by qth1991** [comment]
Hello,I don‘t know why sometime there are "Segmentation fault" in  call "vmi_pid_to_dtb",could you help me?
![TIM截图20190311151746](https://user-images.githubusercontent.com/39185602/54106391-f3aede80-4410-11e9-8b36-c5d6da32d921.png)

![TIM图片20190311151817](https://user-images.githubusercontent.com/39185602/54106399-f7426580-4410-11e9-810c-207dba2a2fec.png)

**Comment by tklengyel** [comment]
You will need to run it through gdb to see where the actual segfault occurs.

**Comment by qth1991** [comment]
OK，this is result of gdb
![TIM图片20190312170054](https://user-images.githubusercontent.com/39185602/54187419-72c31600-44e8-11e9-845d-59c09cfcf980.png)

**Comment by tklengyel** [comment]
Well, according to that trace you got a segfault in `malloc`. I highly doubt the bug is there though. I would suspect faulty hardware but I don't know.

**Comment by qth1991** [comment]
Thank you,Can drakvuf trap multiple virtual machines at the same time?that is “./drakvuf -r /root/windows7-sp1.rekall.json -d 1 2 3 4”？

**Comment by tklengyel** [comment]
> “./drakvuf -r /root/windows7-sp1.rekall.json -d 1 2 3 4”

Technically that would be possible but we don't currently implement that.
