### ISSUE TITLE
DRAKVUF: drakvuf_init() failed

### ISSUE THREAD

**Issue by ultrapikachu** [tklengyel/drakvuf#513]
In start drakvuf throw drakvuf_init() failed

Debug log like this

1546322479.349803 DRAKVUF v0.6-9e6219c
1546322479.349968 Starting DRAKVUF initialization
1546322479.454666 drakvuf_event_fd_add fd=14
1546322479.454705 size of list=1
1546322479.454739 regenerating event_fds and fd_info_lookup...
1546322479.454755 new event_fd i=0 for fd=14
1546322479.454778 new fd_info_lookup i=0 for fd=14
1546322479.454804 drakvuf_init: adding event_fd done
1546322479.471917 libdrakvuf initialization failed
Failed to initialize DRAKVUF: drakvuf_init() failed

**Comment by tklengyel** [comment]
There is not enough information in the log to pinpoint what's wrong so you will have to investigate further. Make sure you have updated LibVMI and that your domain and Rekall profile match.

**Comment by ultrapikachu** [comment]
I did fresh install. 
I'm using ubuntu 18.04 LTS
I followed install instruction on drakvuf.com.
Everything is OK but i got same error.

**Comment by tklengyel** [comment]
What version of Xen? What is the target VM? Does vmi-process-list work? Otherwise you will have to add some debug messages to the code to see where exactly it fails.

**Comment by ultrapikachu** [comment]
Xen version : 4.11
Target VM : W7 x64 & x86 ( i tried both version)
vmi-process-list work successfully without error. 

Only event-example say Could not install sysenter so cant give x86 regs value but in python example (regaccess and memaccess)  i can get all value successfully

**Comment by tklengyel** [comment]
Are you installing LibVMI from the submodule?

**Comment by ultrapikachu** [comment]
Yes. I just did things in the install instruction.
I reinstall ubuntu and still same. 

In debug mode of libvmi, event-example say "An event is already registered on this page: 0"

In drakvuf still i got same error ( libdrakvuf initialization failed)

**Comment by tklengyel** [comment]
Unfortunately I don't know why it fails for you. You will have to add more debug statements into libdrakvuf to see how far it gets.

**Comment by ultrapikachu** [comment]
How can i get debug output of libdrakvuf?
And is it normal that libvmi does?

**Comment by tklengyel** [comment]
The libvmi error is unrelated. To debug this you simply add some `printf` statements to libdrakvuf in the initialization path and recompile. I don't know where it fails so you will have to experiment.

**Comment by ultrapikachu** [comment]
Okey, I'm starting to try.

**Comment by tklengyel** [comment]
I'm closing this issue for now but feel free to reopen once you have more information.
