### ISSUE TITLE
Using libvirt?

### ISSUE THREAD

**Issue by dscdo** [tklengyel/drakvuf#516]
Hi. I installed drakvuf in my system with follow website.
After setup i cant use libvirt and virt-manager too.
xendomains block it and i cant find any way to stop/disable(i try disable on services but still same)

how can i use libvirt with drakvuf

**Comment by tklengyel** [comment]
Managing Xen with libvirt is a question for the `xen-users` mailinglist. As for drakvuf itself, it does not integrate with libvirt in any way.

**Comment by dscdo** [comment]
@tklengyel Okey. Well xendomains is it necessary to drakvuf working? Which parts using? Actually virsh vm xml structure is so basic and it's my reason. Only create machine.

**Comment by tklengyel** [comment]
Xendomains is necessary for Xen to work properly.
