### ISSUE TITLE
VM slowing down

### ISSUE THREAD

**Issue by yguseto** [tklengyel/drakvuf#517]
Hi.
When i start drakvuk, in vm slowing down. When i click any application vm going wait and it take a lot time.

Is this a general problem?
or there is a way to fix problem
@tklengyel

**Comment by tklengyel** [comment]
You can disable the plugins you don't need.

**Comment by yguseto** [comment]
syscall external, I have disabled all plugins. Set timeout to 10000 but still same.
@tklengyel

**Comment by yguseto** [comment]
process based filter is possible?

**Comment by yguseto** [comment]
@tklengyel ? can you give advice? 
Does this have anything to do with the hardware?

**Comment by tklengyel** [comment]
Having faster hardware helps, yes. I don't have any other advice I can give you.
