### ISSUE TITLE
anti-debug func name

### ISSUE THREAD

**Issue by dscdo** [tklengyel/drakvuf#518]
Is Getting more detail from monitoring possible? For example example tried run IsDebugger , how can we get the function name

**Comment by tklengyel** [comment]
I really don't know what your question is here.

**Comment by dscdo** [comment]
@tklengyel How can we solve functions adress from dll(for ex kernel32.dll)

**Comment by tklengyel** [comment]
You mean resolve an address to a symbol? You will need debug data for that.

**Comment by dscdo** [comment]
Not actually. In normally drakvuf set trap each function in rekall profile. How can i add different function to profile / get pdb for that?
For example IsDebuggerPresent(Kernel32.dll)

**Comment by ultrapikachu** [comment]
@tklengyel is there a different solution to pdbparse?
it's buggy and i cant parse my dll

**Comment by tklengyel** [comment]
You can try Rekall. Microsoft open-sourced some stuff too: https://github.com/Microsoft/microsoft-pdb

**Comment by ultrapikachu** [comment]
@tklengyel 
Can we add function to winscproto.h and rekall profile instead of write new plugin?

**Comment by tklengyel** [comment]
I don't know what you mean. winscproto.h is for systemcalls. If its missing a systemcall that can be added. But adding stuff in there for random dll's are not a good idea.
