### ISSUE TITLE
How we can change Xen signatures from machine

### ISSUE THREAD

**Issue by dscdo** [tklengyel/drakvuf#522]
I want to change Xen string from machine to create anti anti-analysis 
(In windows HARDWARE\ACPI\RSDT\Xen)

How can i do it / set custom bios string?  
I need change this on xen source code but i cant find section

**Comment by tklengyel** [comment]
You would have to modify Xen and the ACPI tables it gives to the guest. This is a question for the `xen-devel` mailinglist.
