### ISSUE TITLE
Problem in building Xen from source

### ISSUE THREAD

**Issue by Preetixen** [tklengyel/drakvuf#53]
I am attempting to install DRAKVUF following this [link](http://drakvuf.com/) of the drakvuf page. However I am facing an issue in setting up Xen 4.6 from source. Once I add the fstab entry of /proc/xen, run the update-rc.d and reboot, the system is unable to mount /proc/xen.
 
Can we try installing DRAKVUF at Xen 4.4. Could you suggest if it works at 4.4 ver. of Xen.

Thank you,

**Comment by tklengyel** [comment]
You would only be able to run 0.1 with Xen 4.4, the latest version needs at least Xen 4.6. Are  sure you are booting into Xen when you get the error?

**Comment by Preetixen** [comment]
No, I am not booting into Xen..

Error: can't mount /proc/xen after reboot command.

Please help in this issue

**Comment by Preetixen** [comment]
Hi,

It is not asking the xen-grub entry option after reboot. 

And also, there is no xen folder created inside /proc.

Some warning comming during xen install: EFI VENDOR not set.
(I have created / efi boot partition when i installed ubuntu 14.04 instead of /boot)
Is it causing error?

**Comment by Preetixen** [comment]
I run:

sudo su
make -j4 install-xen
make -j4 install-tools
echo "GRUB_CMDLINE_XEN_DEFAULT=\"dom0_mem=4096M,max:4096M dom0_max_vcpus=4 dom0_vcpus_pin=true hap_1gb=false hap_2mb=false altp2m=1\"" >> /etc/default/grub
echo "/usr/local/lib" > /etc/ld.so.conf.d/xen.conf
ldconfig
update-grub
echo "none /proc/xen xenfs defaults,nofail 0 0" >> /etc/fstab
echo "xen-evtchn" >> /etc/modules
echo "xen-privcmd" >> /etc/modules
update-rc.d xencommons defaults 19 18
update-rc.d xendomains defaults 21 20
update-rc.d xen-watchdog defaults 22 23

then i reboot...
it was showing warnings even after update...

**Comment by Preetixen** [comment]
sure. I will try again tomorrow..

**Comment by tklengyel** [comment]
I assume you have been able to build and boot Xen since so I'm closing this issue.

**Comment by Preetixen** [comment]
Hello sir

**Comment by Preetixen** [comment]
Hello sir,

I did the installation of Xen 4.6, LibVMI, Rekall, Volatility successfully.

But while running following commands:
git clone https://github.com/tklengyel/drakvuf
cd drakvuf
autoreconf -vi
./configure

I am getting error: configure: xenlight (libxl) headers are not usuable.
(i have libxl installed in system).
I am attaching the snapshots. Please help to fix it.
![screenshot from 2016-02-12 19-11-00](https://cloud.githubusercontent.com/assets/16998342/13025615/cd15801a-d25f-11e5-8662-0ea4fb422f24.png)
![screenshot from 2016-02-12 19-16-16](https://cloud.githubusercontent.com/assets/16998342/13025616/cd253bcc-d25f-11e5-89e4-86c0e96b4661.png)
