### ISSUE TITLE
libvmi cannot read config

### ISSUE THREAD

**Issue by johnzion** [tklengyel/drakvuf#555]
![screenshot from 2019-02-09 16-14-35](https://user-images.githubusercontent.com/43522894/52522456-f9849900-2c85-11e9-9490-37c104cf7916.png)
![guid](https://user-images.githubusercontent.com/43522894/52522457-f9849900-2c85-11e9-8515-a7ffcd827009.png)

**Comment by tklengyel** [comment]
You need a space between the vm name and {

**Comment by johnzion** [comment]
![screenshot from 2019-02-17 21-13-07](https://user-images.githubusercontent.com/43522894/52918576-e2365300-32f8-11e9-9d6d-970a96c0d7ac.png)


Same error!

**Comment by aoshiken** [comment]
Recompile Libvmi with debug enabled.
Check if your json file is correctly generated (how you did it?)

**Comment by johnzion** [comment]
root@xen-srv:/home/xen/Downloads# xl create /home/xen/Downloads/win7.hvm 
Parsing config from /home/xen/Downloads/win7.hvm
root@xen-srv:/home/xen/Downloads# gvncviewer localhost
Connected to server
Remote desktop size changed to 720x400
Connection initialized
Remote desktop size changed to 1024x768
Remote desktop size changed to 800x600

root@xen-srv:/home/xen/drakvuf/libvmi# ./autogen.sh 

ibtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:8: installing './compile'
configure.ac:6: installing './missing'
examples/Makefile.am: installing './depcomp'
root@xen-srv:/home/xen/drakvuf/libvmi# 
root@xen-srv:/home/xen/drakvuf/libvmi# ./configure --disable-kvm

Feature         | Option
----------------|---------------------------
Xen Support     | --enable-xen=yes
KVM Support     | --enable-kvm=no
File Support    | --enable-file=yes
Shm-snapshot    | --enable-shm-snapshot=no
Rekall profiles | --enable-rekall-profiles=yes
----------------|---------------------------

OS              | Option
----------------|---------------------------
Windows         | --enable-windows=yes
Linux           | --enable-linux=yes
FreeBSD         | --enable-freebsd=yes

Tools           | Option                    | Reason
----------------|---------------------------|----------------------------
Examples        | --enable-examples=yes
VMIFS           | --enable-vmifs=yes        | yes

If everything is correct, you can now run 'make' and (optionally)
'make install'.  Otherwise, you can run './configure' again.

make
cmake -DENABLE_KVM=OFF -DENABLE_FILE=OFF -DENABLE_BAREFLANK=OFF
CMake Error: The source directory "/home/xen/drakvuf/libvmi" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

make install
Making install in libvmi/config
make[1]: Entering directory '/home/xen/drakvuf/libvmi/libvmi/config'
make[2]: Entering directory '/home/xen/drakvuf/libvmi/libvmi/config'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/xen/drakvuf/libvmi/libvmi/config'
make[1]: Leaving directory '/home/xen/drakvuf/libvmi/libvmi/config'
Making install in libvmi
make[1]: Entering directory '/home/xen/drakvuf/libvmi/libvmi'
make[2]: Entering directory '/home/xen/drakvuf/libvmi/libvmi'
 /bin/mkdir -p '/usr/local/lib'
 /bin/bash ../libtool   --mode=install /usr/bin/install -c   libvmi.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libvmi.so.0.0.13 /usr/local/lib/libvmi.so.0.0.13
libtool: install: (cd /usr/local/lib && { ln -s -f libvmi.so.0.0.13 libvmi.so.0 || { rm -f libvmi.so.0 && ln -s libvmi.so.0.0.13 libvmi.so.0; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libvmi.so.0.0.13 libvmi.so || { rm -f libvmi.so && ln -s libvmi.so.0.0.13 libvmi.so; }; })
libtool: install: /usr/bin/install -c .libs/libvmi.lai /usr/local/lib/libvmi.la
libtool: install: /usr/bin/install -c .libs/libvmi.a /usr/local/lib/libvmi.a
libtool: install: chmod 644 /usr/local/lib/libvmi.a
libtool: install: ranlib /usr/local/lib/libvmi.a
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/sbin" ldconfig -n /usr/local/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/local/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/usr/local/include/libvmi'
 /usr/bin/install -c -m 644 libvmi.h libvmi_extra.h slat.h x86.h events.h peparse.h '/usr/local/include/libvmi'
make[2]: Leaving directory '/home/xen/drakvuf/libvmi/libvmi'
make[1]: Leaving directory '/home/xen/drakvuf/libvmi/libvmi'
Making install in examples/
make[1]: Entering directory '/home/xen/drakvuf/libvmi/examples'
make[2]: Entering directory '/home/xen/drakvuf/libvmi/examples'
make[3]: Entering directory '/home/xen/drakvuf/libvmi/examples'
 /bin/mkdir -p '/usr/local/bin'
  /bin/bash ../libtool   --mode=install /usr/bin/install -c vmi-process-list vmi-module-list vmi-win-guid vmi-dump-memory '/usr/local/bin'
libtool: install: /usr/bin/install -c .libs/vmi-process-list /usr/local/bin/vmi-process-list
libtool: install: /usr/bin/install -c .libs/vmi-module-list /usr/local/bin/vmi-module-list
libtool: install: /usr/bin/install -c .libs/vmi-win-guid /usr/local/bin/vmi-win-guid
libtool: install: /usr/bin/install -c .libs/vmi-dump-memory /usr/local/bin/vmi-dump-memory
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/xen/drakvuf/libvmi/examples'
make[2]: Leaving directory '/home/xen/drakvuf/libvmi/examples'
make[1]: Leaving directory '/home/xen/drakvuf/libvmi/examples'
Making install in tests
make[1]: Entering directory '/home/xen/drakvuf/libvmi/tests'
make[2]: Entering directory '/home/xen/drakvuf/libvmi/tests'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/xen/drakvuf/libvmi/tests'
make[1]: Leaving directory '/home/xen/drakvuf/libvmi/tests'
Making install in tools/vmifs
make[1]: Entering directory '/home/xen/drakvuf/libvmi/tools/vmifs'
make[2]: Entering directory '/home/xen/drakvuf/libvmi/tools/vmifs'
make[3]: Entering directory '/home/xen/drakvuf/libvmi/tools/vmifs'
 /bin/mkdir -p '/usr/local/bin'
  /bin/bash ../../libtool   --mode=install /usr/bin/install -c vmifs '/usr/local/bin'
libtool: install: /usr/bin/install -c .libs/vmifs /usr/local/bin/vmifs
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/xen/drakvuf/libvmi/tools/vmifs'
make[2]: Leaving directory '/home/xen/drakvuf/libvmi/tools/vmifs'
make[1]: Leaving directory '/home/xen/drakvuf/libvmi/tools/vmifs'
make[1]: Entering directory '/home/xen/drakvuf/libvmi'
make[2]: Entering directory '/home/xen/drakvuf/libvmi'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/local/lib/pkgconfig'
 /usr/bin/install -c -m 644 libvmi.pc '/usr/local/lib/pkgconfig'
make[2]: Leaving directory '/home/xen/drakvuf/libvmi'
make[1]: Leaving directory '/home/xen/drakvuf/libvmi'
root@xen-srv:/home/xen/drakvuf/libvmi# echo "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/usr/local/lib" >> ~/.bashrc
root@xen-srv:/home/xen/drakvuf/libvmi# sudo pip install rekall-core
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: rekall-core in /usr/local/lib/python2.7/dist-packages/rekall_core-1.7.3.dev51-py2.7.egg (1.7.3.dev51)
Requirement already satisfied: PyYAML in /usr/lib/python2.7/dist-packages (from rekall-core) (3.12)
Requirement already satisfied: acora==2.1 in /usr/local/lib/python2.7/dist-packages/acora-2.1-py2.7-linux-x86_64.egg (from rekall-core) (2.1)
Requirement already satisfied: arrow==0.10.0 in /usr/lib/python2.7/dist-packages (from rekall-core) (0.10.0)
Requirement already satisfied: artifacts==20170909 in /usr/local/lib/python2.7/dist-packages/artifacts-20170909-py2.7.egg (from rekall-core) (20170909)
Requirement already satisfied: future in /usr/local/lib/python2.7/dist-packages/future-0.17.1-py2.7.egg (from rekall-core) (0.17.1)
Requirement already satisfied: intervaltree==2.1.0 in /usr/lib/python2.7/dist-packages (from rekall-core) (2.1.0)
Requirement already satisfied: ipaddr==2.2.0 in /usr/lib/python2.7/dist-packages (from rekall-core) (2.2.0)
Requirement already satisfied: parsedatetime==2.4 in /usr/local/lib/python2.7/dist-packages/parsedatetime-2.4-py2.7.egg (from rekall-core) (2.4)
Requirement already satisfied: psutil<6.0,>=5.0 in /usr/lib/python2.7/dist-packages (from rekall-core) (5.4.2)
Requirement already satisfied: pyaff4<0.30,>=0.26 in /usr/local/lib/python2.7/dist-packages/pyaff4-0.26.post6-py2.7.egg (from rekall-core) (0.26.post6)
Requirement already satisfied: pycryptodome==3.4.7 in /usr/local/lib/python2.7/dist-packages/pycryptodome-3.4.7-py2.7-linux-x86_64.egg (from rekall-core) (3.4.7)
Requirement already satisfied: pyelftools==0.24 in /usr/lib/python2.7/dist-packages (from rekall-core) (0.24)
Requirement already satisfied: pyparsing==2.1.5 in /usr/local/lib/python2.7/dist-packages/pyparsing-2.1.5-py2.7.egg (from rekall-core) (2.1.5)
Requirement already satisfied: python-dateutil==2.6.1 in /usr/lib/python2.7/dist-packages (from rekall-core) (2.6.1)
Requirement already satisfied: pytsk3==20170802 in /usr/local/lib/python2.7/dist-packages/pytsk3-20170802-py2.7-linux-x86_64.egg (from rekall-core) (20170802)
Requirement already satisfied: pytz==2017.3 in /usr/local/lib/python2.7/dist-packages/pytz-2017.3-py2.7.egg (from rekall-core) (2017.3)
Requirement already satisfied: rekall-capstone==3.0.5.post2 in /usr/local/lib/python2.7/dist-packages/rekall_capstone-3.0.5.post2-py2.7-linux-x86_64.egg (from rekall-core) (3.0.5.post2)
Requirement already satisfied: rekall-efilter<1.7,>=1.6 in /usr/local/lib/python2.7/dist-packages/rekall_efilter-1.6.0-py2.7.egg (from rekall-core) (1.6.0)
Requirement already satisfied: rekall-lib in /usr/local/lib/python2.7/dist-packages/rekall_lib-1.7.2rc1-py2.7.egg (from rekall-core) (1.7.2rc1)
Requirement already satisfied: rekall-yara==3.6.3.1 in /usr/local/lib/python2.7/dist-packages/rekall_yara-3.6.3.1-py2.7-linux-x86_64.egg (from rekall-core) (3.6.3.1)
Collecting aff4-snappy==0.5.1 (from pyaff4<0.30,>=0.26->rekall-core)
  Downloading https://files.pythonhosted.org/packages/79/2a/aded58cebeb7f1ae11fbef99d0fb30a16454a54dabff3d87a7e1f81ecd82/aff4-snappy-0.5.1.zip (64kB)
    100% |████████████████████████████████| 71kB 1.3MB/s 
Collecting expiringdict==1.1.4 (from pyaff4<0.30,>=0.26->rekall-core)
  Downloading https://files.pythonhosted.org/packages/fc/71/f3fe348cb85678c6cce5b96210efa099c2a1994ddfc3f37db5aedf8426de/expiringdict-1.1.4.tar.gz
Requirement already satisfied: html5lib in /usr/lib/python2.7/dist-packages (from pyaff4<0.30,>=0.26->rekall-core) (0.999999999)
Collecting pyblake2==0.9.3 (from pyaff4<0.30,>=0.26->rekall-core)
  Downloading https://files.pythonhosted.org/packages/05/9f/6cf78d565fcd7a328ce91c4a7844b1b591f32083de7e8eab89d6e5d9e3a0/pyblake2-0.9.3.tar.gz (130kB)
    100% |████████████████████████████████| 133kB 3.0MB/s 
Collecting rdflib[sparql]==4.2.2 (from pyaff4<0.30,>=0.26->rekall-core)
  Downloading https://files.pythonhosted.org/packages/c5/77/1fa0f4cffd5faad496b1344ab665902bb2609f56e0fb19bcf80cff485da0/rdflib-4.2.2.tar.gz (905kB)
    100% |████████████████████████████████| 911kB 2.8MB/s 
Requirement already satisfied: six>=1.4.0 in /usr/lib/python2.7/dist-packages (from rekall-efilter<1.7,>=1.6->rekall-core) (1.11.0)
Requirement already satisfied: sortedcontainers==1.5.7 in /usr/lib/python2.7/dist-packages (from rekall-lib->rekall-core) (1.5.7)
Requirement already satisfied: isodate in /usr/lib/python2.7/dist-packages (from rdflib[sparql]==4.2.2->pyaff4<0.30,>=0.26->rekall-core) (0.6.0)
Requirement already satisfied: SPARQLWrapper in /usr/lib/python2.7/dist-packages (from rdflib[sparql]==4.2.2->pyaff4<0.30,>=0.26->rekall-core) (1.7.6)
Building wheels for collected packages: aff4-snappy, expiringdict, pyblake2, rdflib
  Building wheel for aff4-snappy (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/0d/ae/2b/f537e024b658e6de6a7b5da06d526f1e57941da33737044dfb
  Building wheel for expiringdict (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/25/04/47/be4cff83644357264f826c62cebd038dcc0d04005cabd18300
  Building wheel for pyblake2 (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/3a/4e/8f/e0698d866bec95b1a63678d84333484a7e8b4699f1089f4c29
  Building wheel for rdflib (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/8d/f6/b7/f5e9501d0f006fc9fd497c930206952856b2191ab5c836cb97
Successfully built aff4-snappy expiringdict pyblake2 rdflib
Installing collected packages: aff4-snappy, expiringdict, pyblake2, rdflib
  Found existing installation: rdflib 4.2.1
    Uninstalling rdflib-4.2.1:
      Successfully uninstalled rdflib-4.2.1
Successfully installed aff4-snappy-0.5.1 expiringdict-1.1.4 pyblake2-0.9.3 rdflib-4.2.2
root@xen-srv:/home/xen/drakvuf/libvmi# xl list
Name                                        ID   Mem VCPUs	State	Time(s)
Domain-0                                     0  2047     2     r-----     555.5
QWASZX                                       1  6400     4     -b----      74.0
root@xen-srv:/home/xen/drakvuf/libvmi# vmi-win-guid name QWASZX
Windows Kernel found @ 0x261a000
	Version: 64-bit Windows 7
	PE GUID: 4ce7951a5ea000
	PDB GUID: 3844dbb920174967be7aa4a2c20430fa2
	Kernel filename: ntkrnlmp.pdb
	Multi-processor without PAE
	Signature: 17744.
	Machine: 34404.
	# of sections: 24.
	# of symbols: 0.
	Timestamp: 1290245402.
	Characteristics: 34.
	Optional header size: 240.
	Optional header type: 0x20b
	Section 1: .text
	Section 2: INITKDBG
	Section 3: POOLMI
	Section 4: POOLCODE
	Section 5: RWEXEC
	Section 6: .rdata
	Section 7: .data
	Section 8: .pdata
	Section 9: ALMOSTRO
	Section 10: SPINLOCK
	Section 11: PAGELK
	Section 12: PAGE
	Section 13: PAGEKD
	Section 14: PAGEVRFY
	Section 15: PAGEHDLS
	Section 16: PAGEBGFX
	Section 17: PAGEVRFB
	Section 18: .edata
	Section 19: PAGEDATA
	Section 20: PAGEVRFC
	Section 21: PAGEVRFD
	Section 22: INIT
	Section 23: .rsrc
	Section 24: .reloc
root@xen-srv:/home/xen/drakvuf/libvmi# printf "QWASZX  { \n\ostype = \"Windows\"; \n\rekall_profile = \"/root/QWASZX.rekall.json\"; \n\}" >> /etc/libvmi.conf exit
root@xen-srv:/home/xen/drakvuf/libvmi# vmi-process-list QWASZX
error: syntax error
VMI_ERROR: Failed to read config file.
Failed to init LibVMI library.

**Comment by johnzion** [comment]
for the error in cmake i dont have the updated version."cmakes are missing"
How can i do that?
