### ISSUE TITLE
Submodule Libvmi desynchronized?

### ISSUE THREAD

**Issue by aoshiken** [tklengyel/drakvuf#564]
@tklengyel 

Why the Libvmi submodule points to a commit that doesn't exist in any branch of your libvmi fork?

That's driving me nuts when making a branch from my fork because the submodule doesn't gets correctly updated... xD

**Comment by tklengyel** [comment]
Are you sure about that? Travis builds with that submodule and seems to have no issue.

**Comment by aoshiken** [comment]
I'm by no means a git expert that's why I'm opening this issue :)

Until recently the libvmi submodule pointed to your master branch on your libvmi fork right?

**Comment by tklengyel** [comment]
Sometimes it points to master but not always

**Comment by aoshiken** [comment]
Ok, I don't see clearly what happens now that it didn't happen before but it seems it's on my side.

Thank you anyway
