### ISSUE TITLE
about ret=-3

### ISSUE THREAD

**Issue by vitojj** [tklengyel/drakvuf#577]
One day, when I open it, I will have this problem when I create a virtual machine. I hope you can help me solve this problem. Thank you.
![m_7 vy6r5bd6wztnc r15](https://user-images.githubusercontent.com/27283005/53341247-04a61d00-3946-11e9-98e4-3e12d5d4867c.jpg)

**Comment by aoshiken** [comment]
Did the DomU configuration work previously?

**Comment by vitojj** [comment]
> DomU配置以前是否有效？

yes,It works correctly

**Comment by tklengyel** [comment]
This would be a question for the `xen-users` mailinglist

**Comment by vitojj** [comment]
> This would be a question for the `xen-users` mailinglist

How can I solve this problem?

**Comment by vitojj** [comment]
This problem still exists after I reinstall the system.
