### ISSUE TITLE
VNC Freeze

### ISSUE THREAD

**Issue by ultrapikachu** [tklengyel/drakvuf#588]
I'm using drakvuf with xen 4.11.2
But when i start drakvuf, i cant control vm over vnc.
What will i do?
Is it a xen problem?

**Comment by ultrapikachu** [comment]
I try update xen to 4.12 but i got "xl: error while loading shared libraries: libxlutil.so.4.12: cannot open shared object file: No such file or directory"

**Comment by ultrapikachu** [comment]
I updated xen to 4.12 but when i try create machine i got this

libxl: error: libxl_create.c:1543:domcreate_devmodel_started: Domain 1:device model did not start: -3
libxl: error: libxl_dm.c:2874:kill_device_model: Device Model already exited
libxl: error: libxl_domain.c:1038:libxl__destroy_domid: Domain 1:Non-existant domain
libxl: error: libxl_domain.c:993:domain_destroy_callback: Domain 1:Unable to destroy guest
libxl: error: libxl_domain.c:920:domain_destroy_cb: Domain 1:Destruction of domain failed

**Comment by tklengyel** [comment]
Sounds like to you didn't upgrade properly and now Xen can't even create domains. When you upgrade Xen you have to upgrade all tools with it (libxc/xl/qemu/etc.). So I don't think this is a Xen problem, I think this is a problem with your setup.

**Comment by ultrapikachu** [comment]
I updated xen to 4.12 but i got

1552180935.585817 DRAKVUF v0.6-29f19b3
libxl: error: libxl_domain.c:315:libxl_list_domain: getting domain info list: Permission denied
Domain is not running, failed to get domID from name!
Failed to init LibVMI paging.
Failed to initialize DRAKVUF: drakvuf_init() failed

**Comment by ultrapikachu** [comment]
VM working but drakvuf cant start

**Comment by ultrapikachu** [comment]
@tklengyel i did fresh install and still my vnc gone freeze while drakvuf running
