### ISSUE TITLE
Drakvuf Error Xen 4.12

### ISSUE THREAD

**Issue by ultrapikachu** [tklengyel/drakvuf#589]
I updated xen to drakvuf_412 and i reinstall drakvuf
When i try start drakvuf, i go these error

xc: error: Failed to enable vm_event
 (13 = Permission denied): Internal error
VMI_ERROR: Error enabling vm_event
Failed to init LibVMI library.
Failed to initialize DRAKVUF: drakvuf_init() failed

// libvmi work normal

@tklengyel

**Comment by ultrapikachu** [comment]
Updat
I added this line my vm cfg
seclabel='drakvuf:vm_r:drakvuf_domU_t'
Drakvuf started run but after 3 second system gone to crash(main system)

**Comment by ultrapikachu** [comment]
https://i.imgur.com/adHrp2Z.png

**Comment by tklengyel** [comment]
The xen_412 branch in my repository is not for standard drakvuf setups. You should not be using that unless you need XSM enabled.

**Comment by ultrapikachu** [comment]
@tklengyel in otherwise with 4.11 i cant control vm while drakvuf running.
What will i do and i try install xen 4.12 from xenbits, my system gone crash again
Can you look image

**Comment by tklengyel** [comment]
Looks to me like you might be having hardware issues. I don't know what's wrong with your setup.

**Comment by ultrapikachu** [comment]
Hmm okey.
Can the freezing of VNC have anything to do with the GPU card?
Is there a requirement for gpu in Drakvuf?

**Comment by tklengyel** [comment]
There is no gpu requirement. Try to use another system if you can.

**Comment by ultrapikachu** [comment]
Actually i have same error https://github.com/tklengyel/drakvuf/issues/238 but after update to 4.12 i got again crash

**Comment by ultrapikachu** [comment]
I cant understand why vnc gone freeze and cant refresh screen

**Comment by Dos98** [comment]
@ultrapikachu  Is your problem resolved? coz i am facing the same. If yes, Share what u did.

**Comment by icedevml** [comment]
@tklengyel @Dos98 @ultrapikachu I'm not sure if it's related at all, but from what I tested already:

* [Intel Core i3-6100](https://ark.intel.com/content/www/us/en/ark/products/90729/intel-core-i3-6100-processor-3m-cache-3-70-ghz.html) - Xen 4.12 + DRAKVUF, hangs 1-2 seconds after connecting VNC
* [Intel Xeon E5-2620](https://ark.intel.com/content/www/us/en/ark/products/64594/intel-xeon-processor-e5-2620-15m-cache-2-00-ghz-7-20-gt-s-intel-qpi.html) - the same as above
* [Intel Xeon Processor X3470](https://ark.intel.com/content/www/us/en/ark/products/42932/intel-xeon-processor-x3470-8m-cache-2-93-ghz.html) - both Xen 4.12 and VNC work fine, no problems

I wonder if it's related to the processor itself, the particular hardware setup or some race condition somewhere in the software.

**Comment by tklengyel** [comment]
@icedevml I'll open a separate issue for this as others have reported Xen 4.12 regressions as well
