### ISSUE TITLE
How to communicate and send data between Xen patch and Dom0 program

### ISSUE THREAD

**Issue by Preetixen** [tklengyel/drakvuf#61]
Hi, this may not be a right place for asking this question. However, I would like to take some suggestion on following issue.

I have a patch in Xen which stores some information of VM process. I have another program running in Dom0 which intercept this information.

i) I want to configure my patch running in Xen to send the alert notification to program running in Dom0 to read data, probably using event channels.  How to configure event channel?
ii) Which API or command will be used to read the data from patch buffer.

Thanks in anticipation,

**Comment by tklengyel** [comment]
You should be asking Xen related questions on the xen-devel mailinglist.
