### ISSUE TITLE
Xen 4.12 regressions

### ISSUE THREAD

**Issue by tklengyel** [tklengyel/drakvuf#610]
Xen 4.12 seems to involve regressions that need further investigations. At this time if the regressions apply to your system, the recommended workaround is to continue using Xen 4.11.x 

Reported by @icedevml:

I'm not sure if it's related at all, but from what I tested already:

    Intel Core i3-6100 - Xen 4.12 + DRAKVUF, hangs 1-2 seconds after connecting VNC (watchdog detects CPU being stuck)
    Intel Xeon E5-2620 - the same as above
    Intel Xeon Processor X3470 - Xen 4.12, DRAKVUF and VNC work fine, no problems

I wonder if it's related to the processor itself, the particular hardware setup or some race condition somewhere in the software.

**Comment by tklengyel** [comment]
Additional tests

```
Intel Xeon E5-2430 works fine, no problems
Intel Core i7-2600 works fine, no problems
Intel Core i3-7100 regression observed

**Comment by rzvncj** [comment]
Quite possibly the problem is with altp2m emulation (previously available even with no hardware support, to some degree).
Look out for patches like this: https://xenbits.xen.org/gitweb/?p=xen.git;a=commitdiff;h=a2eb46491e28079debc39488a7e23ed76cb5b003
Maybe we went too far with one of them.
I don't, unfortunately, have an old-enough system to debug on.

**Comment by tklengyel** [comment]
@rzvncj Thanks for the suggestion, but we have systems that don't have virtualization exceptions that seem to work just fine (like the E5-2430 and the i7-2600). The problem seem to only appear on old (~2011) and low-end CPUs (i3).

**Comment by rzvncj** [comment]
I don't know what to suggest, other than trying to do a bisection: gradually eliminate altp2m-related patches from a custom Xen 4.12 build until it works, and then we've found our culprit.

**Comment by tklengyel** [comment]
@rzvncj I believe this may be related to your vga logdirty rework (at least the issue occurring only when the VNC is active is one indication of this). I'll try to compile Xen 4.12 without those patches and see if I get the same regression.

**Comment by rzvncj** [comment]
True, if it always involve VNC it does sound like it could be related to the logdirty VGA work - however I can't tell what in that series might make a difference for the worse for older processors.

**Comment by rzvncj** [comment]
FWIW, these are the commits to look out for (for the VGA fix):

https://xenbits.xen.org/gitweb/?p=xen.git;a=commitdiff;h=303cee10a677dd8c5c130e50ddad6517c12e0276
https://xenbits.xen.org/gitweb/?p=xen.git;a=commitdiff;h=1698309f3e5eafedff66b88857c6dc9ad2c9f61b
https://xenbits.xen.org/gitweb/?p=xen.git;a=commitdiff;h=95ba8404d45df56b3c8db88ea0bd414ad6638962
https://xenbits.xen.org/gitweb/?p=xen.git;a=commitdiff;h=6e23f46ea9bb7403c9b6d29449a35d1381f1c56e
https://xenbits.xen.org/gitweb/?p=xen.git;a=commitdiff;h=0fb4b58c8b9cc4036907d595a124b31aa1153f33
https://xenbits.xen.org/gitweb/?p=xen.git;a=commitdiff;h=b5acd075aabc043cc7e9aa533ec697dd68a1d137
https://xenbits.xen.org/gitweb/?p=xen.git;a=commitdiff;h=2bad3829a59a9b227ab652d9e152cfb361b5f62c

Hope I didn't miss one.

**Comment by tklengyel** [comment]
@rzvncj As suspected, after reverting the vga logdirty changes the system doesn't hang. Of course, the VNC session appears to be frozen when DRAKVUF is running. Now here is the interesting bit, I first reverted most of the patches you listed as well, except `303cee10a677dd8c5c130e50ddad6517c12e0276` and the system still hung. With `303cee10a677dd8c5c130e50ddad6517c12e0276` reverted it no longer hangs.

**Comment by rzvncj** [comment]
Huh, I would not really have suspected that patch. You could sprinkle a few `printk()`s to see if it hangs in a `p2m_lock()` somewhere.

**Comment by tklengyel** [comment]
Unfortunately it doesn't seem to be that patch alone - if I keep all the other patches and only revert that it still hangs.

**Comment by tklengyel** [comment]
@rzvncj Actually, I think I found the root cause of the bug. When I reverted just that patch I left one line in as it seems innocuous in the altp2m_init function: `+    p2m->ept.ad = hostp2m->ept.ad;`. With this line in, the system hangs. Without it, it's all good. This lead me to investigate `ept.ad` and boot plain Xen 4.12 with `ept=ad=0` command line option.

And it works. The system no longer hangs and the VNC screen works as expected. So this seems to be related to EPT A/D tracking by the processor not playing nice with altp2ms. And it only seems to be on low-end CPUs, so I would have to speculate it's a microcode issue.

**Comment by rzvncj** [comment]
Nice work! We should probably bring this up on xen-devel, somebody there might know more about the specifics of what's causing this. It did indeed seem that it's either some path that deadlocks some spinlock (that's taken on that class of CPUs) or the `ad` thing.

**Comment by tklengyel** [comment]
Adding `ept=ad=0` to the Xen boot command options resolves the issue.

**Comment by icedevml** [comment]
Awesome, now it works well with VNC. Thanks.
