### ISSUE TITLE
poolmon missed some memory allocation

### ISSUE THREAD

**Issue by wmliang** [tklengyel/drakvuf#611]
i use poolmon on my small demo program&driver

my_demo.exe use DeviceIoControl to call my driver and do nothing
my_driver.sys call ExAllocatePoolWithTag(0, 0x10, (ULONG)"OOXX");

and here is parts of log, which shows that the monitoring is working
```
[POOLMON] TIME:1555494742.209159 VCPU:3 CR3:0x6a500000,"\Device\HarddiskVolume2\Users\wmliang3\my_demo.exe" SessionID:1 SeSd (type: PagedPool, size: 216): nt!se,Security Descriptor
[POOLMON] TIME:1555494742.209630 VCPU:0 CR3:0x6a500000,"\Device\HarddiskVolume2\Users\wmliang3\my_demo.exe" SessionID:1 ObNm (type: PagedPool, size: 248): nt!ob,object names
[POOLMON] TIME:1555494742.209640 VCPU:3 CR3:0x6a500000,"\Device\HarddiskVolume2\Users\wmliang3\my_demo.exe" SessionID:1 SeAc (type: PagedPool, size: 200): nt!se,Security ACL
```
there is around 450 log for my_demo.exe, but none of them contains the tag "OOXX"
ExAllocatePoolWithTag returns a kernel pointer without any problem in my_driver.sys

my question is , is there any limitation about the monitoring or any reason to explain it ?

**Comment by tklengyel** [comment]
That's an interesting case. No, from the looks of it this should not happen. But evidently the function your driver calls is not the same function DRAKVUF is monitoring. You should verify that the address in your driver matches what DRAKVUF computes for `ExAllocatePoolWithTag`. I wouldn't be surprised to find that Windows doesn't give you the real address to the function in the driver and instead routes it through some other path.

**Comment by wmliang** [comment]
oh no
that is a bug in my_demo.exe, it makes the "OOXX" becomes non-ascii character
sorry for bothering you :)

**Comment by tklengyel** [comment]
Happy to hear that the explanation was something simple :)
