### ISSUE TITLE
Outdated rekall command on website

### ISSUE THREAD

**Issue by TimHi** [tklengyel/drakvuf#615]
Hello, 
i went throught the progress of getting drakvuf running today and stumbled upon these commands:  

> python3 rekall fetch_pdb ntkrpamp 684da42a30cc450f81c535b4d18944b12
> python3 rekall parse_pdb ntkrpamp > windows7-sp1.rekall.json

Which resulted in an error, thankfully another GitHub user who had a similar problem in february told me ntkrpamp is outdated. [see rekall issue](https://github.com/google/rekall/issues/298#issuecomment-484439820).

The correct commands would be:  
>python3 rekall fetch_pdb ntkrnlmp 3844dbb920174967be7aa4a2c20430fa2
>python3 rekall parse_pdb ntkrnlmp > windows7-sp1.rekall.json

**Comment by tklengyel** [comment]
Was your kernel debug filename `ntkrpamp` as shown by `vmi-win-guid`?

**Comment by TimHi** [comment]
You are correct, the kernel name was not ntkrpamp it was in fact ntkrnlmp. Should have paid more attention to the output.
