### ISSUE TITLE
Poor performance with latest Windows 10 1809

### ISSUE THREAD

**Issue by trapframe** [tklengyel/drakvuf#621]
Running latest Drakvuf with Xen 4.12 i am experiencing very bad VM performance while Drakvuf is running.

On the same host a Windows 7 SP1 VM run perfectly fine even while Drakvuf is running.

for example:

- starting Word 2010 on win7 takes less than about 3 secondes 
- starting Word 2010 on windows 10 1809  takes about 25 secondes

This is not related to a specific plugin as even if i disable all plugins i have about the same performance issue.

When Drakvuf is not running performance are back to normal even if the VM is not as responsive as the Win7 one (that normal, win10 takes more resources)

Except for the OS , the VMs configurations are strictly equal 

Have you experienced the same issue ?

**Comment by tklengyel** [comment]
Do you know if your Windows 7 instance implements any type of KPTI mitigation to Meltdown? The only thing I can think of is that the performance hit is due to increased cache misses since the only event that is enabled when no plugins are active is trapping on `MOV-TO-CR` which normally involves a TLB flush. It might be that Win10 now relies very heavily on PCID to mask the overhead of KPTI and the constant `MOV-TO-CR3` it comes with but due to us trapping out to the hypervisor the caches are getting hammered (even with VPID).

In any case, it may be wise to start exploring not trapping on `MOV-TO-CR3` unconditionally. It has been more of a convenience then a requirement that thus far added little overhead.

**Comment by tklengyel** [comment]
@trapframe You could also perhaps test my theory if you try https://www.grc.com/inspectre.htm to disable the Win10 meltdown mitigation and see if that improves performance.

**Comment by trapframe** [comment]
Ran Inspectre , disabled both Meltdown & Spectre and then rebooted the VM.

Ran Inspectre again and both are indeed disabled.

but when running Drakvuf i am getting : 

1556201899.424949 DRAKVUF v0.6-2cd9a92
1556201899.425067 Starting DRAKVUF initialization
1556201899.575717 drakvuf_event_fd_add fd=14
1556201899.575756 size of list=1
1556201899.575763 regenerating event_fds and fd_info_lookup...
1556201899.575769 new event_fd i=0 for fd=14
1556201899.575800 new fd_info_lookup i=0 for fd=14
1556201899.575817 drakvuf_init: adding event_fd done
1556201899.576891 init_vmi on domID 67 -> qspy1809
1556201899.577985 init_vmi: initializing vmi done
1556201899.578047 init_vmi: initializing vmi paging done
VMI_ERROR: Error calculating NT base address
VMI_ERROR: Error calculating NT base address
VMI_ERROR: Error calculating NT base address

**Comment by tklengyel** [comment]
That's unfortunate. There is a workaround where you can manually define where the kernel's base address is in the libvmi.conf file and start drakvuf with the `-l` flag to make use of it. That would perhaps get passed that error, but even then I wouldn't be surprised if other things would get broken down the line. So perhaps instead checking the Win7 you are running and is fine if that has meltdown mitigation or not would get us closer to determine if that's the culprit.

**Comment by trapframe** [comment]
Putting kernel base PA & VA in libvmi.conf along with the " -l " command line switch lead to this error while initializing the filetracer plugin (it occurs while registering the Trap) 

`VMI_ERROR: Could not find EPROCESS struct for pid = 4.
`


the error lies in the **windows_pid_to_pgd()** function as the call to **windows_find_eprocess_list_pid()** fails.

While debugging i noticed that both **tasks_offset** and **pid_offset** were set to 0 :

```
	Locals		
		dtb	0	addr_t
		eprocess	0	addr_t
		pdbase_offset	40	int
		pid	4	vmi_pid_t
		ret	VMI_FAILURE (1)	status_t
		tasks_offset	0	int
		vmi	@0x55a2787e8d20	vmi_instance_t
		windows	@0x55a2787ef8b0	windows_instance_t
			kdbg_offset	0	uint64_t
			kdbg_va	0	addr_t
			kpcr_offset	0	uint64_t
			ntoskrnl	32342016	addr_t
			ntoskrnl_va	18446735283959062528	addr_t
			pdbase_offset	40	uint64_t
			pid_offset	0	uint64_t
			pname_offset	0	uint64_t
			rekall_profile	"/kernels/win10_1809/nt.json"	char*
			rekall_profile_json	@0x55a2787efd80	json_object
			sysproc	18446690787892133952	addr_t
			tasks_offset	0	uint64_t
			version	VMI_OS_WINDOWS_10 (9)	win_ver_t
```

So i put them in the libvmi.conf as this :

```
    ostype = "Windows";
    rekall_profile = "/kernels/win10_1809/nt.json";
    win_ntoskrnl = 0x1ed8000;
    win_ntoskrnl_va = 0xFFFFF8017A0B6000;
    win_tasks = 0x2E8;
    win_pid = 0x2E0;
```

With this Drakvuf runs fine and the performance of the VM are much better.

So this is a valid workaround although not very handy since it forces us to put details about the VM kernel in the libvmi configuration file.

Any idea why libvmi cannot retrieve  **tasks_offset** and **pid_offset**  value from the rekall profile ? (values are there and valid)

**Comment by tklengyel** [comment]
Perhaps try enabling the debug output of LibVMI to see why it wasn't able to read those offsets. They should be read in https://github.com/libvmi/libvmi/blob/master/libvmi/os/windows/core.c#L916

**Comment by tklengyel** [comment]
Oh, I see why those offsets weren't read. If you manually define the kernel base address in the config you are effectively skipping the rest of `init_from_rekall_profile` in LibVMI: https://github.com/libvmi/libvmi/blob/master/libvmi/os/windows/core.c#L946

**Comment by tklengyel** [comment]
Also, happy to hear the performance is much better. I assume this is still with the Meltdown mitigation disabled in WIn10, correct?

**Comment by trapframe** [comment]
Yes,  performance are back to normal, for win10, with meltdown and spectre
disabled.

And this is a good news  :)

However the underlying problem remains and it would be better if we can
find a fix for it,  if possible...

But let's see the bright side,  workaround is working!  ;)

Le ven. 26 avr. 2019 à 17:22, Tamas K Lengyel <notifications@github.com> a
écrit :

**Comment by tklengyel** [comment]
Right, at least that tells us its the CR3 trapping hammering the cache-lines being the problem. Perhaps try this branch a try: https://github.com/tklengyel/drakvuf/tree/no_cr3. I haven't really tested it much yet.
