### ISSUE TITLE
How to get sample programs into the xen vm?

### ISSUE THREAD

**Issue by Maikulole** [tklengyel/drakvuf#631]
Whats the best way to get my samples/programs into the VM?

**Comment by tklengyel** [comment]
Depends on what your goals are. The easiest is to connect via VNC to the guest and download the sample the same way you would otherwise. If you need to do it in an automated setup then take a look at https://github.com/tklengyel/drakvuf/wiki/Automated-malware-analysis-setup

**Comment by Maikulole** [comment]
Ok, so it boils down to the usual ways of getting software into the VM

**Comment by tklengyel** [comment]
For the most part, yes. There is doppelganging injection that works for recent Windows 10 versions that you could try as well which injects the target binary into the VM's memory directly, but it has some limitations and it's fairly experimental (see #444).
