### ISSUE TITLE
error installing rekall

### ISSUE THREAD

**Issue by Alibm73** [tklengyel/drakvuf#632]
HI @tklengyel 
I used
```python
cd rekall/rekall-core
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
./setup.py build
sudo ./setup.py install
```
but it doesn't get installed because it requires future==0.16.0:
```python
Installed /usr/local/lib/python3.6/dist-packages/rekall_core-1.7.2rc1-py3.6.egg
Processing dependencies for rekall-core==1.7.2rc1
error: future 0.17.1 is installed but future==0.16.0 is required by {'rekall-efilter'}
```
i used the `pip3 install future==0.16.0` command but i get the same error

**Comment by tklengyel** [comment]
Please report Rekall bugs to the Rekall project. You can also try to just run Rekall without actually installing it.

**Comment by tklengyel** [comment]
I've updated the instructions on the DRAKVUF website. Just run

```
sudo apt-get install python3-dev python3-pip
sudo pip3 install fastchunking future==0.16.0
```

Afterwards you should be able to continue building and installing Rekall.
