### ISSUE TITLE
max_gpfn keeps increasing between Drakvuf runs

### ISSUE THREAD

**Issue by mtarral** [tklengyel/drakvuf#636]
Hi,

today i noticed an issue in either Drakvuf teardown code or Xen's implementation.
Basically, between 2 Drakvuf sequential runs, there is a persistent state in Xen that is not restored to the original values.

The `max gpfn` is increased via `xc_domain_populate_physmap_exact`, and despite the call to `xc_domain_decrease_reservation`, it remains at the modified value.

First run
~~~
$ sudo ./src/drakvuf -r /etc/libvmi/win7.json -d win7 -a bsodmon -v
1558525606.139594 DRAKVUF v0.6-5e1a449
1558525606.139626 Starting DRAKVUF initialization
...
1558525606.176594 init_vmi on domID 51 -> win7
1558525606.177354 init_vmi: initializing vmi done
1558525606.177430 init_vmi: initializing vmi paging done
1558525606.214740 init_vmi: initializing vmi OS done
1558525606.214785 Max GPFN: 0xff000
1558525606.214802 Max mem set? 0
1558525606.214830 Physmap populated? 0
1558525606.214836 write fmask at 0xff001000
...
1558525606.215590 Starting plugin bsodmon finished
1558525606.215597 Beginning DRAKVUF loop
1558525606.215604 Started DRAKVUF loop
^C1558525608.165337 DRAKVUF loop broke unexpectedly: [Errno: 4] Interrupted system call
1558525608.165662 DRAKVUF loop finished
1558525608.165705 Finished DRAKVUF loop
1558525608.165733 close_vmi starting
1558525608.165892 Removed memtrap for GFN 0xff001 in altp2m view 1
1558525608.824247 close_vmi finished
~~~

2nd run
~~~
$ sudo ./src/drakvuf -r /etc/libvmi/win7.json -d win7 -a bsodmon -v
1558525694.772774 Max GPFN: 0xff002
~~~

nth run
~~~
1558525772.857073 Max GPFN: 0xff01a
~~~

Now, This could be one of the sources of my bugs, thinking that i'm testing dravuf sequentially with my test suite.

We should check with the Xen community if that behavior is harmless or could lead to potential issues like an ever increasing memory consumption for example

On my side, i will modify the test suite so that the VM is created and destroyed between each test.
If the bug triggers again, it will not be related to this issue.

Thanks.

**Comment by tklengyel** [comment]
That's normal and it's because of how DRAKVUF's shadow page implementation works. Xen just keeps track of what was the largest gpfn ever mapped into the domain. Since DRAKVUF always adds the shadow pages beyond the current max gpfn, it will always increase that number.
