### ISSUE TITLE
Generating Rekall profiles with python 3.7 broken

### ISSUE THREAD

**Issue by tklengyel** [tklengyel/drakvuf#637]
Workaround is to stick to python 3.5 and use only the Rekall submodule tagged in the DRAKVUF repository.

Rekall issue tracker is https://github.com/google/rekall/issues/474

**Comment by icedevml** [comment]
An attempt to create standalone PDB -> JSON converter:

https://github.com/CERT-Polska/drakpdb

PRs welcome, if some free time would appear then also I'll try to do something around Linux profiles.
