### ISSUE TITLE
How track remote threads

### ISSUE THREAD

**Issue by Necroxys77** [tklengyel/drakvuf#647]
Hi,

I implemented a plugin that is able to track the behavior of a `target process` (first by name then by PID/TID). 
Now, I would like to track any thread created by a call to `CreateRemoteThread` from `target process`. Since at the time of the callback I've no information about the infected process (only the `HANDLE` value and - sometimes - the infected TID), is there any built-in functionality in DRAKVUF to find the name of the infected process and/or PID?

If nothing appropriate is present, I thought that I can follow two strategies:

1. track _any_ call to `OpenProcess` done by `target process`, get (i) `HANDLE` and (ii) associated PID and store them in some place. Anytime that `target process` calls `CreateRemoteThread` I check the `HANDLE` value of the call for a match among the stored ones. In this way, I'm able to correlate the infected TID with the infected PID.
The bad thing of this approach is that for each call to `OpenProcess` I've to store `HANDLE`/PID even if that couple might not be associated to a `CreateRemoteThread` call.
2. for any TID created by `CreateRemoteThread`, I search that TID in the system - but I don't know how to do that through DRAKVUF facilities. The bad thing of this approach is that if `lpThreadId = NULL`, then the TID is not returned.

If someone has a better solution, please propose it! :-)

Thank you.

**Comment by tklengyel** [comment]
I'm not sure I completely follow your process but if you have a handle to the process you can use `drakvuf_get_obj_by_handle` to get the _EPROCESS structure and from there you can get the pid and process' name. That might be what you are looking for.

**Comment by Necroxys77** [comment]
Thanks, that was definitely faster than previous two methods! :+1:
