### ISSUE TITLE
Failed to initialize DRAKVUF: drakvuf_init() failed

### ISSUE THREAD

**Issue by tushariitr1** [tklengyel/drakvuf#648]
Hey Guys,
I am working on Xen 4.9, latest versions of libvmi and Drakvuf with Windows 10 VM. The process list scan is working fine but getting the following error when starting drakvuf. Just FYI, the grub file has altp2m=1. 

DRAKVUF v0.6-48b3678
Starting DRAKVUF initialization
 drakvuf_init: Rekall WoW64 profile not used
drakvuf_event_fd_add fd=14
size of list=1
regenerating event_fds and fd_info_lookup...
new event_fd i=0 for fd=14
new fd_info_lookup i=0 for fd=14
drakvuf_init: adding event_fd done
init_vmi on domID 1 -> win10
init_vmi: initializing vmi done
init_vmi: initializing vmi paging done
init_vmi: initializing vmi OS done
Max GPFN: 0x110093
Max mem set? 0
Physmap populated? 0
Altp2m enabled? -1
close_vmi starting
close_vmi finished
libdrakvuf initialization failed
Failed to initialize DRAKVUF: drakvuf_init() failed

Thanks for help in advance.

**Comment by tklengyel** [comment]
1. Update to Xen 4.12
2. Add altp2m=2 to your domain config

**Comment by tushariitr1** [comment]
thanks for the reply. 
I am working on updating to Xen 4.12.
I think the domain config is xl.config? which is at /etc/xen/xl.conf

**Comment by tklengyel** [comment]
The domain config is the file you use when you run `xl create <domain config>`.
