### ISSUE TITLE
memsharing not enabled

### ISSUE THREAD

**Issue by rstocktox** [tklengyel/drakvuf#66]
Hi @tklengyel,
it's me again, :)

I wonder why the Xen memory sharing between the origin and the clone domains is not used...  
Is there any kind of issues arising with HVM domains?

Cheers,

Robert

**Comment by tklengyel** [comment]
Starting in DRAKVUF 0.2 I've opted to use the Xen altp2m system to allow the analysis VMs to have multiple vCPUs. However, altp2m is currently not compatible with memory sharing so at this time. If you want to experiment with the memory sharing side, you need to use DRAKVUF 0.1.

**Comment by rstocktox** [comment]
@tklengyel thanks for your answer
