### ISSUE TITLE
error: failed to connect to the hypervisor

### ISSUE THREAD

**Issue by tushariitr1** [tklengyel/drakvuf#672]
Drakvuf SCANs are working fine, but I am unable to connect to the hypervisor and view the VMs. 

I am getting the following error for this command "sudo virsh -c xen+ssh://USERNAME@IPADDRESS"    
error: failed to connect to the hypervisor
error: End of file while reading data: nc: unix connect failed: Permission denied: Input/output error

The system configuration is as follows : 
Xen : 4.11, LibVMI : Latest, Libvirt : 5.4.0. 

thanks in advance.

**Comment by tklengyel** [comment]
This seems to be a libvirt issue. You may have better luck finding an answer/help with this on the libvirt and/or xen-users mailinglist.
