### ISSUE TITLE
Scan stops and System Call Names during the scan.

### ISSUE THREAD

**Issue by tushariitr1** [tklengyel/drakvuf#673]
I ran DRAKVUF SCAN on Xen 4.11 without viewing the VM (using any VNC).
I have observed that the scan stopped after a certain time and the system call names are not coming as desired.
Kindly, find the attached file (output) for your reference.

![Output](https://user-images.githubusercontent.com/52755944/61999320-60f3a100-b08c-11e9-9195-89c6d3c03536.png)

**Comment by tklengyel** [comment]
Did you check if the VM is still active or did it crash?

**Comment by tushariitr1** [comment]
The VM was active when I started the scan. 
But when the scan waits (as per the output screen's last line) I have to cancel it (Ctrl +C) and then there was no VM after it (It crashes).

**Comment by tklengyel** [comment]
Well, that's the reason why the scans stopped. You will have to figure out what crashes your VM. Try to disable plugins and enable them one-by-one and see if you can narrow down the issue.

**Comment by tushariitr1** [comment]
I tried to do scans in debug mode by first disabling all the plugins and then enabling one-by-one with system call plugin, but in most of the cases the VM breaks and in few cases the VM pauses. In addition, in the case where VM breaks, the scan starts by generating the System call names.  Below are the debug output for one of the scan

1. Results when the VM breaks:
sudo ./src/drakvuf -r /data/ctam/rekall/win10_new.json -d 49 -v
1564514847.050312 DRAKVUF v0.6-6ef602c
1564514847.050371 Starting DRAKVUF initialization
1564514847.165919 drakvuf_init: Rekall WoW64 profile not used
1564514847.166412 drakvuf_event_fd_add fd=14
1564514847.166431 size of list=1
1564514847.166438 regenerating event_fds and fd_info_lookup...
1564514847.166445 new event_fd i=0 for fd=14
1564514847.166452 new fd_info_lookup i=0 for fd=14
1564514847.166458 drakvuf_init: adding event_fd done
1564514847.166712 init_vmi on domID 49 -> windows10-1
1564514847.167831 init_vmi: initializing vmi done
1564514847.167960 init_vmi: initializing vmi paging done
1564514847.277250 init_vmi: initializing vmi OS done
1564514847.277349 Max GPFN: 0x11004f
1564514847.277378 Max mem set? 0
1564514847.277431 Physmap populated? 0
1564514847.277495 Altp2m enabled? 0
1564514847.277544 Altp2m view X created? 0 with ID 1
1564514847.277565 Altp2m view R created? 0 with ID 2
1564514847.277587 Switched Altp2m view to X? 0
1564514847.277662 init_vmi finished
1564514847.277684 Windows kernel base address is 0xfffff80108e81000
1564514847.277751 Rekall profile: '_EPROCESS' has no 'Wow64Process' member
1564514847.277764 Failed to find offset for _EPROCESS:Wow64Process
1564514847.277788 Rekall profile: '_KPCR' has no 'PrcbData' member
1564514847.277798 Failed to find offset for _KPCR:PrcbData
1564514847.277856 Failed to find offsets for array of structure names and subsymbols.
1564514847.277869 libdrakvuf initialized
1564514847.277878 DRAKVUF initializated
1564514847.277895 Starting plugins
1564514847.277905 Starting plugin syscalls
1564514847.278001 Rekall profile defines 18434 symbols
1564514847.281035 Received 18434 symbols
1564514847.281127 [SYSCALLS] Adding trap to NtAcceptConnectPort
1564514847.281141 [SYSCALLS] Adding trap to NtAccessCheck
1564514847.281153 [SYSCALLS] Adding trap to NtAccessCheckAndAuditAlarm
1564514847.281162 [SYSCALLS] Adding trap to NtAccessCheckByType
1564514847.281173 [SYSCALLS] Adding trap to NtAccessCheckByTypeAndAuditAlarm
1564514847.281182 [SYSCALLS] Adding trap to NtAccessCheckByTypeResultList
1564514847.281210 [SYSCALLS] Adding trap to NtAccessCheckByTypeResultListAndAuditAlarm
1564514847.281221 [SYSCALLS] Adding trap to NtAccessCheckByTypeResultListAndAuditAlarmByHandle
1564514847.281230 [SYSCALLS] Adding trap to NtAddAtom
1564514847.281238 [SYSCALLS] Adding trap to NtAddAtomEx
1564514847.281258 [SYSCALLS]: NtAddAtomEx not found in argument list
1564514847.281268 [SYSCALLS] Adding trap to NtAddBootEntry
1564514847.281278 [SYSCALLS] Adding trap to NtAddDriverEntry
1564514847.281287 [SYSCALLS] Adding trap to NtAdjustGroupsToken
1564514847.281295 [SYSCALLS] Adding trap to NtAdjustPrivilegesToken
1564514847.281304 [SYSCALLS] Adding trap to NtAdjustTokenClaimsAndDeviceGroups
1564514847.281325 [SYSCALLS]: NtAdjustTokenClaimsAndDeviceGroups not found in argument list
1564514847.281335 [SYSCALLS] Adding trap to NtAlertResumeThread
1564514847.281345 [SYSCALLS] Adding trap to NtAlertThread
1564514847.281354 [SYSCALLS] Adding trap to NtAlertThreadByThreadId
1564514847.281367 [SYSCALLS]: NtAlertThreadByThreadId not found in argument list
.
.
.
.
1564514118.874449 Beginning DRAKVUF loop
1564514118.874457 Started DRAKVUF loop
1564514118.879488 Pre mem cb with vCPU 0 @ 0x109cbbfde in view 1: r--
1564514118.879688 Switching to altp2m view 0 on vCPU 0
1564514118.879846 Post mem cb @ 0x109cbbfde vCPU 0 altp2m 0
1564514118.879924 Pre mem cb with vCPU 0 @ 0x109cbbfdf in view 1: r--
1564514118.879947 Switching to altp2m view 0 on vCPU 0
1564514118.880014 Post mem cb @ 0x109cbbfdf vCPU 0 altp2m 0
^C1564514125.046127 DRAKVUF loop broke unexpectedly: [Errno: 4] Interrupted system call
1564514125.046181 DRAKVUF loop finished
1564514125.046193 Finished DRAKVUF loop
1564514125.046206 close_vmi starting
1564514125.050463 Removed memtrap for GFN 0x110050 in altp2m view 1
1564514125.076459 close_vmi finished

Below are my xen and virtual machine configuration details for your reference:

Xen Configuration:
dom0_mem=16384M,max:16384M dom0_max_vcpus=8 dom0_vcpus_pin=true force-ept=1 ept=ad=0 hap_1gb=false hap_2mb=false altp2m=1


VM configuration :
arch = 'x86_64'
name = "windows10-1"
maxmem = 4096
#memory = 4096
vcpus = 1
maxcpus = 1
builder = "hvm"
boot = "d"
hap = 1
acpi = 1
on_poweroff = "destroy"
on_reboot = "destroy"
on_crash = "destroy"
vnc=1
vnclisten="0.0.0.0"
usb = 1
usbdevice = "tablet"
altp2m = 2
#memory = 2048
audio=1
soundhw='hda'
vif = [ 'type=ioemu,model=e1000,bridge=xenbr0,mac=00:06:5B:BA:7C:01' ]
disk = [ 'phy:/dev/ramgroup/windows10,hda,w', 'file:/data/ctam/Windows10.iso,hdc:cdrom,r' ]

**Comment by tklengyel** [comment]
Try upgrading to Xen 4.12

**Comment by tushariitr1** [comment]
I will try to upgrade to Xen 4.12, but is there any tried and tested combination of plugins to get the system call traces ?

**Comment by tklengyel** [comment]
You only need the `syscalls` plugin for the system call traces and that is tested and known to work across Win7-Win10. So what you are seeing is an issue with your particular setup.

**Comment by tushariitr1** [comment]
I will upgrade to the stable version of Xen 4.12. Is VM configuration as per the requirements of drakvuf ?

**Comment by tklengyel** [comment]
You should also define `shadow_memory = 16` or an even larger value if you assign 4gb of memory to the VM, like 32.

**Comment by tushariitr1** [comment]
I have upgraded to Xen 4.12. Here, I am using virsh to create a VM using the XML file. The VM is working fine but I am unable to add ALTP2M and SHADOW_MEMORY features in the XML file. As, these features are not present in the VM, just unable to initiate DRAKVUF SCANs. Could you please help me out in this. I have attached the XML file for your reference.  

<domain type='xen'>
  <name>win10</name>
  <uuid>b91362d6-880f-4fe8-90df-d3da367a9834</uuid>
  <metadata>
    <ctam xmlns="http://app.ctam.org/">
      <os>Windows</os>
      <rekall>win10_new.json</rekall>
    </ctam>
  </metadata>
  <memory unit='KiB'>2000000</memory>
  <currentMemory unit='KiB'>2000000</currentMemory>
  <vcpu placement='static' altp2m='external'>1</vcpu>
  <os>
    <type arch='x86_64' machine='xenfv'>hvm</type>
    <loader type='rom'>/usr/local/lib/xen/boot/hvmloader</loader>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <pae/>
  </features>
  <clock offset='utc'/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <pm>
    <suspend-to-mem enabled='no'/>
    <suspend-to-disk enabled='no'/>
  </pm>
  <devices>
    <emulator>/usr/bin/qemu-system-i386</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='raw'/>
      <source file='/data/ctam/deployment/virtual_machines/Windows_10_Win_10#MasterTushar.img'/>
      <backingStore/>
      <target dev='hda' bus='ide'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
    <controller type='ide' index='0'/>
    <interface type='bridge'>
      <mac address='00:16:3e:6b:38:52'/>
      <source bridge='xenbr0'/>
    </interface>
    <input type='tablet' bus='usb'/>
    <input type='mouse' bus='ps2'/>
    <input type='keyboard' bus='ps2'/>
    <graphics type='vnc' port='5900' autoport='yes' listen='127.0.0.1' keymap='en-us'>
      <listen type='address' address='127.0.0.1'/>
    </graphics>
  <video>
      <model type='cirrus' vram='8192' heads='1'/>
    </video>
  </devices>
  <shadow_memory>16</shadow_memory>
  <altp2m>2</altp2m>
</domain>

**Comment by tklengyel** [comment]
Don't use libvirt. If you must, you will likely have to patch it to accept the altp2m VM option.

**Comment by tushariitr1** [comment]
I am trying to perform system call scan using DRAKVUF (all other plugins disabled) with Xen 4.12 (stable) on a windows 10 VM. But, having the following issues 
Case 1 The scans stops and the VM breaks
Case 2 The scan pause and get this error message "Plugin syscalls startup failed!". The VM does not breaks. 
I have also attached a file that contains the debug message at the time of scan starts for both cases.
Please help and look into it.

![scan starts](https://user-images.githubusercontent.com/52755944/62560745-b594da00-b84b-11e9-9b16-f673b379b280.png)

![case 2](https://user-images.githubusercontent.com/52755944/62560628-78304c80-b84b-11e9-9a6b-49fe1623d343.png)
![case 1](https://user-images.githubusercontent.com/52755944/62560629-78304c80-b84b-11e9-9100-6823f3c71eaa.png)



I have attached the debug reports for both the cases.

**Comment by tushariitr1** [comment]
It worked !!!
I was scanning in debug mode and the VM was breaking for System Call scans. 
Then I scanned without debug mode and pushed the contents to a text file. Everything worked perfectly fine.
