### ISSUE TITLE
Calculate DLL base address from plugin registration phase

### ISSUE THREAD

**Issue by Necroxys77** [tklengyel/drakvuf#678]
Hi again,

is there any built-in way to find the base address of some DLL (given its name) in plugin registration phase? I noticed that DLL base addresses are found as a side effect by an inner procedure when inserting a breakpoint inside some DLL (i.e. one of this is `drakvuf_enumerate_processes_with_module` inside `operator()` of `breakpoint_in_dll_module_searcher`).
I tried to call some of the internal functions from my plugin but I find this method too cumbersome.

Thanks as always :-)

**Comment by tklengyel** [comment]
Here is an example how to use the API:

```
        addr_t eprocess_base;
        if ( !drakvuf_find_process(drakvuf, target_pid, NULL, &eprocess_base) )
            return false;

        addr_t module_list_head;
        if ( !drakvuf_get_module_list(drakvuf, eprocess_base, &module_list_head) )
             return false;

        access_context_t ctx = {
             .translate_mechanism = VMI_TM_PROCESS_PID,
             .pid = target_pid
        };

        addr_t base_addr;
        if ( !drakvuf_get_module_base_addr_ctx(drakvuf, module_list_head, &ctx, target_dll, &base_addr))
              return false;

       /* do what you have to with base_addr */

       return true;
```

Just have to specify the `target_pid` and the `target_dll`.
