### ISSUE TITLE
Adding "altp2m" in XML file for libvirt to create Virtual Machine

### ISSUE THREAD

**Issue by tushariitr1** [tklengyel/drakvuf#680]
Objective : Performing Drakvuf scans on a virtual machine created by Virsh (Libvirt)

I want to create a virtual machine using virsh with a XML file and add "altp2m" feature in it. I tried various ways and means to add it but was unsuccessful. Is there any way to patch it ?

Note : I know that this group is not for Libvirt support, but someone in Drakvuf community might have done this. The help would be highly appreciated.

**Comment by icedevml** [comment]
AFAIR you can enable altp2m on a given domain in runtime

**Comment by tklengyel** [comment]
Yes, running ` xc_hvm_param_set(xch, domid, HVM_PARAM_ALTP2M, 2)` should work.

**Comment by icedevml** [comment]
@tklengyel Maybe some `--force-altp2m` in DRAKVUF, so it enables altp2m for you? I remember this particular problem with libvirt or other tooling appeared at least few times in the past.

Even if libvirt is not supported, IMHO it's worth considering if it's the only critical problem as per now.

**Comment by tklengyel** [comment]
I would say it could even be the default to do an `xc_hvm_param_get` and if its not enabled do an `xc_hvm_param_set`.

**Comment by icedevml** [comment]
I will look at it.

**Comment by tushariitr1** [comment]
@icedevml @tklengyel Actually, I have checked from the VM log file that "altp2m" is disabled by default. 
I found that this function "xc_hvm_param_set" is present in libxl_dom.c file. So,
1. Do I need to change this function in that C file ? or
2. Do I need to make a script that executes "xc_hvm_param_set(xch, domid, HVM_PARAM_ALTP2M, 2)" or on a running VM ? or
3. Do I need to change in the grub file?

**Comment by icedevml** [comment]
You should probably add it here:
https://github.com/tklengyel/drakvuf/blob/d1f08172bf13e5e644c3c7ad2b9f671952105c9a/src/libdrakvuf/vmi.c#L1446

and recompile DRAKVUF. Grub is a separate stuff and you should set everything there as suggested on `drakvuf.com`.

**Comment by tushariitr1** [comment]
@icedevml @tklengyel Thanks a lot for the help guys. It worked :)

**Comment by tklengyel** [comment]
@tushariitr1 Please open a PR with your changes

**Comment by icedevml** [comment]
I've already drafted something, see #681
