### ISSUE TITLE
memdump: Deduplication of memory dumps by hash

### ISSUE THREAD

**Issue by icedevml** [tklengyel/drakvuf#689]
At the moment, `memdump` may create a few identical dumps, because there is no deduplication mechanism implemented.

In our internal tests we've been using [majek/csiphash](https://github.com/majek/csiphash), i.e. we've been calculating a hash for each dump and comparing if there is already a dump with the same hash.

Would it be OK to include such hash implementation in DRAKVUF's code? Especially in terms of the current DRAKVUF license.

**Comment by tklengyel** [comment]
I usually prefer linking with libraries that are either BSD or LGPL. That said csiphash is MIT licensed which is [GPL-compatible](https://en.wikipedia.org/wiki/License_compatibility#GPL_compatibility), and the DRAKVUF license is GPL with extra provisions. But I would prefer if you used something that's already linked, for example glib already has hash functions you could use here: https://developer.gnome.org/glib/2.60/glib-Data-Checksums.html

**Comment by icedevml** [comment]
I was not aware glib supports SHA-1/SHA-256 out of the box, it seems to be a good stuff. Probably going to use it.

**Comment by icedevml** [comment]
Closing as #692 is merged
