### ISSUE TITLE
[socketmon] Missing comma in JSON Format Output

### ISSUE THREAD

**Issue by umarfarook882** [tklengyel/drakvuf#699]
Hi, missing comma in JSON Format Output in socketmon.

https://github.com/tklengyel/drakvuf/blob/9e536f84a5cc2411563a6d2ee598979d8d210541/src/plugins/socketmon/socketmon.cpp#L770

![error1](https://user-images.githubusercontent.com/22318677/64431745-a5854a00-d0d8-11e9-8706-1ff096b6be6c.png)

**Comment by tklengyel** [comment]
Please feel free to open a PR with the fix.
