### ISSUE TITLE
How to extract hypercalls for window machine

### ISSUE THREAD

**Issue by Preetixen** [tklengyel/drakvuf#72]
I have installed DRAKVUF and i am able to extract the traces of different processes for syscall interrupt.
How to extract the traces of hypercalls?

**Comment by tklengyel** [comment]
There is no support for that right now in DRAKVUF. Furthermore, Windows would not issue any hypercall directly to Xen, only if you have some PV drivers installed. For those you would need to get the debug symbol for the kernel driver and determine where you want to breakpoint its execution. If it's a malicious kernel driver that issues hypercalls, you would have to some reverse engineering first or extend Xen to record what hypercalls were issued (there is no support for that right now in Xen). Good luck, let us know if you make progress.
