### ISSUE TITLE
fatal: unable to connect to git.qemu.org

### ISSUE THREAD

**Issue by Alibm73** [tklengyel/drakvuf#723]
Hi
whatever i do i get this error:
![Screenshot from 2019-10-17 09-34-28](https://user-images.githubusercontent.com/39646882/66981891-ef8f2180-f0c1-11e9-8fe0-9f5e422ef234.png)
can't seem to resolve this. i don't have slow internet connection either.

**Comment by Alibm73** [comment]
@tklengyel 
what should i do??

**Comment by AbulesiKanJiJi** [comment]
Hi! Did you solve it? I meet the same problem.

**Comment by tklengyel** [comment]
Usually these errors are due to proxy configurations on your machine not being correct. Try configuring xen with `--enable-githttp` added and make sure you have the correct http proxy settings applied in your shell.
