### ISSUE TITLE
Extra System Calls Records using Xen and Windows 10

### ISSUE THREAD

**Issue by Vladinuto** [tklengyel/drakvuf#725]
Good morning, 

I have a question regarding the system call plugin. I've been testing it to monitor write operations to a file on a windows 10 virtual machine, but for some reason I'm getting duplicate calls for NtWrite. i.e. 8 duplicated system calls at random from 100,000 expected system calls. 

My first guess is that the windows OS is executing the system calls as requested, but sometimes the system call fails and the OS re-executes the system call. If this is the case , is Drakvuf trapping all system calls without checking if they were successful ? 

Any info would be appreciated.

Thanks in advance. 

-CR

**Comment by tklengyel** [comment]
Yes, DRAKVUF traps all systemcalls and it doesn't check the return value. So if the OS automatically re-executes the syscall that will show up in the logs as a duplicate. Gathering the return value of syscalls is an open issue to be developed as an improvement: #442

**Comment by Vladinuto** [comment]
Oh I see. Thanks! Will see if I can contribute to further this. 

-CR
