### ISSUE TITLE
Output interleaving

### ISSUE THREAD

**Issue by Maeriden** [tklengyel/drakvuf#727]
I have a tool that parses the output of plugins to extract information, but sometimes it gives an error related to the number of parameters in a function. Looking through an output file I found a few lines like this
```
syscall,1,0x60d70000,836,\Device\HarddiskVolume2\Windows\System32\svchost.exe,0,ntoskrnl.exe,NtOpenKeyEx,4,OUT,PHANDLE,KeyHandle,0x183f508,,IN,ACCESS_MASK,DesiredAccess,0x2000000,,IN,POBJECT_ATTRIBUTES,ObjectAttributes,0x183f558--V2P cache hit 0x000000000183f560 -- 0x00000000b568d560
--MEMORY cache hit 0xb568d000
--MEMORY cache hit 0xb568d000
--V2P cache hit 0xfffff880009e9188 -- 0x000000006ab2f1880000000183f560 -- 0x00000000b568d560
...some more cache-related lines...
 [XFJFR0lTVFJZXE1BQ0hJTkU=],,IN,ULONG,OpenOptions,0x0,
--Finished handling event.
--Caught single step event!
--Finished handling event.
--Caught int3 interrupt event!
```
It seems like cache-related lines are printed before the syscall line is fully printed, losing related information and introducing unrelated ones.
As a test, I changed the printf()s in the syscalls plugin to sprintf()s and wrote the string out all at once. The tool stopped reporting errors.
Am I correct in assuming this is not the intended output, or am I missing something?

**Comment by tklengyel** [comment]
It looks like you you have the debug log enabled in LibVMI, that's why you have the mangled log. If you don't need it, you should disable the debug options of LibVMI.

**Comment by Maeriden** [comment]
Sorry for the late reply. You're right, it was libVMI debug output.
