### ISSUE TITLE
Does DRAKVUF trap execution of system calls through hypervisor

### ISSUE THREAD

**Issue by Preetixen** [tklengyel/drakvuf#73]
Hi 
I read below line somewhere:

Syscalls do not trap through the hypervisor, only SYSENTER/SYSEXIT instructions do.
When SYSENTER EIP MSR points are set, we must alter them to generate a page fault at a
known address. When the page fault takes place, we need to extract the wanted information.
all this must be done transparently to the OS.

could you please explain how DRAKVUF is trapping the syscalls then at Xen?

**Comment by tklengyel** [comment]
I suggest reading the paper describing how DRAKVUF traps systemcalls through the hypervisor, you can find it at https://www.sec.in.tum.de/assets/Uploads/scalability-fidelity-stealth.pdf, or to review ths sourcecode.

**Comment by Preetixen** [comment]
I read the paper:
It says it obtains the rekall profile first to find internal kernal functions.
Then it uses some technique to know address of kernel functions.
It further injects Break points at that address.

So, here trapping is done using break points..

I am confused what are these break points? (Are they instructions like int 0x2e)
In which file you are doing changes (path and entry to inject such instructions)

What changes you are doing in the handler of break points?

could you please elaborate execution tracing??
Thanks

**Comment by tklengyel** [comment]
Breakpoints are of the kind 0xCC. The cpu is configured to trap those to Xen and not the guest os. Xen then forwards those events to DRAKVUF through LibVMI. No files are changed, breakpoints are only present in memory and are execute only.

**Comment by Preetixen** [comment]
So the purpose of break points is to know some syscall instruction (event) is executing in memory whose value together with process name can be obtained by reading cpu %eax register.

It is passive monitoring. It is not doing any changes in code and neither in the execution flow of window processes. 

But when such event occur it might happen the value of %eax is changed to new process, the moment the event is notified to xen and it starts reading new value of eax. ( so trapping of some functions may be left unread)
Am I right? 

-How you configured CPU to trap to these events (break point execution) to Xen not to guest OS? 

Thanks!!!
