### ISSUE TITLE
Add a section about non-kernel profile generation on drakvuf.com

### ISSUE THREAD

**Issue by icedevml** [tklengyel/drakvuf#735]
Having profiles for DLLs or drivers provided in DRAKVUF's command line is pretty important in terms of additional features that plugins do offer.

I suggest to copy this code listing: https://github.com/tklengyel/drakvuf/wiki/DRAKVUF-Plugin-Documentation#socketmon
to the manual at `drakvuf.com`, as an optional generic guide for getting profiles out of DLLs/drivers.

**Comment by tklengyel** [comment]
Sounds good to me, feel free to open a PR to the gh-pages branch with the changes
