### ISSUE TITLE
Process Injection not working ?

### ISSUE THREAD

**Issue by dorpvom** [tklengyel/drakvuf#74]
Hi,
I've updated the system to the latest commit yesterday and although the monitoring works just find, no process injection seems to take place. I've used the same injection command as before, sth. like
-e "cmd.exe" or -e "C:\\Windows\\System32\\cmd.exe".
The rest of my resources are about a week old (mainly libVMI and Volatility) but there doesn't seem to be critical changes to those repos.

Any leads to a possible reason?

Thanks!

[Update] Just tried the injector binary. It just outputs Starting ... through PID ... and then stalls.

**Comment by tklengyel** [comment]
@dorpvom: can you enable debug output? `make clean; ./configure --enable-debug; make` and post the output of what you see when you try injection. It might be that you are choosing a process to be hijacked that doesn't get scheduled by the OS in which case injection would just keep waiting (and likely crash the host process if you terminate it manually).

**Comment by dorpvom** [comment]
I'll try the re-compilation tomorrow. Regarding the choice of process, I tried several hosts such as rundll32, svchost, explorer and dwm so this seems to be improbable. I'll report back as soon as I have debug output.

**Comment by tklengyel** [comment]
Yea, try something less exotic, like running ping in the VM and then hijacking that or using task manager. DRAKVUF goes through an integration test for each pull request where injection is tested on both 32-bit and 64-bit Windows through task manager and I only merge things when all tests pass. So AFAIK process injection works, with the right host process.

**Comment by dorpvom** [comment]
So using taskmgr hasn't done the trick for me. Here is some debug output:

$ sudo ./src/drakvuf -r /root/win.rekall.json -d 8 -i 3320 -e "cmd.exe" -v 1> mydebug.log
DRAKVUF v0.2
Init VMI on domID 8 -> win
Rekall profile: structure member 'Rip' not found
Failed to find offset for _KTRAP_FRAME:Rip
Reservation increased? 0 with new gfn: 0x3b73ef
Xen altp2m view created with idx: 1 idr: 2
The Rekall profile defines 11313 functions
Inject traps in module list of [4]: System
	ntoskrnl.exe @ 0x82642000
Reservation increased? 0 with new gfn: 0x3b7331
Copied trapped page to new location
Activating remapped gfns in the altp2m views!
		New memory event guard set on page 9838
Creating new breakpoint guard lookup table @ 0x557c1aae06a0
		New memory event guard2 set on page 3896113
Adding 0x266e5c5 to breakpoint guard lookup table @ 0x557c1aae06a0.
		Trap added @ PA 0x266e5c5 RPA 0x3b73315c5 Page 9838 for NtYieldExecution.
[...] Lots of added traps [...]
	hal.dll @ 0x8260b000
	kdcom.dll @ 0x80bb5000
	mcupdate.dll @ 0x8a424000
	PSHED.dll @ 0x8a4a9000
	BOOTVID.dll @ 0x8a4ba000
	CLFS.SYS @ 0x8a4c2000
[...] Lots of addresses [...]
Inject traps in module list of [4]: System
	ntoskrnl.exe @ 0x82642000
Reservation increased? 0 with new gfn: 0x3b7152
Copied trapped page to new location
Activating remapped gfns in the altp2m views!
		New memory event guard set on page 10083
Creating new breakpoint guard lookup table @ 0x557c1ba57b60
		New memory event guard2 set on page 3895634
Adding 0x2763005 to breakpoint guard lookup table @ 0x557c1ba57b60.
		Trap added @ PA 0x2763005 RPA 0x3b7152005 Page 10083 for ExAllocatePoolWithTag. 
Inject traps in module list of [4]: System
	ntoskrnl.exe @ 0x82642000
Inject traps in module list of [4]: System
	ntoskrnl.exe @ 0x82642000
Inject traps in module list of [4]: System
	ntoskrnl.exe @ 0x82642000
Reservation increased? 0 with new gfn: 0x3b7258
Copied trapped page to new location
Activating remapped gfns in the altp2m views!
		New memory event guard set on page 10344
Creating new breakpoint guard lookup table @ 0x557c1ba57c60
		New memory event guard2 set on page 3895896
Adding 0x2868201 to breakpoint guard lookup table @ 0x557c1ba57c60.
		Trap added @ PA 0x2868201 RPA 0x3b7258201 Page 10344 for ObCreateObject. 
Rekall profile: structure member 'Rip' not found
Rekall profile: structure member 'Rax' not found
Rekall profile: structure member 'Rbx' not found
Rekall profile: structure member 'Rcx' not found
Rekall profile: structure member 'Rdx' not found
Rekall profile: structure member 'Rsp' not found
Rekall profile: structure member 'Rbp' not found
Rekall profile: structure member 'Rsi' not found
Rekall profile: structure member 'Rdi' not found
Rekall profile: structure member 'R8' not found
Rekall profile: structure member 'R9' not found
Rekall profile: structure member 'R10' not found
Rekall profile: structure member 'R11' not found
Inject traps in module list of [4]: System
	ntoskrnl.exe @ 0x82642000
Reservation increased? 0 with new gfn: 0x347471
Copied trapped page to new location
Activating remapped gfns in the altp2m views!
		New memory event guard set on page 9974
Creating new breakpoint guard lookup table @ 0x557c1ba57cc0
		New memory event guard2 set on page 3437681
Adding 0x26f6ee0 to breakpoint guard lookup table @ 0x557c1ba57cc0.
		Trap added @ PA 0x26f6ee0 RPA 0x347471ee0 Page 9974 for KiDispatchException. 
Started DRAKVUF loop
Waiting for events in DRAKVUF...
Waiting for events in DRAKVUF...
trap_guard vcpu 0 memaccess @ 0x26c1569. Page 9921. altp2m 1 r--
Waiting for events in DRAKVUF...
reset trap, switching 0->1
Waiting for events in DRAKVUF...
[...] Running System output [...]

DrakvuF output looks regular.

**Comment by dorpvom** [comment]
So there is definetly no line in there representing the debug output of the win-exports.c, which is called by the injection.c in the libdrakvuf.
As far as I undestand there should either be sth. like "Found module in PID 640: taskmgr.exe" or "Failed to get address of kernel32.dll!CreateProcessA" but I'm not seeing any of this.

I'm not able to trace the injection_pid from the main.cpp to anywhere near the 'drakvuf_inject_cmd' function, but me and C are not always on the same page.

So if this is indeed just not working on my machine I should probably look for a fresh setup.
Do you contradict?

**Comment by tklengyel** [comment]
No I don't see the injection related stuff there either so this might be a real bug. Can you try the standalone injector if that works?

**Comment by dorpvom** [comment]
Now there's something..

Starting the process directly with the injector works (sometimes), so there might just be a connection missing from main to injector.
So thank you very much! ;)

It does not work dependable though but I'll put the error message in a new issue as these don't seem related.
