### ISSUE TITLE
getting certain information

### ISSUE THREAD

**Issue by Alibm73** [tklengyel/drakvuf#743]
Hi @tklengyel 
is there a way to get the information of a certain executable?
For example I have a malware, how can i get all the information of that malware? (Just that malware, nothing else)
For example when i use syscall plugin i get all the info, but i want just the info that malware uses.

**Comment by tklengyel** [comment]
It's up to you to determine what is relevant information. You can certainly grep by cr3 to see only the initial malware process but at the risk of missing stuff in case the malware moves into another process via thread injection or similar horizontal move.
