### ISSUE TITLE
Command to take trace of malware program file placed in window 7

### ISSUE THREAD

**Issue by Preetixen** [tklengyel/drakvuf#75]
As you told  to place the executable on the disk somewhere in the VM and use the -i and -e options to make DRAKVUF start it for you.

1. can you please tell the exact command to take trace of malware program.
My file name is 'sam' (malware file) 

I am running command ./src/drakvuf -r /root/windows7-sp1.rekall.json -d 7 | grep sam
where should i place -e or -i in this command or what is the correct command?

 2. After getting whole system trace using drakuf, i have to destroy and create new image everytime. 

Please help in this issue

**Comment by dorpvom** [comment]
To start the sample you need
a) the process id from a already running process that has the kernel32.dll loaded, e.g. explorer.exe, to use with the -i flag and
b) the absolute path to your sample - unless it's parent directory is set in the guest's path variables.

You can retrieve a) by using the process-list <domain_name> command that comes with libvmi.
b) has to be gathered from inside your guest unless you alredy know it.

The command will then look sth like:
./src/drakvuf -r path/to/rekall -d domid -i <pid_of_explorer_exe> -e "C:\\SomeDirectory\\sam.exe"

You should then be able to identify your sample's actions by grepping for sam.exe.

**Comment by Preetixen** [comment]
Ok Thank you. Tommorrow i will try it.

1. Are -i -e opions used to execute sam.exe and will give only traces for sam.exe??

**Comment by dorpvom** [comment]
No, you will still get the whole system trace, but since the last commit you can identify your sample's interaction as the process name is logged for each action
(
e.g. [SYSCALL] vCPU:0 CR3:0xb9e57260,svchost.exe ntoskrnl.exe!NtOpenFile
where svchost.exe is the executing process
)

**Comment by tklengyel** [comment]
@Preetixen: you can also specify the `-t` option with the number of seconds you want to run DRAKVUF for. For example `-t 60` will run it for 60 seconds. For the `-i` option you need to specify the PID you want to hijack, `-i 442` for example. The important thing is that the PID you are choosing needs to be scheduled by the OS, so running applications like solitaire won't do anything until you manually interact with it. I usually recommend task manager as being a good candidate for hijacking, but any process should work.

@dorpvom: thanks for helping ;)

**Comment by Preetixen** [comment]
Could you please send be malware binaries (dataset) to test in DRAKVUF??
Thank you

**Comment by dorpvom** [comment]
You are missing the value for the -i flag (i.e. the PID of the process to hijack for injection)

**Comment by Preetixen** [comment]
How to know that from hypervisor

**Comment by Preetixen** [comment]
1. But if i have to get the pid from guest then, the should be running in the guest but since i have just kept the binary (.exe file) in system. How do i execute it?

2. My windows wants system restore after taking system traces?

**Comment by dorpvom** [comment]
see above:
"You can retrieve a) by using the process-list command that comes with libvmi."
-> say your machine is called "windows7" - so that's the domain name found in the "xl list" command - you call 
$ sudo process-list windows7

There you see sth. like 
Process listing for VM windows7 (id=7)
[    4] System (struct addr:84aba980)
[  220] smss.exe (struct addr:85a44020)
[  300] csrss.exe (struct addr:85f67a68)
[  336] wininit.exe (struct addr:8601e030)
[  348] csrss.exe (struct addr:84ba4030)
[  384] winlogon.exe (struct addr:85966d40)
[  444] services.exe (struct addr:8614c030)
[...]
Then take the PID - number in brackets - of the process you want to use

**Comment by Preetixen** [comment]
i got this output
/home/xen/drakvuf# sudo process-list windows7-sp1
Process listing for VM windows7-sp1 (id=2)
[    4] System (struct addr:fffffa8000c09b30)
[  220] smss.exe (struct addr:fffffa80010ac040)
[  292] csrss.exe (struct addr:fffffa8001173060)
[  332] wininit.exe (struct addr:fffffa80011ba360)
[  340] csrss.exe (struct addr:fffffa80011c3060)
[  376] services.exe (struct addr:fffffa80011f72d0)
[  388] lsass.exe (struct addr:fffffa8001423060)
[  396] lsm.exe (struct addr:fffffa8001425060)
[  524] svchost.exe (struct addr:fffffa80014ef060)
[  588] svchost.exe (struct addr:fffffa8001520b30)
[  632] svchost.exe (struct addr:fffffa8001533a10)
[  708] winlogon.exe (struct addr:fffffa8001549b30)
[  748] winpeshl.exe (struct addr:fffffa800155b4f0)
[  776] recenv.exe (struct addr:fffffa800159ea50)
[  796] StartRep.exe (struct addr:fffffa80015e48b0)
[  940] vds.exe (struct addr:fffffa8001697060)
[ 1012] svchost.exe (struct addr:fffffa800158eb30)
[  296] wmiprvse.exe (struct addr:fffffa8001670b30)
[23492840] H�� (struct addr:fffff8000c23d9a8)

**Comment by Preetixen** [comment]
it shows sam.exe is not running in pc.
how do i execute my malware files from xen

**Comment by Preetixen** [comment]
Also please help me here too:

I cant interpret the following output: 
root@xen:/home/xen/drakvuf# xl list
Name                                        ID   Mem VCPUs	State	Time(s)
Domain-0                                     0  1023     2     r-----     760.0
windows7-sp1                                 4  1000     2     -b----      53.9
root@xen:/home/xen/drakvuf# ./src/drakvuf -r /root/windows7-sp1.rekall.json -d 4 -t 60 -i 1132 -e "\home\xen\Desktop\svchost.exe"| grep svchost.exe
DRAKVUF v0.2
Binary file (standard input) matches

**Comment by dorpvom** [comment]
A couple of things:
a) Do you have transferred the sample you want to run into your guest system?
b) The xl command is documented here: http://xenbits.xen.org/docs/unstable/man/xl.1.html
c) You use the process-list command before running drakvuf to get a PID for another process you can hijack - so not your sample itself
d) drakvuf - not xen - is then used to execute the sample (specified by the -e flag)

**Comment by Preetixen** [comment]
ok ..

Yes i downloaded the malware zip file and then extracted and placed at my desktop machine. I renamed it to sam.exe.
Now in order to get the traces:
how do i know the PID of sam.exe which is just placed at the desktop.
sorry, I can't locate xl command to execute a guest process from xen.

**Comment by Preetixen** [comment]
Actually i want to ask How do I run my malware sam.exe in guest OS? so that it will get the PID
which i will use in drakvuf command.

**Comment by dorpvom** [comment]
That is the point. You don't need to because drakvuf does it for you. The program uses another process to start your sample by injecting a CreateProcessA command from the kernel32.dll into the other process. Thus you need the PID of a process that a) has the kernel32.dll loaded and b) is scheduled, such that drakvuf can hijack it's execution for the creation of the malicious process.

**Comment by dorpvom** [comment]
Say you have the taskmgr.exe running on your guest with PID 640, and your username is, say,  "user",
your -i flag should be 640 while your -e flag should be "C:\\Users\\user\\Desktop\\sam.exe".

**Comment by v-p-b** [comment]
That  `"\home\xen\Desktop\sam.exe"` parameter looks horribly wrong. You should use the path native to the VM (Windows) as @dorpvom noted. Do you even have sam.exe on the guest  (Windows) filesystem?

**Comment by tklengyel** [comment]
There was actually a bug that I just fixed (the -i -e flags were ignored) so injection through the main drakvuf binary would do nothing if you were on the latest master. Do a git pull and recompile to get the fix. The standalone injector still should haven worked however.

And as @v-p-b pointed out, the binary of the executable you want to start has to be **inside** the VM.

**Comment by Preetixen** [comment]
Hi i executed the malware file.
However, i am not able to execute multiple malware programs which are kept in one folder in one short

please tell me the command to execute drakvuf file by one commadline option

**Comment by Preetixen** [comment]
I also can not grep to particular process.
The output says 

DRAKVUF 0.2 
Binary file (standard output ) matches
