### ISSUE TITLE
drakvuf error 

### ISSUE THREAD

**Issue by mismailzz** [tklengyel/drakvuf#750]
During the execution of below command: 

root@kali:~/drakvuf/xen# make -j4 dist-tools

cause an warning error like:
<pre><b>include/ipxe/uri.h:</b> In function ‘<b>uri_get</b>’:
<b>include/ipxe/uri.h:178:12:</b> <font color="#EF2929"><b>error: </b></font>taking address of packed member of ‘<font color="#EF2929"><b>struct uri</b></font>’ may result in an unaligned pointer value [<font color="#EF2929"><b>-Werror=address-of-packed-member</b></font>]
  178 |  ref_get ( <font color="#EF2929"><b>&amp;uri-&gt;refcnt</b></font> );
      |            <font color="#EF2929"><b>^~~~~~~~~~~~</b></font>
<b>include/ipxe/refcnt.h:95:18:</b> <font color="#34E2E2"><b>note: </b></font>in definition of macro ‘<b>ref_get</b>’
   95 |  ref_increment ( <font color="#34E2E2"><b>refcnt</b></font> );     \
      |                  <font color="#34E2E2"><b>^~~~~~</b></font>
<b>include/ipxe/uri.h:</b> In function ‘<b>uri_put</b>’:
<b>include/ipxe/uri.h:189:12:</b> <font color="#EF2929"><b>error: </b></font>taking address of packed member of ‘<font color="#EF2929"><b>struct uri</b></font>’ may result in an unaligned pointer value [<font color="#EF2929"><b>-Werror=address-of-packed-member</b></font>]
  189 |  ref_put ( <font color="#EF2929"><b>&amp;uri-&gt;refcnt</b></font> );
      |            <font color="#EF2929"><b>^~~~~~~~~~~~</b></font>
<b>include/ipxe/refcnt.h:109:18:</b> <font color="#34E2E2"><b>note: </b></font>in definition of macro ‘<b>ref_put</b>’
  109 |  ref_decrement ( <font color="#34E2E2"><b>refcnt</b></font> );     \
      |                  <font color="#34E2E2"><b>^~~~~~</b></font>
In file included from <b>include/ipxe/interface.h:14</b>,
                 from <b>include/ipxe/xfer.h:14</b>,
                 from <b>core/open.c:29</b>:
<b>include/ipxe/uri.h:</b> In function ‘<b>uri_get</b>’:
<b>include/ipxe/uri.h:178:12:</b> <font color="#EF2929"><b>error: </b></font>taking address of packed member of ‘<font color="#EF2929"><b>struct uri</b></font>’ may result in an unaligned pointer value [<font color="#EF2929"><b>-Werror=address-of-packed-member</b></font>]
  178 |  ref_get ( <font color="#EF2929"><b>&amp;uri-&gt;refcnt</b></font> );
      |            <font color="#EF2929"><b>^~~~~~~~~~~~</b></font>
<b>include/ipxe/refcnt.h:95:18:</b> <font color="#34E2E2"><b>note: </b></font>in definition of macro ‘<b>ref_get</b>’
   95 |  ref_increment ( <font color="#34E2E2"><b>refcnt</b></font> );     \
      |                  <font color="#34E2E2"><b>^~~~~~</b></font>
<b>include/ipxe/uri.h:</b> In function ‘<b>uri_put</b>’:
<b>include/ipxe/uri.h:189:12:</b> <font color="#EF2929"><b>error: </b></font>taking address of packed member of ‘<font color="#EF2929"><b>struct uri</b></font>’ may result in an unaligned pointer value [<font color="#EF2929"><b>-Werror=address-of-packed-member</b></font>]
  189 |  ref_put ( <font color="#EF2929"><b>&amp;uri-&gt;refcnt</b></font> );
      |            <font color="#EF2929"><b>^~~~~~~~~~~~</b></font>
<b>include/ipxe/refcnt.h:109:18:</b> <font color="#34E2E2"><b>note: </b></font>in definition of macro ‘<b>ref_put</b>’
  109 |  ref_decrement ( <font color="#34E2E2"><b>refcnt</b></font> );     \
      |                  <font color="#34E2E2"><b>^~~~~~</b></font>
In file included from <b>include/ipxe/params.h:13</b>,
                 from <b>core/uri.c:38</b>:
<b>include/ipxe/uri.h:</b> In function ‘<b>uri_get</b>’:
<b>include/ipxe/uri.h:178:12:</b> <font color="#EF2929"><b>error: </b></font>taking address of packed member of ‘<font color="#EF2929"><b>struct uri</b></font>’ may result in an unaligned pointer value [<font color="#EF2929"><b>-Werror=address-of-packed-member</b></font>]
  178 |  ref_get ( <font color="#EF2929"><b>&amp;uri-&gt;refcnt</b></font> );
      |            <font color="#EF2929"><b>^~~~~~~~~~~~</b></font>
<b>include/ipxe/refcnt.h:95:18:</b> <font color="#34E2E2"><b>note: </b></font>in definition of macro ‘<b>ref_get</b>’
   95 |  ref_increment ( <font color="#34E2E2"><b>refcnt</b></font> );     \
      |                  <font color="#34E2E2"><b>^~~~~~</b></font>
<b>include/ipxe/uri.h:</b> In function ‘<b>uri_put</b>’:
<b>include/ipxe/uri.h:189:12:</b> <font color="#EF2929"><b>error: </b></font>taking address of packed member of ‘<font color="#EF2929"><b>struct uri</b></font>’ may result in an unaligned pointer value [<font color="#EF2929"><b>-Werror=address-of-packed-member</b></font>]
  189 |  ref_put ( <font color="#EF2929"><b>&amp;uri-&gt;refcnt</b></font> );
      |            <font color="#EF2929"><b>^~~~~~~~~~~~</b></font>
<b>include/ipxe/refcnt.h:109:18:</b> <font color="#34E2E2"><b>note: </b></font>in definition of macro ‘<b>ref_put</b>’
  109 |  ref_decrement ( <font color="#34E2E2"><b>refcnt</b></font> );     \
      |                  <font color="#34E2E2"><b>^~~~~~</b></font>
<b>core/uri.c:</b> In function ‘<b>parse_uri</b>’:
<b>core/uri.c:310:13:</b> <font color="#EF2929"><b>error: </b></font>taking address of packed member of ‘<b>struct uri</b>’ may result in an unaligned pointer value [<font color="#EF2929"><b>-Werror=address-of-packed-member</b></font>]
  310 |  ref_init ( &amp;uri-&gt;refcnt, uri_free );
<b>include/ipxe/refcnt.h:68:15:</b> <font color="#34E2E2"><b>note: </b></font>in definition of macro ‘<b>ref_init</b>’
   68 |   ref_init ( (<font color="#34E2E2"><b>refcnt</b></font>), (free) );    \
      |               <font color="#34E2E2"><b>^~~~~~</b></font>
<b>core/uri.c:</b> In function ‘<b>uri_dup</b>’:
<b>core/uri.c:585:13:</b> <font color="#EF2929"><b>error: </b></font>taking address of packed member of ‘<b>struct uri</b>’ may result in an unaligned pointer value [<font color="#EF2929"><b>-Werror=address-of-packed-member</b></font>]
  585 |  ref_init ( &amp;dup-&gt;refcnt, uri_free );
<b>include/ipxe/refcnt.h:68:15:</b> <font color="#34E2E2"><b>note: </b></font>in definition of macro ‘<b>ref_init</b>’
   68 |   ref_init ( (<font color="#34E2E2"><b>refcnt</b></font>), (free) );    \
      |               <font color="#34E2E2"><b>^~~~~~</b></font>
</pre>

**Comment by tklengyel** [comment]
This seems to be an issue with Xen/ipxe and your compiler. Please look for help regarding this issue on the xen-devel mailinglist and also post your compiler version and that this is with Xen 4.12.1
