### ISSUE TITLE
[MEMDUMP] User DLL hooks fails on Windows 10 1903

### ISSUE THREAD

**Issue by trapframe** [tklengyel/drakvuf#752]
User DLL hooking fails when running on Windows 10 1903 (x64)

Running in verbose mode shows thousands of error like :

```
1575363159.530031 [MEMDUMP] Failed to find MMVAD for memory passed to NtProtectVirtualMemory
1575363159.530234 [MEMDUMP] Failed to find MMVAD for memory passed to NtProtectVirtualMemory
1575363159.530460 [MEMDUMP] Failed to find MMVAD for memory passed to NtProtectVirtualMemory
```

or 

```
1575363187.062374 [MEMDUMP] Failed to find MMVAD for memory passed to NtFreeVirtualMemory
1575363187.071607 [MEMDUMP] Failed to find MMVAD for memory passed to NtFreeVirtualMemory
1575363187.072577 [MEMDUMP] Failed to find MMVAD for memory passed to NtFreeVirtualMemory
1575363187.072965 [MEMDUMP] Failed to find MMVAD for memory passed to NtFreeVirtualMemory
1575363187.073319 [MEMDUMP] Failed to find MMVAD for memory passed to NtFreeVirtualMemory
1575363187.074009 [MEMDUMP] Failed to find MMVAD for memory passed to NtFreeVirtualMemory
```

It looks like one of the problems lies in create_dll_meta :

```
static user_dll_t* create_dll_meta(drakvuf_t drakvuf, drakvuf_trap_info* info, memdump* plugin, addr_t dll_base)
{
    mmvad_info_t mmvad;
    if (!drakvuf_find_mmvad(drakvuf, info->proc_data.base_addr, dll_base, &mmvad))
        return nullptr;
```

the **drakvuf_find_mmvad**  always fails 

Same version works perfectly on Windows 7

**Comment by icedevml** [comment]
I will look at it soon.

**Comment by icedevml** [comment]
@trapframe Could you try to disable page file? Windows 10 has the ability to swap out some parts of the kernel and this makes it much harder to work with.

**Comment by trapframe** [comment]
Disablling pagefile makes no change.

But i think i found where the problems lies.
When drakvuf starts we can see those errors:

```
1575878034.416676 Rekall profile: no 'VadRoot' found
1575878034.416769 Failed to find offset for VadRoot:BalancedRoot
1575878034.416866 Rekall profile: '_MMVAD' has no 'LeftChild' member
1575878034.416945 Failed to find offset for _MMVAD:LeftChild
1575878034.416957 Rekall profile: '_MMVAD' has no 'RightChild' member
1575878034.417043 Failed to find offset for _MMVAD:RightChild
1575878034.417050 Rekall profile: '_MMVAD' has no 'StartingVpn' member
1575878034.417129 Failed to find offset for _MMVAD:StartingVpn
1575878034.417200 Rekall profile: '_MMVAD' has no 'EndingVpn' member
1575878034.417267 Failed to find offset for _MMVAD:EndingVpn
1575878034.417279 Rekall profile: '_MMVAD' has no 'u' member
1575878034.417360 Failed to find offset for _MMVAD:u
```

looking into the kernel json profile of windows 7 we can see for the _MMVAD struct : 

![image](https://user-images.githubusercontent.com/9018546/70421681-8e088500-1a6a-11ea-8209-36937a1d9318.png)

but for Windows 10 1903:

![image](https://user-images.githubusercontent.com/9018546/70421874-00796500-1a6b-11ea-9399-5f6adf70f642.png)

Big change, most of the fields we used are now embedded in the Core field which is a _MMVAD_SHORT structure

**Comment by icedevml** [comment]
@trapframe Huge thanks for this investigation, I will look at it soon and hopefully this will be solved soon.

As per now, the only production-grade-well-supported system for `memdump` is Windows 7 x64. Be aware that additional issues may pop out when using Windows 10, but of course I will try to address them when I have some time available.

**Comment by trapframe** [comment]
thanks,  looks like there is other changes in VAD management (this come back to win8/8.1).

VadRoot is a different tree (_MM_AVL_TABLE  in win7 and _RTL_AVL_TREE in win10 1903) and its nodes are a new _RTL_BALANCED_NODE stuct.

there is also new StartingVpnHigh / EndingVpnHigh fields in the _MMVAD_SHORT struct.

Here a short description from Rekall source  (the talk about VadRoot needs to be adjusted for win10 as the node struct type has changed again) :

```
 # In windows 8 the VadRoot is actually composed from _MM_AVL_NODE instead of 
 # _MMVAD structs or _MMADDRESS_NODE. The structs appear to be organised by 
 # functional order - the _MM_AVL_NODE is always the first member of the struct, 
 # then the _MMVAD_SHORT, then the _MMVAD. For example, the tree traversal code, 
 # simply casts all objects to an _MM_AVL_NODE without caring what they actually 
 # are, then depending on the vad tag, they get casted to different structs. 
  
 # Additionally in windows 8.1 there are new fields StartingVpnHigh and 
 # EndingVpnHigh which are chars representing the high part of the PFN. Therefore 
 # the real PFN is (StartingVpnHigh << 32) | StartingVpn. The below overlay 
 # gracefully falls back to the old profiles (where StartingVpnHigh does not 
 # exist).
```

**Comment by icedevml** [comment]
@trapframe should be working now, could you confirm?

**Comment by trapframe** [comment]
well, DLL APIs hooking now works, however after a while i got a BSOD:

![image](https://user-images.githubusercontent.com/9018546/70634774-1df92b00-1c33-11ea-9b45-c5b800eefc00.png)

Still need to confirm it this is directly related to MEMDUMP, will do additionnal testing and let you know

**Comment by trapframe** [comment]
Attached  is the debug output corresponding to the BSOD:
[bug.txt](https://github.com/tklengyel/drakvuf/files/3951161/bug.txt)

the extract below shows that hooking was indeed successfull:

```
1576078446.583363 [MEMDUMP-USER] Found DLL which is worth processing 7ff815c30000
1576078446.583432 [MEMDUMP-USER] Export info not accessible, page fault 7ff815cb3000
1576078446.583789 [MEMDUMP-USER] Export info not accessible, page fault 7ff815cb4000
1576078446.584062 [MEMDUMP-USER] Export info not accessible, page fault 7ff815cb5000
1576078446.584346 [MEMDUMP-USER] Export info not accessible, page fault 7ff815cb6000
1576078446.584950 [MEMDUMP-USER] Hook CreateServiceA (vaddr = 0x7ff815c732c0, dll_base = 0x7ff815c30000, result = OK)
1576078446.584986 [MEMDUMP-USER] Hook CreateServiceW (vaddr = 0x7ff815c73e50, dll_base = 0x7ff815c30000, result = OK)
1576078446.585012 [MEMDUMP-USER] Hook ControlServiceExA (vaddr = 0x7ff815c73170, dll_base = 0x7ff815c30000, result = OK)
1576078446.585338 [MEMDUMP-USER] Hook ControlServiceExW (vaddr = 0x7ff815c3db80, dll_base = 0x7ff815c30000, result = OK)
1576078446.585643 [MEMDUMP-USER] Hook ControlService (vaddr = 0x7ff815c3e310, dll_base = 0x7ff815c30000, result = OK)
1576078446.585974 [MEMDUMP-USER] Hook DeleteService (vaddr = 0x7ff815c742c0, dll_base = 0x7ff815c30000, result = OK)
1576078446.585990 [MEMDUMP-USER] Done, flag DLL as hooked
1576078446.586271 [MEMDUMP-USER] DLL 5096!7ff815c30000 is already hooked
1576078446.586290 Removing breakpoint trap from 0x25cdf95.
1576078446.586347 Successfully set access to rw- on GFN 0x25cd!
1576078446.586368 Successfully set access to rwx on GFN 0xff007!
1576078446.586387 Ignoring old breakpoint event found in the queue
1576078446.586509 [MEMDUMP-USER] copy on write called: vaddr: 7ff815cb98c0 pte: ffff823ffc0ae5c8, pid: 5096, cr3: 784e8002
1576078446.586524 [MEMDUMP-USER] old CoW PA: 254818c0
1576078446.586797 [MEMDUMP-USER] copy on write called: vaddr: 7ff815cc2000 pte: ffff823ffc0ae610, pid: 5096, cr3: 784e8002
1576078446.586813 [MEMDUMP-USER] old CoW PA: 24e89000
1576078446.587080 [MEMDUMP-USER] DLL 5096!7ff815c30000 is already hooked
1576078446.587435 [MEMDUMP-USER] DLL 5096!7ff815c30000 is already hooked
1576078446.587764 [MEMDUMP-USER] copy on write called: vaddr: 7ff815c9ded0 pte: ffff823ffc0ae4e8, pid: 5096, cr3: 784e8002
1576078446.587780 [MEMDUMP-USER] old CoW PA: 1ac3ced0
1576078446.588047 [MEMDUMP-USER] DLL 5096!7ff815c30000 is already hooked
1576078446.588339 [MEMDUMP-USER] DLL 5096!7ff815c30000 is already hooked
1576078446.588621 [MEMDUMP-USER] DLL 5096!7ff815c30000 is already hooked
1576078446.589574 [MEMDUMP-USER] DLL 5096!7ff815c30000 is already hooked
```

**Comment by icedevml** [comment]
A good news is that it was even working for a while:
```
1576078402.244096 [MEMDUMP-USER] Usermode callback called 6180!CreateServiceW
```

perhaps we made some corruption somewhere. I will look at it.

**Comment by trapframe** [comment]
hold on, got the same BSOD after a few minutes without MEMDUMP activated....

So there is something else here, i will check it is is related to the VM itself.

For info , last output from drakvuf before BSOD below, current process is MemCompression, not sure it there is a relationship with the BSOD but name is odd enough ....

```
[CPUIDMON] TIME:1576079597.474303 VCPU:0 CR3:0x3108a002,"MemCompression" SessionID:-1. Leaf: 0x1. Subleaf: 0x0. RAX: 0x406e3 RBX: 0x200800 RCX: 0xfffa3203 RDX: 0x1fcbfbff
[CPUIDMON] TIME:1576079597.474610 VCPU:0 CR3:0x3108a002,"MemCompression" SessionID:-1. Leaf: 0x40000001. Subleaf: 0x0. RAX: 0x4000d RBX: 0x0 RCX: 0x0 RDX: 0x0
[CPUIDMON] TIME:1576079597.474720 VCPU:0 CR3:0x3108a002,"MemCompression" SessionID:-1. Leaf: 0x40000001. Subleaf: 0x0. RAX: 0x4000d RBX: 0x0 RCX: 0x0 RDX: 0x0
[CPUIDMON] TIME:1576079599.040348 VCPU:0 CR3:0x3108a002,"MemCompression" SessionID:-1. Leaf: 0x1. Subleaf: 0x0. RAX: 0x406e3 RBX: 0x200800 RCX: 0xfffa3203 RDX: 0x1fcbfbff
[CPUIDMON] TIME:1576079599.043289 VCPU:0 CR3:0x3108a002,"MemCompression" SessionID:-1. Leaf: 0x40000001. Subleaf: 0x0. RAX: 0x4000d RBX: 0x0 RCX: 0x0 RDX: 0x0
[CPUIDMON] TIME:1576079599.043885 VCPU:0 CR3:0x3108a002,"MemCompression" SessionID:-1. Leaf: 0x40000001. Subleaf: 0x0. RAX: 0x4000d RBX: 0x0 RCX: 0x0 RDX: 0x0
[CPUIDMON] TIME:1576079599.044089 VCPU:0 CR3:0x3108a002,"MemCompression" SessionID:-1. Leaf: 0x1. Subleaf: 0x0. RAX: 0x406e3 RBX: 0x200800 RCX: 0xfffa3203 RDX: 0x1fcbfbff
[CPUIDMON] TIME:1576079599.044358 VCPU:0 CR3:0x3108a002,"MemCompression" SessionID:-1. Leaf: 0x40000001. Subleaf: 0x0. RAX: 0x4000d RBX: 0x0 RCX: 0x0 RDX: 0x0
[CPUIDMON] TIME:1576079599.044546 VCPU:0 CR3:0x3108a002,"MemCompression" SessionID:-1. Leaf: 0x40000001. Subleaf: 0x0. RAX: 0x4000d RBX: 0x0 RCX: 0x0 RDX: 0x0
[CPUIDMON] TIME:1576079599.104029 VCPU:0 CR3:0x3108a002,"MemCompression" SessionID:-1. Leaf: 0x0. Subleaf: 0x0. RAX: 0xd RBX: 0x756e6547 RCX: 0x6c65746e RDX: 0x49656e69
[CPUIDMON] TIME:1576079599.104346 VCPU:0 CR3:0x3108a002,"MemCompression" SessionID:-1. Leaf: 0x1. Subleaf: 0x1. RAX: 0x406e3 RBX: 0x200800 RCX: 0xfffa3203 RDX: 0x1fcbfbff
[CPUIDMON] TIME:1576079599.104514 VCPU:0 CR3:0x3108a002,"MemCompression" SessionID:-1. Leaf: 0x2. Subleaf: 0x2. RAX: 0x76036301 RBX: 0xf0b5ff RCX: 0x0 RDX: 0xc30000
[CPUIDMON] TIME:1576079599.104669 VCPU:0 CR3:0x3108a002,"MemCompression" SessionID:-1. Leaf: 0x4. Subleaf: 0x4. RAX: 0x0 RBX: 0x0 RCX: 0x0 RDX: 0x0
[CPUIDMON] TIME:1576079599.104760 VCPU:0 CR3:0x3108a002,"MemCompression" SessionID:-1. Leaf: 0x5. Subleaf: 0x5. RAX: 0x0 RBX: 0x0 RCX: 0x0 RDX: 0x0
[CPUIDMON] TIME:1576079599.104875 VCPU:0 CR3:0x3108a002,"MemCompression" SessionID:-1. Leaf: 0x6. Subleaf: 0x6. RAX: 0x0 RBX: 0x0 RCX: 0x0 RDX: 0x0
[CPUIDMON] TIME:1576079599.105032 VCPU:0 CR3:0x3108a002,"MemCompression" SessionID:-1. Leaf: 0x7. Subleaf: 0x7. RAX: 0x0 RBX: 0x0 RCX: 0x0 RDX: 0x0
[CPUIDMON] TIME:1576079599.105189 VCPU:0 CR3:0x3108a002,"MemCompression" SessionID:-1. Leaf: 0x8. Subleaf: 0x8. RAX: 0x0 RBX: 0x0 RCX: 0x0 RDX: 0x0
```

**Comment by trapframe** [comment]
Thinking about it, per you request  i disabled the pagefile on the VM, will re-enable it and check it bugcheck again

**Comment by icedevml** [comment]
@trapframe Could you try with `-a memdump`? This will leave only `memdump` plugin activated without other plugins interferrence. Will it work correctly in such a case?

**Comment by tklengyel** [comment]
@trapframe if you are re-running DRAKVUF on the same VM several times there is a bug that's known to cause in-guest BSOD, we just haven't been able to track it down so far. It seemed to only get triggered by listening to the CR3 register writes though, so if you had plugins active that used that, just disable those.

**Comment by icedevml** [comment]
Yes, these plugins typically are `dkommon` and `crashmon`, so either use `-a memdump` to have only memdump plugin activated for testing or use `-x dkommon -x crashmon` to disable the ones known for causing problems in such case.

Also please try to reload snapshot/re-run VM before running DRAKVUF.

**Comment by trapframe** [comment]
@tklengyel nope, each time i run drakvuf it is on a fresh VM instance
@icedevml i did run it with -a memdump , and still get the BSOD

i re-enabled pagefile but still get BSOD (without memdump).

And still the same last outputs are related to memory compression, so no coincidence here i think, will check if this feature can be disabled:

```
[CPUIDMON] TIME:1576081519.386572 VCPU:1 CR3:0x3108a002,"MemCompression" SessionID:-1. Leaf: 0x1. Subleaf: 0x0. RAX: 0x406e3 RBX: 0x2200800 RCX: 0xfffa3203 RDX: 0x1fcbfbff
[CPUIDMON] TIME:1576081519.386954 VCPU:1 CR3:0x3108a002,"MemCompression" SessionID:-1. Leaf: 0x40000001. Subleaf: 0x0. RAX: 0x4000d RBX: 0x0 RCX: 0x0 RDX: 0x0
[CPUIDMON] TIME:1576081519.387126 VCPU:1 CR3:0x3108a002,"MemCompression" SessionID:-1. Leaf: 0x40000000. Subleaf: 0x0. RAX: 0x40000005 RBX: 0x566e6558 RCX: 0x65584d4d RDX: 0x4d4d566e
[CPUIDMON] TIME:1576081519.387326 VCPU:1 CR3:0x3108a002,"MemCompression" SessionID:-1. Leaf: 0x1. Subleaf: 0x0. RAX: 0x406e3 RBX: 0x2200800 RCX: 0xfffa3203 RDX: 0x1fcbfbff
```

**Comment by tklengyel** [comment]
It's odd that you get CPUIDMON output when you run just with `-a memdump`. The cpuidmon plugin shouldn't have got activated O.o

**Comment by trapframe** [comment]
no, the CPUIDMON output was when i disabled memdump through  "configure"

Anyway problem is solved (well at least bypass), BSOD are related to the new memory compression stuff in windows 10.

I disabled the memory compression through the powershell command 

> Disable-MMAgent -m

![image](https://user-images.githubusercontent.com/9018546/70642116-fb6d0f00-1c3e-11ea-8c9f-8e48a795e83f.png)

after a reboot , no more BSOD, even with MEMDUMP running :)
And Dll hooking is working !

**Comment by trapframe** [comment]
One last thing, when running Get-MMAgent we can see a line with:
PageCombining : True

it refers to this feature :

> Specify the PageCombining parameter to help reduce the physical memory that the operating system uses. Page combining causes the memory manager to periodically combine pages in physical memory that have identical content.

I m not sure if this feature can have side effect with introspection, but in doubt i have decided to disable it as well through 

> Disable-MMAgent -PageCombining

Just in case ...

**Comment by tklengyel** [comment]
It likely could affect introspection. Say page A and B have the same contents and you have breakpoints only on B. Then the page-merging kicks in an discards B and remaps it to A. Now your breakpoints are on an unmapped page so you would not get the callbacks. Or worse, page B could get reused somewhere else and you would get unrelated events.

It's the same issue with the pagefile. If something you are monitoring gets paged out and then brought back in at another location, your breakpoints would still be at the old physical location. Unless we want to implement logic that tracks these systems internals and reconstruct when pages are being moved so we can move the breakpoints with them, the only option is to disable them. Unfortunately since these are all on by default, disabling them also makes the environment more prone to be fingerprinted as an analysis sandbox.
