### ISSUE TITLE
How to inject break points in Linux machine

### ISSUE THREAD

**Issue by Preetixen** [tklengyel/drakvuf#76]
The DRAKVUF Paper explains very well about the break point injection techniques at windows by parsing the guest os symbol file and injecting break points.

How does break point injection technique works in linux machines? Can you provide me some detail information.

Thanks

**Comment by tklengyel** [comment]
The breakpoint injection method is OS agnostic, it would work with anything running in the VM. The only thing you need is the address to inject the breakpoint to, so in this case the debug information for the Linux kernel you are inspecting. This is something I've already started working (see https://github.com/libvmi/libvmi/pull/313) and should be available soon in DRAKVUF.

**Comment by Preetixen** [comment]
Hi,

How are you? its long time talking you.
If have you have made any enhancement to trap Linux syscalls??

**Comment by tklengyel** [comment]
I'll update this ticket when there is some development in this regard.

**Comment by Preetixen** [comment]
Hello,
Is there any updation in drakvuf to support linux VM for trace extraction as supported by Xenini-IDS

**Comment by tklengyel** [comment]
#226 implemented Linux support so I'm closing this issue.

**Comment by Preetixen** [comment]
Hi

With reference to #226, can you please provide the commands and instructions for Linux syscall trapping for required programs as provided in https://drakvuf.com/ for windows syscalls.

Thanks
