### ISSUE TITLE
system restarts in between after running DRAKVUF two three times

### ISSUE THREAD

**Issue by Preetixen** [tklengyel/drakvuf#78]
Hi i am facing a problem in usage with DRAKVUF..

I was collecting traces of processes. I tried this command two three times for collecting traces of all processes. Output was comming.
But after sometime drakvuf does not give the trace and system automatically restarts

**Comment by tklengyel** [comment]
It could happen that the system crashed. DRAKVUF does not currently detect this case. You should change your domain config that on crash the domain should be destroyed instead of restarted to prevent any malware getting activated in it on reboot without tracing.
