### ISSUE TITLE
Host Crash while monitor win10

### ISSUE THREAD

**Issue by meowwoem1** [tklengyel/drakvuf#785]
Hello. While trying to monitor win10 with Drakvuf, the system crashes suddenly.(system where drakvuf running - ubuntu)
I couldn't see any log

in addition there is very low performance status in windows10. I have disabled spectre protection but still poor performence.

**Comment by tklengyel** [comment]
You will have to provide more information in order for us to try to help you. By host crash you mean the actual host system where you run DRAKVUF crashed? Did Xen crash or your operating system? Without obtaining the logs there isn't really anything we can tell you other than that "it works for me".
