### ISSUE TITLE
Process Blacklist

### ISSUE THREAD

**Issue by meowwoem1** [tklengyel/drakvuf#786]
Hello. The system applications of windows during the monitor have a lot of processing and therefore there is a poor performance problem.

Can blacklist application list be included in drakvuf?
For example, dont add a breakpoint for dwm.exe.

**Comment by tklengyel** [comment]
I think you have the wrong idea about how the system monitoring works with DRAKVUF. Most plugins don't monitor specific processes, they monitor the kernel itself. If you have a lot of plugins enabled then each will add overhead as they monitor separate aspects of the kernel's execution. You have to decide which of the plugins you actually need and disable the ones you don't.
