### ISSUE TITLE
Move usermode-hooking functionality out of memdump to libdrakvuf

### ISSUE THREAD

**Issue by icedevml** [tklengyel/drakvuf#787]
Split `memdump` into `memdump` and some other usermode plugins, move core functionality of usermode hooking into `libdrakvuf`.

**Comment by icedevml** [comment]
@tklengyel As far as I see, for now it would be easiest to create `usermode` plugin which would provide the core functionality and then some other plugins would depend on it? I wonder if you would be fine with such solution as per now AFAIK there are no such dependencies between plugins.

The deal is that current implementation strongly depends on `pluginex` features which would be not available if moved into libdrakvuf. We need to hook some syscalls and do some pretty expensive stuff before usermode can be actually hooked. When debugging, it would cause massive headache if each usermode-related plugin would do setup on its own instead of using shared setup.

This would cause that plugins like `apimon` (WinAPI monitoring) or `memdump` would check if `usermode` is loaded and if so, would ask it to hook some DLLs.

How do you feel about such solution?

**Comment by tklengyel** [comment]
> dependencies between plugins

I would like to avoid that as much as possible, the idea of plugins is that you can easily turn them off and only pick the one you need.

> The deal is that current implementation strongly depends on pluginex features which would be not available if moved into libdrakvuf.

The usermode hooking stuff would be fine to be a similar deal to `pluginex`, being a feature plugins can subscribe to if they want to.

**Comment by icedevml** [comment]
@tklengyel Sure, I will try to implement it within libdrakvuf then.

**Comment by tklengyel** [comment]
What I meant was it doesn't have to be in libdrakvuf itself, it could be next to pluginex.
