### ISSUE TITLE
Error while get submodule

### ISSUE THREAD

**Issue by darkbytex1** [tklengyel/drakvuf#789]
I got error while get libvmi 
(git submodule update)
error: Server does not allow request for unadvertised object aed296eac5d232c9dfd099a07894e729029cd5cf
Fetched in submodule path 'libvmi', but it did not contain aed296eac5d232c9dfd099a07894e729029cd5cf. Direct fetching of that commit failed.

**Comment by tklengyel** [comment]
Thanks for reporting the issue, not really sure what happened but it should be resolved now.

**Comment by icedevml** [comment]
We hit the same just today, I wonder how GitHub was able to display the commit successfully but it was not actually attached to anything? Maybe it was related to some branch, but then the branch was deleted but the submodule link remained?

**Comment by tklengyel** [comment]
Yea, I was wondering the same thing. That's why I always update the LibVMI submodule to the master branch, so that even if a feature-branch gets merged and deleted the submodule isn't pointing to something non-existent.
