### ISSUE TITLE
identifier error while make

### ISSUE THREAD

**Issue by darkbytex1** [tklengyel/drakvuf#791]
I tried install drakvuf but i got the error
```
socketmon/socketmon.cpp:882:24: error: use of undeclared identifier 'get_winver'; did you mean
      'get_win_ver'?

socketmon/socketmon.cpp:882:35: error: cannot initialize a parameter of type 'drakvuf_t' (aka 'drakvuf *')
      with an lvalue of type 'vmi_instance_t' (aka 'vmi_instance *')
```

**Comment by tklengyel** [comment]
Make sure you are using the latest LibVMI from the submodule: `git submodule update --init libvmi`

**Comment by darkbytex1** [comment]
yes. actually i got same error after new clone

**Comment by tklengyel** [comment]
Well, to me this definitely look like an error on your side because the code compiles just fine through the CI system and on a lot of other people's setup. I would suggest that you grab a pre-compiled package from https://github.com/tklengyel/drakvuf-builds/releases instead.

**Comment by tklengyel** [comment]
Do you still have the error?
