### ISSUE TITLE
File Push via Drakvuf

### ISSUE THREAD

**Issue by kaboreka** [tklengyel/drakvuf#802]
How can i upload any file to running VM with Drakvuf? Is it possible?

**Comment by tklengyel** [comment]
No, we don't provide such functionality. There is experimental support to injecting an executable directly into memory but it hasn't been tested in a while. You can of course just use whatever tool you would normally use to download a file into the VM.

**Comment by icedevml** [comment]
My workflow is that I just restore the VM from snapshot and execute:
```
xl qemu-monitor-command domain_name "change ide1-cd0 /tmp/dsl-4.4.10.iso"
```
this would mount a fake CD from the specified ISO path. You need to know the device name (usually different than `ide1-cd0`), to determine it:
```
xl qemu-monitor-command domain_name "info block"
```

This is pretty hacky/low level but works pretty well for me.
