### ISSUE TITLE
socketmon tcp_endpoint struct creation

### ISSUE THREAD

**Issue by chengsteven** [tklengyel/drakvuf#803]
Do you have any direction in how are the current `tcp_endpoint*` structs are created in `socketmon/private.h`?

**Comment by tklengyel** [comment]
They were reverse engineered by the Volatility folks, the structure layouts defined here are based on https://github.com/volatilityfoundation/volatility/blob/aa6b960c1077e447bda9d64df507ec02f8fcc958/volatility/plugins/overlays/windows/tcpip_vtypes.py

**Comment by chengsteven** [comment]
Thanks!
