### ISSUE TITLE
Ability to modify returns of function

### ISSUE THREAD

**Issue by icevmi001** [tklengyel/drakvuf#805]
Hi Is it possible to modify return values of function during a call back? For example, how would you go about returning zero delay if delaymon picked up a malware trying to sleep for a certain period of time?

Thanks!

**Comment by icedevml** [comment]
@icevmi001 The example you've provided would be about passing zero argument to the delay function, rather than changing the return value of function.

Looking at this code:
https://github.com/tklengyel/drakvuf/blob/master/src/plugins/delaymon/delaymon.cpp#L7

```cpp
        if ( VMI_FAILURE == vmi_read_64(vmi_lg.vmi, &ctx, reinterpret_cast<uint64_t*>(&delay)) )
```

if you would replace this `vmi_read_64` with `vmi_write_64` and override the memory cell which contains the delay value before the function gets called, the delay should be ignored.

I don't really know if this would be really sufficient and how Windows would behave if you would override ALL possible delays ;)

**Comment by icevmi001** [comment]
@icedevml 

Yeah that's exactly what I'm looking for. I'm guessing since the callback still have context to the pid/process I can execute the write base on which process called it right? Do you have an example of overriding the memory cell that you describe. Thanks for the quick reply and info!

**Comment by icedevml** [comment]
Yes, the `vmi_read` I've mentioned above has the argument `ctx` which contains some information about process context. This reads the function's argument right from the stack and this is a perfect moment for you to modify it, if you wish. Thus, you may just add `vmi_write` and tamper it.

**Comment by icevmi001** [comment]
This should perform it correctly right?

`
int64_t newDelay = 1;
vmi_write_64(vmi_lg.vmi, &ctx, reinterpret_cast<uint64_t*>(newDelay)
`

This causes a segfault for me instead. Any recommendation or am I missing anything here? Thanks again!

**Comment by icevmi001** [comment]
I was able to successfully change the parameter to zero. However, a sleep function seems to just keep sleeping and spamming NtDelayExecution. Do I have to bp on this sleep userhook then to modify and remove the sleep time?

Thanks

**Comment by tklengyel** [comment]
Why not just skip the function call completely? You can move the instruction pointer ahead and just put whatever you want in RAX as if the function finished and returned.

**Comment by xSalice** [comment]
Is there example of that somewhere @tklengyel. If there's somewhere in the API that already does that, would be awesome to see!

**Comment by icevmi001** [comment]
Hi @tklengyel. Thanks for the suggestion. How would you implement the write_vmi to move ahead and replace RAX? Any reference you can link me too?

**Comment by icedevml** [comment]
@icevmi001 Replace this line:

https://github.com/tklengyel/drakvuf/blob/b082a337844bab145317c2a40ac9d4982382b133/src/plugins/delaymon/delaymon.cpp#L80

with

```cpp
    // emulate `ret` instruction
    addr_t saved_rip = 0;
    access_context_t ctx =
    {
        .translate_mechanism = VMI_TM_PROCESS_DTB,
        .dtb = info->regs->cr3,
        .addr = info->regs->rsp,
    };

    vmi_instance_t vmi = drakvuf_lock_and_get_vmi(drakvuf);
    bool success = (VMI_SUCCESS == vmi_read(vmi, &ctx, sizeof(addr_t), &saved_rip, NULL));
    drakvuf_release_vmi(drakvuf);

    if ( !success )
    {
        PRINT_DEBUG("error while reading rsp\n");
        return VMI_EVENT_RESPONSE_NONE;
    }

    info->regs->rip = saved_rip;
    info->regs->rsp += sizeof(addr_t);
    info->regs->rax = 0;
    return VMI_EVENT_RESPONSE_SET_REGISTERS;
```

reference:
https://github.com/tklengyel/drakvuf/blob/a09ff34c8230cb7c3a5b97fc44841e637da12db7/src/plugins/memdump/userhook.cpp#L770

**Comment by tklengyel** [comment]
On Windows you have to adjust the stack more (info->regs->rsp), even inputs that are passed via registers get a space on the stack (called homing space). So the above would work if the function took no inputs, but otherwise the stack may get misaligned on return.

See for a reference how the stack gets setup in https://github.com/tklengyel/drakvuf/blob/master/src/libinjector/injector_stack.c#L290

**Comment by tklengyel** [comment]
Oh, and it would also be possible to `emulate ret` by actually using Xen's built-in emulator. You can return the opcode for ret in the `vmi_event_t`'s `emul_insn->data` field and set the response to VMI_EVENT_RESPONSE_SET_EMUL_INSN. Might just be the simplest approach.

**Comment by icedevml** [comment]
> So the above would work if the function took no inputs, but otherwise the stack may get misaligned on return.

It depends on the calling convention. If it's a caller clean-up then it would work and if no, then I agree that the above code has to be modified to fix the stack accordingly.

**Comment by icevmi001** [comment]
I've tried to implement it, but it seems to still sleep and call NtDelayExecution for many many iteration.

As for setting up the stack, it seems like I'm getting (pushing two args to the stack):
```
*** stack smashing detected ***: <unknown> terminated
```

@tklengyel I'm totally confused on how to emulate that response based on drakvuf structure. Can you elaborate more on this feature and its usage?

**Comment by icedevml** [comment]
@icevmi001 Could you put your code on some branch/fork/whatever and show it here?

**Comment by hexaphil** [comment]
> I've tried to implement it, but it seems to still sleep and call NtDelayExecution for many many iteration.
> 
> As for setting up the stack, it seems like I'm getting (pushing two args to the stack):
> 
> ```
> *** stack smashing detected ***: <unknown> terminated
> ```
> 
> [@tklengyel](https://github.com/tklengyel) I'm totally confused on how to emulate that response based on drakvuf structure. Can you elaborate more on this feature and its usage?

It might be too late , so for those who are still wondering
```
static event_response_t trap_NtDelayExecution_cb(drakvuf_t drakvuf, drakvuf_trap_info_t* info)
{
    std::string proc_name_full(info->proc_data.name);
    std::string proc_name_short = proc_name_full.substr(proc_name_full.find_last_of("/\\")+1);
	
	vmi_event_t event = drakvuf_get_interrupt_event(drakvuf); // define a helper function to obtain an event in libdrakvuf/drakvuf.c (drakvuf->interrupt_event)
	
	if (proc_name_short != "explorer.exe" && proc_name_short != "conhost.exe" && proc_name_short != "SearchIndexer.exe" && proc_name_short != "SearchProtocolHost.exe")
    {

           event.emul_insn->data[0] = 0xC3;
           return VMI_EVENT_RESPONSE_SET_EMUL_INSN;

    } else { return 0; }
```
