### ISSUE TITLE
Time out during the automated malware analysis

### ISSUE THREAD

**Issue by alexandrafengfei** [tklengyel/drakvuf#81]
Hi. I did what "automated malware analysis setup" says with the latest version of drakvuf whose main.cpp has been fixed. However, after the execution of preconfig.sh, it shows "failed to execute on  domid because of a time out, creating new clone". Then the creation of new clone repeats. 
Is this timeout because of apache2? The apache2 seems not working well with Ubuntu. I did what https://log.axcoto.com/article/164442852 tells, but I am not sure this really works out or not.
Btw, should I change the "MrX" to my username in the preconfig.sh?

**Comment by tklengyel** [comment]
Of course, you need to tweak these scripts to match your setup. These are just included as samples on how to approach setting things up. You should first test each manually to see if it works before doing it automatically.

**Comment by alexandrafengfei** [comment]
I see. Would please tell me when is the apache2 used during the automated analysis? I am trying to figure out whether the timeout is caused by apache2 or not.

**Comment by tklengyel** [comment]
It's only used to transfer the malware sample go the vm. You can use any other method for that, like tftp, nfs or even a samba share.
