### ISSUE TITLE
How CPU is configured to trap to hypervisor not toguest os on occurrence of a syscall

### ISSUE THREAD

**Issue by Preetixen** [tklengyel/drakvuf#82]
could you please clear this concept.

"How CPU is configured to trap to hypervisor not to guest os on occurrence of a syscall?"

Have you done some change in do_guest_trap() (file
xen/arch/x86/traps.c ) so that you can collect the information related to the process generating the trap?
What changes are done in the trap file to collected system call data.

**Comment by Preetixen** [comment]
I read in some paper:
SYSCALL-based System Calls. System calls may also be implemented using
the SYSCALL instruction and its analogue counterpart SYSRET. Both of these
rely on a set of MSRs, namely STAR MSR, CSTAR MSR, and LSTAR MSR.
Exactly which of these registers is used depends on whether the guest OS is
running in legacy, long, or compatibility mode. Additionally, this mechanism
can effectively be turned on and off by setting and unsetting the SCE 
flag in the Extended Feature Enable Register (EFER). Making use of either SYSCALL
or SYSRET with the SCE  flag not set results in an invalid opcode exception. which can be traped at hypervisor.


is this same with drakuf?

**Comment by Preetixen** [comment]
As i read from your paper. That int 0xcc instructions are written in the vm memory which causes VM_EXIT and trap to hypervisor. 

1. How this trap is handled? could you please locate me the file path and what code is written on occurrence on int 3 interrupt? How the process resumes its execution after this interrupt? 

2. After determining the location of kernel function, int 3 can be used to trap the functions. I am not getting this concept.
where this int 3 is injected in memory and how a full trace is obtained for a process?

**Comment by tklengyel** [comment]
Xen had native support for enabling trapping software debug exceptions into the VMM. It's done by setting the corresponding bits in the VMCS of each vCPU of the guest. You are welcome to read the source-code of Xen (see http://xenbits.xen.org/gitweb/?p=xen.git;a=blob;f=xen/arch/x86/hvm/vmx/vmx.c;h=44e778fa7164a725fa759c2c32eacb36690329af;hb=refs/heads/master#l1249).

When Xen gets such VMEXITs (http://xenbits.xen.org/gitweb/?p=xen.git;a=blob;f=xen/arch/x86/hvm/vmx/vmx.c;h=44e778fa7164a725fa759c2c32eacb36690329af;hb=refs/heads/master#l3184) it uses the vm_event subsystem to forward it to the listener (LibVMI) which then calls DRAKVUF. You can follow the flow of code from the link.

The int3 is written in memory at the start of each function, not after. Not sure what you mean by "full trace of a process".

**Comment by Preetixen** [comment]
full trace of a process I mean : a sequence of system calls invoked by a process

**Comment by tklengyel** [comment]
Well, the syscall plugin writes int3 into each kernel function responsible for handling system calls. So that way it gets a full trace of what system calls are issued.

**Comment by Preetixen** [comment]
int 3 is written at the start of each function. It means when a kernel function is invoked; a trap will be generated which will transfer control to xen.

then what are steps then xen is performing to get the trace of system calls. (again how the system calls are executed if kernel function is still after trap instruction and hence not executed)

**Comment by tklengyel** [comment]
Xen doesn't care/know if it's a system-call or anything else. All it knows is that a software debug exception occured and let's the listener decide what to do next. If there is no listener it reinjects the exception into the guest. The listener can also tell Xen to do that (in case an in-guest debugger is using int3's). Afterwards to allow the original instruction to execute DRAKVUF now uses altp2m, where a clean copy of the memory page exists without the injected int3's. DRAKVUF simply tell's Xen to use that altp2m view for a duration of a singlestep, which allows the guest OS to fetch the instruction from memory and continue executing. After the singlestep we switch back to the trapped altp2m view, so we still get subsequent traps on the vCPU.

**Comment by tklengyel** [comment]
I've written a blog post for Xen about this part, unfortunately it still haven't been posted yet but you can read it at http://lists.xenproject.org/archives/html/publicity/2016-01/msg00009.html.

**Comment by Preetixen** [comment]
okie thanks..

can i know more about altp2m.

**Comment by tklengyel** [comment]
Read that blog post or read the Xen source. That's all there is that's available on it right now.

**Comment by Preetixen** [comment]
The code written in 
 http://xenbits.xen.org/gitweb/?p=xen.git;a=blob;f=xen/arch/x86/hvm/vmx/vmx.c;h=44e778fa7164a725fa759c2c32eacb36690329af;hb=refs/heads/master#l1249).

When Xen gets such VMEXITs (http://xenbits.xen.org/gitweb/?p=xen.git;a=blob;f=xen/arch/x86/hvm/vmx/vmx.c;h=44e778fa7164a725fa759c2c32eacb36690329af;hb=refs/heads/master#l3184) 
is quite complex. A number of time int3 and vm_exit repeated.

could you please paste here only specific modules or code
1. responsible for causing software debug (int 3) and writing corresponding entry into VMCS of vcpu
2. responsible for causing VM_exit
3. responsibe (VM_event) subsystem which calls to libvmi on each software debug exception
4. So libvmi will call to drakvuf if the software debug is because of int 3? otherwize will inject a exception in guest vm?

**Comment by tklengyel** [comment]
"could you please paste here only specific modules or code".

Sorry, no. You are welcome to read the code and do your best to understand what it does. If you have questions about it, feel free to try to get help on the xen-devel mailinglist. I'm closing this ticket as I have answered your DRAKVUF related questions here already.

**Comment by Preetixen** [comment]
ok thanks..i will  try..
