### ISSUE TITLE
Rewrite OUTPUT_JSON printouts to use json-c library

### ISSUE THREAD

**Issue by icedevml** [tklengyel/drakvuf#832]
Right now, most of JSON printouts is glued manually using `printf`, which is very prone to syntax errors.

`OUTPUT_JSON` printouts should be rewritten to use json-c which is both more readable and simpler to use, e.g.:
https://github.com/tklengyel/drakvuf/blob/f7fa4b84899a1f5b830c73ac3f50398421011e88/src/plugins/memdump/memdump.cpp#L136

**Comment by manorit2001** [comment]
This is an old issue and almost all of the plugin codes are now using `fmt` plugin, but some codes are still using `jsonfmt`, `kvfmt` despite having a generic `fmt` handler. I was thinking of working on this to refactor this a bit but I am seeing weird `if` conditions which I don't really know why they exist. 
For e.g
https://github.com/tklengyel/drakvuf/blob/a26e57ec5e589502c521db9007d00a37c5231aea/src/plugins/debugmon/debugmon.cpp#L143-L167
In this, when the format is `OUTPUT_JSON` we are print extra info (`VCPU`, `CR3`) but on other formats, we are omitting it. Is this the desired working? If yes, then isn't the term `OUTPUT_JSON` kinda misleading as it is somehow containing some other information that makes it like `OUTPUT_DEBUG` or `OUTPUT_VERBOSE` in json format?

**Comment by tklengyel** [comment]
Yea, would be better to have the same info printed in all formats. Feel free to fix inconsistencies like that.
