### ISSUE TITLE
how to get the task_struct of current process in user mode?

### ISSUE THREAD

**Issue by GameCaretaker** [tklengyel/drakvuf#839]
i want to use drakvuf to monitor the function in user mode.but after i traped the PA,the output tell me that process name is null.
then i read the linux-process.c, drakvuf find current process data with rsp rigisters. but in user mode ,it doesn't seems to work.
so how can i find the task_struct in user mode?if you give me some advice, i will be really grateful to you .

and····hmmmm，in new libvmi ,if vmi_process_list cannot work, please comment out the Line 569 code in core.c.

**Comment by GameCaretaker** [comment]
hmmmmm····well,we can find TSS by tr registers.and in TSS,we can find the address of kernel base.However,which one is tr register in libvmi.h?

**Comment by tklengyel** [comment]
Using `drakvuf_get_current_process` will get your the current task_struct. If it doesn't work for you for some reason, enable the debug messages and post the output here. Also the details for the Linux VM, kernel version, kpti enabled, etc.

**Comment by GameCaretaker** [comment]
linux process has two stacks.one is in user space,and the other is in kenel space.When process run in user mode, the address in rsp is the address of user stack.The function drakvuf_get current_process has only provided a funtion to get thread_info in kernel mode.

**Comment by GameCaretaker** [comment]
When linux switch user mode to kernel mode.it will find the pointer of kernel stack from TSS.the register TR store the pointer point to the  TSS of current CPU.

**Comment by tklengyel** [comment]
I looked into this but getting the process name while in userspace doesn't depend on having the kernel stack. What we need is the correct gs, ie while in userspace use the shadow_gs. There is a fallback method that does search the stack for extra information if that doesn't work but AFAICT as of 5.4 kernel it's never needed. I can get the correct process name every time for a trap triggered from userspace.

As for getting the tss, you can get that by reading the `TR_BASE` register using `vmi_get_vcpureg`, which will point to a  `x86_hw_tss` structure, and there `sp0` or `sp1` field will have the kernel stack. But again, what you need to find is not the kernel stack but the process base address.
