### ISSUE TITLE
Windows blue screen after xl restore when there are more than one vcpu

### ISSUE THREAD

**Issue by alexandrafengfei** [tklengyel/drakvuf#84]
Hi. After I restore my windows 7 vm by xl restore, it went into blue screen.
Then I found this link. http://www.novell.com/support/kb/doc.php?id=7000036, which says "Windows queries a register on the front side bus in order to determine whether or not there are multiple processors. In some cases fully-virtual Windows machines, especially Windows Server 2003 R2, will load up only to blue screen later in the load process". So I changed the number of vcpu in the conf file to 1 and the problem is solved. 
I suppose this is a problem in xen. However, drakvuf supports multiple vcpu in guest vm, right?

**Comment by tklengyel** [comment]
DRAKVUF supports multiple-vCPUs, yes. This doesn't seem to be an issue with DRAKVUF though so I'm closing it. You should probably try to gather as much information about the state of the VM and ask for help on the xen-users mailinglist.
