### ISSUE TITLE
command to execute multiple malware files

### ISSUE THREAD

**Issue by Preetixen** [tklengyel/drakvuf#85]
Hi i am facing a problem in trace collection.

since guest OS hangs on each run of drakvuf command.

It is difficult for me to take traces of around 1000 malware files.

Is there any way to execute all malwares and get the traces in a few commands??

**Comment by tklengyel** [comment]
There is no single command to that. You should read the Wiki, there are some tips on how to setup an automated loop to analyze malware in bulk.
