### ISSUE TITLE
Does Drakvuf monitor reading, writing and deleting in Windows Registry?

### ISSUE THREAD

**Issue by alexandrafengfei** [tklengyel/drakvuf#86]
Hi. I would like to ask does Drakvuf monitor reading, writing and deleting in Windows Registry?
I find syscall-NtGetMUIRegistryInfo and poolmon-Registry query buffer in my log file. Does Drakvuf monitors where (/HKEY..., I mean) the reading, writing and deleting happened in Windows Registry?

**Comment by tklengyel** [comment]
Right now there is no plugin that monitors registry accesses directly but it could be implemented.
