### ISSUE TITLE
Getting System Call parameters from Windows guest

### ISSUE THREAD

**Issue by willow19** [tklengyel/drakvuf#88]
I am running Drakvuf on a Ubuntu host. I want to extract System Call parameters from a Windows 7 SP1 guest. How should I approach this?

**Comment by tklengyel** [comment]
This is not yet implemented. The system call prototypes are already defined in a header at https://github.com/tklengyel/drakvuf/blob/master/src/plugins/syscalls/scproto.h, so what you would have to do is use this information to grab the parameters at runtime in the syscall plugin from the stack/registers. It will require writing extra code in the plugin.

**Comment by willow19** [comment]
Thanks!
