### ISSUE TITLE
LibVMI fails altp2m requests

### ISSUE THREAD

**Issue by JordanBoulan** [tklengyel/drakvuf#889]
The output i get is this:

sudo drakvuf -d 2 -r /home/jade/win10.json

```
1590094514.702309 DRAKVUF v0.7-git20200519164913+aa3625d-1 Copyright (C) 2014-2020 Tamas K Lengyel
VMI_ERROR: xc_altp2m_switch_to_view returned rc: -1
VMI_ERROR: xc_altp2m_set_domain_state returned rc: -1
Failed to initialize DRAKVUF: drakvuf_init() failed
```

This appears to be related to libvmi, however my libvmi is working, I can list processes etc.

This is where the error is thrown...

```
 rc = xen->libxcw.xc_altp2m_switch_to_view (xch, domain_id, altp2m_idx );
    if ( rc ) {
        errprint ("xc_altp2m_switch_to_view returned rc: %i\n", rc);
        return VMI_FAILURE;
    }
```

Is this an error on my end? Does anyone here know?

**Comment by icedevml** [comment]
> rc prints as -1 but for some reason the if evaluates as true

such if would evaluate as true whenever `rc != 0` and this is normal in C++; these functions return `rc=0` on success and the error code otherwise

**Comment by icedevml** [comment]
Have you installed Xen according to the instructions on drakvuf.com? Also, do you have `altp2m = 2` in your domain config?

**Comment by icedevml** [comment]
Also, I'm pretty not sure about that but it looks like `-1` error code is returned by these lines:
https://github.com/xen-project/xen/blob/437211cb696515ee5bd5dae0ab72866c9f382a33/tools/libxc/xc_altp2m.c#L150-L152
which would basically mean that the memory allocation (on your host system) has failed.

**Comment by tklengyel** [comment]
Yeap, the hypervisor would return -22 (`-EINVAL`) if the hypercall didn't work at https://github.com/xen-project/xen/blob/16bbf8e7b39b50457bb2f6547f166bd54d50e4cd/xen/arch/x86/mm/p2m.c#L2347 so that -1 is coming from libxc

**Comment by JordanBoulan** [comment]
Thanks for taking a look and your quick response. I guess the default grub boot commands didn't take, after making sure xen was passed altp2m on boot im getting the following:

```
1590172531.888474 DRAKVUF v0.7-git20200519164913+aa3625d-1 Copyright (C) 2014-2020 Tamas K Lengyel
xc: error: Failed to populate ring pfn
 (16 = Device or resource busy): Internal error
VMI_ERROR: vm_event is (or was) active on this domain
Failed to init LibVMI library.
Failed to initialize DRAKVUF: drakvuf_init() failed
```

**Comment by tklengyel** [comment]
`VMI_ERROR: vm_event is (or was) active on this domain`

That happens if you run DRAKVUF on a domain and exit without properly shutting down things, like if you issue `kill -9` to the process. You should just restart the domain.

**Comment by tklengyel** [comment]
Also, for an VM with 8GB RAM your shadow_memory setting is likely going to be very low. You probably want to at least double it.

**Comment by JordanBoulan** [comment]
This error seems to happen even after a fresh reboot.

Reboot VM, run drakvuf -r ... -d ...

Still get the same error. Thanks, I upped the shadow memory.
