### ISSUE TITLE
Segmentation Fault on running Drakvuf

### ISSUE THREAD

**Issue by willow19** [tklengyel/drakvuf#90]
I am getting a Segmentation Fault (core dumped) on running ./drakvuf since the cpp update. Should there be any change in the installation instructions for this?

**Comment by Preetixen** [comment]
Hi, i want to ask you something as yu are also working on drakvuf:
Have you ever faced this problem;


/drakvuf$ sudo ./src/drakvuf -r /root/windows7-sp1.rekall.json -d 2
DRAKVUF v0.2
Init VMI on domID 2 -> windows7-sp1
Rekall profile: '_KPCR' has no 'PrcbData' member
Failed to find offset for _KPCR:PrcbData
VMI_ERROR: Error -1 setting HVM single step
Reservation increased? 0 with new gfn: 0x5cb25
Xen altp2m view created with idx: 1 idr: 2

**Comment by Preetixen** [comment]
in my case to system suddenly restarted on running ./drakvuf

**Comment by willow19** [comment]
Not same @Preetixen. In my case ./drakvuf just crashes giving me a "Segmentation Fault (core dumped)". ./injector is working fine though.

**Comment by Preetixen** [comment]
./src/drakvuf -r /root/windows7-sp1.rekall.json -d 2
DRAKVUF v0.2
Init VMI on domID 2 -> windows7-sp1
Rekall profile: '_KPCR' has no 'PrcbData' member
Failed to find offset for _KPCR:PrcbData
VMI_ERROR: Error -1 setting HVM single step
Reservation increased? 0 with new gfn: 0x5cb1e
Xen altp2m view created with idx: 7 idr: 8
Segmentation fault (core dumped)

this is what i am getting

**Comment by tklengyel** [comment]
The only change since the C++ switch is the requirement to install clang. Also, make sure you are doing a clean build. If you are getting a segfault, the best way to figure out why is if you run it through gdb. It will tell you where exactly it crashes. It works fine on all my systems with git head so I'm not able to reproduce the issue on my side.

**Comment by willow19** [comment]
I got this output in GDB:
**Starting program: /home/rachit/drakvuf/src/drakvuf -r /root/window.json -d 12
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
DRAKVUF v0.2

Program received signal SIGSEGV, Segmentation fault.
drakvuf_get_symbols_from_rekall (rekall_profile=<optimized out>)
    at win-symbols.c:241
241	        ret->symbols[i].name = g_strdup(json_object_iter_peek_name(&it));
**
What could it mean?

**Comment by v-p-b** [comment]
Since we're getting a SEGFAULT it's possible that `ret->symbols` is overindexed, there are no explicit checks about this in the code (although the JSON lib may take care of this). 

You should check your Rekall profile (/root/window.json - wild guess: isn't there an 's' missing from the filename?).

**Comment by tklengyel** [comment]
If it segfaults there then something might be wrong with your rekall profile. The peek_name function must be returning NULL, and running strdup on it is causing the fault. Its very odd that it even gets that far if the profile is faulty though. Or it may be what @buheratot suggests, but then I would expect it would fail for everyone, not just you..

**Comment by willow19** [comment]
An older drakvuf (the C one) version is running fine on the same Rekall profile.

**Comment by tklengyel** [comment]
Can you send me the profile?

**Comment by willow19** [comment]
[window.json.txt](https://github.com/tklengyel/drakvuf/files/152624/window.json.txt)

**Comment by tklengyel** [comment]
It's pretty odd, I'm unable to reproduce the problem you have on my side with this profile. Make sure you build a recent version of LibVMI as well when you update DRAKVUF to git head.

**Comment by willow19** [comment]
Not updating LibVMI was the reason. Thanks!
