### ISSUE TITLE
Drakvuf not work on Win10

### ISSUE THREAD

**Issue by kobirona** [tklengyel/drakvuf#906]
Hi, I tried use drakvuf on windows 10 vm (i disabled meltdown & spectre protection) but when i start drakvuf , vm goes to freeze.
```
1593167416.149328 DRAKVUF v0.7-git20200623132954+c4a3bde-1 Copyright (C) 2014-2020 Tamas K Lengyel
1593167416.149408 Starting DRAKVUF initialization
1593167416.149427 drakvuf_init: Rekall WoW64 profile not used
1593167416.149962 drakvuf_event_fd_add fd=14
1593167416.149986 size of list=1
1593167416.149995 regenerating event_fds and fd_info_lookup...
1593167416.150004 new event_fd i=0 for fd=14
1593167416.150021 new fd_info_lookup i=0 for fd=14
1593167416.150042 drakvuf_init: adding event_fd done
1593167416.151372 init_vmi on domID 60 -> win10x64
1593167416.152495 init_vmi: initializing vmi done
1593167416.152586 init_vmi: initializing vmi paging done
```
In verbose mod, i got these outputs. 

// my windows version = win10 pro 1809

**Comment by icedevml** [comment]
Please try to run DRAKVUF with -k switch, i.e.

```
vmi-win-offsets name $VM_NAME -r $REKALL_PROFILE -k
```

This will output some value like `0x123456`, then plug it into DRAKVUF using `-k` switch:

```
drakvuf -k (value from previous command) (... remaining parameters ...)
```

**Comment by ninjakos** [comment]
I have the same problem.
@icedevml when i run vmi-win-offsets, my vm again freeze :/

Is there any version limit about windows? or what i need to disable avoid freeze?
I didn't get any problem with win7

**Comment by icedevml** [comment]
@kobirona Was the problem solved?
