### ISSUE TITLE
simultaneous memory events

### ISSUE THREAD

**Issue by chengsteven** [tklengyel/drakvuf#913]
I've found that drakvuf and libvmi does not support simultaneous memory events. For example, if I have an X trap on page A and a W trap on page B, with page A containing code that writes to page B, only a single memory event is triggered even though I should expect two events.

Any advice? Thanks in advance

**Comment by icedevml** [comment]
Once you hit the X trap, there is a EPT violation (i.e. trying to execute non-executable page). In response to that, DRAKVUF will switch the EPT view into a "normal one" and re-execute the instruction in a single step mode. So yes, I think in this case you might be missing the memory access write event.

Reference: https://github.com/tklengyel/drakvuf/blob/0cdb2f4e11c29e515b987e8c289da93c569c2ee1/src/libdrakvuf/vmi.c#L479

**Comment by tklengyel** [comment]
That's correct, only the first violation is recorded in that setup. When we singlestep we execute with the default SLAT id 0, which has no EPT permissions set. This is the way DRAKVUF is setup, you can set things up differently using LibVMI.
