### ISSUE TITLE
Ability to stop Drakvuf before time runs out

### ISSUE THREAD

**Issue by Vladinuto** [tklengyel/drakvuf#915]
Hello,

Is there a way to stop Drakvuf and gracefully release the VMI objects before the timeout?

I know we could send a KILL signal to the process, but I'm not sure if there is another way?

Thanks in advance!

**Comment by icedevml** [comment]
You can send SIGINT signal and DRAKVUF will gracefully terminate. I belive this is the common pattern for console programs targetting Linux.

**Comment by icedevml** [comment]
Right now there is no other way to immediately initiate graceful termination of DRAKVUF. Could you elaborate what kind of mechanism would you expect in this case?

**Comment by tklengyel** [comment]
There is another way this could be implemented. DRAKVUF by default polls on Xen's VMI event channel fd to be notified when a new event is generated by the target VM, but you can also poll on additional fd's. This has been used in some setups to also poll on network events and process those alongside the VMI events. You could use this mechanism to listen for additional commands such as an exit request.
