### ISSUE TITLE
Segmentation fault with drakvuf on Win10 vm

### ISSUE THREAD

**Issue by alexmocha** [tklengyel/drakvuf#917]
Hello,

When I try to run drakvuf on a Windows 10 virtual machine, it produces a segmentation fault:  

```console
drakvuf -d 14 -r win10-vol.json -v -k 0x1aa002
 DRAKVUF v0.7-git20200718192524+eca39e2-1 Copyright (C) 2014-2020 Tamas K Lengyel
 Starting DRAKVUF initialization
 drakvuf_init: Rekall WoW64 profile not used
 drakvuf_event_fd_add fd=14
 size of list=1
 regenerating event_fds and fd_info_lookup...
 new event_fd i=0 for fd=14
 new fd_info_lookup i=0 for fd=14
 drakvuf_init: adding event_fd done
 init_vmi on domID 14 -> windows10-x64
 init_vmi: initializing vmi done
 init_vmi: initializing vmi paging done
 init_vmi: initializing vmi OS done
 Max GPFN: 0xff000
 Max mem set? 0
 Physmap populated? 0
 Altp2m enabled? 1
 Altp2m view X created with ID 1
 Altp2m view R created with ID 2
 init_vmi finished
 Windows kernel base address is 0xfffff80426815000
 Failed to find address for symbol KiInitialPCR
 Failed to find offset for _EPROCESS:Wow64Process
 Failed to find offset for VadRoot:BalancedRoot
 Failed to find offset for _MMVAD:LeftChild
 Failed to find offset for _MMVAD:RightChild
 Failed to find offset for _MMVAD:StartingVpn
 Failed to find offset for _MMVAD:EndingVpn
 Failed to find offset for _MMVAD:u
 Failed to find offset for _KPCR:PrcbData
 Failed to find offsets for array of structure names and subsymbols.
 Failed to find offsets for of bitfield: _MMVAD_FLAGS:MemCommit.
 Failed to find offsets for of bitfield: (null):(null).
 Failed to find offsets for of bitfield: _MMVAD_FLAGS:CommitCharge.
Segmentation fault (core dumped)
```

Xen version : V4.13
Windows version : Windows 10 Pro 1903

**Comment by icedevml** [comment]
Could you try with gdb?

```
gdb --args drakvuf -d 14 -r win10-vol.json -v -k 0x1aa002
```

and then type `run` inside gdb

**Comment by alexmocha** [comment]
I have the following output

```console
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff799e403 in volatility_ist_symbol_to_rva (json=<optimized out>, symbol=0x5555557494d4 "_HANDLE_TABLE_ENTRY", subsymbol=0x0, rva=0x0, size=<optimized out>) at libvmi/json_profiles/volatility_ist.c:61
61	libvmi/json_profiles/volatility_ist.c: No such file or directory.
```

**Comment by icedevml** [comment]
Have you compiled libvmi with debugging printouts?

**Comment by icedevml** [comment]
I bet this might be this `*rva` dereference here:

https://github.com/libvmi/libvmi/blob/e9f081a30fa93706af57f17ac9b2b0edb5396476/libvmi/json_profiles/volatility_ist.c#L103

I think a null check is missing here. Could you try to change this line into:

```c
dbprint(VMI_DEBUG_MISC, "Volatility IST profile lookup %s %s: 0x%lx\n", symbol ?: NULL, subsymbol ?: NULL, rva ? *rva : 0);
```

recompile and test?

**Comment by tklengyel** [comment]
Odd, how does `rva=0x0` this happen? We can add a NULL-check for it in LibVMI but a full backtrace would the segfault would be helpful as well to see what caller is passing in a NULL-pointer.

**Comment by chivay** [comment]
My guess is that it's this function
```c
status_t vmi_get_struct_size_from_json(vmi_instance_t vmi, json_object* json, const char* struct_name, size_t* size)
{
    if ( !vmi->json.handler )
        return VMI_FAILURE;

    return vmi->json.handler(json, struct_name, NULL, NULL, size);
}
```

which is in turn called by `libdrakvuf/win.c` at:
```c
    if ( VMI_FAILURE == vmi_get_struct_size_from_json(drakvuf->vmi, vmi_get_kernel_json(drakvuf->vmi), "_HANDLE_TABLE_ENTRY", &drakvuf->sizes[HANDLE_TABLE_ENTRY]) )
    {
        return 0;
    }

```

It seems to agree with the GDB ouptut (`_HANDLE_TABLE_ENTRY` argument)

**Comment by alexmocha** [comment]
> dbprint(VMI_DEBUG_MISC, "Volatility IST profile lookup %s %s: 0x%lx\n", symbol ?: NULL, subsymbol ?: NULL, rva ? *rva : 0);

It solved the segmentation fault, but now the plugin `regomon` fails at startup

**Comment by icedevml** [comment]
So perhaps now some required Volatility profile entry is missing?

**Comment by alexmocha** [comment]
> So perhaps now some offset is missing from Volatility profile but is required by regmon? Take a look at regmon's constructor and check whether your profile contains all the required symbols/offsets.

After verification, each symbol used by regmon is inside the Volatility profile

**Comment by icedevml** [comment]
Could you add some debug prints before each `throw -1` in regmon constructor to find out what exactly is causing problem?

**Comment by alexmocha** [comment]
After a reboot of the VM, the plugin regmon starts. But after some seconds of monitoring, the VM displays a BSoD with the message `KMODE_EXCEPTION NOT HANDLED`

**Comment by alexmocha** [comment]
> After a reboot of the VM, the plugin regmon starts. But after some seconds of monitoring, the VM displays a BSoD with the message `ATTEMPTED_EXECUTE_OF_NOEXECUTE_MEMORY`

An update of my volatility version and a new export of the vm profile solved this problem
