### ISSUE TITLE
libinjector brakes target process in Windows

### ISSUE THREAD

**Issue by skvl** [tklengyel/drakvuf#925]
Hello.

-----
*NOTE* The error is observable in single machine only with Xen 4.12.

Though other machines with Xen 4.12 works perfectly. Any help appreciated.

-----

While executing _drakvuf_ with arguments like this `-i 2584 -e calc.exe` where _2584_ is an _explorer.exe_ I observe the target process crash on access violation.

Debugging it with _WinDbg_ and adding a bunch of debug messages into _drakvuf_ I could conclude that _drakvuf_ don't catch the return from _CreateProcessW_ (or _ResumeThread_ in some cases). So the stack not restores after injection.

I believe that the _CreateProcessW_ completes because I could catch the `ret` instruction from it with `ba e 1 ...` in _WinDbg_. And I even could see the `calc.exe` in _Task manager_ for a period of time: it appears, switches to _Suspended_ state and goes out.

Sometimes it catches the return from _CreateProcessW_ and injects the _ResumeThread_. Then the picture is similar: it misses the return from _ResumeThread_.

With custom debug messages I could observe next (with _ResumeThread_ caught):
```
1596003299.138852 DRAKVUF v0.7-git20200723134213+ptms.sandbox.drakvuf-0.0.0.1395-build-it-1 Copyright (C) 2014-2020 Tamas K Lengyel
["inject_trap_pa":1297] g_hash_table_lookup insert: pa 0xab4d6e4
["wait_for_target_process_cb":748] User-mode hook at 0x7ff915ce96e4
["int3_cb":523] At the begining of the time
["int3_cb":626] Before PID 2584 RIP 0x7ff915ce96e4 RSP 0x87bfc78
["injector_int3_cb":964] RIP 0x7ff915ce96e4 RSP 0x87bfc78
["injector_int3_cb":1110] Hit trapframe: RIP 0x7ff915ce96e4 RSP 0x87bfc78
>>> REGISTERS <<<
rax 0x0000000000000001 rbx 0x0000000000000001 rcx 0x00007ff915ce96e4 rdx 0x0000000000000000
rsi 0x0000000000001120 rdi 0x0000000006aabed0 rbp 0x00000000087bfdd9 rsp 0x00000000087bfc78
r8  0x00000000087bfc78 r9  0x00000000087bfdd9 r10 0x0000000000000000 r11 0x0000000000000246
r12 0x0000000000000000 r13 0x0000000000000000 r14 0x0000000000000000 r15 0x0000000005c7fad0
rip 0x00007ff915ce96e4 rflags 0x0000000000000246
CS 0x0033 DS 0x002b ES 0x002b SS 0x002b FS 0x0053 GS 0x002b
FS_BASE 0x0000000000000000 GS_BASE 0x00000000007b3000 SHADOW_GS 0xffffda806c520000
CR0 0x0000000080050031 CR2 0xffffc98722802460 CR3 0x000000002a380000 CR4 0x00000000001506f8
>>> BEFORE <<<
>>> STACK <<<

	0x087BFC78 | +0x0000 | 9D 02 5A 17 F9 7F 00 00 00 00 00 00 00 00 00 00 | ..Z.............
	0x087BFC88 | +0x0010 | 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 | ................
	0x087BFC98 | +0x0020 | 00 00 00 00 00 00 00 00 06 00 00 00 00 00 00 00 | ................
	0x087BFCA8 | +0x0030 | 00 00 00 00 00 00 00 00 D0 BE AA 06 00 00 00 00 | ................
	0x087BFCB8 | +0x0040 | 96 08 B4 07 F9 7F 00 00 01 00 00 00 00 00 00 00 | ................
	0x087BFCC8 | +0x0050 | D9 FD 7B 08 00 00 00 00 20 11 00 00 00 00 00 00 | ..{..... .......
	0x087BFCD8 | +0x0060 | 20 11 00 00 00 00 00 00 06 00 00 00 00 00 00 00 |  ...............
	0x087BFCE8 | +0x0070 | 00 00 00 00 00 00 00 00 22 01 01 00 00 00 00 00 | ........".......
>>> BEFORE <<<
>>> REGISTERS <<<
rax 0x0000000000000001 rbx 0x0000000000000001 rcx 0x0000000000000000 rdx 0x00000000087bfc60
rsi 0x0000000000001120 rdi 0x0000000006aabed0 rbp 0x00000000087bfdd9 rsp 0x00000000087bfb78
r8  0x0000000000000000 r9  0x0000000000000000 r10 0x0000000000000000 r11 0x0000000000000246
r12 0x0000000000000000 r13 0x0000000000000000 r14 0x0000000000000000 r15 0x0000000005c7fad0
rip 0x00007ff915ce96e4 rflags 0x0000000000000246
CS 0x0033 DS 0x002b ES 0x002b SS 0x002b FS 0x0053 GS 0x002b
FS_BASE 0x0000000000000000 GS_BASE 0x00000000007b3000 SHADOW_GS 0xffffda806c520000
CR0 0x0000000080050031 CR2 0xffffc98722802460 CR3 0x000000002a380000 CR4 0x00000000001506f8
>>> AFTER <<<
>>> STACK <<<

	0x087BFB78 | +0x0000 | E4 96 CE 15 F9 7F 00 00 BE BA EF BE BE BA EF BE | ................
	0x087BFB88 | +0x0010 | FF 10 00 C0 FF 10 00 C0 BE BA FE CA BE BA FE CA | ................
	0x087BFB98 | +0x0020 | AF BE AD DE AF BE AD DE 00 00 00 00 00 00 00 00 | ................
	0x087BFBA8 | +0x0030 | 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................
	0x087BFBB8 | +0x0040 | 00 00 00 00 00 00 00 00 F0 FB 7B 08 00 00 00 00 | ..........{.....
	0x087BFBC8 | +0x0050 | D0 FB 7B 08 00 00 00 00 00 00 00 00 00 00 00 00 | ..{.............
	0x087BFBD8 | +0x0060 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................
	0x087BFBE8 | +0x0070 | 50 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | P...............
>>> AFTER <<<
["int3_cb":636] After PID 2584 RIP 0x7ff9174da0b0 RSP 0x87bfb78
["int3_cb":523] At the begining of the time
["int3_cb":626] Before PID 2584 RIP 0x7ff915ce96e4 RSP 0x87bfb80
["injector_int3_cb":964] RIP 0x7ff915ce96e4 RSP 0x87bfb80
["injector_int3_cb":1237] Return from CreateProcessW: RIP 0x7ff915ce96e4 RSP 0x87bfb80
>>> ResumeThread [2]: REGISTERS <<<
rax 0x0000000000000001 rbx 0x0000000000000001 rcx 0x00007ff915ce96e4 rdx 0x0000000000000000
rsi 0x0000000000001120 rdi 0x0000000006aabed0 rbp 0x00000000087bfdd9 rsp 0x00000000087bfc78
r8  0x00000000087bfc78 r9  0x00000000087bfdd9 r10 0x0000000000000000 r11 0x0000000000000246
r12 0x0000000000000000 r13 0x0000000000000000 r14 0x0000000000000000 r15 0x0000000005c7fad0
rip 0x00007ff915ce96e4 rflags 0x0000000000000246
CS 0x0033 DS 0x002b ES 0x002b SS 0x002b FS 0x0053 GS 0x002b
FS_BASE 0x0000000000000000 GS_BASE 0x00000000007b3000 SHADOW_GS 0xffffda806c520000
CR0 0x0000000080050031 CR2 0xffffc98722802460 CR3 0x000000002a380000 CR4 0x00000000001506f8
>>> BEFORE <<<
>>> STACK <<<

	0x087BFC78 | +0x0000 | 9D 02 5A 17 F9 7F 00 00 00 00 00 00 00 00 00 00 | ..Z.............
	0x087BFC88 | +0x0010 | 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 | ................
	0x087BFC98 | +0x0020 | 00 00 00 00 00 00 00 00 06 00 00 00 00 00 00 00 | ................
	0x087BFCA8 | +0x0030 | 00 00 00 00 00 00 00 00 D0 BE AA 06 00 00 00 00 | ................
	0x087BFCB8 | +0x0040 | 96 08 B4 07 F9 7F 00 00 01 00 00 00 00 00 00 00 | ................
	0x087BFCC8 | +0x0050 | D9 FD 7B 08 00 00 00 00 20 11 00 00 00 00 00 00 | ..{..... .......
	0x087BFCD8 | +0x0060 | 20 11 00 00 00 00 00 00 06 00 00 00 00 00 00 00 |  ...............
	0x087BFCE8 | +0x0070 | 00 00 00 00 00 00 00 00 22 01 01 00 00 00 00 00 | ........".......
>>> BEFORE <<<
>>> REGISTERS <<<
rax 0x0000000000000001 rbx 0x0000000000000001 rcx 0x0000000000001f10 rdx 0x0000000000000000
rsi 0x0000000000001120 rdi 0x0000000006aabed0 rbp 0x00000000087bfdd9 rsp 0x00000000087bfc48
r8  0x00000000087bfc78 r9  0x00000000087bfdd9 r10 0x0000000000000000 r11 0x0000000000000246
r12 0x0000000000000000 r13 0x0000000000000000 r14 0x0000000000000000 r15 0x0000000005c7fad0
rip 0x00007ff915ce96e4 rflags 0x0000000000000246
CS 0x0033 DS 0x002b ES 0x002b SS 0x002b FS 0x0053 GS 0x002b
FS_BASE 0x0000000000000000 GS_BASE 0x00000000007b3000 SHADOW_GS 0xffffda806c520000
CR0 0x0000000080050031 CR2 0xffffc98722802460 CR3 0x000000002a380000 CR4 0x00000000001506f8
>>> AFTER <<<
>>> STACK <<<

	0x087BFC48 | +0x0000 | E4 96 CE 15 F9 7F 00 00 BE BA EF BE BE BA EF BE | ................
	0x087BFC58 | +0x0010 | FF 10 00 C0 FF 10 00 C0 BE BA FE CA BE BA FE CA | ................
	0x087BFC68 | +0x0020 | AF BE AD DE AF BE AD DE 00 00 00 00 00 00 00 00 | ................
	0x087BFC78 | +0x0030 | 9D 02 5A 17 F9 7F 00 00 00 00 00 00 00 00 00 00 | ..Z.............
	0x087BFC88 | +0x0040 | 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 | ................
	0x087BFC98 | +0x0050 | 00 00 00 00 00 00 00 00 06 00 00 00 00 00 00 00 | ................
	0x087BFCA8 | +0x0060 | 00 00 00 00 00 00 00 00 D0 BE AA 06 00 00 00 00 | ................
	0x087BFCB8 | +0x0070 | 96 08 B4 07 F9 7F 00 00 01 00 00 00 00 00 00 00 | ................
>>> AFTER <<<
["injector_int3_cb":1289] RIP 0x7ff9174dbd80 RSP 0x87bfc48
["int3_cb":636] After PID 2584 RIP 0x7ff9174dbd80 RSP 0x87bfc48
```

(I have added some dummy values on home space while stack setup like `0xdeadbeaf` here)

**Comment by icedevml** [comment]
Huge thanks for this report, I was also debugging this for a few days. Seen this bug but can't reliably reproduce.

**Comment by tklengyel** [comment]
Xen 4.12 is no longer supported by DRAKVUF, you would need to backport a lot of patches from 4.14 to 4.12 to make it work.

**Comment by skvl** [comment]
Hello.

I'm very sorry to disappear for this days.

> Huge thanks for this report, I was also debugging this for a few days. Seen this bug but can't reliably reproduce.

What is the status? Have you debugged this? What Xen version do you use?

> Xen 4.12 is no longer supported by DRAKVUF

Thank you. I know this. Several patches have been back-ported. And everything works accept the bug. But @icedevml catch the bug too.

**Comment by tklengyel** [comment]
I've also confirmed that this bug appears on the CI box intermittently, as far as I can tell if I do multiple injections in a row the likelihood of the target process crashing increases significantly.

**Comment by icedevml** [comment]
Yes. I think it will be necessary to do something about it. I bet there is (yet another :D ) complex issue that is triggering in some corner cases.

I'm a little bit afraid of the things libinjector is doing in usermode, knowing how hard was to figure out `libusermode` working properly. Injector was written prior to our work, so it may hit some known or unknown problems around user mode.

I will try to inspect/debug this soon and also cc @chivay @BonusPlay

**Comment by tklengyel** [comment]
What's interesting here is that libinjector has been stable for a while, and only recently have we started to see this issue. On the CI the VMs haven't been updated or anything. It might be worth going back to see where start to experience this issue.

**Comment by tklengyel** [comment]
Another datapoint, I can only reproduce the crash if the VM is running with multiple vCPUs. With a single vCPU it all seems very stable. Perhaps we are restoring the wrong register values after the injection because the return path is hit on a different vCPU?

**Comment by icedevml** [comment]
This is very probable and it applies to many bugs, the "high level" ones as well as the ones directly related to Xen.

I'll check this soon.

**Comment by skvl** [comment]
Looks reasonable.

I have faced similar error in #751 (see https://github.com/tklengyel/drakvuf/blob/fa74f425f8a09fe06ab5c3d8a273f33f436e544e/src/plugins/filedelete/filedelete2_helpers.cpp#L141).

**Comment by tklengyel** [comment]
OK, I've identified the issue to be with `VMI_EVENT_RESPONSE_SET_REGISTERS` on the Xen side. If we call `vmi_set_vcpuregs` instead I can't reproduce the crash. I don't yet know what the issue is with Xen but the processing of that flag is similarly delayed in Xen until the vCPU gets schedule, so I think it may be the same bug we had with the CR event processing and exiting too early.

**Comment by tklengyel** [comment]
@skvl Btw regarding #751, Xen doesn't actually change the FS/GS/SHADOW_GS registers when you respond with  `VMI_EVENT_RESPONSE_SET_REGISTERS`, only the general purpose registers are being set using that route. See https://xenbits.xen.org/gitweb/?p=xen.git;a=blob;f=xen/arch/x86/hvm/vm_event.c;h=19aac19bc35406675624c0cd7e64f78f10bf8005;hb=HEAD#l29

**Comment by icedevml** [comment]
Great, thanks for that input which is very helpful in terms of debugging this.

**Comment by icedevml** [comment]
There also might be an issue with context switches

Successful pass:
```
root@zen:~/drakvuf-sandbox/drakvuf# cat logz1 | grep vcpu
INT3 Callback @ 0x77b5933a. CR3 0xd986000. vcpu 1
1596894455.100594 Switching altp2m and to singlestep on vcpu 1
INT3 Callback @ 0x77b5933a. CR3 0xd986000. vcpu 1
1596894455.102979 Switching altp2m and to singlestep on vcpu 1
INT3 Callback @ 0x77b5933a. CR3 0xd986000. vcpu 1
1596894455.116557 Switching altp2m and to singlestep on vcpu 1
INT3 Callback @ 0x77b5933a. CR3 0xd986000. vcpu 1
1596894455.118700 Switching altp2m and to singlestep on vcpu 1
INT3 Callback @ 0x77b5933a. CR3 0xd986000. vcpu 1
1596894455.152763 Switching altp2m and to singlestep on vcpu 1
INT3 Callback @ 0x77b5933a. CR3 0xd986000. vcpu 1
1596894455.168738 Switching altp2m and to singlestep on vcpu 1
INT3 Callback @ 0x77b5933a. CR3 0xd986000. vcpu 1
1596894455.172110 Switching altp2m and to singlestep on vcpu 1
INT3 Callback @ 0x77b5933a. CR3 0xd986000. vcpu 1
1596894455.173854 Switching altp2m and to singlestep on vcpu 1
INT3 Callback @ 0x77b5933a. CR3 0xd986000. vcpu 1
```

Crash afterwards:
```
root@zen:~/drakvuf-sandbox/drakvuf# cat logz2 | grep vcpu
INT3 Callback @ 0x77b5933a. CR3 0xd986000. vcpu 1
1596894474.533498 Switching altp2m and to singlestep on vcpu 1
INT3 Callback @ 0x77b5933a. CR3 0xd986000. vcpu 1
1596894474.536604 Switching altp2m and to singlestep on vcpu 1
INT3 Callback @ 0x77b5933a. CR3 0xd986000. vcpu 1
1596894474.547394 Switching altp2m and to singlestep on vcpu 1
INT3 Callback @ 0x77b5933a. CR3 0xd986000. vcpu 1
1596894474.550098 Switching altp2m and to singlestep on vcpu 1
INT3 Callback @ 0x77b5933a. CR3 0xd986000. vcpu 0
1596894474.582065 Switching altp2m and to singlestep on vcpu 0
INT3 Callback @ 0x77b5933a. CR3 0xd986000. vcpu 0
1596894474.589387 Switching altp2m and to singlestep on vcpu 0
INT3 Callback @ 0x77b5933a. CR3 0xd986000. vcpu 1
1596894474.590341 Switching altp2m and to singlestep on vcpu 1
INT3 Callback @ 0x77b5933a. CR3 0xd986000. vcpu 0
1596894474.590949 Switching altp2m and to singlestep on vcpu 0
INT3 Callback @ 0x77b5933a. CR3 0xd986000. vcpu 1
```

reproduced it few times

**Comment by icedevml** [comment]
Generally if the vCPU is switched in between then everything screws up to the ground :|

@tklengyel @skvl Do you have an idea how to address this issue? AFAIK we don't have direct control over the CPU preemption. What shall we do if we arrive back to INT3 callback with the switched vCPU? Loop until it's switched back to the correct vCPU? :thinking:

**Comment by icedevml** [comment]
Or hmm, should we ever try to restore all possible registers after injection? This might not be valid due to hijacked process being moved across CPUs in the meantime. I think it's only required to adjust a few registers (rip? rsp?) after successful injection. The more register assignments we do, the bigger is the chance to trigger some bug.

**Comment by icedevml** [comment]
Ok, I see this was already addressed by Tamas, i.e. only the general purpose registers are restored and the rest is left untouched. I'm also unsure about what I wrote previously about switching CPUs. This is somehow related but it seems not to be a direct reason.

I've also found something super weird. Windows 7 x64, hijacking explorer.exe. If we run injector while explorer.exe is in such state (i.e. with right-click tooltip opened):

![image](https://user-images.githubusercontent.com/6976513/89716389-d6d35d80-d9ac-11ea-996b-78944365a280.png)

Then the injector keeps looping waiting for INT3 until some tooltip option is clicked (e.g. `Refresh`). It might go few steps further and again start looping, then again we need to open the tooltip and click some option and only then the injector will manage to finish succesfully.

My theory is that there is some different type of system entry specifically used by explorer's GUI. As far as I understand, currently injector is just waiting until the process enters some system call (using whichever path) and then steps out from this path back into user mode, putting appropriate breakpoints. So if it's out of luck, it would place it's INT3 breakpoint on some very unpopular/weird path and it would not work as expected.

I've also managed to even crash the VM by doing some other actions while the injector was looping:

![image](https://user-images.githubusercontent.com/6976513/89716453-7133a100-d9ad-11ea-8921-56e775c7ba49.png)

**Comment by tklengyel** [comment]
So one assumption injection makes when you only specify the target PID is that the next time the target process' CR3 is loaded, the thread that's currently saved on the stack is one that will get scheduled. We look at the KTRAP_FRAME, read out the RIP, and breakpoint it. When that BP hits is when we can start injecting the function calls. However, if that thread never gets scheduled, the injection is just going to be sitting there waiting. I wonder if that's what you ran into.

**Comment by icedevml** [comment]
Yup, seems to match what I observe.

I can confirm everything is pretty stable when the VM has only 1 vCPU:
```
while [ true ] ; do injector -v -i 144 -r /var/lib/drakrun/profiles/kernel.json -d vm-1 -m writefile -e "%USERPROFILE%\\Desktop\\test$RANDOM.exe" -B /root/putty.exe ; sleep 1 ; done
```
this loops for minutes without any problem.

Still there is some problem with 2 vCPU VM. From time to time the hijacked process gets crashed. There must be something around vCPU switching or sth.

**Comment by icedevml** [comment]
more: on 2 vCPU VM it doesn't help that the hijacked process is pinned to a single CPU using task manager, the hijacked process still crashes after few runs

**Comment by tklengyel** [comment]
I can't reproduce that with the default injection mechanism:

```
while [ true ] ; do ./src/injector -r /shared/cfg/windows10-2004.json -d windows10-2004-jenkins -e calc.exe -i 6296 -v ; sleep 1 ; done
```
```
vmi-process-list windows10-2004-jenkins | grep -i calc | wc -l
55
```

With `-m writefile` there is certainly some strangeness happening. It seems to work fine for ~10-15 injections, then injection still works, the hijacked process doesn't crash but the disk utilization starts spinning at 100% according to Task manager. The icons on the desktop stop refreshing and after a while the VM bluescreens.

**Comment by icedevml** [comment]
On my machine the default injection used against explorer.exe (Win7x64) is also causing crashes from time to time :( Also, sometimes there is a BSOD - `DRIVER_IRQL_NOT_LESS_OR_EQUAL`.

**Comment by icedevml** [comment]
Also, this looks very racey, it's much easier to reproduce on slower hardware.

**Comment by tklengyel** [comment]
Using `explorer.exe` is not something that's been tested much. I always just task manager as the injection target, that seems to be very stable.

**Comment by tklengyel** [comment]
Also to make this a bit more easier to test, try to specify the same thread as an injection target after the VM is restored from a snapshot in a paused state. That would help narrow down if it's reproducible with just certain types of threads, which I suspect is the case.

**Comment by tklengyel** [comment]
I also have the impression that the issue is heavily dependent on how much time elapsed between injections, which would again be very much the same issue we saw with the CR3 events before. I think after the injection we have to wait until each vCPU gets scheduled before trying another round of injection, otherwise Xen skips some of the emulation steps that were pending for a vCPU, leading to the intermittent/random crashes we see.

**Comment by icedevml** [comment]
Good remark, I will check this out.

**Comment by icedevml** [comment]
Ok, so seems like this line is missing:

https://github.com/tklengyel/drakvuf/pull/933/files#diff-0a39142ffa8911f618328b220d6f0271R1577

one down. Still there is something not right but it gained much more sanity/stability with this patch.

**Comment by icedevml** [comment]
>  I think after the injection we have to wait until each vCPU gets scheduled before trying another round of injection, otherwise Xen skips some of the emulation steps that were pending for a vCPU, leading to the intermittent/random crashes we see.

Ok, this is pretty concerning but I have strong impression that adding `sleep(5);` before `drakvuf_close()` in injector's `main()` actually really helps with the stability.

**Comment by icedevml** [comment]
Running injector in a loop, after few iterations there is a BSOD and usually it stops in one of these two places:

```
INT3 Callback @ 0x76e9933a. CR3 0xe621000. vcpu 1
RAX: 0x1
Injected PID: 2484. TID: 2468
Waiting for injected process
1597001834.678146 Switching altp2m and to singlestep on vcpu 1
INT3 Callback @ 0x76e9933a. CR3 0xe621000. vcpu 1
Resume RAX: 0x1
Resumed
1597001834.679104 Removing breakpoint trap from 0x58c5533a.
1597001834.679217 Removed memtrap for GFN 0x58c55 in altp2m view 1
1597001834.679274 Removed memtrap for GFN 0xff00b in altp2m view 1
<BSOD>
```

```
CR3 changed to 0xe621000. PID: 1104 PPID: 1948 TID: 1940
1597001948.196361 Breakpoint VA 0x76e9933a -> PA 0x58c5533a
1597001948.196563 Physmap populated? 0
1597001948.196892 Copied trapped page to new location
1597001948.197144 Activating remapped gfns in the altp2m views!
1597001948.197265               Trap added @ PA 0x58c5533a RPA 0xff01333a Page 363605 for entry.
Got return address 0x76e9933a from trapframe and it's now trapped!
INT3 Callback @ 0x76e9933a. CR3 0xe621000. vcpu 1
1597001948.199044 Switching altp2m and to singlestep on vcpu 1
<BSOD>
```

**Comment by icedevml** [comment]
Another question:

```
INT3 Callback @ 0x76e9933a. CR3 0xe621000. vcpu 1
Writing to allocated virtual memory to allocate physical memory..
Payload is at: 0x5e20000
1597003658.816212 Switching altp2m and to singlestep on vcpu 1
INT3 Callback @ 0x76e9933a. CR3 0xe621000. vcpu 1
Expanding shell...
1597003658.826270 Switching altp2m and to singlestep on vcpu 1
INT3 Callback @ 0x76e9933a. CR3 0xe621000. vcpu 1
Env expand status: 24
Expanded: C:\Users\janusz\Desktop\lol8611.exe
Opening file...
1597003658.828317 Switching altp2m and to singlestep on vcpu 1
1597003658.828846 CR3 cb on vCPU 1: 0x187000
1597003658.829299 CR3 cb on vCPU 1: 0xe621000
1597003658.831931 CR3 cb on vCPU 0: 0x187000
1597003658.842389 CR3 cb on vCPU 0: 0xb3b21000
1597003658.842713 CR3 cb on vCPU 0: 0x12e8b000
1597003658.844016 CR3 cb on vCPU 1: 0xa6770000
1597003658.844391 CR3 cb on vCPU 1: 0xe621000
1597003658.845007 CR3 cb on vCPU 1: 0x187000
1597003658.845586 CR3 cb on vCPU 1: 0xe621000
INT3 Callback @ 0x76e9933a. CR3 0xe621000. vcpu 1
File create result e4
Writing file...
Amount: ffff8
Writing...
1597003658.864955 Switching altp2m and to singlestep on vcpu 1
1597003658.864994 CR3 cb on vCPU 0: 0x187000
1597003658.868231 CR3 cb on vCPU 0: 0x12e8b000
1597003658.869445 CR3 cb on vCPU 0: 0xe621000
1597003658.871730 CR3 cb on vCPU 0: 0x187000
1597003658.872340 CR3 cb on vCPU 0: 0xe621000
1597003658.875347 CR3 cb on vCPU 0: 0x12e8b000
1597003658.875690 CR3 cb on vCPU 0: 0x187000
1597003658.876570 CR3 cb on vCPU 0: 0x87c77000
INT3 Callback @ 0x76e9933a. CR3 0xe621000. vcpu 1
Writing file...
Amount: 1fd98
Writing...
1597003658.882206 Switching altp2m and to singlestep on vcpu 1
```

we have multiple entries of `switching altp2m and to singlestep` but it's not coupled with the usual `reset trap on vCPU ...` Doesn't this mean that we are constantly in wrong SLAT? 🤔

**Comment by tklengyel** [comment]
The CI is running with Xen 4.14 that has fast singlestepping, ie the switch back is handled in Xen without having to catch it here.

**Comment by icedevml** [comment]
What is the semantic of this fast single step in case we change RIP and return `VMI_EVENT_RESPONSE_NONE` from int3 cb?

**Comment by tklengyel** [comment]
The int3 callbacks through libdrakvuf always perform the singlestep, ie. altp2m is switched to view 0, MTF gets enabled, and then in the singlestep exit the view is switched back to altp2m_idx and singlestep is disabled. This last part of switching back to altp2m_idx and disabling MTF is now done in Xen instead of `vmi_reset_trap` in drakvuf.

**Comment by icedevml** [comment]
> The int3 callbacks through libdrakvuf always perform the singlestep

I've checked that if we change RIP inside the int3 callback, then a single-step will be made over the first instruction under the new RIP. This is not necessary but also this doesn't seem to be related to the bug anyway ¯\_(ツ)_/¯

**Comment by tklengyel** [comment]
Yea, unless the int3 callback is the only subscriber and removes the trap in the callback itself the singlestep will always be performed.

**Comment by icedevml** [comment]
This situation is reproducible for me:

```
CR3 changed to 0xe621000. PID: 1104 PPID: 1948 TID: 1940
1597001948.196361 Breakpoint VA 0x76e9933a -> PA 0x58c5533a
1597001948.196563 Physmap populated? 0
1597001948.196892 Copied trapped page to new location
1597001948.197144 Activating remapped gfns in the altp2m views!
1597001948.197265               Trap added @ PA 0x58c5533a RPA 0xff01333a Page 363605 for entry.
Got return address 0x76e9933a from trapframe and it's now trapped!
INT3 Callback @ 0x76e9933a. CR3 0xe621000. vcpu 1
1597001948.199044 Switching altp2m and to singlestep on vcpu 1
<BSOD>
```

I load the VM from the snapshot before each injection and I have both PID and TID pinned. It screws up with some probability like 30%. Sometimes BSOD occurs just after the first step (when `VirtualAlloc` stack is set up), sometimes after the second step (when `memset` stack is set up) etc.

it gives many different BSODs, mostly `KMODE_EXCEPTION_NOT_HANDLED`, `SYSTEM_THREAD_EXCEPTION_NOT_HANDLED`, `DRIVER_IRQL_NOT_LESS_OR_EQUAL`.

It's concerning that this is BSOD (and it's always BSOD, I don't see any crashes in user mode anymore), so it looks like there is some corruption around kernel, not the hijacked process. I wonder if the process gets somehow preempted? Theoretically we should not be ever able to crash Windows if we are overriding some vCPU context being inside user mode.

**Comment by icedevml** [comment]
Or the BSOD codes suggest that this could have to do something with interrupts and all this low level kernel stuff 🤔

**Comment by tklengyel** [comment]
Could you try a simple experiment with adding a check to see if all vCPU's are in the running state at https://github.com/tklengyel/drakvuf/blob/master/src/injector.c#L341 (just before `drakvuf_close`)?

**Comment by icedevml** [comment]
But right now with the recent master I don't experience any crashes in usermode anymore. The current test algorithm is:

1. restore VM from snapshot
2. run injector with `-m writefile` and explicitly specified PID and TID
3. back to point 1

so each injector execution has the same clean VM. There is about 30% possibility that injector would stop in the middle and there would be BSOD.

Sometimes there is a BSOD after injector returns from here:
https://github.com/tklengyel/drakvuf/blob/b0225c855f443ea7c841f9a024bfd2eb874ab856/src/libinjector/win_injector.c#L1157

sometimes here:
https://github.com/tklengyel/drakvuf/blob/b0225c855f443ea7c841f9a024bfd2eb874ab856/src/libinjector/win_injector.c#L1183

and sometimes few steps further. In such case always the last logged line is:
```
1597003658.882206 Switching altp2m and to singlestep on vcpu 1
```

and then the injector gets stuck forever and Windows just displays bugcheck.

Before all these fixes we had the hijacked process crashing and right now I almost never observe the process crash, it's rather BSOD immediately.

**Comment by icedevml** [comment]
Wait, I have some idea, I will drop some branch in a few minutes to let you test.

**Comment by icedevml** [comment]
Check this: https://github.com/CERT-Polska/drakvuf/tree/debug-injector

I've added the old hack with `vmi_wait_vm` which loops until all vCPUs are scheduled. Moreover I've downgraded DRAKVUF to commit a1a5d7c685b6257287eaccee43fd0a2c7286476a (i.e. before `vmi_vcpu_setregs` was implemented in the injector).

vmi_wait_vm implementation in libvmi
https://github.com/tklengyel/libvmi/commit/db334d5efec263c4598443dc50a6c5d8285c239c

usage in DRAKVUF
https://github.com/CERT-Polska/drakvuf/commit/bbff50398c7b07a53415ead7148c6eec500284c9#diff-4345295d2e1a70e24bf3d761b1c10740R1623

I've launched 20x injector in a loop without any sleeps, default injection method, hijacking `explorer.exe` on Win7x64 without pinned TID - works like a hammer. The hijacked process is still fully functional after getting through all of this.

**Comment by icedevml** [comment]
And the second version: https://github.com/CERT-Polska/drakvuf/tree/debug-injector2

This version is the current master + `vmi_wait_vm`.

Again, I've launched 20x injector loop using the same command as before. This doesn't complete because the VM does bugcheck after few iterations :(

So I understand that `vmi_vcpu_setregs` is bypassing Xen's deferred logic around setting registers, but instead it appears (to me) like it's somehow interfering with kernel interrupts or other asynchronous mechanism in the kernel.

**Comment by tklengyel** [comment]
The `vmi_vcpu_setregs` is an heavy handed call as it saves the VMs entire HVM context, changes the registers for the one vCPU, and then reloads the entire HVM context. This involves pausing the entire domain and reloading the context for each vCPU, not just the one we have changed, alongside all the other stuff contained in the HVM context. It's effectively what happens when you save & then later restore the VM. So it's a large overhead but as long as it's done only a couple times it's not horrible. Also, this path should be extremely well tested and without bugs as this is used for VM save/restore/migration/fork as well. So a bug here that would mess with the interrupts of the guest would be unlikely to have gone undetected.

**Comment by tklengyel** [comment]
Ah, I think I know what's up. LibVMI doesn't pause the VM in `xen_set_vcpuregs_hvm` and `xen_set_vcpuregs_hvm`. That makes it racy.

**Comment by tklengyel** [comment]
Haha, there is a helpful comment in LibVMI from Steve:
```
e5431980 libvmi/driver/xen.c     (Steven Maresca     2013-01-08 04:57:00 -0500 1346)      * NOTE: to avoid inducing race conditions/errors, run while VM is paused.
```

**Comment by icedevml** [comment]
I'm testing the branch debug-injector2 with pause/resume added in these LibVMI functions

**Comment by tklengyel** [comment]
Yea, I think we really should just make these calls safe in LibVMI.

**Comment by icedevml** [comment]
Ok with version c0bcb599ca7b554b38f4bed40eb33369e0c65ca8 after additionally applying #938 #939 #941 it's now passing the test in which I was running injector 100 times in a row, hijacking `explorer.exe` without explicit thread ID provided, using `-m writefile`. It uploaded 100 binaries to the desktop and the hijacked explorer is still fully functional :)

**Comment by skvl** [comment]
@tklengyel, @icedevml, I afraid that the bug not fixed yet.

I have ported fixes from c0bcb599ca7b554b38f4bed40eb33369e0c65ca8 and get the issue again.

I don't have access to the machine at the time but I will check the pure master as soon as possible.

**Comment by skvl** [comment]
Is it possible that you have tested with patched `libvmi`. On current master I have libvmi e9f081a30fa93706af57f17ac9b2b0edb5396476

**Comment by icedevml** [comment]
> I have ported fixes from c0bcb59 and get the issue again.

There were some other fixes around injector, e.g.: https://github.com/tklengyel/drakvuf/pull/939

**Comment by skvl** [comment]
@icedevml, thank you. I will check.

**Comment by skvl** [comment]
@tklengyel, @icedevml, I have re-tested the master several times. The bug continues to reproduce.

Do you experience the same problem on yours machines?

**Comment by tklengyel** [comment]
Nope, on my end everything is stable, no in-guest crashes at all
