### ISSUE TITLE
How to execute .jar files by injector?

### ISSUE THREAD

**Issue by alexandrafengfei** [tklengyel/drakvuf#95]
Hi. Now I am trying to analyze a malware sample which is a jar file. I tried to hijack the taskmgr.exe to execute it but failed. I had to execute it by double-clicking it.  
Is this because now injector can only execute .exe files?

**Comment by tklengyel** [comment]
Injector can execute anything as long as you have the right tools installed in the guest (in this case Java) and you send the proper start info to it. The first hit on google tells me you execute jar files by running `java -jar helloworld.jar`.
