### ISSUE TITLE
Possible bug in inject_trap_pa mechanics

### ISSUE THREAD

**Issue by icedevml** [tklengyel/drakvuf#960]
Steps to reproduce:

1. Create a `MEMACCESS` trap with `trap.access = VMI_MEMACCESS_X`
2. Create `BREAKPOINT` trap on the same physical address as the above trap
3. Remove trap from point (1)
4. DRAKVUF doesn't update access permissions for this GFN and keeps trapping X, which is causing every instruction on the page to be single-stepped (huge performance impact)

I think the cause is that when `BREAKPOINT` trap is created, it checks whether `MEMACCESS` trap already exists on this GFN:

https://github.com/tklengyel/drakvuf/blob/master/src/libdrakvuf/vmi.c#L1113-L1118

and then the access rights for the new trap are merged with the previous one:

https://github.com/tklengyel/drakvuf/blob/master/src/libdrakvuf/vmi.c#L1200-L1201

so even when we would remove our original `MEMACCESS` trap, the guard trap of `BREAKPOINT` would keep trapping X (I think unnecessarily).

AFAIK `inject_trap_mem` is able to handle the situation when there are multiple `MEMACCESS` traps on the same physical page and it would resolve it internally, so is this code actually required?

I see there was some issue about this (years ago): https://github.com/tklengyel/drakvuf/pull/194

Could we reconsider this?

**Comment by tklengyel** [comment]
I think the solutionis pretty straight forward. Whenever a memaccess X trap is removed we should check if there are any breakpoint traps active for that page and just remove the X trap from their guard trap. It's not really a bug so much as an unnecessary overhead at that point.

**Comment by icedevml** [comment]
Yup. I'm interested in improving performance due to one of my use cases which is intensively generating such situations.

I will make a PR according to your hint.

**Comment by icedevml** [comment]
Hmm, but is there any particular reason why we need to add `VMI_MEMACCESS_X` to the breakpoint's guard trap if there is `MEMACCESS` trap already present?

If we have both `MEMACCESS` trap on X and classical `BREAKPOINT` trap, then anyway we would hit `pre_mem_cb` and the int3 event would be simulated, so I think it's not going to break anything if we would just drop these lines:
https://github.com/tklengyel/drakvuf/blob/master/src/libdrakvuf/vmi.c#L1113-L1118

or am I wrong?

**Comment by icedevml** [comment]
I.e. since we have this patch https://github.com/tklengyel/drakvuf/pull/195, do we still really need this patch https://github.com/tklengyel/drakvuf/pull/194 ?

**Comment by tklengyel** [comment]
> Hmm, but is there any particular reason why we need to add VMI_MEMACCESS_X to the breakpoint's guard trap if there is MEMACCESS trap already present?

No, we don't. The guard page for breakpoint only needs to catch R/W.

> so I think it's not going to break anything if we would just drop these lines

Yea, I think so too. The existing routine in adding/removing mem_access traps will compute the final required permission after each trap addition/removal, so the breakpoint trap guard handler shouldn't need to be aware of other memaccess traps.

**Comment by icedevml** [comment]
Ok so I will simply remove this code. I've tested this a little bit and all looks fine at the first glance. From the code itself it also looks like this would be safe for removal.
