### ISSUE TITLE
How to update drakvuf to 0.7? Documentation?

### ISSUE THREAD

**Issue by Id3aFly** [tklengyel/drakvuf#962]
Hey guys,

so it's not a bug but I didn't know where to ask apart from here:
I Installed drakvuf (according to the notes on the website by cloning the git repo, etc) half a year ago.
Now I'd like to get the latest version 0.7. How do I get this update?
Can I just run _git pull_ or do I have to do something else additionally? I don't want to crash my setup so I thought I'd rather ask first.

Thank you

**Comment by icedevml** [comment]
I think if you clone the new version along with submodules (`git submodule update`) and re-run all the commands from drakvuf.com then it should be fine. Remember to reboot in order to boot from updated Xen version.

**Comment by Id3aFly** [comment]
I guess you mean this part?

```
cd drakvuf
git submodule update --init
cd xen
./configure --enable-githttp --disable-pvshim
make -j4 dist-xen
make -j4 dist-tools
sudo su
make -j4 install-xen
make -j4 install-tools
echo "GRUB_CMDLINE_XEN_DEFAULT=\"dom0_mem=4096M,max:4096M dom0_max_vcpus=4 dom0_vcpus_pin=1 force-ept=1 ept=pml=0 hap_1gb=0 hap_2mb=0 altp2m=1 smt=0\"" >> /etc/default/grub
echo "/usr/local/lib" > /etc/ld.so.conf.d/xen.conf
ldconfig
echo "none /proc/xen xenfs defaults,nofail 0 0" >> /etc/fstab
echo "xen-evtchn" >> /etc/modules
echo "xen-privcmd" >> /etc/modules
systemctl enable xen-qemu-dom0-disk-backend.service
systemctl enable xen-init-dom0.service
systemctl enable xenconsoled.service
update-grub
reboot
```

Is every command of above necessary? Or do you think I could destroy when just rerunning all those commands?

**Comment by icedevml** [comment]
I think all commands expect these starting with `echo` can be safely repeated. The ones with `echo` are not needed since you should already have appropriate files modified by these commands previously.

**Comment by tklengyel** [comment]
I would actually just recommend that you install the package automatically generated for the latest builds from https://github.com/tklengyel/drakvuf-builds/releases/latest

**Comment by Id3aFly** [comment]
1. If I  want to modify the source code / write custom plugins, then I clone it, shouldn't I?
2. What is packaged in the builds? Xen/LibVMI/..? I mean, what parts mentioned at drakvuf.com do I still need to do?

**Comment by icedevml** [comment]
1 - yes
2 - the package is pretty huge and it contains DRAKVUF, LibVMI and Xen hypervisor&tools, all of them in compatible versions

**Comment by icedevml** [comment]
according to command list you've pasted above, you can safely re-exexute everything except `echo`s which you should simply skip

**Comment by tklengyel** [comment]
> If I want to modify the source code / write custom plugins, then I clone it, shouldn't I?

You can still install the package and then you only have to compile your custom DRAKVUF source based on the master branch, that way you don't have to keep track all the other dependencies. So I think that's still the best way, otherwise you can easily end up with old/conflicting libraries littered around your system.

**Comment by icedevml** [comment]
> You can still install the package and then you only have to compile your custom DRAKVUF source based on the master branch, that way you don't have to keep track all the other dependencies

+1, also doing it this way on some dev environments

**Comment by Id3aFly** [comment]
I think it would be a great advantage to note this down in some documentation.
From my side things are clearer now. Thanks for your help.
