### ISSUE TITLE
Guest Windows has strange bugs with latest drakvuf 0.7

### ISSUE THREAD

**Issue by Id3aFly** [tklengyel/drakvuf#966]
Hey guys,

so today I installed the latest drakvuf according to the guide at drakvuf.com.
When starting/installing my windows 10 guest via my vncviewer as alsways the image is only black-white (even at some moments like at the end of booting it flickers to color for a quick moment), the image resolution is really low (and the font really big) and the guest is very slow at all. Thus I am not able to use it.

Do you have any idea why this would happen? With previous drakvuf (or installing xen manually) this didn't happen.

Thank you

**Comment by tklengyel** [comment]
Do you have `stdvga=1` in your VM's config file?

**Comment by Id3aFly** [comment]
Thanks Tamas! Your hint was part of the solution.
I have read previously that stdvga would be [deprecated in favor of vga](https://xenbits.xen.org/docs/unstable/man/xl.cfg.5.html). 
`This option [stdvga=1] is deprecated, use vga="stdvga" instead.`

While in my old setup it worked without specifying neither stdvga nor vga (for whatever reason I missed to specify it), it now required to set vga="stdvga" or stdvga=1 (both solutions are working).

Thank you!

**Comment by tklengyel** [comment]
You're welcome. I've ran into the same issue when I first upgraded to 4.14. Thanks for the tip on `stdvga=1` being deprecated, I'll update the example config to new format.
