### ISSUE TITLE
vmi-win-guid name cant find libvmi.so.0

### ISSUE THREAD

**Issue by Id3aFly** [tklengyel/drakvuf#967]
Hey guys,
I followed the installation on drakvuf.com and wanted to run:
`sudo vmi-win-guid name win10` (where win10 is the name of my running xen guest)

But strangely I get following error:
`vmi-win-guid: error while loading shared libraries: libvmi.so.0: cannot open shared object file: No such file or directory`

libvmi.so.0 is available in following paths:
```
/home/userX/drakvuf/libvmi/libvmi/.libs/libvmi.so.0
/usr/local/lib/libvmi.so.0
```
Same error is raised when running: `sudo vmi-process-list win10`

Do you have any idea what is wrong? Or how to fix this?
Thank you

**Comment by Id3aFly** [comment]
A workaround is:
`~/drakvuf/libvmi/examples$ sudo ./vmi-win-guid name win10`

**Comment by icedevml** [comment]
Please try

```
export LD_LIBRARY_PATH=/usr/local/lib
```

**Comment by Id3aFly** [comment]
Hey icedevml,

your idea didn't help me. The error is still raised.

**Comment by Id3aFly** [comment]
Also calling "sudo ./src/drakvuf -r /root/windows7-sp1.json -d 7" raises this  same error.:
`error while loading shared libraries: libvmi.so.0: cannot open shared object file: No such file or directory`

I'm running the latest Ubuntu x64, if you need more information just tell me. :)

**Comment by tklengyel** [comment]
You probably didn't run `make install` in the libvmi folder

**Comment by Id3aFly** [comment]
I surely ran `make install` previously. This was the output:

kali@kali-W350SKQ-W370SK:~/drakvuf/libvmi$ sudo make install
[sudo] Passwort für kali: 
make[1]: Verzeichnis „/home/kali/drakvuf/libvmi“ wird betreten
 /usr/bin/mkdir -p '/usr/local/lib'
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   libvmi/libvmi.la '/usr/local/lib'
libtool: install: /usr/bin/install -c libvmi/.libs/libvmi.so.0.0.13 /usr/local/lib/libvmi.so.0.0.13
libtool: install: (cd /usr/local/lib && { ln -s -f libvmi.so.0.0.13 libvmi.so.0 || { rm -f libvmi.so.0 && ln -s libvmi.so.0.0.13 libvmi.so.0; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libvmi.so.0.0.13 libvmi.so || { rm -f libvmi.so && ln -s libvmi.so.0.0.13 libvmi.so; }; })
libtool: install: /usr/bin/install -c libvmi/.libs/libvmi.lai /usr/local/lib/libvmi.la
libtool: install: /usr/bin/install -c libvmi/.libs/libvmi.a /usr/local/lib/libvmi.a
libtool: install: chmod 644 /usr/local/lib/libvmi.a
libtool: install: ranlib /usr/local/lib/libvmi.a
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n /usr/local/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/local/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /usr/bin/mkdir -p '/usr/local/bin'
  /bin/bash ./libtool   --mode=install /usr/bin/install -c tools/vmifs/vmifs examples/vmi-process-list examples/vmi-module-list examples/vmi-dump-memory examples/vmi-win-guid examples/vmi-win-offsets '/usr/local/bin'
libtool: install: /usr/bin/install -c tools/vmifs/.libs/vmifs /usr/local/bin/vmifs
libtool: install: /usr/bin/install -c examples/.libs/vmi-process-list /usr/local/bin/vmi-process-list
libtool: install: /usr/bin/install -c examples/.libs/vmi-module-list /usr/local/bin/vmi-module-list
libtool: install: /usr/bin/install -c examples/.libs/vmi-dump-memory /usr/local/bin/vmi-dump-memory
libtool: install: /usr/bin/install -c examples/.libs/vmi-win-guid /usr/local/bin/vmi-win-guid
libtool: install: /usr/bin/install -c examples/.libs/vmi-win-offsets /usr/local/bin/vmi-win-offsets
 /usr/bin/mkdir -p '/usr/local/include/libvmi'
 /usr/bin/install -c -m 644 libvmi/libvmi.h libvmi/libvmi_extra.h libvmi/slat.h libvmi/x86.h libvmi/events.h libvmi/peparse.h '/usr/local/include/libvmi'
 /usr/bin/mkdir -p '/usr/local/lib/pkgconfig'
 /usr/bin/install -c -m 644 libvmi.pc '/usr/local/lib/pkgconfig'
make[1]: Verzeichnis „/home/kali/drakvuf/libvmi“ wird verlassen

**Comment by Id3aFly** [comment]
I was able to solve this problem, but am not sure what the best solution would be. What I did at first was to look at the linked libraries:
```
ldd /usr/local/bin/vmi-win-guid
	linux-vdso.so.1 (0x00007ffd2cee6000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fdfb814d000)
	libvmi.so.0 => /usr/local/lib/libvmi.so.0 (0x00007fdfb8112000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdfb7f20000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fdfb7ead000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdfb7e8a000)
	libjson-c.so.4 => /lib/x86_64-linux-gnu/libjson-c.so.4 (0x00007fdfb7e78000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdfb7e70000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fdfb8291000)
```
So libvmi.so.0 seems to be linked. Maybe at this point it would have been enough to run ldconfig again (but I didn't try it out).

What I did instead was to copy libvmi.so.0 to /usr/lib
added `include include /usr/local/lib ` to /etc/ld.so.conf
and ran ldconfig.
Even this resolved my problem, there seems to be a problem. Either with the installation of libvmi or the registration of libraries, or with the installation tutorial of drakvuf.

**Comment by tklengyel** [comment]
```What I did instead was to copy libvmi.so.0 to /usr/lib
added include /usr/local/lib to /etc/ld.so.conf
```
That doesn't really make sense. You are copying to `/usr/lib` and then add `/usr/local/lib` to your ld.so.conf. And if you followed the tutorial you already have `/usr/local/lib` in your ld conf after you installed Xen. And the tutorial explicitely shows you have to run `ldconfig` to activate it. So this to me still just looks like an error in your configuration by not following the tutorial step-by-step.

**Comment by Id3aFly** [comment]
Yeah, u are right.
I looked in the bash_history and it seems I mixed something up with a second installation I did.
Thank you

**Comment by Id3aFly** [comment]
To confirm my the mentioned bug was my mistake I did a full reinstall followed exactly every step ... and got the above mentioned error again, when trying to execute 
`sudo vmi-win-guid name windows7-sp1-x86`

Luckily I was able to fix it easily. 
After running 
`sudo python3 ./setup.py install` (which is mentioned in the tutorial at drakvuf.com, the line before sudo vmi-win-guid ...)
I executed this command:
`sudo ldconfig`

Now it works.

**Comment by Id3aFly** [comment]
I'm not sure why the bug got closed.

When I did my last install of drakvuf the installation notes at drakvuf.com didn't fix the initially mentioned error.
In addition to the notes I had to execute `sudo ldconfig` right before running `sudo python3 ./setup.py install` to make everythin work correct.
