### ISSUE TITLE
Native filename extraction in FILEDELETE

### ISSUE THREAD

**Issue by v-p-b** [tklengyel/drakvuf#98]
There is a nice debug "facility" in the FILEDELETE plugin that simply prints the name of the extracted file before invoking Volatility:

https://github.com/tklengyel/drakvuf/blob/master/src/plugins/filedelete/filedelete.cpp#L221

It seems (and for my purposes it definitely is) useful to have the filename without invoking a (pretty slow) external command. Can we enable this debug print by default? (Volatility can be trivially disabled without touching DRAKVUF if not needed) If yes, what would be the desirable output format?

**Comment by tklengyel** [comment]
That sounds fine to me, it just has to print print both in plain and csv format. I think the filetracer ouput could be used as the example to follow here too.
