### ISSUE TITLE
compiling errors encountered on Ubuntu 20.04.1 LTS, amd64 machine

### ISSUE THREAD

**Issue by liuya0904** [tklengyel/drakvuf#980]
Hi guys，

The following errors were encountered when compiling on ubuntu 20.04.1 machine: 
In file included from ../../src/plugins/output_format/common.h:111,
                 from ../../src/plugins/output_format.h:108,
                 from syscalls/syscalls.cpp:114:
../../src/plugins/private.h:112:1: sorry, unimplemented: non-trivial designated initializers not supported
  112 | };
      | ^
In file included from syscalls/syscalls.h:109,
                 from syscalls/syscalls.cpp:115:
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
  226 | };
      | ^
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:226:1: sorry, unimplemented: non-trivial designated initializers not supported
../../src/plugins/plugins.h:240:53: error: expected identifier before numeric constant
  240 |     plugin* plugins[__DRAKVUF_PLUGIN_LIST_MAX] = { [0 ... __DRAKVUF_PLUGIN_LIST_MAX-1] = nullptr };
      |                                                     ^
../../src/plugins/plugins.h: In lambda function:
../../src/plugins/plugins.h:240:88: error: expected ‘{’ before ‘=’ token
  240 |     plugin* plugins[__DRAKVUF_PLUGIN_LIST_MAX] = { [0 ... __DRAKVUF_PLUGIN_LIST_MAX-1] = nullptr };
      |                                                                                        ^
../../src/plugins/plugins.h: At global scope:
../../src/plugins/plugins.h:240:90: error: no match for ‘operator=’ (operand types are ‘drakvuf_plugins::<lambda()>’ and ‘std::nullptr_t’)
  240 |     plugin* plugins[__DRAKVUF_PLUGIN_LIST_MAX] = { [0 ... __DRAKVUF_PLUGIN_LIST_MAX-1] = nullptr };
      |                                                                                          ^~~~~~~
../../src/plugins/plugins.h:240:86: note: candidate: ‘drakvuf_plugins::<lambda()>& drakvuf_plugins::<lambda()>::operator=(const drakvuf_plugins::<lambda()>&)’ <deleted>
  240 |     plugin* plugins[__DRAKVUF_PLUGIN_LIST_MAX] = { [0 ... __DRAKVUF_PLUGIN_LIST_MAX-1] = nullptr };
      |                                                                                      ^
../../src/plugins/plugins.h:240:86: note:   no known conversion for argument 1 from ‘std::nullptr_t’ to ‘const drakvuf_plugins::<lambda()>&’
cc1plus: warning: unrecognized command line option ‘-Wno-reorder-init-list’
cc1plus: warning: unrecognized command line option ‘-Wno-c99-designator’
make[3]: *** [Makefile:1053: syscalls/syscalls.lo] Error 1
make[3]: Leaving directory '/home/liuya/tools/drakvuf/src/plugins'
make[2]: *** [Makefile:744: all-recursive] Error 1
make[2]: Leaving directory '/home/liuya/tools/drakvuf/src'
make[1]: *** [Makefile:529: all-recursive] Error 1
make[1]: Leaving directory '/home/liuya/tools/drakvuf'
make: *** [Makefile:461: all] Error 2

Everything is OK in autogen.sh and configure. The gcc version is 9.3.0:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-10ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)

Thanks for solving.

Regards,
liuya

**Comment by tklengyel** [comment]
You need to use clang and clang++ as your compilers. The configure step shouldn't have let you continue without the proper compiler found.

**Comment by liuya0904** [comment]
Hi tklengyel, 

Thank you for response. It did let me go to make when clang wasn't installed. 

After I installed clang and run ./configure, the following errors were encountered:

checking whether clang++ supports C++17 features by default... no
checking whether clang++ supports C++17 features with -std=gnu++17... no
checking whether clang++ supports C++17 features with -std=gnu++1z... no
configure: error: *** A compiler with support for C++17 language features is required.

Both clang-6 and  clang-7  have been been tested error. I also tested clang to compile other demo c++ files with -std=c++17, it works.

**Comment by tklengyel** [comment]
Use a newer clang, clang-9 or 10 works fine.

**Comment by liuya0904** [comment]
thank you. clang-10 is OK.
